/* Auto-generated by scripts/generate-agent-icon-sprites.mjs. Do not edit manually. */
export const AGENT_ICON_SPRITES = {
  "dark": {
    "src": "/agent_icons/sprite-dark.webp",
    "columns": 21,
    "cells": {
      "assistant": 0,
      "automation": 1,
      "calendar": 2,
      "code": 3,
      "content": 4,
      "data": 5,
      "devops": 6,
      "director": 7,
      "document": 8,
      "email": 9,
      "finance": 10,
      "hr": 11,
      "legal": 12,
      "marketing": 13,
      "monitor": 14,
      "notification": 15,
      "research": 16,
      "sales": 17,
      "search": 18,
      "security": 19,
      "support": 20
    }
  },
  "light": {
    "src": "/agent_icons/sprite-light.webp",
    "columns": 21,
    "cells": {
      "assistant": 0,
      "automation": 1,
      "calendar": 2,
      "code": 3,
      "content": 4,
      "data": 5,
      "devops": 6,
      "director": 7,
      "document": 8,
      "email": 9,
      "finance": 10,
      "hr": 11,
      "legal": 12,
      "marketing": 13,
      "monitor": 14,
      "notification": 15,
      "research": 16,
      "sales": 17,
      "search": 18,
      "security": 19,
      "support": 20
    }
  }
} as const;

export type AgentIconSpriteMode = keyof typeof AGENT_ICON_SPRITES;
export type AgentIconSpriteId = keyof typeof AGENT_ICON_SPRITES.dark.cells;
