import { useMemo } from 'react';
import { Link, CheckCircle2, AlertCircle, Loader2, RefreshCw, Wrench, Zap, ListChecks } from 'lucide-react';
import { usePersonaStore } from '@/stores/personaStore';
import { CredentialDesignModal } from '@/features/vault/sub_design/CredentialDesignModal';
import {
  useConnectorStatuses,
  type DraftConnector,
} from './useConnectorStatuses';
import { ConnectorRow } from './ConnectorRow';
import type { N8nEntitiesTabProps, DraftTool, DraftTrigger } from './N8nEntitiesTab.types';

// Re-export types so existing consumers don't break
export type { N8nEntitiesTabProps, DraftTool, DraftTrigger } from './N8nEntitiesTab.types';

// ============================================================================
// Component
// ============================================================================

export function N8nEntitiesTab({
  draft,
  parsedResult,
  selectedToolIndices,
  selectedTriggerIndices,
  selectedConnectorNames,
  manualLinks,
  updateDraft,
  onLink,
  onMissingCountChange,
  onGoToAnalyze,
}: N8nEntitiesTabProps) {
  const credentials = usePersonaStore((s) => s.credentials);

  // -- Extract entities from draft (post-transform) or parser results (pre-transform) --

  const draftTools: DraftTool[] | null = draft.tools ?? null;
  const draftTriggers: DraftTrigger[] | null = draft.triggers ?? null;
  const draftConnectors: DraftConnector[] = draft.required_connectors ?? [];

  // Fallback from parser results
  const selectedTools = parsedResult.suggested_tools.filter((_, i) => selectedToolIndices.has(i));
  const selectedTriggers = parsedResult.suggested_triggers.filter((_, i) => selectedTriggerIndices.has(i));
  const selectedConnectors = (parsedResult.suggested_connectors ?? []).filter((c) =>
    selectedConnectorNames.has(c.name),
  );

  const toolItems: DraftTool[] = draftTools ?? selectedTools.map((t) => ({ name: t }));
  const triggerItems: DraftTrigger[] = draftTriggers ?? selectedTriggers;
  const connectorItems: DraftConnector[] = draftConnectors.length > 0
    ? draftConnectors
    : selectedConnectors.map((c) => ({ name: c.name, n8n_credential_type: c.name, has_credential: false }));

  // -- Group tools by connector --

  const { connectorToolMap, generalTools } = useMemo(() => {
    const connNames = new Set(connectorItems.map((c) => c.name));
    const map = new Map<string, DraftTool[]>();
    const general: DraftTool[] = [];

    for (const tool of toolItems) {
      const credType = tool.requires_credential_type;
      if (credType && connNames.has(credType)) {
        const arr = map.get(credType) ?? [];
        arr.push(tool);
        map.set(credType, arr);
      } else {
        general.push(tool);
      }
    }
    return { connectorToolMap: map, generalTools: general };
  }, [toolItems, connectorItems]);

  // -- Connector status tracking (via shared hook) --

  const cs = useConnectorStatuses({
    connectors: connectorItems,
    manualLinks,
    updateDraft,
    onLink,
    onMissingCountChange,
  });

  // -- Render --

  const hasConnectors = connectorItems.length > 0;
  const hasGeneralTools = generalTools.length > 0;
  const hasTriggers = triggerItems.length > 0;
  const isEmpty = !hasConnectors && !hasGeneralTools && !hasTriggers;

  if (isEmpty) {
    return (
      <div className="text-center py-12 space-y-2">
        <ListChecks className="w-10 h-10 text-muted-foreground/40 mx-auto" />
        <p className="text-sm font-medium text-muted-foreground/60">
          No entities selected.
        </p>
        <p className="text-sm text-muted-foreground/60">
          Go back to the Analyze step to select tools and triggers.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4 h-full overflow-y-auto pr-1">
      {/* Header bar */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <p className="text-sm text-muted-foreground/80">
            {draftTools
              ? 'Entities generated by the transformation.'
              : 'Items from your n8n workflow associated with this persona.'}
          </p>
          {cs.readyCount > 0 && (
            <span className="inline-flex items-center gap-1 px-2 py-0.5 text-sm rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400">
              <CheckCircle2 className="w-2.5 h-2.5" />
              {cs.readyCount} ready
            </span>
          )}
          {cs.missingCount > 0 && (
            <span className="inline-flex items-center gap-1 px-2 py-0.5 text-sm rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-400">
              <AlertCircle className="w-2.5 h-2.5" />
              {cs.missingCount} missing
            </span>
          )}
        </div>
        <div className="flex items-center gap-1.5">
          {onGoToAnalyze && (
            <button
              onClick={onGoToAnalyze}
              className="px-3 py-1.5 text-sm rounded-xl border border-primary/15 text-muted-foreground/80 hover:bg-secondary/50 transition-colors"
            >
              Edit Selection
            </button>
          )}
          {cs.testableCount > 0 && (
            <button
              onClick={() => void cs.handleTestAll()}
              disabled={cs.testingAll}
              className="flex items-center gap-1.5 px-3 py-1.5 text-sm rounded-xl border border-primary/15 text-muted-foreground/80 hover:bg-secondary/50 hover:text-foreground/95 transition-colors disabled:opacity-40"
            >
              {cs.testingAll ? <Loader2 className="w-3 h-3 animate-spin" /> : <RefreshCw className="w-3 h-3" />}
              Test All
            </button>
          )}
        </div>
      </div>

      {/* -- Connectors section -- */}
      {hasConnectors && (
        <div className="space-y-2">
          <h5 className="flex items-center gap-2 text-sm font-semibold text-muted-foreground/80 uppercase tracking-wider">
            <Link className="w-3 h-3" />
            Connectors ({connectorItems.length})
          </h5>

          {cs.statuses.map((status) => (
            <ConnectorRow
              key={status.name}
              status={status}
              tools={connectorToolMap.get(status.name) ?? []}
              credentials={credentials}
              isLinking={cs.linkingConnector === status.name}
              onToggleLink={() => cs.setLinkingConnector(cs.linkingConnector === status.name ? null : status.name)}
              onTest={() => void cs.testConnector(status.name, status.credentialId!)}
              onAddCredential={() => cs.handleAddCredential(status.name, status.n8nType)}
              onLinkCredential={(credId, credName) => cs.handleLinkCredential(status.name, credId, credName)}
            />
          ))}
        </div>
      )}

      {/* -- General Tools (no connector required) -- */}
      {hasGeneralTools && (
        <div className="bg-secondary/20 border border-primary/10 rounded-xl p-4">
          <h5 className="flex items-center gap-2 text-sm font-semibold text-muted-foreground/80 uppercase tracking-wider mb-2.5">
            <Wrench className="w-3 h-3" />
            General Tools ({generalTools.length})
          </h5>
          <div className="flex flex-wrap gap-1.5">
            {generalTools.map((tool) => (
              <span
                key={tool.name}
                className="px-2.5 py-1 text-sm font-mono rounded-xl bg-blue-500/10 text-blue-400 border border-blue-500/20"
                title={tool.description ?? undefined}
              >
                {tool.name}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* -- Triggers -- */}
      {hasTriggers && (
        <div className="bg-secondary/20 border border-primary/10 rounded-xl p-4">
          <h5 className="flex items-center gap-2 text-sm font-semibold text-muted-foreground/80 uppercase tracking-wider mb-2.5">
            <Zap className="w-3 h-3" />
            Triggers ({triggerItems.length})
          </h5>
          <div className="space-y-1.5">
            {triggerItems.map((trigger, i) => (
              <div key={i} className="flex items-center gap-2 text-sm text-foreground/90">
                <span className="px-1.5 py-0.5 text-sm font-mono rounded-lg bg-amber-500/10 text-amber-400 border border-amber-500/20">
                  {trigger.trigger_type}
                </span>
                <span className="truncate">{trigger.description}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Embedded credential design modal */}
      {cs.designOpen && (
        <div className="mt-4 border border-violet-500/20 rounded-xl">
          <CredentialDesignModal
            open={cs.designOpen}
            embedded
            initialInstruction={cs.designInstruction}
            onClose={cs.handleDesignClose}
            onComplete={cs.handleDesignComplete}
          />
        </div>
      )}
    </div>
  );
}
