import { Wrench, Zap, Link } from 'lucide-react';
import type { N8nPersonaDraft } from '@/api/n8nTransform';
import type { DesignAnalysisResult } from '@/lib/types/designTypes';

interface N8nToolsPreviewTabProps {
  draft?: N8nPersonaDraft;
  parsedResult: DesignAnalysisResult;
  selectedToolIndices: Set<number>;
  selectedTriggerIndices: Set<number>;
  selectedConnectorNames: Set<string>;
  onGoToAnalyze?: () => void;
}

export function N8nToolsPreviewTab({
  draft,
  parsedResult,
  selectedToolIndices,
  selectedTriggerIndices,
  selectedConnectorNames,
  onGoToAnalyze,
}: N8nToolsPreviewTabProps) {
  // Prefer draft entities (post-transform) over parser results (pre-transform)
  const draftObj = draft as unknown as Record<string, unknown> | undefined;
  const draftTools = draftObj && Array.isArray(draftObj.tools)
    ? (draftObj.tools as { name: string; category?: string; description?: string }[])
    : null;
  const draftTriggers = draftObj && Array.isArray(draftObj.triggers)
    ? (draftObj.triggers as { trigger_type: string; description?: string }[])
    : null;
  const draftConnectors = draftObj && Array.isArray(draftObj.required_connectors)
    ? (draftObj.required_connectors as { name: string; n8n_credential_type?: string; has_credential?: boolean }[])
    : null;

  // Fallback: parser results filtered by selections
  const selectedTools = parsedResult.suggested_tools.filter((_, i) => selectedToolIndices.has(i));
  const selectedTriggers = parsedResult.suggested_triggers.filter((_, i) => selectedTriggerIndices.has(i));
  const selectedConnectors = (parsedResult.suggested_connectors ?? []).filter((c) =>
    selectedConnectorNames.has(c.name),
  );

  const toolItems = draftTools ?? selectedTools.map((t) => ({ name: t }));
  const triggerItems = draftTriggers ?? selectedTriggers;
  const connectorItems = draftConnectors ?? selectedConnectors.map((c) => ({ name: c.name }));

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground/80">
          {draftTools
            ? 'These entities were generated by the transformation.'
            : 'These items from your n8n workflow will be associated with this persona.'}
        </p>
        {onGoToAnalyze && (
          <button
            onClick={onGoToAnalyze}
            className="px-3 py-1.5 text-sm rounded-lg border border-primary/15 text-muted-foreground/80 hover:bg-secondary/50 transition-colors"
          >
            Edit Selection
          </button>
        )}
      </div>

      {/* Tools */}
      {toolItems.length > 0 && (
        <div className="bg-secondary/20 border border-primary/10 rounded-2xl p-4">
          <h5 className="flex items-center gap-2 text-sm font-semibold text-muted-foreground/80 uppercase tracking-wider mb-2.5">
            <Wrench className="w-3 h-3" />
            Tools ({toolItems.length})
          </h5>
          <div className="flex flex-wrap gap-1.5">
            {toolItems.map((tool) => (
              <span
                key={tool.name}
                className="px-2.5 py-1 text-sm font-mono rounded-lg bg-blue-500/10 text-blue-400 border border-blue-500/20"
                title={'description' in tool ? (tool as { description?: string }).description : undefined}
              >
                {tool.name}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Triggers */}
      {triggerItems.length > 0 && (
        <div className="bg-secondary/20 border border-primary/10 rounded-2xl p-4">
          <h5 className="flex items-center gap-2 text-sm font-semibold text-muted-foreground/80 uppercase tracking-wider mb-2.5">
            <Zap className="w-3 h-3" />
            Triggers ({triggerItems.length})
          </h5>
          <div className="space-y-1.5">
            {triggerItems.map((trigger, i) => (
              <div key={i} className="flex items-center gap-2 text-sm text-foreground/90">
                <span className="px-1.5 py-0.5 text-sm font-mono rounded bg-amber-500/10 text-amber-400 border border-amber-500/20">
                  {trigger.trigger_type}
                </span>
                <span className="truncate">{trigger.description}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Connectors */}
      {connectorItems.length > 0 && (
        <div className="bg-secondary/20 border border-primary/10 rounded-2xl p-4">
          <h5 className="flex items-center gap-2 text-sm font-semibold text-muted-foreground/80 uppercase tracking-wider mb-2.5">
            <Link className="w-3 h-3" />
            Connectors ({connectorItems.length})
          </h5>
          <div className="flex flex-wrap gap-1.5">
            {connectorItems.map((conn) => (
              <span
                key={conn.name}
                className="px-2.5 py-1 text-sm font-medium rounded-lg bg-emerald-500/10 text-emerald-400 border border-emerald-500/20"
              >
                {conn.name}
              </span>
            ))}
          </div>
        </div>
      )}

      {toolItems.length === 0 && triggerItems.length === 0 && connectorItems.length === 0 && (
        <div className="text-center py-8 text-muted-foreground/80 text-sm">
          No items selected. Go back to the Analyze step to select tools and triggers.
        </div>
      )}
    </div>
  );
}
