// PROTOTYPE ROUND (spark council-readout). Dossier's own English words.
// Consolidation moves the winner's into `t.council` with all 14 locales.
export const S = {
  contents: 'Contents',
  verdict: 'Verdict',
  mustAddress: 'Must address',
  members: 'Members',
  evidence: 'Evidence',
  rounds: 'Rounds',
  scope: 'Scope',
  esc: 'Esc',
  overall: 'Overall',
  bar: 'bar',
  noOverall: 'No overall',
  noOverallWhy: 'Too little was measured to form one.',
  short: '{gap} short of the bar',
  clears: 'clears the bar by {gap}',
  measured: '{percent} of the weight measured',
  measuredTail: 'of the weight measured · floor {floor}',
  advisory:
    'Uncalibrated council: judged floors are advisory and the overall only orders the queue. Below the bar is a reading, not a refusal.',
  trusted: 'Calibrated council: floors and the bar bind.',
  fullRound: 'Full council',
  liteRound: 'Lite round',
  roundOf: 'round {round} of {cap}',
  liteNote: 'Lite rounds are read, never decided. A full council has to run before this can reach you.',
  oldRound: 'You are reading round {round}. The gate decides the latest round only.',
  summaryFallback: 'The council left no summary. This is the subject’s own description.',
  hardFailures: 'Hard failures',
  nothingToAddress: 'The council asked for nothing to be addressed.',
  general: 'Council',
  weight: '{percent} of the overall',
  floor: 'floor {floor}',
  advisoryFloor: 'advisory floor {floor}',
  floorHit: 'Below its floor',
  confidence: '{level} confidence',
  kind: { mechanical: 'Mechanical', judged: 'Judged', mixed: 'Mixed' } as Record<string, string>,
  level: { low: 'Low', med: 'Medium', high: 'High' } as Record<string, string>,
  severity: { high: 'High', med: 'Medium', low: 'Low' } as Record<string, string>,
  notMeasured: 'Not measured',
  notApplicable: 'Not applicable',
  notRun: 'The round never reached this member.',
  carried: 'Carried from an earlier round',
  seen: 'seen {count} times',
  readMore: 'Read the whole finding',
  readLess: 'Show less',
  noFindings: 'No findings.',
  findings: '{count} findings',
  moreEvidence: 'Show {count} more',
  lessEvidence: 'Show fewer',
  techniques: 'Registry techniques',
  proof: { execution: 'executed', inspection: 'inspected', claim: 'claimed' } as Record<string, string>,
  roundLabel: 'Round {round}',
  onScreen: 'On screen',
  latest: 'Latest',
  show: 'Read this round',
  paths: '{count} files judged',
  allPaths: 'Every file in the span',
  head: 'Head',
  finished: 'Finished',
  ingested: 'Ingested',
  runDir: 'Run folder',
  copy: 'Copy the run folder',
  figure: 'Each member’s score, drawn as tall as its weight',
  figureHint: 'Band height is the member’s weight; the line is the bar.',
  loading: 'Reading the council',
};

/** `{name}` interpolation for the strings above. */
export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => String(vars[k] ?? ''));
}
