/**
 * Commands referenced in the frontend that are NOT yet registered in the Rust
 * invoke_handler. These are either planned commands or dead code.
 *
 * When a command is implemented and added to lib.rs invoke_handler, re-run
 * `node scripts/generate-command-names.mjs` and remove it from this list.
 */
export type UnregisteredCommand =
  | "persona_blast_radius"
  | "credential_blast_radius"
  | "automation_blast_radius"
  | "dev_tools_accept_idea"
  | "dev_tools_batch_create_tasks"
  | "dev_tools_cancel_task"
  | "dev_tools_delete_triage_idea"
  | "dev_tools_generate_context_description"
  | "dev_tools_get_active_project"
  | "dev_tools_get_batch_status"
  | "dev_tools_cancel_scan"
  | "dev_tools_list_scan_agents"
  | "dev_tools_move_context"
  | "dev_tools_run_scan"
  | "dev_tools_record_goal_signal"
  | "dev_tools_reject_idea"
  | "dev_tools_run_triage_rules"
  | "dev_tools_cancel_scan_codebase"
  | "dev_tools_get_scan_codebase_status"
  | "dev_tools_scan_codebase"
  | "dev_tools_scan_directory"
  | "dev_tools_set_active_project"
  | "dev_tools_start_batch"
  | "dev_tools_start_task"
  | "dev_tools_execute_task"
  | "dev_tools_cancel_task_execution"
  | "dev_tools_triage_ideas"
  | "gitlab_connect_from_vault"
  | "gitlab_get_job_log"
  | "gitlab_get_pipeline"
  | "gitlab_list_pipeline_jobs"
  | "gitlab_list_pipelines"
  | "gitlab_trigger_pipeline"
  | "get_persona_config_warnings"
  | "get_persona_detail"
  | "create_chat_session"
  | "seed_mock_event"
  | "seed_mock_message"
  | "start_build_session"
  | "answer_build_question"
  | "cancel_build_session"
  | "get_active_build_session"
  | "list_build_sessions"
  | "promote_build_draft"
  | "test_build_draft"
  | "zapier_create_zap"
  | "zapier_list_zaps"
  | "zapier_trigger_webhook"
  | "cloud_webhook_relay_status"
  | "smee_get_channel_url"
  | "smee_set_channel_url"
  | "smee_disconnect"
  | "smee_relay_list"
  | "smee_relay_create"
  | "smee_relay_update"
  | "smee_relay_set_status"
  | "smee_relay_delete"
  | "get_execution_log_lines"

  | "cloud_get_execution_output"
  | "resolve_effective_config"
  | "gitlab_list_persona_versions"
  | "gitlab_deploy_persona_versioned"
  | "gitlab_rollback_persona"
  | "gitlab_list_persona_branches"
  | "gitlab_setup_persona_branches"
  | "sign_document"
  | "verify_document"
  | "list_document_signatures"
  | "get_document_signature"
  | "delete_document_signature"
  | "export_signature_sidecar"
  | "write_sidecar_file"
  | "read_sidecar_file"
  | "ocr_with_gemini"
  | "ocr_with_claude"
  | "list_ocr_documents"
  | "get_ocr_document"
  | "delete_ocr_document"
  | "save_chat_session_context"
  | "get_chat_session_context"
  | "get_latest_chat_session"
  | "gitlab_list_deployment_history"
  | "gitlab_rollback_from_history"
  | "get_app_setting"
  | "set_app_setting"
  | "delete_app_setting"
  | "verify_template_integrity"
  | "verify_template_integrity_batch"
  | "get_template_manifest_count"
  | "resolve_share_deep_link"
  // Alert Rules (backend-persisted)
  | "list_alert_rules"
  | "create_alert_rule"
  | "update_alert_rule"
  | "delete_alert_rule"
  | "toggle_alert_rule"
  | "list_fired_alerts"
  | "create_fired_alert"
  | "dismiss_fired_alert"
  | "clear_fired_alerts"
  // Cross-project / codebases
  | "dev_tools_get_cross_project_map"
  | "dev_tools_upsert_cross_project_relation"
  | "dev_tools_list_cross_project_relations"
  | "dev_tools_create_idea_batch"
  | "dev_tools_search_across_projects"
  | "dev_tools_get_project_summary"
  | "dev_tools_get_dependency_graph"
  // Implementation pipeline
  | "dev_tools_create_branch"
  | "dev_tools_apply_diff"
  | "dev_tools_run_tests"
  | "dev_tools_get_git_status"
  | "dev_tools_commit_changes"
  // Portfolio intelligence
  | "dev_tools_get_portfolio_health"
  | "dev_tools_get_tech_radar"
  | "dev_tools_get_risk_matrix"
  // Shared events
  | "shared_events_browse_catalog"
  | "shared_events_refresh_catalog"
  | "shared_events_subscribe"
  | "shared_events_unsubscribe"
  | "shared_events_list_subscriptions"
  // Claude Desktop MCP
  | "register_claude_desktop_mcp"
  | "unregister_claude_desktop_mcp"
  | "check_claude_desktop_mcp";
