import { test, expect } from '@playwright/test';
import { bridge, CompanionBridge } from './companion-bridge';

/**
 * Goal-to-Plan planner smoke test against the live Tauri app (idea-ba306c32).
 *
 * Pre-req:
 *   npm run tauri:dev:test
 * (App must be on a master build that includes the merged planner arc, so the
 * Personas → Plan tab + `plan_goal_llm` command are present.)
 *
 * Verifies the whole read-only scenario is achievable end-to-end:
 *  1. Personas → Plan opens (sidebar `tab-planner`).
 *  2. Empty state offers clickable starter-goal examples.
 *  3. Typing a goal surfaces the live intent-signal chips.
 *  4. "Preview plan" produces a plan — exercises the real PlanProvider seam:
 *     `plan_goal_llm` (Sonnet via the Claude CLI) first, deterministic rule
 *     planner as fallback. Either brain is a pass; the test logs which ran.
 *  5. The plan renders reviewable steps (the confirm-gate step is always last).
 *  6. The "Watch the plan" player advances (status line shows "Step …").
 *  7. The "Create a persona" hand-off into the build composer is present.
 *
 * Nothing here mutates persona/connector/trigger state — the planner is
 * read-only and the hand-off uses autoLaunch=false.
 *
 * Bridge methods: navigate, clickTestId, fillField, query, findText, waitFor.
 */

let app: CompanionBridge;

async function gotoPlannerFresh(app: CompanionBridge): Promise<void> {
  // Bounce through another section so the Personas pane remounts the planner
  // fresh (clears any plan generated by a prior step).
  await app.navigate('overview');
  await app.navigate('personas');
  const tab = await app.query('[data-testid="tab-planner"]');
  if (tab.length === 0) {
    throw new Error(
      'tab-planner not found — is the running app a master build with the merged planner arc (idea-ba306c32)?',
    );
  }
  await app.clickTestId('tab-planner');
  await app.waitFor('[data-testid="planner-goal-input"]', 8_000);
}

const GOAL = 'Watch a competitor pricing page daily and email me the changes';

test.describe('Goal-to-Plan planner smoke', () => {
  test.setTimeout(180_000);

  test.beforeAll(async () => {
    app = bridge();
    const h = await app.health();
    expect(h.status).toBe('ok');
  });

  test('empty state offers starter-goal examples', async () => {
    await gotoPlannerFresh(app);
    const examples = await app.query('[data-testid="planner-example-goal"]');
    expect(examples.length).toBeGreaterThan(0);
  });

  test('typing a goal surfaces live intent chips', async () => {
    await gotoPlannerFresh(app);
    await app.fillField('planner-goal-input', GOAL);
    // Chips render off the goal state — give React a tick.
    await app.waitFor('[data-testid="planner-intent-chips"]', 5_000);
    const chips = await app.query('[data-testid="planner-intent-chips"]');
    expect(chips.length).toBeGreaterThan(0);
  });

  test('preview produces a reviewable plan (LLM brain or rule fallback)', async () => {
    await gotoPlannerFresh(app);
    await app.fillField('planner-goal-input', GOAL);
    await app.clickTestId('planner-preview-button');

    // The plan-only "Watch" button appears once a plan exists. The LLM brain
    // (Claude CLI) can take tens of seconds; allow generous headroom.
    await app.waitFor('[data-testid="planner-watch-button"]', 120_000);

    // Log which brain produced the plan (both are acceptable).
    const llm = await app.findText('AI-generated preview');
    const rule = await app.findText('Rule-based preview');
    const brain = llm.length > 0 ? 'LLM (plan_goal_llm / Sonnet)' : rule.length > 0 ? 'rule fallback' : 'unknown';
    // eslint-disable-next-line no-console
    console.log(`[planner-smoke] plan generated by: ${brain}`);

    // The confirm-gate step is always present and always last.
    const confirm = await app.findText('Review & confirm');
    expect(confirm.length).toBeGreaterThan(0);

    // The graduate-to-build hand-off is offered.
    const handoff = await app.query('[data-testid="planner-start-build"]');
    expect(handoff.length).toBeGreaterThan(0);
  });

  test('Watch player advances through the steps', async () => {
    await gotoPlannerFresh(app);
    await app.fillField('planner-goal-input', GOAL);
    await app.clickTestId('planner-preview-button');
    await app.waitFor('[data-testid="planner-watch-button"]', 120_000);

    await app.clickTestId('planner-watch-button');
    // Status line reads "Step N of M" while playing.
    await app.waitFor('[data-testid="planner-watch-button"]', 2_000).catch(() => {});
    const step = await app.findText('Step ');
    expect(step.length).toBeGreaterThan(0);
  });
});
