/* ==============================================================================
   Scenario Parser
   Parses the harness-scenario.md into a typed ScenarioDefinition.
   For the personas 3-goal scenario, this provides a hardcoded definition
   that matches the markdown spec exactly.
   ============================================================================== */

import type { ScenarioDefinition, ScenarioArea, ScenarioGoal, VerificationGate } from './types';

// ---------------------------------------------------------------------------
//  Personas 3-Goal Scenario
// ---------------------------------------------------------------------------

export function getPersonasScenario(): ScenarioDefinition {
  return {
    title: 'Codebase-Wide Quality Goals',
    goals: GOALS,
    areas: AREAS,
    customGates: CUSTOM_GATES,
  };
}

const GOALS: ScenarioGoal[] = [
  {
    id: 'typography',
    title: 'Typography Token Coverage',
    description: 'All typography uses semantic typo-* classes with dynamic text-scale support',
    successCriteria: [
      '0 raw text-{size} classes in .tsx files',
      '0 raw font-{weight} classes (weight is part of semantic class)',
      'All text renders at all 4 scale tiers',
    ],
  },
  {
    id: 'i18n',
    title: 'Full i18n Coverage',
    description: 'All user-facing text uses useTranslation() hook and translation keys',
    successCriteria: [
      'Every .tsx with user-facing text imports useTranslation',
      'All placeholder, title, aria-label attributes use t.* keys',
      'All JSX text content uses t.* keys',
      'Translation keys added to en.ts',
    ],
  },
  {
    id: 'notifications',
    title: 'Background LLM Process Notifications',
    description: 'All background LLM processes have sidebar indicator, OS notification, in-app notification with redirect',
    successCriteria: [
      'All 10 processes have sidebar pulsing indicator',
      'All 10 trigger OS notification on completion',
      'All 10 add to notification center with redirect button',
      'Notification center in header with unread count badge',
    ],
  },
];

const CUSTOM_GATES: VerificationGate[] = [
  {
    name: 'typography-audit',
    type: 'custom',
    required: false,
    command: 'grep -rn "\\btext-xs\\b\\|\\btext-sm\\b\\|\\btext-base\\b\\|\\btext-lg\\b\\|\\btext-xl\\b\\|\\btext-2xl\\b\\|\\btext-3xl\\b\\|\\btext-4xl\\b" src/features/ --include="*.tsx" | grep -v "text-foreground\\|text-muted\\|text-background\\|text-primary\\|text-secondary\\|text-accent\\|text-status\\|text-brand\\|text-card\\|text-destructive\\|text-white\\|text-black\\|text-inherit\\|text-current\\|text-transparent\\|text-center\\|text-left\\|text-right\\|text-ellipsis\\|text-wrap\\|text-nowrap\\|text-balance\\|text-clip\\|text-start\\|text-end" | wc -l',
  },
  {
    name: 'i18n-audit',
    type: 'custom',
    required: false,
    command: 'grep -rn \'placeholder="[A-Z]\\|title="[A-Z]\\|aria-label="[A-Z]\' src/features/ --include="*.tsx" | grep -v "node_modules\\|\\.test\\." | wc -l',
  },
  {
    name: 'notification-coverage',
    type: 'custom',
    required: false,
    command: 'grep -rn "notifyProcessComplete" src/ --include="*.ts" --include="*.tsx" | wc -l',
  },
];

// ---------------------------------------------------------------------------
//  Area Definitions (35 total)
// ---------------------------------------------------------------------------

const AREAS: ScenarioArea[] = [
  // ── Tier 0: Foundation ──────────────────────────────────────────────────
  {
    id: 'typo-mapping',
    moduleId: 'typography',
    label: 'Typography Mapping Reference',
    description: 'Create definitive mapping from raw Tailwind text classes to semantic typo-* classes. Document the mapping, handle ambiguous cases, create grep audit pattern.',
    scope: ['docs/harness/'],
    features: [
      'Document text-* to typo-* mapping table',
      'Handle ambiguous font-weight cases',
      'Create migration grep pattern',
    ],
    dependsOn: [],
  },
  {
    id: 'i18n-key-structure',
    moduleId: 'i18n',
    label: 'i18n Key Structure Expansion',
    description: 'Expand en.ts key structure to cover all feature areas with namespaces for agents, overview, triggers, credentials, templates, plugins, deployment.',
    scope: ['src/i18n/en.ts'],
    features: [
      'Add key namespaces for all feature areas',
      'Add keys for common patterns (tables, empty states, tooltips)',
      'Maintain translator guide comments',
    ],
    dependsOn: [],
  },
  {
    id: 'notification-infra',
    moduleId: 'notifications',
    label: 'Notification Infrastructure',
    description: 'Extend notification center store with ProcessNotification type, addProcessNotification(), markAsReadByRedirect(), redirect button component, combined unread count.',
    scope: ['src/stores/', 'src/features/shared/components/'],
    features: [
      'ProcessNotification type with redirectPath',
      'addProcessNotification() store action',
      'markProcessReadByNavigation() action',
      'Redirect button component',
      'Combined unread count (pipeline + process)',
    ],
    dependsOn: [],
  },

  // ── Tier 1: Typography Migration ────────────────────────────────────────
  {
    id: 'typo-shared',
    moduleId: 'typography',
    label: 'shared/components Typography',
    description: 'Migrate all shared components to typo-* classes: buttons, forms, display, feedback, layout, overlays, editors.',
    scope: ['src/features/shared/components/'],
    features: [
      'buttons/ uses typo-* classes',
      'forms/ uses typo-* classes',
      'display/ uses typo-* classes',
      'feedback/ uses typo-* classes',
      'layout/ uses typo-* classes',
      'overlays/ uses typo-* classes',
      'editors/ uses typo-* classes',
    ],
    dependsOn: ['typo-mapping'],
  },
  {
    id: 'typo-home',
    moduleId: 'typography',
    label: 'home/ Typography',
    description: 'Migrate home feature to typo-* classes.',
    scope: ['src/features/home/'],
    features: ['HomeWelcome.tsx', 'LanguageSwitcher.tsx', 'All home sub-components'],
    dependsOn: ['typo-mapping'],
  },
  {
    id: 'typo-settings',
    moduleId: 'typography',
    label: 'settings/ Typography',
    description: 'Migrate settings feature to typo-* classes.',
    scope: ['src/features/settings/'],
    features: ['SettingsPage tabs', 'AccountSettings', 'AppearanceSettings', 'NotificationSettings', 'All sub-settings panels'],
    dependsOn: ['typo-mapping'],
  },
  {
    id: 'typo-overview',
    moduleId: 'typography',
    label: 'overview/ Typography',
    description: 'Migrate overview feature to typo-* classes: dashboard, executions, events, health, memories, messages, manual-review, knowledge, timeline, cron agents.',
    scope: ['src/features/overview/'],
    features: [
      'OverviewPage dashboard',
      'sub_executions/',
      'sub_events/',
      'sub_health/',
      'sub_memories/',
      'sub_messages/',
      'sub_manual-review/',
      'sub_knowledge/',
      'sub_timeline/',
      'sub_cron_agents/',
    ],
    dependsOn: ['typo-mapping'],
  },
  {
    id: 'typo-agents-core',
    moduleId: 'typography',
    label: 'agents/ Typography (core)',
    description: 'Migrate agents core components to typo-* classes: creation, matrix, onboarding, persona, chat.',
    scope: ['src/features/agents/components/'],
    features: [
      'creation/ steps',
      'matrix/ components',
      'onboarding/ components',
      'persona/ components',
      'ChatThread.tsx',
    ],
    dependsOn: ['typo-mapping'],
  },
  {
    id: 'typo-agents-sub',
    moduleId: 'typography',
    label: 'agents/ Typography (sub-features)',
    description: 'Migrate agents sub-features to typo-* classes.',
    scope: ['src/features/agents/sub_activity/', 'src/features/agents/sub_connectors/', 'src/features/agents/sub_design/', 'src/features/agents/sub_lab/', 'src/features/agents/sub_prompt/', 'src/features/agents/sub_tests/', 'src/features/agents/sub_tools/', 'src/features/agents/sub_versions/'],
    features: ['sub_activity/', 'sub_connectors/', 'sub_design/', 'sub_lab/', 'sub_prompt/', 'sub_tests/', 'sub_tools/', 'sub_versions/'],
    dependsOn: ['typo-agents-core'],
  },
  {
    id: 'typo-triggers',
    moduleId: 'typography',
    label: 'triggers/ Typography',
    description: 'Migrate triggers feature to typo-* classes.',
    scope: ['src/features/triggers/'],
    features: ['sub_builder/', 'sub_live_stream/', 'sub_studio/'],
    dependsOn: ['typo-mapping'],
  },
  {
    id: 'typo-templates',
    moduleId: 'typography',
    label: 'templates/ Typography',
    description: 'Migrate templates feature to typo-* classes.',
    scope: ['src/features/templates/'],
    features: ['sub_generated/', 'sub_n8n/'],
    dependsOn: ['typo-mapping'],
  },
  {
    id: 'typo-plugins',
    moduleId: 'typography',
    label: 'plugins/ Typography',
    description: 'Migrate plugins feature to typo-* classes.',
    scope: ['src/features/plugins/'],
    features: ['artist/', 'dev-tools/'],
    dependsOn: ['typo-mapping'],
  },
  {
    id: 'typo-remaining',
    moduleId: 'typography',
    label: 'Remaining Typography',
    description: 'Migrate remaining features: personas page, schedules, deployment, credentials.',
    scope: ['src/features/personas/', 'src/features/schedules/', 'src/features/deployment/', 'src/features/credentials/'],
    features: ['PersonasPage.tsx', 'schedules/', 'deployment/', 'credentials/'],
    dependsOn: ['typo-mapping'],
  },

  // ── Tier 2: i18n Migration ──────────────────────────────────────────────
  {
    id: 'i18n-shared',
    moduleId: 'i18n',
    label: 'shared/components i18n',
    description: 'Add translation keys to all shared components: buttons, forms, modals, panels, tooltips.',
    scope: ['src/features/shared/'],
    features: ['Button labels', 'Form placeholders', 'Modal titles', 'Panel headers', 'Tooltip text', 'aria-labels'],
    dependsOn: ['i18n-key-structure'],
  },
  {
    id: 'i18n-home',
    moduleId: 'i18n',
    label: 'home/ i18n',
    description: 'Verify and complete i18n for home feature (already partially done).',
    scope: ['src/features/home/'],
    features: ['Verify all strings use t.* keys', 'Add any missing keys'],
    dependsOn: ['i18n-key-structure'],
  },
  {
    id: 'i18n-settings',
    moduleId: 'i18n',
    label: 'settings/ i18n',
    description: 'Add i18n to settings feature: tab labels, form labels, descriptions, toggles.',
    scope: ['src/features/settings/'],
    features: ['Tab labels', 'Form labels and descriptions', 'Toggle labels', 'Help text'],
    dependsOn: ['i18n-key-structure'],
  },
  {
    id: 'i18n-overview',
    moduleId: 'i18n',
    label: 'overview/ i18n',
    description: 'Add i18n to overview feature: dashboard labels, widget titles, table headers, status labels.',
    scope: ['src/features/overview/'],
    features: ['Dashboard labels', 'Widget titles', 'Table headers', 'Status labels', 'Event log labels', 'Memory cards', 'Review panel text'],
    dependsOn: ['i18n-key-structure'],
  },
  {
    id: 'i18n-agents-core',
    moduleId: 'i18n',
    label: 'agents/ i18n (core)',
    description: 'Add i18n to agents core components: creation wizard, matrix, onboarding, chat.',
    scope: ['src/features/agents/components/'],
    features: ['Creation wizard labels', 'Matrix table headers', 'Onboarding text', 'Chat messages', 'Persona overview labels'],
    dependsOn: ['i18n-key-structure'],
  },
  {
    id: 'i18n-agents-sub',
    moduleId: 'i18n',
    label: 'agents/ i18n (sub-features)',
    description: 'Add i18n to agents sub-features: activity, connectors, design, lab, prompt, tools.',
    scope: ['src/features/agents/sub_activity/', 'src/features/agents/sub_connectors/', 'src/features/agents/sub_design/', 'src/features/agents/sub_lab/', 'src/features/agents/sub_prompt/', 'src/features/agents/sub_tests/', 'src/features/agents/sub_tools/', 'src/features/agents/sub_versions/'],
    features: ['Activity labels', 'Connector UI text', 'Design conversation labels', 'Lab result labels', 'Prompt editor labels', 'Tool config text'],
    dependsOn: ['i18n-agents-core'],
  },
  {
    id: 'i18n-triggers',
    moduleId: 'i18n',
    label: 'triggers/ i18n',
    description: 'Add i18n to triggers feature: canvas, event bus, live stream, studio.',
    scope: ['src/features/triggers/'],
    features: ['Canvas labels', 'Modal text', 'Event bus labels', 'Live stream labels', 'Studio palette labels'],
    dependsOn: ['i18n-key-structure'],
  },
  {
    id: 'i18n-templates',
    moduleId: 'i18n',
    label: 'templates/ i18n',
    description: 'Add i18n to templates feature: adoption view, gallery, build modal, n8n import.',
    scope: ['src/features/templates/'],
    features: ['Adoption view labels', 'Questionnaire text', 'Gallery labels', 'Build modal text', 'n8n import labels'],
    dependsOn: ['i18n-key-structure'],
  },
  {
    id: 'i18n-plugins',
    moduleId: 'i18n',
    label: 'plugins/ i18n',
    description: 'Add i18n to plugins feature: artist gallery, dev tools.',
    scope: ['src/features/plugins/'],
    features: ['Artist gallery labels', 'Dev tools labels'],
    dependsOn: ['i18n-key-structure'],
  },
  {
    id: 'i18n-remaining',
    moduleId: 'i18n',
    label: 'Remaining i18n',
    description: 'Add i18n to remaining features: personas page, schedules, deployment, credentials.',
    scope: ['src/features/personas/', 'src/features/schedules/', 'src/features/deployment/', 'src/features/credentials/'],
    features: ['PersonasPage.tsx', 'schedules/', 'deployment/', 'credentials/'],
    dependsOn: ['i18n-key-structure'],
  },

  // ── Tier 3: Notifications ──────────────────────────────────────────────
  {
    id: 'notify-center',
    moduleId: 'notifications',
    label: 'Notification Center Extension',
    description: 'Extend notification center store: ProcessNotification type, addProcessNotification(), markProcessRead(), combined unread count, localStorage persistence.',
    scope: ['src/stores/'],
    features: ['ProcessNotification type', 'addProcessNotification()', 'markProcessRead()', 'markProcessReadByNavigation()', 'Combined unread count', 'localStorage persistence (max 100)'],
    dependsOn: ['notification-infra'],
  },
  {
    id: 'notify-bell-ui',
    moduleId: 'notifications',
    label: 'Notification Bell UI',
    description: 'Update header bell icon: combined unread badge, process notifications list, view/redirect button, mark as read.',
    scope: ['src/features/shared/components/layout/'],
    features: ['Combined unread count badge', 'Process notification list item', 'View redirect button', 'Mark as read on click', 'Mark all as read', 'Empty state'],
    dependsOn: ['notify-center'],
  },
  {
    id: 'notify-os-util',
    moduleId: 'notifications',
    label: 'OS Notification Utility',
    description: 'Create reusable notifyProcessComplete() helper: checks permission, sends OS notification, adds to notification center store.',
    scope: ['src/lib/', 'src/api/'],
    features: ['notifyProcessComplete() helper', 'Permission check + request', 'OS notification with title/body', 'Dual delivery (OS + app notification center)'],
    dependsOn: ['notify-center'],
  },
  {
    id: 'notify-n8n',
    moduleId: 'notifications',
    label: 'n8nTransform Notifications',
    description: 'Add OS + app notifications to n8nTransform. Redirect: templates > n8n tab.',
    scope: ['src/features/templates/sub_n8n/', 'src/hooks/'],
    features: ['notifyProcessComplete() on completion', 'Redirect to templates > n8n'],
    dependsOn: ['notify-os-util'],
  },
  {
    id: 'notify-execution',
    moduleId: 'notifications',
    label: 'Execution Notifications',
    description: 'Add OS + app notifications to agent execution completion. Redirect: agents > persona > executions tab.',
    scope: ['src/stores/slices/agents/', 'src/hooks/'],
    features: ['notifyProcessComplete() on finish', 'Redirect to agents > persona > executions'],
    dependsOn: ['notify-os-util'],
  },
  {
    id: 'notify-lab',
    moduleId: 'notifications',
    label: 'Lab Run Notifications',
    description: 'Add OS + app notifications to lab runs. Redirect: agents > persona > lab tab.',
    scope: ['src/stores/slices/agents/', 'src/hooks/'],
    features: ['notifyProcessComplete() on lab completion', 'Redirect to agents > persona > lab'],
    dependsOn: ['notify-os-util'],
  },
  {
    id: 'notify-matrix',
    moduleId: 'notifications',
    label: 'Matrix Build Notifications',
    description: 'Add OS + app notifications to matrix build. Redirect: agents > persona > matrix tab.',
    scope: ['src/stores/slices/agents/'],
    features: ['notifyProcessComplete() on build completion', 'Redirect to agents > persona > matrix'],
    dependsOn: ['notify-os-util'],
  },
  {
    id: 'notify-connector',
    moduleId: 'notifications',
    label: 'Connector Test Notifications',
    description: 'Add OS + app notifications to connector test. Redirect: agents > persona > connectors tab.',
    scope: ['src/hooks/', 'src/features/agents/'],
    features: ['notifyProcessComplete() on test completion', 'Redirect to agents > persona > connectors'],
    dependsOn: ['notify-os-util'],
  },
  {
    id: 'notify-creative',
    moduleId: 'notifications',
    label: 'Creative Session Notifications',
    description: 'Add OS + app notifications to artist/blender sessions. Redirect: plugins > artist > gallery.',
    scope: ['src/stores/slices/system/', 'src/features/plugins/artist/'],
    features: ['notifyProcessComplete() on session completion', 'Redirect to plugins > artist > gallery'],
    dependsOn: ['notify-os-util'],
  },
  {
    id: 'notify-context-scan',
    moduleId: 'notifications',
    label: 'Context Scan App Notification',
    description: 'Add app notification to context scan (already has OS notification). Redirect: plugins > dev-tools > context-map.',
    scope: ['src/features/plugins/dev-tools/hooks/'],
    features: ['Add to notification center on completion', 'Redirect to dev-tools > context-map'],
    dependsOn: ['notify-os-util'],
  },
  {
    id: 'notify-rebuild-test',
    moduleId: 'notifications',
    label: 'Rebuild + Template Test Notifications',
    description: 'Add OS notifications to rebuild and templateTest (already have app notifications). Add redirect buttons.',
    scope: ['src/hooks/design/core/'],
    features: ['OS notification on rebuild completion', 'OS notification on template test completion', 'Redirect button for rebuild (agents > persona > overview)', 'Redirect button for templateTest (agents > persona > tests)'],
    dependsOn: ['notify-os-util'],
  },
  {
    id: 'notify-adopt-redirect',
    moduleId: 'notifications',
    label: 'Template Adopt Redirect',
    description: 'Add redirect button to templateAdopt notification (already has OS + app). Redirect: agents > adopted persona.',
    scope: ['src/features/templates/sub_generated/adoption/'],
    features: ['Redirect to agents > adopted persona'],
    dependsOn: ['notify-os-util'],
  },
];
