/**
 * The plan, as a local fixture - and why one exists at all.
 *
 * `curator_plan_run` has 0 rows today: the instrument has never run, so there
 * is no projection to draw. The variant still has to be judged on a full
 * ledger, so these 19 rows are lifted VERBATIM from the registry's own scan
 * (`src-tauri/src/commands/curator/fixtures/librarian-scan.json`, 471 subjects)
 * and re-scored with the scan's own weights. Nothing here is invented: the
 * subject ids, the points, the clause sentences, `demandKnown` and the
 * application counts are the scan's.
 *
 * Three of the four inks come straight out of the corpus, by the same rules
 * `model/buildModel.ts` uses:
 *  - SCORED: a clause the scan wrote, at the points it scored.
 *  - UNKNOWN: channels 1 and 7 are written by consumers, and demand is read in
 *    5 of the 10 bundles. In the other 5 nobody has looked.
 *  - MEASURED ZERO: everything else. Citation-gone, expired and no-use_when
 *    occur exactly 0 times in this corpus - measured, and found none.
 *
 * The fourth, UNMEASURABLE, has no producer in `buildModel` yet (its own
 * comment says so: the clock figures are corpus-wide, so it cannot make a
 * per-subject claim). It is derived here from a fact the scan DOES carry per
 * subject: 5 of these subjects have `applications: 0`, and "expired
 * application" / "application near its clock" cannot be asked of a subject
 * with no application to age. That is the shape the cell will take the day the
 * backend can say it, and the ink has to exist before then or the four facts
 * collapse into three.
 */
import type { CellMark } from '../../../model/types';
import type { ChannelId } from '../../../model/channels';

/** One subject the plan would act on, cut down to what this variant draws. */
export interface PlanRow {
  id: string;
  domain: string;
  slug: string;
  taxonomy: string;
  points: number;
  techniques: number;
  applications: number;
  stacks: string[];
  demandKnown: boolean;
  lastSwept: string | null;
  engine: string;
  state: string;
  cells: Record<ChannelId, CellMark>;
}

export const PLAN_ROWS: readonly PlanRow[] = [
  {"id":"software-engineering/agent-memory","domain":"software-engineering","slug":"agent-memory","taxonomy":"llm-agent/prompt-and-context","points":56,"techniques":27,"applications":27,"stacks":["bun","claude-code","node","python","rust","sql"],"demandKnown":true,"lastSwept":"2026-09-07","engine":"conform","state":"dispatched","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"measured-zero"},"5":{"kind":"measured-zero"},"6":{"kind":"measured-zero"},"7":{"kind":"scored","mark":{"channel":7,"code":"deviation","points":56,"detail":"14–28 consumer deviation(s)","count":14,"floor":14,"ceil":28}},"8":{"kind":"measured-zero"},"9":{"kind":"measured-zero"}}},
  {"id":"software-engineering/quality-gates","domain":"software-engineering","slug":"quality-gates","taxonomy":"engineering-process/standards-and-gates","points":52,"techniques":26,"applications":26,"stacks":["claude-code","cpp","next","node","process","python","react","rust"],"demandKnown":true,"lastSwept":"2026-09-06","engine":"conform","state":"planned","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"measured-zero"},"5":{"kind":"measured-zero"},"6":{"kind":"measured-zero"},"7":{"kind":"scored","mark":{"channel":7,"code":"deviation","points":52,"detail":"13 consumer deviation(s)","count":13,"floor":13}},"8":{"kind":"measured-zero"},"9":{"kind":"measured-zero"}}},
  {"id":"software-engineering/accessibility","domain":"software-engineering","slug":"accessibility","taxonomy":"ui-surfaces/feedback-and-style","points":44,"techniques":8,"applications":6,"stacks":["react","rust"],"demandKnown":true,"lastSwept":"2026-09-01","engine":"conform","state":"landed","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"measured-zero"},"5":{"kind":"measured-zero"},"6":{"kind":"measured-zero"},"7":{"kind":"scored","mark":{"channel":7,"code":"deviation","points":44,"detail":"11–17 consumer deviation(s)","count":11,"floor":11,"ceil":17}},"8":{"kind":"measured-zero"},"9":{"kind":"measured-zero"}}},
  {"id":"software-engineering/diff-comparison","domain":"software-engineering","slug":"diff-comparison","taxonomy":"ui-surfaces/data-display","points":43,"techniques":8,"applications":8,"stacks":["next","react","rust"],"demandKnown":true,"lastSwept":null,"engine":"conform","state":"planned","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"measured-zero"},"5":{"kind":"scored","mark":{"channel":5,"code":"never_swept","points":3,"detail":"never swept by the librarian"}},"6":{"kind":"measured-zero"},"7":{"kind":"scored","mark":{"channel":7,"code":"deviation","points":40,"detail":"10–20 consumer deviation(s)","count":10,"floor":10,"ceil":20}},"8":{"kind":"measured-zero"},"9":{"kind":"measured-zero"}}},
  {"id":"llm-observability/operator-surfaces-for-llm-spend","domain":"llm-observability","slug":"operator-surfaces-for-llm-spend","taxonomy":"federation-and-surfaces","points":40,"techniques":6,"applications":3,"stacks":["process","rust"],"demandKnown":true,"lastSwept":"2026-09-10","engine":"conform","state":"planned","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"measured-zero"},"5":{"kind":"measured-zero"},"6":{"kind":"measured-zero"},"7":{"kind":"scored","mark":{"channel":7,"code":"deviation","points":40,"detail":"10–20 consumer deviation(s)","count":10,"floor":10,"ceil":20}},"8":{"kind":"measured-zero"},"9":{"kind":"measured-zero"}}},
  {"id":"software-engineering/templates-scaffolding","domain":"software-engineering","slug":"templates-scaffolding","taxonomy":"integration/external-systems","points":21,"techniques":6,"applications":3,"stacks":["react"],"demandKnown":true,"lastSwept":null,"engine":"conform","state":"idled","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"measured-zero"},"5":{"kind":"scored","mark":{"channel":5,"code":"never_swept","points":3,"detail":"never swept by the librarian"}},"6":{"kind":"measured-zero"},"7":{"kind":"scored","mark":{"channel":7,"code":"deviation","points":16,"detail":"4–8 consumer deviation(s)","count":4,"floor":4,"ceil":8}},"8":{"kind":"scored","mark":{"channel":8,"code":"single_stack","points":2,"detail":"single stack (react)","stack":"react"}},"9":{"kind":"measured-zero"}}},
  {"id":"software-engineering/conditional-service-composition","domain":"software-engineering","slug":"conditional-service-composition","taxonomy":"operations/service-operations","points":13,"techniques":3,"applications":0,"stacks":[],"demandKnown":true,"lastSwept":null,"engine":"apply","state":"planned","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"scored","mark":{"channel":2,"code":"no_application","points":6,"detail":"no application — never reconciled against real code"}},"3":{"kind":"unmeasurable"},"4":{"kind":"scored","mark":{"channel":4,"code":"thin_techniques","points":4,"detail":"3 techniques (design floor is 4)","count":3,"designFloor":4}},"5":{"kind":"scored","mark":{"channel":5,"code":"never_swept","points":3,"detail":"never swept by the librarian"}},"6":{"kind":"measured-zero"},"7":{"kind":"measured-zero"},"8":{"kind":"measured-zero"},"9":{"kind":"unmeasurable"}}},
  {"id":"software-engineering/connector-catalog","domain":"software-engineering","slug":"connector-catalog","taxonomy":"integration/external-systems","points":13,"techniques":6,"applications":3,"stacks":["react"],"demandKnown":true,"lastSwept":null,"engine":"conform","state":"planned","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"measured-zero"},"5":{"kind":"scored","mark":{"channel":5,"code":"never_swept","points":3,"detail":"never swept by the librarian"}},"6":{"kind":"measured-zero"},"7":{"kind":"scored","mark":{"channel":7,"code":"deviation","points":8,"detail":"2 consumer deviation(s)","count":2,"floor":2}},"8":{"kind":"scored","mark":{"channel":8,"code":"single_stack","points":2,"detail":"single stack (react)","stack":"react"}},"9":{"kind":"measured-zero"}}},
  {"id":"agent-operations/agent-benchmark-design","domain":"agent-operations","slug":"agent-benchmark-design","taxonomy":"measurement","points":9,"techniques":3,"applications":1,"stacks":["process"],"demandKnown":false,"lastSwept":null,"engine":"deepen","state":"planned","cells":{"1":{"kind":"unknown"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"scored","mark":{"channel":4,"code":"thin_techniques","points":4,"detail":"3 techniques (design floor is 4)","count":3,"designFloor":4}},"5":{"kind":"scored","mark":{"channel":5,"code":"never_swept","points":3,"detail":"never swept by the librarian"}},"6":{"kind":"measured-zero"},"7":{"kind":"unknown"},"8":{"kind":"scored","mark":{"channel":8,"code":"single_stack","points":2,"detail":"single stack (process)","stack":"process"}},"9":{"kind":"measured-zero"}}},
  {"id":"agent-operations/agent-run-budgeting","domain":"agent-operations","slug":"agent-run-budgeting","taxonomy":"configuration-choice","points":9,"techniques":3,"applications":2,"stacks":["process"],"demandKnown":false,"lastSwept":null,"engine":"deepen","state":"planned","cells":{"1":{"kind":"unknown"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"scored","mark":{"channel":4,"code":"thin_techniques","points":4,"detail":"3 techniques (design floor is 4)","count":3,"designFloor":4}},"5":{"kind":"scored","mark":{"channel":5,"code":"never_swept","points":3,"detail":"never swept by the librarian"}},"6":{"kind":"measured-zero"},"7":{"kind":"unknown"},"8":{"kind":"scored","mark":{"channel":8,"code":"single_stack","points":2,"detail":"single stack (process)","stack":"process"}},"9":{"kind":"measured-zero"}}},
  {"id":"software-engineering/embedded-db","domain":"software-engineering","slug":"embedded-db","taxonomy":"backend-platform/data-layer","points":9,"techniques":10,"applications":8,"stacks":["c","go","node","python","rust"],"demandKnown":true,"lastSwept":"2026-09-02","engine":"conform","state":"planned","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"measured-zero"},"5":{"kind":"measured-zero"},"6":{"kind":"measured-zero"},"7":{"kind":"scored","mark":{"channel":7,"code":"deviation","points":8,"detail":"2 consumer deviation(s)","count":2,"floor":2}},"8":{"kind":"measured-zero"},"9":{"kind":"scored","mark":{"channel":9,"code":"at_risk_application","points":1,"detail":"1 application(s) near their clock","count":1}}}},
  {"id":"software-engineering/native-document-format","domain":"software-engineering","slug":"native-document-format","taxonomy":"integration/acquisition-and-ingest","points":9,"techniques":6,"applications":0,"stacks":[],"demandKnown":true,"lastSwept":null,"engine":"apply","state":"planned","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"scored","mark":{"channel":2,"code":"no_application","points":6,"detail":"no application — never reconciled against real code"}},"3":{"kind":"unmeasurable"},"4":{"kind":"measured-zero"},"5":{"kind":"scored","mark":{"channel":5,"code":"never_swept","points":3,"detail":"never swept by the librarian"}},"6":{"kind":"measured-zero"},"7":{"kind":"measured-zero"},"8":{"kind":"measured-zero"},"9":{"kind":"unmeasurable"}}},
  {"id":"game-production/imported-material-conformance","domain":"game-production","slug":"imported-material-conformance","taxonomy":"asset-production/surface-and-imagery","points":6,"techniques":6,"applications":0,"stacks":[],"demandKnown":true,"lastSwept":"2026-09-10","engine":"apply","state":"planned","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"scored","mark":{"channel":2,"code":"no_application","points":6,"detail":"no application — never reconciled against real code"}},"3":{"kind":"unmeasurable"},"4":{"kind":"measured-zero"},"5":{"kind":"measured-zero"},"6":{"kind":"measured-zero"},"7":{"kind":"measured-zero"},"8":{"kind":"measured-zero"},"9":{"kind":"unmeasurable"}}},
  {"id":"localization/translation-quality-measurement","domain":"localization","slug":"translation-quality-measurement","taxonomy":"craft","points":6,"techniques":10,"applications":0,"stacks":[],"demandKnown":false,"lastSwept":"2026-09-14","engine":"apply","state":"planned","cells":{"1":{"kind":"unknown"},"2":{"kind":"scored","mark":{"channel":2,"code":"no_application","points":6,"detail":"no application — never reconciled against real code"}},"3":{"kind":"unmeasurable"},"4":{"kind":"measured-zero"},"5":{"kind":"measured-zero"},"6":{"kind":"measured-zero"},"7":{"kind":"unknown"},"8":{"kind":"measured-zero"},"9":{"kind":"unmeasurable"}}},
  {"id":"software-engineering/durable-agent-operations","domain":"software-engineering","slug":"durable-agent-operations","taxonomy":"llm-agent/orchestration","points":6,"techniques":6,"applications":0,"stacks":[],"demandKnown":true,"lastSwept":"2026-09-09","engine":"apply","state":"planned","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"scored","mark":{"channel":2,"code":"no_application","points":6,"detail":"no application — never reconciled against real code"}},"3":{"kind":"unmeasurable"},"4":{"kind":"measured-zero"},"5":{"kind":"measured-zero"},"6":{"kind":"measured-zero"},"7":{"kind":"measured-zero"},"8":{"kind":"measured-zero"},"9":{"kind":"unmeasurable"}}},
  {"id":"software-engineering/bounded-enumeration","domain":"software-engineering","slug":"bounded-enumeration","taxonomy":"backend-platform/data-layer","points":5,"techniques":6,"applications":3,"stacks":["go"],"demandKnown":true,"lastSwept":null,"engine":"reconcile","state":"planned","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"measured-zero"},"5":{"kind":"scored","mark":{"channel":5,"code":"never_swept","points":3,"detail":"never swept by the librarian"}},"6":{"kind":"measured-zero"},"7":{"kind":"measured-zero"},"8":{"kind":"scored","mark":{"channel":8,"code":"single_stack","points":2,"detail":"single stack (go)","stack":"go"}},"9":{"kind":"measured-zero"}}},
  {"id":"marketing/answer-engine-visibility","domain":"marketing","slug":"answer-engine-visibility","taxonomy":"search-and-content","points":2,"techniques":6,"applications":2,"stacks":["prompt-pipeline"],"demandKnown":false,"lastSwept":"2026-09-09","engine":"deepen","state":"planned","cells":{"1":{"kind":"unknown"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"measured-zero"},"5":{"kind":"measured-zero"},"6":{"kind":"measured-zero"},"7":{"kind":"unknown"},"8":{"kind":"scored","mark":{"channel":8,"code":"single_stack","points":2,"detail":"single stack (prompt-pipeline)","stack":"prompt-pipeline"}},"9":{"kind":"measured-zero"}}},
  {"id":"civic-intelligence/accountability-publishing-ethics","domain":"civic-intelligence","slug":"accountability-publishing-ethics","taxonomy":"accountability-method","points":0,"techniques":6,"applications":2,"stacks":["process","react"],"demandKnown":false,"lastSwept":"2026-09-09","engine":"none","state":"planned","cells":{"1":{"kind":"unknown"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"measured-zero"},"5":{"kind":"measured-zero"},"6":{"kind":"measured-zero"},"7":{"kind":"unknown"},"8":{"kind":"measured-zero"},"9":{"kind":"measured-zero"}}},
  {"id":"game-production/asset-class-poly-budgeting","domain":"game-production","slug":"asset-class-poly-budgeting","taxonomy":"asset-production/geometry","points":0,"techniques":6,"applications":2,"stacks":["node","process"],"demandKnown":true,"lastSwept":"2026-09-10","engine":"none","state":"planned","cells":{"1":{"kind":"measured-zero"},"2":{"kind":"measured-zero"},"3":{"kind":"measured-zero"},"4":{"kind":"measured-zero"},"5":{"kind":"measured-zero"},"6":{"kind":"measured-zero"},"7":{"kind":"measured-zero"},"8":{"kind":"measured-zero"},"9":{"kind":"measured-zero"}}},];

/**
 * The largest single cell in the plan (56 points). Every bar in every
 * signature is drawn against this one number, so a tall bar means the same
 * thing on row 1 and on row 19.
 */
export const MAX_CELL_POINTS = PLAN_ROWS.reduce((max, row) => {
  for (const cell of Object.values(row.cells)) {
    if (cell.kind === 'scored' && cell.mark.points > max) max = cell.mark.points;
  }
  return max;
}, 1);
