/** PROTOTYPE COPY — migrated to i18n if this variant wins */

export const grokCopy = {
  searchPlaceholder: 'Find by title or body',
  searchAria: 'Filter notes by title or body',
  matching: '{count} matching',
  noMatches: 'No notes match that filter.',
  noMatchesHint: 'Press Escape to clear, then type a broader query.',
  cheatTitle: 'Desk keys',
  cheatSubtitle: 'The lamp follows the selected note. Every verb the mouse can reach is a key.',
  groupNav: 'Move',
  groupFilter: 'Filter',
  groupAct: 'Selected note',
  navArrows: 'Move the lamp across the grid',
  navVim: 'Previous / next note',
  navHome: 'First note',
  navEnd: 'Last note',
  navOpen: 'Open in the editor',
  filterFind: 'Find by title or body',
  filterEsc: 'Clear find, then step out',
  filterStatus: 'Drafts / scoped / all',
  filterProject: 'Jump to a project tab',
  filterCycle: 'Cycle project tabs',
  actAsk: 'Ask Athena',
  actPublish: 'Publish to Fleet',
  actGoals: 'Turn into goals',
  actThread: 'Open thread',
  actReply: 'Reply in the thread',
  actApprove: 'Approve a pending review',
  actReject: 'Reject a pending review',
  actDelete: 'Delete permanently',
  actHelp: 'This cheat sheet',
  hintMove: 'Move',
  hintOpen: 'Open',
  hintFind: 'Find',
  hintRails: 'Rails',
  hintHelp: 'Keys',
  hintAsk: 'Ask',
  hintPublish: 'Publish',
  hintGoals: 'Goals',
  hintThread: 'Thread',
  hintReply: 'Reply',
  hintYes: 'Approve',
  hintNo: 'Reject',
  hintDelete: 'Delete',
  selectedAria: 'Selected note',
  captureHint: 'Enter',
} as const;

export type GrokCopyKey = keyof typeof grokCopy;
