import type { AdoptState } from './adoptTypes';

export const INITIAL_STATE: AdoptState = {
  step: 'choose',
  templateName: '',
  reviewId: '',
  designResult: null,
  designResultJson: '',
  selectedUseCaseIds: new Set(),
  selectedToolIndices: new Set(),
  selectedTriggerIndices: new Set(),
  selectedConnectorNames: new Set(),
  selectedChannelIndices: new Set(),
  selectedEventIndices: new Set(),
  variableValues: {},
  triggerConfigs: {},
  questions: null,
  userAnswers: {},
  questionGenerating: false,
  connectorCredentialMap: {},
  inlineCredentialConnector: null,
  connectorSwaps: {},
  requireApproval: false,
  autoApproveSeverity: 'info',
  reviewTimeout: '24h',
  memoryEnabled: true,
  memoryScope: '',
  transforming: false,
  backgroundAdoptId: null,
  adjustmentRequest: '',
  transformPhase: 'idle',
  transformLines: [],
  draft: null,
  draftJson: '',
  draftJsonError: null,
  confirming: false,
  created: false,
  partialEntityErrors: [],
  showEditInline: false,
  error: null,
  databaseMode: 'create',
  selectedTableNames: [],
  databaseTable: '',
  databaseSchema: '',
  autoResolved: false,
  safetyCriticalOverride: false,
};
