//! Index-file knowledge navigation.
//!
//! Inspired by Karpathy-style LLM knowledge bases (research run 2026-04-08).
//! Karpathy's insight: *"I thought I had to reach for fancy RAG, but the LLM
//! has been pretty good about auto-maintaining index files."* For small-to-
//! medium knowledge bases, an auto-maintained `index.md` describing the file
//! tree is dramatically cheaper than embeddings, fully explainable, and lets
//! the agent navigate by browse rather than vector search.
//!
//! This module is a **complement** to the existing vector KB
//! (`engine/kb_ingest.rs`), not a replacement. Use it when:
//!
//! - The KB is < 1000 markdown files (vector index overhead isn't worth it).
//! - You want the agent to *browse* rather than *retrieve* (deterministic).
//! - You want a human-readable map of what's available alongside the data.
//!
//! It produces a single `index.md` that lists every note grouped by folder,
//! with headings extracted so the agent can tell what each note is about
//! before opening it.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use chrono::Utc;

use crate::error::AppError;

/// Default name of the generated index file.
pub const DEFAULT_INDEX_FILENAME: &str = "index.md";

/// Maximum number of headings to extract per file. The index is meant to be
/// a high-level map, not a TOC — keep it skimmable.
const MAX_HEADINGS_PER_FILE: usize = 3;

/// Maximum number of files to surface inside a single folder. Folders with
/// more than this get a count + the most-recently-modified subset.
const MAX_FILES_PER_FOLDER: usize = 50;

/// Build the index for a knowledge base directory tree.
///
/// Returns the index content as a string. Caller decides whether to write
/// it to disk or pass it directly into a prompt.
pub fn build_index(root: &Path) -> Result<String, AppError> {
    if !root.exists() || !root.is_dir() {
        return Err(AppError::Validation(format!(
            "Index root does not exist or is not a directory: {}",
            root.display()
        )));
    }

    // Group .md files by their containing directory (relative to root).
    let mut by_folder: BTreeMap<String, Vec<NoteEntry>> = BTreeMap::new();
    walk(root, root, &mut by_folder)?;

    let total_files: usize = by_folder.values().map(|v| v.len()).sum();
    let folder_count = by_folder.len();

    let mut out = String::new();
    out.push_str("# Knowledge Base Index\n\n");
    out.push_str(&format!(
        "> Auto-generated by personas `kb_index` on {}.\n",
        Utc::now().to_rfc3339()
    ));
    out.push_str(&format!(
        "> Root: `{}` — {} folder(s), {} note(s).\n\n",
        root.display(),
        folder_count,
        total_files
    ));
    out.push_str("This file is the agent's entry point. Each section below \
is a folder; each bullet is a note. Use the headings under each note to \
decide whether to open it.\n\n");

    if by_folder.is_empty() {
        out.push_str("_(No markdown files found.)_\n");
        return Ok(out);
    }

    for (folder, notes) in &by_folder {
        let folder_label = if folder.is_empty() { "/ (root)" } else { folder };
        out.push_str(&format!("## {}\n\n", folder_label));

        if notes.len() > MAX_FILES_PER_FOLDER {
            out.push_str(&format!(
                "_{} notes total — showing {} most recently modified._\n\n",
                notes.len(),
                MAX_FILES_PER_FOLDER
            ));
        }

        let limit = MAX_FILES_PER_FOLDER.min(notes.len());
        for note in notes.iter().take(limit) {
            // Bullet line: filename (linked) + first heading if any.
            let title = note.first_heading.clone().unwrap_or_else(|| note.filename.clone());
            out.push_str(&format!("- **{}** — `{}`\n", title, note.relative_path));

            // Subsequent headings as nested bullets, capped to keep the file readable.
            for heading in note.headings.iter().skip(1).take(MAX_HEADINGS_PER_FILE - 1) {
                out.push_str(&format!("    - {}\n", heading));
            }
        }
        out.push('\n');
    }

    Ok(out)
}

/// Build the index AND write it to `<root>/<filename>`. Returns the path
/// of the file that was written.
pub fn build_and_write_index(root: &Path, filename: Option<&str>) -> Result<PathBuf, AppError> {
    let content = build_index(root)?;
    let target = root.join(filename.unwrap_or(DEFAULT_INDEX_FILENAME));
    std::fs::write(&target, content)
        .map_err(|e| AppError::Internal(format!("write index file {}: {e}", target.display())))?;
    Ok(target)
}

#[derive(Debug, Clone)]
struct NoteEntry {
    filename: String,
    relative_path: String,
    /// All H1/H2 headings extracted from the note, in document order.
    headings: Vec<String>,
    /// Convenience accessor for the first heading (often the title).
    first_heading: Option<String>,
    /// mtime as unix seconds, for "most recently modified" sort.
    mtime_secs: i64,
}

fn walk(
    root: &Path,
    dir: &Path,
    out: &mut BTreeMap<String, Vec<NoteEntry>>,
) -> Result<(), AppError> {
    let entries = std::fs::read_dir(dir)
        .map_err(|e| AppError::Internal(format!("read_dir {}: {e}", dir.display())))?;

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            // Skip dot-dirs (.obsidian, .git, .trash, etc.) and the index file itself.
            if path
                .file_name()
                .and_then(|n| n.to_str())
                .map(|n| n.starts_with('.'))
                .unwrap_or(false)
            {
                continue;
            }
            walk(root, &path, out)?;
        } else if path.extension().map(|e| e == "md").unwrap_or(false) {
            // Skip the index.md itself if it lives in this tree, so the
            // index doesn't reference itself.
            if path.file_name().and_then(|n| n.to_str()) == Some(DEFAULT_INDEX_FILENAME) {
                continue;
            }

            let folder = relative_folder(root, &path);
            let filename = path
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("")
                .to_string();
            let relative_path = relative_path(root, &path);
            let headings = extract_headings(&path);
            let first_heading = headings.first().cloned();
            let mtime_secs = mtime_unix(&path);

            out.entry(folder).or_default().push(NoteEntry {
                filename,
                relative_path,
                headings,
                first_heading,
                mtime_secs,
            });
        }
    }

    // After populating, sort each folder's notes by mtime descending so the
    // "max files" cap surfaces the freshest material.
    for notes in out.values_mut() {
        notes.sort_by(|a, b| b.mtime_secs.cmp(&a.mtime_secs));
    }

    Ok(())
}

fn relative_folder(root: &Path, file: &Path) -> String {
    let rel = file.strip_prefix(root).unwrap_or(file);
    rel.parent()
        .map(|p| p.display().to_string().replace('\\', "/"))
        .unwrap_or_default()
}

fn relative_path(root: &Path, file: &Path) -> String {
    file.strip_prefix(root)
        .unwrap_or(file)
        .display()
        .to_string()
        .replace('\\', "/")
}

fn mtime_unix(path: &Path) -> i64 {
    std::fs::metadata(path)
        .and_then(|m| m.modified())
        .ok()
        .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

/// Pull H1/H2 headings out of a markdown file. Returns at most a handful —
/// the index is meant to be a map, not a transcript.
fn extract_headings(path: &Path) -> Vec<String> {
    let content = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return Vec::new(),
    };

    let mut out = Vec::new();
    let mut in_code_fence = false;
    for line in content.lines() {
        // Skip headings inside fenced code blocks.
        if line.starts_with("```") {
            in_code_fence = !in_code_fence;
            continue;
        }
        if in_code_fence {
            continue;
        }
        let trimmed = line.trim_start();
        if let Some(rest) = trimmed.strip_prefix("# ") {
            out.push(rest.trim().to_string());
        } else if let Some(rest) = trimmed.strip_prefix("## ") {
            out.push(rest.trim().to_string());
        }
        if out.len() >= MAX_HEADINGS_PER_FILE {
            break;
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::io::Write;

    fn write(path: &Path, content: &str) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        let mut f = fs::File::create(path).unwrap();
        f.write_all(content.as_bytes()).unwrap();
    }

    #[test]
    fn build_index_empty_dir() {
        let tmp = tempfile::tempdir().unwrap();
        let idx = build_index(tmp.path()).unwrap();
        assert!(idx.contains("Knowledge Base Index"));
        assert!(idx.contains("0 folder"));
        assert!(idx.contains("0 note"));
        assert!(idx.contains("No markdown files"));
    }

    #[test]
    fn build_index_extracts_headings() {
        let tmp = tempfile::tempdir().unwrap();
        write(
            &tmp.path().join("notes/foo.md"),
            "# Foo Title\n\nIntro paragraph.\n\n## Section A\nstuff\n\n## Section B\nmore\n",
        );
        let idx = build_index(tmp.path()).unwrap();
        assert!(idx.contains("Foo Title"));
        assert!(idx.contains("Section A"));
        assert!(idx.contains("notes/foo.md"));
    }

    #[test]
    fn build_index_skips_dot_dirs_and_self() {
        let tmp = tempfile::tempdir().unwrap();
        write(&tmp.path().join("real.md"), "# Real\n");
        write(&tmp.path().join(".obsidian/config.md"), "# Hidden\n");
        write(&tmp.path().join(DEFAULT_INDEX_FILENAME), "# Old Index\n");

        let idx = build_index(tmp.path()).unwrap();
        assert!(idx.contains("Real"));
        assert!(!idx.contains("Hidden"));
        // The index file itself shouldn't list itself.
        assert!(!idx.contains("Old Index"));
    }

    #[test]
    fn build_index_handles_no_headings() {
        let tmp = tempfile::tempdir().unwrap();
        write(&tmp.path().join("plain.md"), "just text, no heading\n");
        let idx = build_index(tmp.path()).unwrap();
        // Falls back to filename when no heading found.
        assert!(idx.contains("plain.md"));
    }

    #[test]
    fn build_and_write_index_creates_file() {
        let tmp = tempfile::tempdir().unwrap();
        write(&tmp.path().join("a.md"), "# A\n");
        let written = build_and_write_index(tmp.path(), None).unwrap();
        assert!(written.exists());
        assert!(written.ends_with(DEFAULT_INDEX_FILENAME));
        let body = fs::read_to_string(&written).unwrap();
        assert!(body.contains("Knowledge Base Index"));
    }

    #[test]
    fn extract_headings_skips_code_fences() {
        let tmp = tempfile::tempdir().unwrap();
        let p = tmp.path().join("code.md");
        write(
            &p,
            "# Real Heading\n\n```\n# Not a heading\n## Also not\n```\n\n## Real Section\n",
        );
        let headings = extract_headings(&p);
        assert_eq!(headings.len(), 2);
        assert_eq!(headings[0], "Real Heading");
        assert_eq!(headings[1], "Real Section");
    }
}
