// PROTOTYPE COPY — migrated to i18n if this variant wins.
//
// Every string the v2 desk needs that has no existing `t.notepad.*` /
// `t.common.*` key lives here, in one object, so the migration is one move into
// `en.json` (+ the 13 locales) and one find-and-replace of `COPY.` → `t.notepad.desk_v2_`.
// Templates use the same `{name}` placeholders `tx` interpolates.
export const COPY = {
  mode_browse: 'Browse',
  mode_find: 'Find',
  mode_write: 'Write',
  find_placeholder: 'Find a note — title or body. Esc clears',
  find_count: '{shown} of {total}',
  find_no_match_title: 'No note matches “{query}”',
  find_no_match_create: 'Press Enter to keep it as a new draft',
  filters_empty_title: 'Nothing on this desk under these filters',
  filters_reset: 'Show every note',
  hint_find: 'find',
  hint_keep: 'keep',
  hint_send: 'send',
  hint_close: 'close',
  hint_pick: 'Pick a note with the arrow keys or j / k',
  selected_announce: 'Selected: {title}',
  project_prev: 'Previous project',
  project_next: 'Next project',
  project_all: 'All projects',
  keys_title: 'Keyboard',
  keys_open: 'All keys',
  keys_group_move: 'Move',
  keys_group_filter: 'Find & filter',
  keys_group_note: 'The selected note',
  keys_group_review: 'Thread & review',
  key_move: 'Move the cursor across the grid',
  key_next_prev: 'Next / previous note',
  key_ends: 'First / last note',
  key_open: 'Open in the editor',
  key_find: 'Find — fuzzy over title and body',
  key_write: 'Write — capture a new draft',
  key_status: 'Drafts · Scoped · All',
  key_project: 'Previous / next project',
  key_project_all: 'All projects',
  key_escape: 'Clear the filter, then step out',
  key_ask: 'Ask Athena',
  key_edit: 'Write on the card',
  key_step: 'Take the next lifecycle step',
  key_publish: 'Publish to Fleet',
  key_goals: 'Turn into goals',
  key_menu: 'All actions (menu)',
  key_archive: 'Archive',
  key_delete: 'Delete permanently',
  key_thread: 'Open the thread',
  key_reply: 'Reply in the thread',
  key_approve: 'Approve the waiting review',
  key_reject: 'Reject the waiting review',
  key_keys: 'Show / hide this panel',
  chip_open: 'Open',
  chip_reply: 'Reply',
  chip_thread: 'Thread',
  chip_ask: 'Ask',
  chip_edit: 'Write',
  no_review: 'No review is waiting on this note.',
  approved: 'Approved.',
  rejected: 'Rejected.',
  edit_locked: 'This note is too long or no longer a draft to write on its card — Enter opens it.',
  archived: 'Archived. Restore it from the archive drawer.',
  replying_to: 'Replying to {author}',
  compose_ask_title: 'Ask Athena about this note',
  compose_reply_title: 'Reply in the thread',
  // Keycap faces that are words, not glyphs.
  keycap_esc: 'Esc',
  keycap_del: 'Del',
  keycap_home: 'Home',
  keycap_end: 'End',
  keycap_menu: 'Shift F10',
} as const;
