/**
 * P1 prototype copy. Dev-only prototype chrome: English data, not product
 * copy (the census excludes this folder; the consolidation package moves the
 * survivor's strings into `t.monitor.dc_*`). Kept in one object so the JSX
 * stays free of literals and the eventual i18n move is one file.
 */
import type { DecisionKind, HubChip } from '../../../model/decisionModel';

export const COPY = {
  chip: {
    gates: 'Gates',
    proposals: 'Proposals',
    backlog: 'Backlog',
    incidents: 'Incidents',
    council: 'Council',
    reports: 'Reports',
    chat: 'Chat',
    ready: 'Ready',
  } satisfies Record<HubChip, string>,
  chipHint: {
    gates: 'Reviews, build questions and Athena approvals holding work',
    proposals: 'Policy, evolution and goal sign-offs',
    backlog: 'Scanner ideas waiting for accept or reject',
    incidents: 'Failures and alerts that need a call',
    council: 'Council verdicts to approve or send back',
    reports: 'Reports waiting to be read',
    chat: 'Threads waiting for your reply',
    ready: 'Accepted ideas ready to dispatch',
  } satisfies Record<HubChip, string>,
  kind: {
    review: 'Review gate',
    question: 'Build question',
    approval: 'Athena approval',
    policy: 'Policy proposal',
    evolution: 'Evolution proposal',
    goal: 'Goal sign-off',
    idea: 'Backlog idea',
    incident: 'Incident',
    council: 'Council verdict',
    report: 'Report',
    message: 'Chat',
  } satisfies Record<DecisionKind, string>,
  /** What saying YES does, when the item carries no alert of its own. */
  consequence: {
    review: 'The run continues exactly as drafted.',
    question: 'Your answers are submitted and the build resumes.',
    approval: 'Athena carries out the action now.',
    policy: 'The change applies to every future run.',
    evolution: 'The challenger replaces the incumbent.',
    goal: 'The goal closes as done.',
    idea: 'The idea moves to Ready to dispatch.',
    incident: 'The incident is marked resolved.',
    council: 'The verdict is accepted and the work proceeds.',
    report: 'The report is marked read.',
    message: 'Your reply posts to the thread.',
  } satisfies Record<DecisionKind, string>,
  /** Queue name when the Lab opens straight onto a modal type. */
  typeScope: { approval: 'approvals', backlog: 'Backlog', report: 'reports & council', chat: 'Chat' },
  strip: {
    triageAll: 'Triage all',
    needYou: 'need you',
    next: 'Next',
    failed: 'Source did not answer',
    none: 'Nothing waiting',
    fleetPlaceholder: 'Fleet state tally · layout · toggle',
  },
  peek: {
    open: 'Open',
    dispatch: 'Dispatch',
    dispatchAll: 'Dispatch all',
    clear: 'All clear here.',
    failed: 'This source did not answer. Counts are unknown, not zero.',
    confirmReject: 'Enter to reject',
    walk: 'move',
    openKey: 'open',
    close: 'close',
  },
  cost: {
    oneKey: 'one key',
    answers: (n: number) => `${n} answer${n === 1 ? '' : 's'}`,
    read: (min: number) => `${min} min read`,
    reply: 'reply',
    effort: (v: string) => `effort ${v}/10`,
  },
  sheet: {
    of: 'of',
    in: 'in',
    triageAll: 'all decisions',
    prev: 'Previous',
    next: 'Next',
    close: 'Close',
    ifDone: 'When you mark it done',
    ifYes: (verb: string) => `If you ${verb.toLowerCase()}`,
    facts: 'Facts',
    case: 'The case',
    why: 'Why it was raised',
    evidence: 'Evidence',
    category: 'Category',
    origin: 'Origin',
    options: 'Other ways to answer',
    links: 'Look first',
    questions: 'Answer to continue',
    contents: 'Contents',
    format: 'Format',
    htmlNote: 'HTML document, rendered sandboxed with its own styles. Contents are not indexed.',
    progress: 'read',
    rate: 'Rate',
    composer: 'Write a reply',
    send: 'Send',
    newline: 'new line',
    cannotReply: 'This channel takes replies in its own view only.',
    askedYou: 'Asked of you',
    reasonMin: (n: number) => `${n} / 12 characters minimum`,
    noReason: 'No reason',
    withReason: 'Reject with reason',
    sendBack: 'Send back',
    confirm: 'Enter to confirm',
    cancel: 'Esc cancel',
    armedReject: 'Reject this?',
    armedAccept: 'Approve this verdict?',
    queueEmpty: 'Queue cleared',
  },
  keys: {
    walk: 'walk',
    scroll: 'scroll',
    later: 'later',
    back: 'back',
    branch: 'option',
    rate: 'rate',
    reply: 'reply',
    done: 'done',
  },
  verdict: {
    accept: 'Approved',
    reject: 'Rejected',
    done: 'Marked done',
    reply: 'Reply sent',
    skip: 'Later',
  },
} as const;
