// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A live summary of one chain that currently has in-flight work — the answer
 * to "what chains are running right now?", which was otherwise unanswerable
 * (CascadeMetrics is log-only and the Chain tab is retrospective per-run).
 *
 * Grouped from the currently `running`/`queued` executions by the
 * `chain_trace_id` carried in each run's `input_data`.
 */
export type ActiveChain = { 
/**
 * The distributed chain trace id shared by every hop of this chain.
 */
chainTraceId: string, 
/**
 * How many executions of this chain are in flight right now (running or
 * queued). This is a LIVE count, not the chain's lifetime hop total.
 */
inFlightCount: number, 
/**
 * The deepest hop reached so far (max `_chain_depth` across the in-flight
 * runs). Bounded by `MAX_CHAIN_DEPTH`.
 */
maxDepth: number, 
/**
 * USD spent by the chain up to its most recent completed hop — the max of
 * the accumulated `_chain_cost_usd` propagated in the in-flight runs'
 * metadata. In-flight runs have not booked their own cost yet, so this is
 * spend-through-the-latest-hop, not including the running hops themselves.
 */
accumulatedCostUsd: number, 
/**
 * Distinct personas with in-flight work in this chain (first-seen order).
 */
personaIds: Array<string>, 
/**
 * When the oldest in-flight run of this chain began (its `started_at`, or
 * `created_at` when not yet started) — the chain's live age anchor.
 */
oldestStartedAt: string, };
