// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many personas are running right now, and the ceiling they are measured
 * against.
 *
 * Reported by `GET /dev-tools/app-master/{project}` and rendered into the App
 * Master's decision prompt, so an autonomous loop planning a workforce can see
 * how much of the machine is already busy.
 */
export type ActivePersonaHeadroom = { 
/**
 * Personas holding at least one queued or running execution right now.
 *
 * Renamed from `active` on 2026-09-08 with the meaning: the old field
 * counted `enabled = 1 AND lifecycle = 'active'` ROWS, which is roster
 * size. A reader that still says "active personas" is describing the
 * roster and is wrong about this number.
 */
running: number, 
/**
 * The configured ceiling — `max_active_personas`, or its default.
 */
cap: number, };
