// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One per-member adoption failure. `reason` is a human-readable string
 * from the underlying error chain; the frontend renders it inline next
 * to the failed role in the preview modal's status table.
 */
export type AdoptedTeamPresetFailure = { role: string, template_id: string, reason: string, };
