// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported alert severity levels.
 */
export type AlertSeverity = "info" | "warning" | "critical";
