// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AmbientSignalEntry } from "./AmbientSignalEntry";

/**
 * A snapshot of the fused ambient context, ready for prompt injection.
 */
export type AmbientContextSnapshot = { 
/**
 * Current focused app (if known).
 */
activeApp: string | null, 
/**
 * Current window title (if known).
 */
activeWindowTitle: string | null, 
/**
 * Rolling signal entries.
 */
signals: Array<AmbientSignalEntry>, 
/**
 * Total signals captured since engine start.
 */
totalSignalsCaptured: bigint, 
/**
 * Whether ambient context is enabled.
 */
enabled: boolean, };
