// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single entry in the snapshot (serialisable version of AmbientSignal).
 */
export type AmbientSignalEntry = { 
/**
 * Stable per-signal id (format `sig_<n>`), assigned at capture time.
 * Used by the "What did Athena see?" view to delete a single row
 * without timestamp-collision races.
 */
id: string, source: string, summary: string, capturedAt: bigint, 
/**
 * Seconds ago relative to snapshot time.
 */
ageSecs: bigint, };
