// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AmendGoalInput = { title: string | null, description: string | null, 
/**
 * `open` | `in-progress` | `blocked` | `awaiting_acceptance`. `done` is
 * refused: closing a goal is the operator's acceptance.
 */
status: string | null, };
