// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The things that should make an operator look: consecutive failed passes,
 * today's refusals, disputed memories, drafts the human threw out this week.
 */
export type AnomalyStrip = { 
/**
 * Consecutive most-recent ledger rows with `verdict = 'failed'`.
 */
failedStreak: number, refusedToday: number, 
/**
 * Memories with at least one open negative claim.
 */
openDisputes: number, 
/**
 * Review proposals discarded in the last 7 days (any kind).
 */
rejectedDrafts7d: number, };
