// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiParameter } from "./ApiParameter";
import type { ApiRequestBody } from "./ApiRequestBody";

export type ApiEndpoint = { method: string, path: string, summary: string | null, description: string | null, parameters: ApiParameter[], request_body: ApiRequestBody | null, tags: string[], };
