// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parameter for an API endpoint.
 */
export type ApiParameter = { name: string, 
/**
 * "path", "query", "header", or "cookie"
 */
location: string, required: boolean, schema_type: string | null, description: string | null, };
