// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivePersonaHeadroom } from "./ActivePersonaHeadroom";
import type { AppMasterCharterOutcome } from "./AppMasterCharterOutcome";
import type { AppMasterOpenAsk } from "./AppMasterOpenAsk";

/**
 * What the adoption actually did. Every field is a fact; `notes` carries
 * everything that did not happen and why.
 */
export type AppMasterAdoption = { personaId: string, personaName: string, projectId: string, 
/**
 * True when this call created the persona; false when it updated one.
 */
created: boolean, charters: Array<AppMasterCharterOutcome>, 
/**
 * Recipe slugs whose charter this call suspended because the request no
 * longer names them. Suspended, never deleted.
 */
suspended: Array<string>, 
/**
 * `None` when the manifest could not be seeded — see `notes`.
 */
manifestPath?: string, notes: Array<string>, 
/**
 * Questions this App Master has put to the operator that nobody has
 * answered. Empty on the adopt path — an adoption has not woken yet, so it
 * cannot have asked anything.
 */
openAsks: Array<AppMasterOpenAsk>, 
/**
 * The App Master's own last word about where it stands: the newest
 * coverage note its decision lane wrote. `None` when it has never decided.
 *
 * Reported here because a terminal reading this route is otherwise looking
 * at charter titles and statuses — none of which say *the loop is blocked
 * and here is what it needs*, which is the one thing the note carries.
 */
lastNote?: string, 
/**
 * How many personas the machine is RUNNING and the ceiling on that (G17),
 * as measured when this response was built.
 *
 * A concurrency reading, not a headcount: since 2026-09-08 nothing here
 * refuses an adoption or a hire. It is reported so a headless caller can
 * see how busy the machine is and pace itself — a full machine means the
 * personas it starts will WAIT, which is a reason to finish work in flight
 * before widening the front, not a reason not to hire.
 */
activePersonas: ActivePersonaHeadroom, };
