// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Typed record of an **App master** hire (kp `docs/concepts/app-master.md`
 * §4.2, P4). Written once by the `kp_hire_request` approval executor when the
 * inbound request carried an `appMaster` block, alongside — never instead of —
 * [`KpLink`]: an App master is still a kp hire, so the counters reporter keeps
 * working through the same link.
 *
 * This is the **provenance** record: what kp sent and what Personas did with
 * it. It is deliberately NOT the enforcement authority. The mandate the
 * autonomy gate and the diff chokepoint read lives in a
 * `persona_responsibilities` row (the hire's charter, [`Self::mandate_key`]
 * holds its id), resolved per *project* because only the project id is in
 * scope at those call sites. Two copies of a rung that could disagree is
 * exactly the bug a single authority prevents — so the rung is not repeated
 * here, only the pointer that finds it.
 */
export type AppMasterLink = { 
/**
 * The `dev_projects.id` this App master owns.
 */
projectId: string, 
/**
 * The team the persona was added to, bound to the project.
 */
teamId: string | null, 
/**
 * `dev_kpis.id` per objective seeded at hire, in spec order. An objective
 * that could not be seeded is absent — the list is what exists, not what
 * was asked for.
 */
kpiIds: Array<string>, 
/**
 * `persona_triggers.id` per installed cadence trigger.
 */
triggerIds: Array<string>, 
/**
 * Cadence trigger kinds kp asked for that Personas has no mapping for
 * (`pr`, `kpi_tick` as of P4). Recorded rather than approximated: a
 * trigger wired to the nearest-looking event would fire on the wrong
 * thing and read, from kp, as a working cadence.
 */
unsupportedTriggers: Array<string>, 
/**
 * RFC-3339 probation end — approval time + `tenure.probationDays`.
 */
probationEndsAt: string, 
/**
 * The `persona_responsibilities` row id (`resp_…`) holding this hire's
 * charter — the enforceable mandate record. Formerly the `app_settings`
 * mandate key (`app_master_mandate:<project_id>`), which the boot
 * migration retired; links stamped before that carry the legacy key
 * string, and nothing parses either shape — enforcement resolves the
 * charter by project, not through this pointer. Empty when the hire's
 * charter row could not be persisted.
 */
mandateKey: string, 
/**
 * What the binding pass did and did not manage, in order. Duplicated from
 * `setup_detail` on purpose: `promote_build_draft` OVERWRITES
 * `setup_detail` from the connector-readiness pass, so the display copy
 * does not survive the build. A partial hire that silently reads complete
 * after promote is the exact failure this field prevents.
 */
setupNotes: Array<string>, 
/**
 * The `AppMasterSpec` kp sent, verbatim. Kept whole so a later phase can
 * read a field this one does not know about, and so a review packet can
 * quote the spec rather than a lossy projection of it.
 */
spec: JsonValue | null, };
