// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One charter as this adoption left it.
 */
export type AppMasterCharterOutcome = { id: string, slug: string, title: string, priority?: number, status: string, 
/**
 * True when this call minted the charter; false when it updated one.
 */
created: boolean, };
