// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One unanswered ask, as the state route reports it.
 */
export type AppMasterOpenAsk = { 
/**
 * The `persona_manual_reviews` row the operator answers.
 */
reviewId: string, 
/**
 * `accept_ideas` | `decision` | `unblock`.
 */
kind: string, 
/**
 * The question itself, without the `App Master <project>: ` display prefix.
 */
title: string, createdAt: string, };
