// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AthenaProactiveStats = { 
/**
 * Cards that ever surfaced (status != queued) in the window.
 */
delivered: number, engaged: number, dismissed: number, expired: number, budgetUsedToday: number, budgetCap: number, };
