// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AthenaOriginRollup } from "./AthenaOriginRollup";
import type { AthenaUsageDay } from "./AthenaUsageDay";
import type { AthenaUsageTotals } from "./AthenaUsageTotals";

export type AthenaUsageDashboard = { daily: Array<AthenaUsageDay>, byOrigin: Array<AthenaOriginRollup>, totals: AthenaUsageTotals, };
