// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacklogVerdict } from "./BacklogVerdict";
import type { SkippedIdea } from "./SkippedIdea";

/**
 * What the verdict card renders.
 */
export type AthenaTriageBatch = { 
/**
 * The pending `companion_approval` row holding these verdicts.
 */
approvalId: string, 
/**
 * Athena's one-line batch summary (also the approval's rationale).
 */
summary: string, items: Array<BacklogVerdict>, skipped: Array<SkippedIdea>, };
