// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AthenaPromptBlockStat = { turnId: string, origin: string, triggerKind: string | null, createdAt: string, 
/**
 * Real `system_prompt.len()` for that turn.
 */
totalPromptChars: number, 
/**
 * `{"constitution": 5123, "identity": 812, …}` — raw JSON, so a new
 * block shows up here without a binding change.
 */
blocksJson: string, };
