// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the cross-project Attention queue — a goal (or team step) that
 * needs the user. `kind` ∈ awaiting_review | overdue | stalled | unstaffed.
 */
export type AttentionItem = { kind: string, goalId: string, goalTitle: string, projectId: string, projectName: string, status: string, progress: number, 
/**
 * Human-meaningful context: e.g. "8 days overdue", "stalled 11d", step title.
 */
detail: string, 
/**
 * Present for `awaiting_review` rows so the UI can resolve the step inline.
 */
assignmentId: string | null, stepId: string | null, 
/**
 * 0 = highest urgency; drives ranking in the queue.
 */
rank: number, };
