// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the cross-project Attention queue — a goal, an idea, or a task
 * that needs the user.
 *
 * `kind` ∈ `awaiting_review` | `overdue` | `stalled` | `unstaffed`
 *        | `undispatched_idea` | `stuck_task` | `stale_queued_task`
 *        | `kpi_gone_dark` | `kpi_never_measured`.
 *
 * The first four are goal signals and keep their original `rank` values; every
 * later kind is APPENDED at the next free rank rather than interleaved, so the
 * pre-existing ordering contract is untouched (record-widening at 4-6, the two
 * KPI-freshness kinds at 7-8). Within a rank the queue sorts by age, worst
 * first.
 */
export type AttentionItem = { kind: string, 
/**
 * Which record type this row is about: `goal` | `idea` | `task` | `kpi`.
 */
entityKind: string, 
/**
 * Id of the record that needs attention — a goal, idea, task or KPI id.
 * Always the thing the UI should open.
 */
entityId: string, entityTitle: string, 
/**
 * The goal in play. A `goal` row always carries it; an idea or task row
 * carries its linked goal when it has one and `None` when it does not.
 * (These were non-optional while the queue was goal-only; an idea with no
 * goal would have had to be given an empty id that reads as a real link.)
 */
goalId: string | null, goalTitle: string | null, 
/**
 * Ideas and tasks may be project-less (`dev_tasks.project_id` and
 * `dev_ideas.project_id` are both nullable); goal rows always have one.
 */
projectId: string | null, projectName: string | null, status: string, 
/**
 * 0-100 where the record tracks it (goals, tasks). `None` for ideas, which
 * have no progress — a `0` there would read as "started, got nowhere".
 */
progress: number | null, 
/**
 * Human-meaningful context: e.g. "8d overdue", "stalled 11d", step title.
 */
detail: string, 
/**
 * Present for `awaiting_review` rows so the UI can resolve the step inline.
 */
assignmentId: string | null, stepId: string | null, 
/**
 * Age of the SIGNAL in whole hours — days overdue, hours since the last
 * heartbeat, hours since acceptance. Hours (not days) because a task
 * signal lives at hour resolution and a goal signal at day resolution, and
 * one unit that can express both beats two fields that disagree.
 * `None` when the underlying timestamp could not be parsed — never 0.
 */
ageHours: number | null, 
/**
 * 0 = highest urgency; drives ranking in the queue.
 */
rank: number, };
