// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of `persona_attention_ledger` — an attention/consolidation pass.
 */
export type AttentionLedgerEntry = { id: string, personaId: string, responsibilityId?: string,
/**
 * 'attention' | 'consolidation' (DB CHECK-enforced).
 */
kind: string,
/**
 * Optional sub-lane within the kind (e.g. an attention trigger class).
 */
lane?: string,
/**
 * 'started' while running; then 'acted' | 'noop' | 'refused' | 'failed'.
 */
verdict: string, reason: string,
/**
 * Watermark: episodes with `created_at` <= this were consumed.
 */
consumedThrough?: string, statsJson?: string, costUsd?: number, startedAt: string, completedAt?: string, };
