// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthUser } from "./AuthUser";

export type AuthStateResponse = { is_authenticated: boolean, is_offline: boolean, is_offline_authenticated: boolean, user: AuthUser | null, };
