// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the Run Desk's auto-run banner rehydrates from.
 *
 * `live = true` means the in-memory scheduler still owns this run (the
 * tallies are the last durable snapshot, not a live count); `live = false`
 * means this is the most recent finished run. `run_id: None` = the project
 * has never had an auto-run.
 */
export type AutoRunStatus = { run_id: string | null, project_id: string | null, 
/**
 * `running` | `completed` | `cancelled` | `failed`, or `None` when there
 * is no run to report.
 */
status: string | null, snapshot_size: number, completed: number, failed: number, skipped: number, iterations: number, termination_reason: string | null, started_at: string | null, finished_at: string | null, 
/**
 * True when the in-memory scheduler still reports this run as running.
 */
live: boolean, };
