// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The quota governor's view, as the board shows it next to the pacing.
 */
export type AutopilotGovernor = { 
/**
 * The loop is stopped: the worst window is at or above `stop_pct`.
 */
blocked: boolean, stopPct: number, worstKey: string | null, worstPct: number, 
/**
 * Minutes — a week is 10,080 of them.
 */
resetsInMinutes: number | null, 
/**
 * Minutes until the worst window reaches the stop at the measured burn
 * rate; `None` when nothing is climbing.
 */
minutesToStop: number | null, unavailableReason: string | null, };
