// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationSuggestionEvidence } from "./AutomationSuggestionEvidence";
import type { AutomationSuggestionStatus } from "./AutomationSuggestionStatus";

/**
 * A mined automation-suggestion row (`automation_suggestions` table).
 */
export type AutomationSuggestion = { id: string, eventType: string, personaId: string, status: AutomationSuggestionStatus, occurrenceCount: number, manualRunCount: number, support: number, windowSeconds: number, lookbackDays: number, evidence: Array<AutomationSuggestionEvidence>, committedTriggerId: string | null, firstSeenAt: string | null, lastSeenAt: string | null, decidedAt: string | null, createdAt: string, updatedAt: string, };
