// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle status of a mined automation suggestion.
 */
export type AutomationSuggestionStatus = "proposed" | "accepted" | "rejected";
