// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationSuggestion } from "./AutomationSuggestion";

/**
 * The suggestions feed plus the miner's honesty context.
 */
export type AutomationSuggestionFeed = { suggestions: Array<AutomationSuggestion>, minerEnabled: boolean, minCoOccurrences: number, windowSeconds: number, lookbackDays: number, };
