// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutoCredBrowserResult = { session_id: string, extracted_values: Record<string, string>, procedure_log: string, partial: boolean, };
