// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle status of a suggestion. Strings on the wire so the table
 * CHECK constraint can lock the value space (mirrors `RecipeSuggestionEventType`).
 */
export type AutomationSuggestionStatus = "proposed" | "accepted" | "rejected";
