// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface BlueprintMember {
  persona_id: string;
  persona_name: string;
  role: string;
  position_x: number;
  position_y: number;
}
