// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardEnvelope } from "./BoardEnvelope";
import type { BoardRound } from "./BoardRound";
import type { BoardScenario } from "./BoardScenario";
import type { BoardVerdict } from "./BoardVerdict";
import type { CouncilSubjectState } from "./CouncilSubjectState";

export type BoardFeature = { id: string, slug: string, name: string, description: string | null, 
/**
 * 'user_flow' | 'capability' | 'integration' | 'ops'
 */
kind: string, 
/**
 * 'major' | 'standard'
 */
tier: string, contextIds: Array<string>, 
/**
 * The distinct groups this feature's slice crosses.
 */
groupIds: Array<string>, primaryContextId: string | null, 
/**
 * `None` when no council has ever judged this feature - which is NOT the
 * same as a council that found nothing.
 */
council: CouncilSubjectState | null, 
/**
 * The LATEST run's verdicts, one per rubric dimension.
 */
verdicts: Array<BoardVerdict>, 
/**
 * Every round, oldest first.
 */
history: Array<BoardRound>, scenarios: Array<BoardScenario>, 
/**
 * Where this feature's approval holds, is weak, and was never looked at.
 * `None` when the feature declares no scenarios and no run reported any -
 * which is not an empty envelope, it is no envelope. Computed by
 * [`aggregate_scenarios`], the same function the ingest door recomputes
 * an incoming result with, so the page cannot show a second answer.
 */
envelope: BoardEnvelope | null, 
/**
 * 30-day LLM spend attributed to this feature. `None` everywhere today:
 * `dev_llm_spend` carries no use-case dimension, and a join invented here
 * would be a number with nothing behind it.
 */
spend30dUsd: number | null, };
