// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockingCause } from "./BlockingCause";
import type { BrainCounters } from "./BrainCounters";
import type { HealthStage } from "./HealthStage";

/**
 * The whole report.
 */
export type BrainHealth = { 
/**
 * True when every stage is `Ok` or `Skipped`.
 */
healthy: boolean, 
/**
 * Whether the vector lane is live. `false` on a lite build is normal, and
 * the keyword lane carries recall alone.
 */
vectorLane: boolean, firstBlockingCause: BlockingCause | null, stages: Array<HealthStage>, counters: BrainCounters, };
