// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Raw counters behind the verdicts. Present regardless of health, so a
 * healthy report is still worth reading.
 */
export type BrainCounters = { nodes: bigint, 
/**
 * Nodes carrying an `embedding_model` stamp.
 */
embedded: bigint, 
/**
 * Nodes with no stamp — the vector lane cannot see these.
 */
unembedded: bigint, 
/**
 * Rows in the `companion_embedding` vec0 table, or `None` when that table
 * does not exist yet (never embedded) — which is itself the answer.
 */
vectors: bigint | null, ftsRows: bigint, episodes: bigint, facts: bigint, procedurals: bigint, doctrineChunks: bigint, 
/**
 * Process-cumulative recall hits dropped by the embedding-model guard.
 */
modelGuardExcluded: bigint, lastCycleAt: string | null, };
