// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One observed (credential, consumer) usage edge, refreshed on every proxied
 * call through the management API's `/api/proxy/{credential_id}` route. The
 * consumer is the `external_api_keys` row that authenticated the call, so the
 * blast-radius graph reflects live reality rather than declared bindings.
 */
export type BrokerConsumerEdge = { id: string, credentialId: string, consumerKeyId: string, consumerName: string, callCount: bigint, 
/**
 * HTTP status of the most recent proxied call, if recorded.
 */
lastStatus: bigint | null, firstUsedAt: string, lastUsedAt: string, };
