// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a scan could not reach tier 2.
 */
export type BrowserScanBlocker = "captcha" | "login_wall" | "csp_frozen_globals";
