// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool class after manifest derivation + per-origin tightening.
 * Mirrors the TS `BrowserToolClass`.
 */
export type BrowserToolClass = "read" | "auto" | "gated";
