// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserScanStatus } from "./BrowserScanStatus";
import type { BrowserSiteScan } from "./BrowserSiteScan";
import type { BrowserToolClass } from "./BrowserToolClass";

/**
 * One row of `browser_sites` — the origin gate's unit of decision.
 */
export type BrowserSite = { 
/**
 * `scheme://host[:port]`, the ascii serialization of the URL's origin.
 */
origin: string, label: string, 
/**
 * Deny-by-default: a row created by a request is NOT enabled.
 */
enabled: boolean, 
/**
 * tool name -> class. Tighten-only: the repo refuses anything but
 * [`BrowserToolClass::Gated`].
 */
overrides: { [key in string]?: BrowserToolClass }, 
/**
 * Per-turn call budget for this origin.
 */
budget: number, credential_id: string | null, scan_status: BrowserScanStatus, 
/**
 * 0 | 1 | 2 — `None` until a scan answers.
 */
scan_tier: number | null, scan_report: BrowserSiteScan | null, 
/**
 * Epoch ms. i64 because SQLite INTEGER is 64-bit; epoch-ms stays far
 * under 2^53, so the JS `number` pin is lossless.
 */
scan_at: number | null, first_seen: number, last_seen: number, 
/**
 * `operator` | `athena` | `session:<id>` — the wire form of
 * `browser_bridge::backend::Principal`.
 */
created_by: string, };
