// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebBuildPhase } from "./WebBuildPhase";

/**
 * Result of a build turn: Athena's cleaned reply, an optional updated plan, and
 * an optional question she needs answered before proceeding (`NEEDS_INPUT`).
 */
export type BuildTurnResult = { reply: string, phases: Array<WebBuildPhase> | null, question: string | null, 
/**
 * Clickable options for the question (A1). Empty = free-text answer.
 */
options: Array<string>, };
