// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialHealthcheckOutcome } from "./CredentialHealthcheckOutcome";

/**
 * Summary of a bulk / daily credential healthcheck sweep.
 */
export type BulkHealthcheckSummary = { total: number, passed: number, failed: number, results: Array<CredentialHealthcheckOutcome>, completedAt: string, };
