// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-id result of a `bulk_delete_personas` call. `status` is one of
 * `deleted` | `protected` | `failed`; `reason` carries the human-readable
 * cause for the non-`deleted` outcomes (system-origin protection, not-found,
 * or a DB error).
 */
export type BulkDeleteOutcome = { id: string, status: string, reason: string | null, };
