// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceRule } from "./ComplianceRule";
import type { RoutingRule } from "./RoutingRule";

export type ByomPolicy = { enabled: boolean, allowed_providers: string[], blocked_providers: string[], routing_rules: RoutingRule[], compliance_rules: ComplianceRule[], };
