// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health status returned by [`Capability::healthcheck`].
 */
export type CapabilityHealth = { healthy: boolean, latency_ms: bigint, message: string | null, };
