// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-kind row counts for a team's channel.
 *
 * The Stream's facet rail cannot count what it did not fetch — and deliberation
 * turns are deliberately absent from the blended read (they used to leak into
 * the conversation), so the rail was showing "Deliberation 0" for teams with
 * hundreds of turns. Counting has to happen where the rows are.
 */
export type ChannelKindCounts = { step: number, event: number, memory: number, message: number, deliberation: number, 
/**
 * Channel rows authored by an external Slack participant. Counted
 * separately from `message` for the same reason the lens splits them: they
 * are people outside the team talking in it.
 */
slack: number, };
