// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One connector role as ADOPTION left it: the role, the type it wanted, and
 * the concrete connector bound to it — or `None`, which is a question the
 * adopter still owes an answer to and never a silent default.
 */
export type CharterConnectorBinding = { role: string, connectorType: string, 
/**
 * `None` = unresolved. The charter's `connectors` allowlist is a runtime
 * gate, so an unbound role binds NOTHING rather than guessing.
 */
connector?: string, };
