// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CircuitTransitionEvent } from "./CircuitTransitionEvent";
import type { ProviderCircuitState } from "./ProviderCircuitState";

export interface CircuitBreakerStatus {
  providers: Array<ProviderCircuitState>;
  globalPaused: boolean;
  globalCooldownRemainingSecs: number;
  globalFailureCount: number;
  recentTransitions: Array<CircuitTransitionEvent>;
}
