// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single circuit breaker state transition event.
 */
export type CircuitTransitionEvent = { 
/**
 * Provider name (e.g. "claude_code") or "global" for the global breaker.
 */
provider: string, 
/**
 * Previous state: "closed", "open", "half_open", "paused".
 */
fromState: string, 
/**
 * New state.
 */
toState: string, 
/**
 * ISO-8601 timestamp of the transition.
 */
timestamp: string, 
/**
 * Consecutive failures at the time of transition (0 for global).
 */
failureCount: number, };
