// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the spawned Claude Code CLI exposes — read from its `system/init` event.
 */
export type CliCapabilities = { 
/**
 * Model the CLI resolved to (e.g. `claude-opus-4-8[1m]`).
 */
model: string, 
/**
 * CLI version from the init event (e.g. `2.1.177`).
 */
cliVersion: string | null, 
/**
 * Full tool registry exposed to a headless execution.
 */
tools: Array<string>, 
/**
 * Subagent types available to the `Task` tool (e.g. `claude`, `Explore`).
 */
agents: Array<string>, 
/**
 * `Workflow` tool present — the dynamic many-agent orchestration tool.
 */
hasWorkflow: boolean, 
/**
 * `Task` tool present — single / parallel subagent delegation.
 */
hasTask: boolean, 
/**
 * `true` when fan-out is possible at all (either tool present).
 */
deepFanoutAvailable: boolean, 
/**
 * RFC3339 timestamp of the probe.
 */
probedAt: string, };
