// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rate-limit window of a provider.
 */
export type CliUsageWindow = { 
/**
 * `"primary"` or `"secondary"`.
 */
key: string, windowMinutes: number, usedPercent: number, resetsAtMs: number | null, };
