// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a provider has no usage windows to show.
 */
export type CliUsageReason = "not_installed" | "no_quota_source" | "no_sessions" | "unreadable";
