// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a pairing QR opens, for the Settings panel to show before and while
 * the QR is up.
 */
export type CloudPairingOrigin = { 
/**
 * The effective origin, normalised (`https://host[:port]`, no slash).
 */
origin: string, 
/**
 * Whether the operator set it (false: the built-in default).
 */
custom: boolean, };
