// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `isExpired` semantics:
 * - `true`  — the token is confirmed expired
 * - `false` — the token is confirmed valid (not expired)
 * - `null`  — expiration has not been checked yet (e.g. backend could not determine validity)
 *
 * UI consumers must NOT treat `null` as "not expired". Show a distinct
 * "status unknown" indicator instead.
 */
export type CloudOAuthStatusResponse = { connected: boolean, scopes: Array<string> | null, expiresAt: string | null, isExpired: boolean | null, };
