// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloudSyncStatus = { enabled: boolean, lastSyncAt: string | null, lastError: string | null, rowsSyncedLast: bigint, };
