// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloudTrigger = { id: string, project_id: string, persona_id: string, trigger_type: string, config: string | null, enabled: boolean, last_triggered_at: string | null, next_trigger_at: string | null, health_status: string | null, health_message: string | null, use_case_id: string | null, created_at: string | null, updated_at: string | null, };
