// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the last-24h autonomy rollup: what a single wake surface did.
 *
 * snake_case (no `rename_all`) — the Companion impact strip has read
 * `row.cli_calls` since before this payload was typed.
 */
export type CompanionWakeSurfaceStats = { 
/**
 * Wake-surface id (exec triage, message triage, channel reactions, ...).
 */
surface: string, 
/**
 * Number of times the surface actually woke (skipped ticks are not logged).
 */
wakes: number, signals: number, cliCalls: number, actions: number, };
