// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompanionWakeSurfaceStats } from "./CompanionWakeSurfaceStats";

/**
 * 24h rollup of autonomy wakes / signals / actions, grouped by surface.
 */
export type CompanionWakeStats = { 
/**
 * The configured wake-window length, so the UI can render cadence next to
 * the counts instead of hardcoding it.
 */
window_minutes: number, surfaces: Array<CompanionWakeSurfaceStats>, };
