// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { CompanionBlocker } from "./CompanionBlocker";
import type { CompanionDetailDto } from "./CompanionDetailDto";
import type { CompanionId } from "./CompanionId";

/**
 * One companion's standing. `enabled` is the operator's intent, `eligible` is
 * whether the prerequisite is met; a surface treats them separately, because
 * losing the prerequisite must never silently rewrite the intent.
 */
export type CompanionStatusDto = { id: CompanionId, enabled: boolean, eligible: boolean, blocker?: CompanionBlocker, onboarded: boolean, detail: CompanionDetailDto, };
