// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompetitiveImportPreview = { sourcePlatform: string, workflowName: string, description: string, suggestedTools: Array<string>, suggestedTriggers: Array<string>, };
