// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompanionBlocker } from "./CompanionBlocker";
import type { CompanionDetailDto } from "./CompanionDetailDto";
import type { CompanionId } from "./CompanionId";

/**
 * One companion's standing. `enabled` is the operator's intent, `eligible` is
 * whether the prerequisite is met; a surface treats them separately, because
 * losing the prerequisite must never silently rewrite the intent.
 */
export type CompanionStatusDto = { id: CompanionId, 
/**
 * The operator's switch (settings `athena_enabled` / `overseer_enabled` /
 * `curator_enabled`).
 */
enabled: boolean, 
/**
 * Whether the prerequisite is met right now.
 */
eligible: boolean, 
/**
 * Set when `eligible` is false; names which prerequisite is missing.
 */
blocker?: CompanionBlocker, 
/**
 * Athena: the onboarding wizard was finished (or her brain proves it).
 * Always true for the other two, which have nothing to onboard.
 */
onboarded: boolean, detail: CompanionDetailDto, };
