// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A config-level warning surfaced to the frontend health check system.
 */
export type ConfigWarning = { id: string, severity: string, category: string, description: string, };
