// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectionMetricsSnapshot = { connectionsEstablished: number, connectionsDroppedHealth: number, connectionsDroppedUser: number, connectionsDroppedShutdown: number, connectionsDroppedProtocol: number, connectionsRejectedCapacity: number, connectionAttempts: number, avgConnectDurationMs: number | null, };
