// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One completed consolidation pass, decoded from the attention ledger's
 * `stats_json` (`engine::persona_brain::sleep_cycle` writes the keys).
 */
export type ConsolidationPoint = { completedAt: string, episodesFed: number, created: number, updated: number, rejected: number, skippedTombstoned: number, 
/**
 * Absent when the pass reported no cost (subscription lane) — not zero.
 */
costUsd?: number, 
/**
 * 'acted' | 'noop' | 'failed' | ...
 */
verdict: string, };
