// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which engine CLIs resolve on this machine.
 */
export type ContestEngineAvailability = { claude: boolean, codex: boolean, grok: boolean, };
