// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a seat builds variants or judges them.
 */
export type ContestSeatKind = "participant" | "judge";
