// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContestPhase } from "./ContestPhase";

/**
 * A contest as listed. Keyed by `(projectId, contestId)`.
 */
export type ContestSummary = { projectId: string, projectName: string, contestId: string, title: string, date: string, phase: ContestPhase, seatCount: number, variantsPerSeat: number, 
/**
 * The participant seat specs (`engine:model@effort[#label]`), in seat order.
 * Keys the seat win-rate board across decided contests.
 */
seatSpecs: Array<string>, 
/**
 * The winning variant key (`"A/2"`), once decided.
 */
winner: string | null, winnerSeatSpec: string | null, 
/**
 * Shortlisted variant keys.
 */
shortlist: Array<string>, 
/**
 * The contest this one refines (a refine round), if any.
 */
parentId: string | null, round: number | null, updatedAtMs: number, };
