// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextEvent = {
  source: string;
  summary: string;
  timestamp: number;
  paths: string[];
  appName: string | null;
  windowTitle: string | null;
};
