// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The owner's decision on a contest, tagged on `kind`.
 *
 * `shortlist` runs `verdict --shortlist`, then `refine --feedback REVIEW.md`,
 * and the returned summary is the child (next-round) contest.
 */
export type ContestDecision = { "kind": "winner", winner: string, runnerUp: string | null, note: string, } | { "kind": "shortlist", keys: Array<string>, note: string, };
