// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The review tray a variant has been sorted into.
 */
export type ContestReviewBucket = "failure" | "impractical" | "shortlist" | "winner";
