// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload of the `contest-changed` event (`event_name::CONTEST_CHANGED`),
 * emitted on every seat-state change and every chain step.
 */
export type ContestChangedPayload = { projectId: string, contestId: string, };
