// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One retryable step of the autopilot chain (`contest_run_step`).
 */
export type ContestStep = "collect" | "visual" | "judge" | "aggregate";
