// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextFingerprintRefreshSummary = { contextsTotal: number, contextsRefreshed: number, 
/**
 * Contexts whose `content_hash` matched the cached row — zero files read.
 */
contextsSkipped: number, 
/**
 * Files actually read from disk during this refresh.
 */
filesRead: number, 
/**
 * Mapped `file_paths` entries that no longer exist on disk, summed over
 * every context inspected. Reported rather than silently swallowed: ~13% of
 * the live map is dangling, and that staleness must be visible.
 */
missingFiles: number, };
