// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CorpusMapEntry = { 
/**
 * Filename under `docs/concepts/golden-paths/`.
 */
legacyFile: string, subject: string, };
