// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One council round over one subject. Runs supersede, never rewrite.
 */
export type CouncilRun = { id: string, subjectId: string, roundNo: number, supersedesRunId: string | null, 
/**
 * 'feature-v1' | 'architecture-v1'
 */
rubricVersion: string, 
/**
 * 'uncalibrated' | 'untrusted' | 'trusted'
 */
trustState: string, 
/**
 * 'ready' | 'fail' | 'incomplete' | 'stalled'
 */
outcome: string, 
/**
 * Weighted mean over MEASURED dimensions. `None` when nothing was
 * measured - never `0.0`.
 */
overall: number | null, 
/**
 * Measured weight over applicable weight. Always known, so not optional.
 */
coverage: number, headSha: string, spanDigest: string, 
/**
 * JSON array of repo-relative paths the run judged.
 */
spannedPathsJson: string, 
/**
 * JSON array of `{code, detail}`.
 */
hardFailuresJson: string, 
/**
 * JSON array of strings.
 */
mustAddressJson: string, summary: string, 
/**
 * True when this run's summary is, character for character, the SUBJECT'S
 * own description rather than anything the council concluded. Computed at
 * read time (never stored): the ingest door substituted the description
 * for an empty summary until 2026-09-22, and rows written before that
 * still carry it. Runs supersede and are never rewritten, so the truth is
 * exposed rather than repaired - a surface presenting `summary` as the
 * verdict should say so when this is set. Only a `use_case` subject can
 * ever set it; an architecture subject stores no description to compare.
 */
summaryIsSubjectFallback: boolean, runDir: string, startedAt: string | null, finishedAt: string | null, ingestedAt: string, };
