// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One thing a council judges. A `use_case` subject is bound to a
 * `dev_use_cases` row; an `architecture` subject is free-standing and carries
 * its own title (its ADR lives in the vault, not here).
 */
export type CouncilSubject = { id: string, projectId: string, 
/**
 * 'use_case' | 'architecture'
 */
kind: string, 
/**
 * Set only for kind `use_case`. `ON DELETE SET NULL`: the verdict chain
 * outlives the feature row it judged.
 */
useCaseId: string | null, slug: string, title: string, 
/**
 * 'none' | 'grown' | 'changed' | 'unknown'
 */
drift: string, driftCheckedAt: string | null, createdAt: string, updatedAt: string, };
