// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CouncilDecision } from "./CouncilDecision";
import type { CouncilRun } from "./CouncilRun";
import type { CouncilSubject } from "./CouncilSubject";
import type { CouncilVerdict } from "./CouncilVerdict";

/**
 * One run with everything the human gate needs to look at, including the
 * `saw_digest` it must hand back when it decides.
 */
export type CouncilRunDetail = { run: CouncilRun, subject: CouncilSubject, verdicts: Array<CouncilVerdict>, 
/**
 * The compare-and-swap token. A decision quoting a stale digest is
 * refused rather than recorded.
 */
sawDigest: string, 
/**
 * Whether this run is still the subject's latest. A decision may only be
 * taken on the latest run.
 */
isLatest: boolean, 
/**
 * The decision standing on this subject right now, if any.
 */
decision: CouncilDecision | null, };
