// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one council round found for one scenario.
 */
export type CouncilScenarioResult = { id: string, runId: string, scenarioId: string, 
/**
 * 'measured' | 'unmeasured'
 */
state: string, 
/**
 * `None` unless `state` is `measured`. Never `0.0` for "we did not look".
 */
score: number | null, 
/**
 * 'low' | 'med' | 'high'
 */
confidence: string, 
/**
 * How many runs or turns the score rests on. `None` when the member did
 * not say, which is not the same as one.
 */
n: number | null, 
/**
 * 'observed' | 'replayed' | 'simulated' | 'claimed'
 */
proof: string, floorHit: boolean, 
/**
 * A floor hit that is RECORDED and does not sink the run, because the
 * member that raised it has not earned the authority yet.
 */
advisory: boolean, summary: string, };
