// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A human's verdict on a run. The ONLY row in this whole chain a person
 * writes, and the only one that can admit anything.
 */
export type CouncilDecision = { id: string, subjectId: string, 
/**
 * `ON DELETE RESTRICT`: the run a person looked at cannot be deleted out
 * from under the decision that cites it.
 */
runId: string, 
/**
 * 'approved' | 'rejected'
 */
decision: string, 
/**
 * Mandatory and non-blank when `decision` is `rejected`.
 */
reason: string | null, 
/**
 * The digest of what the decider was looking at, captured at the moment
 * they decided. The decide command compares it against the run's current
 * digest and refuses on a mismatch, so a decision can never be recorded
 * against a page that had already moved.
 */
sawDigest: string, supersedesDecisionId: string | null, decidedAt: string, };
