// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One evidence file read from inside a run directory. Path-confined by the
 * door; the frontend turns the bytes into an object URL.
 */
export type CouncilMedia = { mime: string, bytes: Array<number>, };
