// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCredentialInput = { name: string, serviceType: string, encryptedData: string, iv: string, metadata: string | null, sessionEncryptedData: string | null, 
/**
 * When true, persist an initial healthcheck_last_success=true on creation
 * (used by catalog flows where the credential was tested before saving).
 */
healthcheckPassed: boolean | null, };
