// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectTemplate } from "./ProjectTemplate";

/**
 * The creation request.
 */
export type CreateProjectRepositoryInput = { 
/**
 * A `dev_workspaces` id, or a name. A name that matches no workspace
 * **creates** one — the Architect starts from an empty app and should not
 * need a second call to have somewhere to put the first project.
 */
workspace: string, 
/**
 * The repository's folder name and the project's display name.
 */
name: string, description?: string, techStack?: string, 
/**
 * Defaults to `empty`.
 */
template?: ProjectTemplate, 
/**
 * An absolute directory that replaces the configured simulation root for
 * this call. The workspace slug and project name are still appended.
 */
root?: string, };
