// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevProject } from "./DevProject";

/**
 * What the call did.
 */
export type CreatedProjectRepository = { 
/**
 * The registered row, as `POST /dev-tools/projects` would have returned it.
 */
project: DevProject, 
/**
 * Canonical absolute path of the repository.
 */
repositoryPath: string, 
/**
 * The workspace the project is now assigned to.
 */
workspaceId: string, 
/**
 * True when this call created the repository. False when the folder
 * already held a registered project and the call only re-registered and
 * re-assigned it.
 */
created: boolean, 
/**
 * True when this call minted the workspace row.
 */
workspaceCreated: boolean, };
