// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateKpiInput = { project_id: string, name: string, description: string | null, category: string | null, measure_kind: string | null, 
/**
 * JSON blob describing HOW the number is read. Defaults to `{}`.
 */
measure_config: string | null, unit: string | null, direction: string | null, baseline_value: number | null, target_value: number | null, target_date: string | null, cadence: string | null, 
/**
 * `proposed` (default) or `active`. A worker proposing a meter is the
 * normal case; activating one is a claim it can already be read.
 */
status: string | null, rationale: string | null, context_group_id: string | null, context_id: string | null, };
