// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateManualReviewInput = { execution_id: string, persona_id: string, title: string, description: string | null, severity: string | null, context_data: string | null, suggested_actions: string | null, };
