// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResearchSource } from "./ResearchSource";

/**
 * Result of `create_source`: the source row plus whether it was *newly*
 * inserted (`created = true`) or resolved to a pre-existing row via the
 * DOI/URL dedup guard (`created = false`). Callers need this to report
 * honest counts — e.g. the arXiv import toast must not count deduped papers
 * as freshly added.
 */
export type CreateSourceResult = { source: ResearchSource, created: boolean, };
