// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RotationEntryStatus } from "./RotationEntryStatus";

export type CredentialRotationEntry = { id: string, credential_id: string, rotation_type: string, status: RotationEntryStatus, detail: string | null, created_at: string, };
