// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CredentialFieldMeta = { id: string, credentialId: string, fieldKey: string, fieldType: string, isSensitive: boolean, createdAt: string, updatedAt: string, };
