// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-persona assignment fitness: terminal team-assignment steps attributed
 * to this persona. `success_rate` is None until at least one terminal step
 * exists — the UI must render an honest "no data yet", never a fake 100%.
 */
export type CrewFitnessPersona = { personaId: string, personaName: string, role: string, stepsDone: bigint, stepsFailed: bigint, 
/**
 * done + failed (skipped steps are excluded — they carry no signal).
 */
stepsTotal: bigint, 
/**
 * done / (done + failed), None when steps_total == 0.
 */
successRate: number | null, };
