// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CuratorRequestState } from "./CuratorRequestState";

/**
 * One request the operator put in Curator's human lane, in the order they wrote
 * it. She drains this lane before her own plan.
 */
export type CuratorRequest = { id: string, 
/**
 * The registry skill to run, e.g. `intake`.
 */
skill: string, 
/**
 * What to run it on - a URL, a bundle, a domain. Null for a bare-runnable skill.
 */
argument: string | null, 
/**
 * The operator's own words, carried into the worker's brief unchanged.
 */
note: string | null, state: CuratorRequestState, createdAt: string, startedAt: string | null, settledAt: string | null, 
/**
 * The fleet session she dispatched for it, once admitted.
 */
sessionId: string | null, 
/**
 * The run-result outcome once the worker wrote one, else null.
 */
outcome: string | null, 
/**
 * Where the worker's `result.json` landed, so the row can be traced to evidence.
 */
resultRef: string | null, failureReason: string | null, };
