// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which way one metric, or the ecosystem as a whole, has moved.
 */
export type CuratorTrend = "grew" | "flat" | "shrank" | "unknown";
