// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which registry skill answers a finding. `None` is reachable and meaningful:
 * it is what an item routes to when the scan reported a clause this app's
 * routing table does not know, which is a finding about the app, not the
 * corpus.
 */
export type CuratorEngine = "conform" | "deepen" | "apply" | "reconcile" | "intake" | "forge" | "none";
