// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bundle's share of the subjects that score nothing.
 *
 * The projection makes a plan item only for a subject that scores, so the 170
 * quiet subjects have no row anywhere. They are not noise: `table` scores 0 and
 * still holds 16 stale verdicts across 6 projects. This carries them as counts
 * so a surface can say "wanting nothing is a fact about the subject" rather
 * than leaving them out and calling the remainder the corpus.
 */
export type CuratorQuietBundle = { domain: string, 
/**
 * Subjects in this bundle scoring zero.
 */
subjects: number, 
/**
 * False for the five bundles whose demand was never read, where a zero on the
 * demand-fed channels means "nobody looked", not "nothing found".
 */
demandKnown: boolean, };
