// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CuratorEngine } from "./CuratorEngine";
import type { CuratorImpedimentKind } from "./CuratorImpedimentKind";

/**
 * One measured impediment, ranked by how much of her plan it frees.
 */
export type CuratorImpediment = { 
/**
 * Stable across ticks, so a fix already attempted is not re-attempted:
 * `<kind>:<skill>`.
 */
id: string, kind: CuratorImpedimentKind, 
/**
 * The engine whose items it blocks.
 */
engine: CuratorEngine, 
/**
 * The registry skill that would answer that engine.
 */
skill: string, 
/**
 * **Standing plan items this impediment holds, right now.** Counted from
 * the plan rows in front of her, never guessed.
 */
blocks: number, 
/**
 * **Of those, how many closing it would actually release.** The rank, and
 * deliberately not [`Self::blocks`].
 *
 * Measured 2026-09-26 against the live plan, which is what forced the two
 * fields apart: `conform` documents its invocation only inside a prose
 * sentence in its `description:` frontmatter, so it reads as undocumented
 * and holds **99** items - and documenting it properly would free **none**
 * of them, because a `conform` plan item also cannot carry the project that
 * invocation needs. Two different things are missing and only one of them is
 * in the registry.
 *
 * Ranking on `blocks` would therefore have sent her to fix the largest
 * number on the board and unblocked nothing - the eight-refill-passes waste
 * in a new costume. `frees` is `blocks` only when the engine can already
 * carry its own argument, so the skill's side is genuinely the last thing
 * missing.
 */
frees: number, 
/**
 * The file that would have to change, as the registry states its path.
 * `None` when there is no such file, which is what `SkillMissing` means.
 */
file: string | null, 
/**
 * One line naming what is absent. Written for the worker's brief, so it
 * says what to add, not merely what is wrong.
 */
summary: string, 
/**
 * `true` only for [`CuratorImpedimentKind::self_fixable`].
 */
selfFixable: boolean, 
/**
 * Why it is not hers, when it is not. `None` when it is.
 */
refusal: string | null, };
