// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CuratorDemand } from "./CuratorDemand";
import type { CuratorEngine } from "./CuratorEngine";
import type { CuratorPlanItemState } from "./CuratorPlanItemState";
import type { CuratorReason } from "./CuratorReason";
import type { CuratorReasonCode } from "./CuratorReasonCode";

/**
 * One subject the projection would act on. Items exist only for subjects the
 * scan scored above zero - a subject with no finding is not work, and a plan
 * that listed all 471 would bury the 301 that are.
 */
export type CuratorPlanItem = { id: string, planRunId: string, 
/**
 * `<domain>/<slug>` - the scan's own id.
 */
subjectId: string, domain: string, 
/**
 * Where the subject sits in its bundle's taxonomy.
 */
at: string, 
/**
 * The scan's own attention points. Equal to the sum of `reasons[].weight`
 * whenever every clause was recognised, which is the invariant the
 * projection's test asserts over all 471 real subjects.
 */
points: number, reasons: Array<CuratorReason>, dominantReason: CuratorReasonCode, engine: CuratorEngine, techniques: number, applications: number, stacks: Array<string>, 
/**
 * Whether ANY consumer reports demand for this subject. When false,
 * `demand` is `None` and demand is UNKNOWN - never zero.
 */
demandKnown: boolean, demand: CuratorDemand | null, 
/**
 * When the librarian last swept this subject. `None` = no sweep recorded,
 * which the scan itself scores as the `never_swept` clause.
 */
lastSwept: string | null, 
/**
 * **The registry's `dry_streak`, carried as an input she does not trust,
 * and never the basis of `suppressed_by_saturation`.**
 *
 * Measured 2026-09-23 against the registry: 349 of 349 subject notes
 * carrying the field read `0`, no other value exists anywhere in that
 * tree, and exactly two call sites mention it - the librarian's doctrine
 * READS it (`>= 2` suppresses a saturated subject) while reconcile WRITES
 * it, but only as `0` at note creation. **Nothing increments it**, so the
 * predicate can never be true and a consumer cannot tell that apart from
 * "no subject is saturated".
 *
 * So `0` here means UNKNOWN, not "not saturated". It is stored because
 * the day the registry starts incrementing it, the disagreement between
 * this column and [`Self::suppressed_by_saturation`] is the signal - and
 * a column that was never carried could not show it.
 */
registryDryStreak: number, 
/**
 * **Hers**, computed from her own recorded outcomes: the number of
 * consecutive most-recent plan runs in which this subject reached
 * `idled`, broken by any other terminal state, compared against
 * [`CURATOR_SATURATION_THRESHOLD`]. A subject she has never dispatched is
 * NOT suppressed - an absent history is not a dry one.
 */
suppressedBySaturation: boolean, 
/**
 * Whether any row in `librarian/applied.md` names this subject. `None`
 * when the ledger could not be READ; a ledger that exists and names
 * nothing gives `Some(false)`.
 */
hasAppliedRow: boolean | null, state: CuratorPlanItemState, declinedReason: string | null, dispatchedRunId: string | null, evidenceRef: string | null, updatedAt: string, };
