// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What her loop is doing right now. Every cap here is a real brake: the
 * operator's standing instruction is that she never idles, so these are the
 * only things that ever stop her.
 */
export type CuratorRuntime = { enabled: boolean, 
/**
 * Terminals she currently holds.
 */
running: number, workerCap: number, 
/**
 * Processes those terminals have fanned out to, when known. A dispatcher skill
 * spawns its own pool - `librarian` and `forge` cap at 10, `harvest` at 5,
 * `hygiene` at 6 - so a worker cap of 2 is not a cap of 2 processes. Null when
 * she cannot see inside a worker.
 *
 * **Measured 2026-09-24, and the answer got worse rather than better when a
 * loop was finally attached:** her workers are headless `claude` sessions and
 * a dispatcher skill fans out through the Task tool, which runs its agents
 * IN-PROCESS. There is no child process to count, so no OS-level reading of
 * the pool exists at all - not merely one this app has not written. The only
 * figure that is ever knowable from here is the zero, when she holds no
 * terminal.
 */
fannedOut: number | null, 
/**
 * Which lane she is serving: the operator's queue, her own plan, the refill
 * research pass, or her reconcile sleep.
 */
lane: string, 
/**
 * Why she is stopped, when she is. Null while she is working.
 */
haltedReason: string | null, spentTodayUsd: number, 
/**
 * Dollars she may spend today. `None` = no ceiling declared;
 * `Some(0.0)` = declared, and none.
 */
dailyBudgetUsd: number | null, runsToday: number, 
/**
 * Dispatches she may start today. `None` = no cap declared.
 */
dailyRunCap: number | null, commitsToday: number, 
/**
 * Commits she may land today. `None` = no cap declared.
 */
dailyCommitCap: number | null, lastSleepAt: string | null, };
