// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CuratorReasonCode } from "./CuratorReasonCode";

/**
 * One recognised clause from the scan, with the prose the scan wrote for it.
 */
export type CuratorReason = { code: CuratorReasonCode, 
/**
 * What this clause contributed to the subject's `points` - the per-unit
 * weight TIMES the count the scan applied it to, which is why it is
 * stored rather than looked up.
 */
weight: number, 
/**
 * The scan's own sentence, kept so a surface can show the registry's
 * words rather than this app's paraphrase.
 */
detail: string, };
