// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **One sample of the ecosystem's size.** Her goal signal, and the operator's
 * question in one row: is the fleet of projects growing, or is she only busy?
 *
 * Every field is `Option` and none of them defaults to zero. That is not
 * decoration - it is the rule this module has already been bitten by three
 * times (`registry_dry_streak` reading `0` for "nobody increments it",
 * `CuratorRuntime`'s caps rendering `0` for "no ceiling declared", and
 * `ScanSubject::dry_streak` failing a whole document on one bad field). A
 * metric that could not be read must not report as a metric that measured
 * nothing.
 */
export type CuratorGrowth = { measuredAt: string, 
/**
 * Consumer projects the registry's map joins. **The numerator of the
 * operator's question**: the ecosystem is projects, not subjects.
 */
projects: number | null, 
/**
 * Context-to-subject pairs carrying any verdict at all.
 */
judgedPairs: number | null, 
/**
 * Judged pairs whose subject has since moved, so the verdict is a claim
 * about a document that no longer exists in that form. **Down is growth
 * here** - see [`CuratorGrowthMetric::higher_is_better`].
 */
staleVerdicts: number | null, 
/**
 * Distinct subjects `librarian/applied.md` says reached a project. The
 * only metric that proves knowledge left the registry.
 */
appliedSubjects: number | null, subjects: number | null, techniques: number | null, applications: number | null, };
