// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CuratorProcessSession } from "./CuratorProcessSession";
import type { CuratorProcessSource } from "./CuratorProcessSource";

export type CuratorProcess = { 
/**
 * Step kinds; a step's first tuple field indexes this list.
 */
kinds: Array<string>, 
/**
 * Kind -> phase (`brief`, `explore`, `edit`, `verify`, `ship`, or a non-work kind).
 */
phases: { [key in string]?: string }, sessions: Array<CuratorProcessSession>, source: CuratorProcessSource, };
