// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CuratorProcessSession = { id: string, 
/**
 * The fleet slug of the checkout the session ran in.
 */
project: string, 
/**
 * 1 when the session ran in a git worktree.
 */
wt: number, 
/**
 * `interactive` (a person steering) or `headless` (launched by a tool).
 */
mode: string | null, model: string | null, effort: string | null, start: string, 
/**
 * Wall-clock seconds, idle included.
 */
dur: number, 
/**
 * Seconds with every gap over ten minutes capped at ten minutes.
 */
active: number, prompts: number, interrupts: number, compactions: number, errors: number, commits: number, skills: Array<string>, steps: Array<[number, number, number, number, number, string | null]>, };
