// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TablePerfStats } from "./TablePerfStats";

export interface DbPerfSnapshot {
  tables: TablePerfStats[];
  totalQueries: number;
  totalSlowQueries: number;
  bufferCapacity: number;
  bufferUsed: number;
}
