// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step proposal returned by `decompose_goal`. The frontend wraps these
 * into editable composer rows before the user submits.
 */
export type DecomposedStep = { title: string, description: string, suggestedPersonaId: string | null, suggestedUseCaseId: string | null, };
