// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMasterLink } from "./AppMasterLink";
import type { ConnectorPipelineStep } from "./ConnectorPipelineStep";
import type { DesignFilesSection } from "./DesignFilesSection";
import type { DesignUseCase } from "./DesignUseCase";
import type { KpLink } from "./KpLink";

/**
 * Structured envelope for the `design_context` JSON column.
 *
 * Independent sections:
 * - `design_files` -- files & references for the AI design prompt
 * - `credential_links` -- connector name -> credential ID mappings
 * - `use_cases` -- structured workflow descriptions from design results
 * - `summary` -- optional human-readable summary (legacy compat)
 * - `connector_pipeline` -- chronological connector interaction sequence
 */
export type DesignContextData = { designFiles: DesignFilesSection | null, credentialLinks: { [key in string]?: string } | null, useCases: Array<DesignUseCase> | null, summary: string | null, connectorPipeline: Array<ConnectorPipelineStep> | null, 
/**
 * Twin profile this persona is pinned to. When `Some`, the
 * `builtin-twin` connector resolves this id instead of the
 * globally-active twin via `twin_get_active_profile(persona_id)`.
 * A deleted twin id silently falls back to the active twin so the
 * connector never errors on stale design_context entries.
 */
twinId: string | null, 
/**
 * Dev Tools project (codebase) this persona is pinned to. When `Some`,
 * the `codebase` connector resolves THIS `dev_projects.id` instead of the
 * globally-first project (`resolve_context_project`), so a team adopted
 * for repo X reads repo X. Set once by the team adoption questionnaire and
 * written to every member, so each persona keeps its binding independently
 * (it survives team disband). A deleted/inactive project silently falls
 * back to the global probe so the connector never errors on stale entries.
 * Mirrors `twin_id`.
 */
devProjectId: string | null, 
/**
 * Foundry foundation provenance — which mentality archetype this
 * persona was composed from (`scripts/templates/_archetypes.json`
 * id, e.g. `guardian`). Display + analytics only; the archetype's
 * content was compiled into the prompt at creation, so a stale or
 * deleted archetype id never breaks anything.
 */
archetypeId: string | null, 
/**
 * Foundry memory-strategy intent (`focused` | `learner` |
 * `team-player` | `grounded-expert` | `second-brain`). v1 records
 * the intent and drives setup guidance chips; the subsystems it
 * names are wired through their own existing surfaces.
 */
memoryStrategyId: string | null, 
/**
 * Agent-candidate bridge — the KP hiring-app job this persona was hired
 * for. `None` for every persona not created through a KP hire request.
 * Mirrors the `dev_project_id` precedent: typed + defaulted so existing
 * rows deserialize unchanged.
 */
kpLink: KpLink | null, 
/**
 * App master hire record (P4). `None` for every persona not hired through
 * a kp request carrying an `appMaster` block — including ordinary kp
 * hires, which keep `kp_link` alone. Typed + defaulted for the same
 * reason as `kp_link`: `DesignContextData` has no serde catch-all, so an
 * untyped key would be silently DROPPED on the next round-trip.
 */
appMaster: AppMasterLink | null, 
/**
 * Dev Tools WORKSPACE this persona is pinned to — the cross-project twin
 * of [`Self::dev_project_id`], set by the Architect adoption door. A
 * persona carrying this sees every project in the workspace rather than
 * one codebase; the two pins coexist (an Architect may also be pinned to
 * a project for its own connector reads) and neither implies the other.
 * Typed + defaulted for the same reason as `kp_link`: `DesignContextData`
 * has no serde catch-all, so an untyped key would be silently DROPPED on
 * the next round-trip.
 */
workspaceId: string | null, 
/**
 * The project a WORKSPACE-bound persona writes into when it has no
 * codebase of its own — the Architect's home.
 *
 * Deliberately NOT [`Self::dev_project_id`]. That key is what makes a
 * persona a project's App Master (`app_master_of_project` keys the
 * ownership lookup on it), so pinning the Architect there would report it
 * as the platform project's owner and send a second App Master adoption
 * looking for a project that already has one. This key carries the same
 * fact the Architect actually needs — *where do my documents go, and which
 * project do my project-shaped verbs default to* — without claiming
 * ownership of anything.
 *
 * Read through `personas_engine::design_context::working_project_id`,
 * which prefers `dev_project_id` and falls back here, so a project-bound
 * persona is untouched by its existence.
 */
homeProjectId: string | null, };
