// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectorPipelineStep } from "./ConnectorPipelineStep";
import type { DesignFilesSection } from "./DesignFilesSection";
import type { DesignUseCase } from "./DesignUseCase";

/**
 * Structured envelope for the `design_context` JSON column.
 *
 * Independent sections:
 * - `design_files` -- files & references for the AI design prompt
 * - `credential_links` -- connector name -> credential ID mappings
 * - `use_cases` -- structured workflow descriptions from design results
 * - `summary` -- optional human-readable summary (legacy compat)
 * - `connector_pipeline` -- chronological connector interaction sequence
 */
export type DesignContextData = { designFiles: DesignFilesSection | null, credentialLinks: { [key in string]?: string } | null, useCases: Array<DesignUseCase> | null, summary: string | null, connectorPipeline: Array<ConnectorPipelineStep> | null, 
/**
 * Twin profile this persona is pinned to. When `Some`, the
 * `builtin-twin` connector resolves this id instead of the
 * globally-active twin via `twin_get_active_profile(persona_id)`.
 * A deleted twin id silently falls back to the active twin so the
 * connector never errors on stale design_context entries.
 */
twinId: string | null, 
/**
 * Dev Tools project (codebase) this persona is pinned to. When `Some`,
 * the `codebase` connector resolves THIS `dev_projects.id` instead of the
 * globally-first project (`resolve_context_project`), so a team adopted
 * for repo X reads repo X. Set once by the team adoption questionnaire and
 * written to every member, so each persona keeps its binding independently
 * (it survives team disband). A deleted/inactive project silently falls
 * back to the global probe so the connector never errors on stale entries.
 * Mirrors `twin_id`.
 */
devProjectId: string | null, };
