// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A persistent design conversation that accumulates multi-turn context.
 */
export type DesignConversation = { id: string, personaId: string, 
/**
 * Short label for the conversation (auto-generated from first instruction)
 */
title: string, 
/**
 * Current conversation status: "active", "completed", "abandoned"
 */
status: string, 
/**
 * JSON array of DesignConversationMessage
 */
messages: string, 
/**
 * The latest design result JSON (cached for quick access)
 */
lastResult: string | null, createdAt: string, updatedAt: string, };
