// This file was generated by [ts-rs]. Do not edit this file manually.

export interface DesignConversation {
  id: string;
  personaId: string;
  title: string;
  status: string;
  messages: string;
  lastResult?: string;
  createdAt: string;
  updatedAt: string;
}
