// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesktopCapability } from "./DesktopCapability";

export type DesktopConnectorManifest = { connector_id: string, capabilities: DesktopCapability[], allowed_binaries: string[], allowed_paths: string[], allowed_ports: number[], justifications: Record<string, string>, };
