// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevCompetitionSlot = { id: string, competition_id: string, task_id: string, strategy_label: string, strategy_prompt: string | null, worktree_name: string, branch_name: string | null, slot_index: number, created_at: string };
