// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevGoalItem = { id: string, goal_id: string, title: string, done: boolean, order_index: number, created_at: string, updated_at: string, };
