// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevIdea = { id: string, project_id: string | null, context_id: string | null, scan_type: string, category: string, title: string, description: string | null, reasoning: string | null, status: string, effort: number | null, impact: number | null, risk: number | null, provider: string | null, model: string | null, rejection_reason: string | null, created_at: string, updated_at: string };
