// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevKpi = { id: string, project_id: string, 
/**
 * NULL = project-level KPI; otherwise attached to a context group.
 */
context_group_id: string | null,
/**
 * NULL unless the KPI is scoped to a single context. When set,
 * `context_group_id` is expected to be that context's parent group —
 * see context_taxonomy / Part 3 context-level KPIs.
 */
context_id: string | null, name: string, description: string | null,
/**
 * 'technical' | 'traffic' | 'value' | 'quality'
 */
category: string, 
/**
 * 'codebase' | 'connector' | 'manual' | 'derived'
 */
measure_kind: string, 
/**
 * JSON measurement procedure, shape per measure_kind.
 */
measure_config: string, unit: string, 
/**
 * 'up' | 'down' — which way is better.
 */
direction: string, baseline_value: number | null, target_value: number | null, target_date: string | null, current_value: number | null, last_measured_at: string | null, 
/**
 * 'manual' | 'daily' | 'weekly'
 */
cadence: string, 
/**
 * 'proposed' | 'active' | 'paused' | 'archived'
 */
status: string, 
/**
 * 'user' | 'scan'
 */
created_by: string, rationale: string | null, 
/**
 * Connector this KPI needs to be measurable — drives the
 * "Connect <service>" vault-catalog CTA on parked KPIs.
 */
needed_connector: string | null, 
/**
 * Semantic measurement capability (P6 type-bound connectors) — e.g.
 * `unique_visitors`, `llm_tokens`. The tool is a swappable binding.
 */
metric_type: string | null, 
/**
 * `north_star` | `primary` | `supporting` — derivation precedence
 * ("0 users beats 100% coverage").
 */
tier: string, created_at: string, updated_at: string, };
