// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevKpiBinding = { id: string, kpi_id: string, credential_id: string, service_type: string, 
/**
 * Frozen retrieval procedure JSON (engine::kpi_binding::Procedure).
 */
procedure: string, 
/**
 * 'recipe' | 'llm'
 */
composed_by: string, 
/**
 * 'active' | 'archived' | 'degraded'
 */
status: string, verified_at: string | null, created_at: string, };
