// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevKpiMeasurement = { id: string, kpi_id: string, value: number, measured_at: string, source: string, evidence: string | null, note: string | null, };
