// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scope membership: one row per (milestone, item). `item_kind` 'use_case'
 * rows are the work (bucketed core/later/never); 'goal' rows are bound
 * objectives. Contexts are never members — they derive from the bound use
 * cases' slices at read time.
 */
export type DevMilestoneItem = { milestone_id: string, 
/**
 * 'use_case' | 'goal'
 */
item_kind: string, item_id: string, 
/**
 * 'core' | 'later' | 'never'
 */
bucket: string, 
/**
 * Proposed after the cut — scope creep awaiting triage.
 */
added_after_cut: boolean, order_index: number, created_at: string, };
