// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteStatus } from "./NoteStatus";

/**
 * One note. Mirrors `dev_notes` column-for-column.
 */
export type DevNote = { id: string, 
/**
 * The repo this note is about. NULL until the operator picks one — and
 * NULL again if that project is deleted (`ON DELETE SET NULL`), because
 * the thinking outlives the row it pointed at.
 */
projectId: string | null, title: string, bodyMd: string, status: NoteStatus, orderIndex: number, 
/**
 * 'fleet' | 'athena_goals' — where this note was handed to. NULL until a
 * dispatch happens.
 */
dispatchTarget: string | null, 
/**
 * `note:<id>` — the address the dispatcher stamps on the session name so
 * the sweeper can find the run that belongs to this note.
 */
dispatchKey: string | null, fleetSessionId: string | null, 
/**
 * Reserved for a future per-note agent binding; always NULL in v1.
 */
agentId: string | null, 
/**
 * JSON text. Fleet runs store the `result.json` body
 * (`{schema_version,status,summary,artifacts[]}`); an Athena goals
 * dispatch stores `{goal_ids: [...]}`.
 */
resultJson: string | null, publishedAt: string | null, startedAt: string | null, completedAt: string | null, archivedAt: string | null, createdAt: string, updatedAt: string, };
