// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegistryPairingState } from "./RegistryPairingState";

/**
 * A knowledge registry: the repo, the working copy on this machine, and what
 * pairing found inside it.
 *
 * `id` is `owner/repo` (or, for a local checkout with no catalog entry, the
 * `registry.yaml` name or the folder path) — the identity, so picking the same
 * repo in a second workspace resolves to the SAME row rather than cloning it
 * twice.
 */
export type DevRegistry = { id: string, fullName: string, url: string, defaultBranch: string, 
/**
 * Vault credential the repo was picked with; empty for a local checkout,
 * which needs none.
 */
credentialId: string, 
/**
 * Absolute path of the local clone — CHOSEN by the operator, not derived.
 * A scan reads the registry working copy and the project repos side by
 * side, so a URL alone is not a usable wiring.
 */
clonePath: string, state: RegistryPairingState, 
/**
 * Fleet session that ran (or is running) the pairing brief.
 */
sessionId: string | null, 
/**
 * Lanes the registry actually publishes, discovered by pairing. Plain
 * strings rather than an enum: the lane vocabulary belongs to the registry
 * spec, which grows without this app's permission, and a lane this build
 * has not heard of must travel rather than fail a deserialize.
 */
lanes: Array<string>, 
/**
 * Bundle domains under `knowledge/`, discovered by pairing.
 */
domains: Array<string>, 
/**
 * Commit the local clone is pinned at.
 */
sha: string | null, pairedAt: string | null, error: string | null, createdAt: string, updatedAt: string, };
