// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegistryPairingState } from "./RegistryPairingState";

/**
 * What a writer supplies. The two timestamps are the store's to mint, so they
 * are absent here rather than accepted and overwritten.
 */
export type DevRegistryInput = { id: string, fullName: string, url: string, defaultBranch: string, credentialId: string, clonePath: string, state: RegistryPairingState, sessionId: string | null, lanes: Array<string>, domains: Array<string>, sha: string | null, pairedAt: string | null, error: string | null, };
