// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One per-rule compliance finding from the golden-standard LLM scan
 * (`standards_scan.rs`). The scan adapts the shipped golden ruleset to the
 * repo's character and reports each rule's status to this table.
 */
export type DevStandard = { id: string, project_id: string, scan_id: string | null, 
/**
 * Stable rule identifier, e.g. `lint.config`, `docs.readme`, `tests.coverage`, `branching.naming`.
 */
rule_key: string, 
/**
 * `precommit` | `docs` | `code_quality` | `branching` | `testing`.
 */
category: string, title: string, 
/**
 * `present` | `partial` | `missing`.
 */
status: string, 
/**
 * `info` | `warn` | `critical`.
 */
severity: string, evidence: string | null, recommendation: string | null, created_at: string, updated_at: string, };
