// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevStandard = { id: string, project_id: string, scan_id: string | null, rule_key: string, category: string, title: string, status: string, severity: string, evidence: string | null, recommendation: string | null, created_at: string, updated_at: string, };
