// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevScan = { id: string, project_id: string | null, scan_type: string, status: string, idea_count: number, input_tokens: bigint | null, output_tokens: bigint | null, duration_ms: bigint | null, error: string | null, created_at: string, };
