// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevTask = { id: string, project_id: string | null, title: string, description: string | null, source_idea_id: string | null, goal_id: string | null, status: string, session_id: string | null, progress_pct: number, output_lines: number, error: string | null, started_at: string | null, completed_at: string | null, created_at: string, depth: string };
