// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DigestPersonaTrend {
  personaId: string;
  personaName: string;
  successRate: number;
  prevSuccessRate: number;
  trend: number;
  totalExecutions: number;
  totalCost: number;
}
