// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectorRosterEntry } from "./DirectorRosterEntry";
import type { DirectorScoreBand } from "./DirectorScoreBand";
import type { ValueRollup } from "./ValueRollup";

/**
 * Portfolio-level Director analytics for the command center: the whole-fleet
 * value rollup, the in-scope roster, the latest-score distribution, and
 * headline counts. Composed entirely from existing aggregates.
 */
export type DirectorPortfolio = { 
/**
 * Whole-fleet value rollup (all personas, not only starred) — the
 * Director's domain is the whole fleet's value, so the headline KPIs are
 * fleet-wide.
 */
rollup: ValueRollup, 
/**
 * One entry per starred (in-scope) persona.
 */
roster: Array<DirectorRosterEntry>, 
/**
 * Latest-score histogram across in-scope personas (always 6 bands 0..=5).
 */
scoreDistribution: Array<DirectorScoreBand>, inScope: number, reviewed: number, unreviewed: number, 
/**
 * Mean latest-score across reviewed in-scope personas; `None` when none
 * have been reviewed yet.
 */
avgScore: number | null, periodDays: number, };
