// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectorCategory } from "./DirectorCategory";
import type { DirectorSeverity } from "./DirectorSeverity";

/**
 * A single piece of coaching. Produced by an evaluator, routed into the
 * Human Review layer.
 */
export type DirectorVerdict = { targetPersonaId: string, severity: DirectorSeverity, category: DirectorCategory, title: string, description: string, rationale: string | null, suggestedActions: Array<string>, };
