// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiscoveredApp = { connector_name: string, label: string, installed: boolean, binary_path: string | null, version: string | null, running: boolean, category: string, };
