// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DispatchVerdict } from "./DispatchVerdict";

/**
 * One persona in the order the loop will walk, with what the next tick
 * would do to it. Every field the Orchestration tab renders.
 */
export type DispatchPreviewRow = { personaId: string, personaName: string, personaIcon: string | null, personaColor: string | null, 
/**
 * 1-based position in the walk.
 */
position: number, 
/**
 * The operator's rank (1-based) when ranked; `None` = unranked, sorted
 * after every ranked persona by need.
 */
rank: number | null, wakePending: boolean, lastServedAt: string | null, 
/**
 * The interval floor the persona is owed between passes, in minutes —
 * an App Master's own `nextWakeMinutes`, else the most conservative
 * charter interval.
 */
intervalMinutes: number, selfPaced: boolean, appMaster: boolean, 
/**
 * Active attention charters.
 */
charters: number, verdict: DispatchVerdict, 
/**
 * The lane the tick would take (`arrivals` / `advance` / `improve` /
 * `decide` / `maintenance`), when admitted with work.
 */
lane: string | null, };
