// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DispatchPreviewRow } from "./DispatchPreviewRow";

/**
 * The next tick as the loop would plan it right now, without planning it.
 */
export type DispatchPreview = { 
/**
 * Starts this tick may make: the pacing slots capped by the running-work
 * headroom and `MAX_DISPATCHES_PER_TICK` — zero while the pacing holds.
 */
budget: number, 
/**
 * Personas that would be started (`Dispatch` verdicts).
 */
wouldStart: number, 
/**
 * Personas admitted with work but out of budget (`WaitsForSlot`).
 */
waiting: number, rows: Array<DispatchPreviewRow>, };
