// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One idea that made it onto the runway, with everything either executor needs.
 */
export type DispatchedIdea = { ideaId: string, taskId: string, title: string, projectId: string | null, projectName: string | null, 
/**
 * The project's working directory — `None` when the project is gone or
 * pathless. The fleet arm needs it; the runner arm doesn't.
 */
rootPath: string | null, 
/**
 * The composed task description, so the fleet arm can seed a session with
 * the exact same text the runner would have executed.
 */
prompt: string, };
