// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DispatchVerdict } from "./DispatchVerdict";
import type { HeadlessState } from "./HeadlessState";

/**
 * One persona in the order the loop will walk, with what the next tick
 * would do to it. Every field the Orchestration tab renders.
 */
export type DispatchPreviewRow = { personaId: string, personaName: string, personaIcon: string | null, personaColor: string | null, 
/**
 * The persona's Active/Off switch. A disabled persona keeps its place in
 * the order but is never walked (`DispatchVerdict::Disabled`).
 */
enabled: boolean, 
/**
 * 1-based position in the walk.
 */
position: number, wakePending: boolean, lastServedAt: string | null, 
/**
 * The interval floor the persona is owed between passes, in minutes —
 * an App Master's own `nextWakeMinutes`, else the most conservative
 * charter interval.
 */
intervalMinutes: number, selfPaced: boolean, appMaster: boolean, 
/**
 * Active attention charters.
 */
charters: number, verdict: DispatchVerdict, 
/**
 * The lane the tick would take (`arrivals` / `advance` / `improve` /
 * `decide` / `maintenance`), when admitted with work.
 */
lane: string | null, 
/**
 * The project's headless App Master (`/appmaster`), when this persona is
 * that project's App Master and a beat was ever posted for it. Filled
 * whatever the persona's own switch says: a switched-off in-app master
 * whose project a terminal is running must not read only "Switched off".
 */
headless?: HeadlessState, };
