// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An idea that could not be dispatched, and why. Reported per item — a batch
 * dispatch that silently drops half its input is worse than one that fails.
 */
export type DispatchSkip = { ideaId: string, reason: string, };
