// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolIssue } from "./ToolIssue";

export type DraftValidationResult = { passed: boolean, error: string | null, output_preview: string | null, tool_issues: ToolIssue[], };
