// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DriveTagColor = "red" | "orange" | "yellow" | "green" | "blue" | "purple" | "gray";
