// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriveTagColor } from "./DriveTagColor";

export type DriveTag = { 
/**
 * `label:<color>` for the seven builtins, `tag:<uuid>` for user tags.
 */
id: string, 
/**
 * Display name. Builtins carry the colour token name; the UI localises.
 */
name: string, color: DriveTagColor, 
/**
 * Builtins cannot be deleted or renamed.
 */
builtin: boolean, };
