// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCategoryCount } from "./ErrorCategoryCount";
import type { PersonaTopErrorCategory } from "./PersonaTopErrorCategory";

/**
 * Per-category failure counts over a window plus the immediately-prior window
 * of equal length, so the dashboard can surface **category-grounded deltas**
 * instead of a bare error rate (raw trends were deliberately dropped as noise).
 *
 * Classification runs at aggregation time by feeding each stored
 * `error_message` through the shared `engine::error_taxonomy::classify_error_str`
 * — the SAME 11-category taxonomy used by healing and failover, not a fork.
 * Simulations are excluded (their failures are stubbed, not real signal), the
 * same way `get_value_rollup` excludes them.
 */
export type ErrorCategoryBreakdown = { periodDays: number, 
/**
 * Total classified failures in the current window.
 */
totalFailures: number, 
/**
 * Total classified failures in the prior window of equal length.
 */
priorTotalFailures: number, 
/**
 * Per-category counts, descending by current-window count.
 */
categories: Array<ErrorCategoryCount>, 
/**
 * Per-persona dominant failure category (descending by count), capped.
 */
personaTopCategories: Array<PersonaTopErrorCategory>, };
