// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight per-run row for the history list and cert grouping.
 */
export type EvalRunSummary = { runId: string, team: string | null, teamId: string | null, seed: string | null, startedAt: string | null, 
/**
 * Resolved from `verdict` ?? `provisional_verdict`.
 */
verdict: string | null, 
/**
 * `true` when `verdict` resolved from `provisional_verdict`.
 */
provisional: boolean, teamScore: number | null, heldOut: boolean, hasScorecard: boolean, hasCodeTrack: boolean, delivered: boolean | null, selfVetoed: boolean, cascadeStalled: boolean | null, groundingPct: number | null, costUsd: number | null, rubricVersion: string | null, };
