// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EvolutionPolicy {
  id: string;
  personaId: string;
  enabled: boolean;
  fitnessObjective: string;
  mutationRate: number;
  variantsPerCycle: number;
  improvementThreshold: number;
  minExecutionsBetween: number;
  lastCycleAt: string | null;
  totalCycles: number;
  totalPromotions: number;
  createdAt: string;
  updatedAt: string;
}
