// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EvolutionCycle {
  id: string;
  policyId: string;
  personaId: string;
  status: string;
  variantsTested: number;
  winnerFitness: number | null;
  incumbentFitness: number | null;
  promoted: boolean;
  summary: string | null;
  error: string | null;
  startedAt: string;
  completedAt: string | null;
}
