// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunBudgetState } from "./RunBudgetState";

/**
 * Summary of an evolution cycle result.
 */
export type EvolutionCycleSummary = { cycleId: string, personaId: string, generation: number, variantsTested: number, winnerFitness: number | null, incumbentFitness: number | null, promoted: boolean, promotedPersonaId: string | null, 
/**
 * Whether all status updates succeeded during the cycle.
 * `false` means the frontend may have shown stale status at some point.
 */
statusReliable: boolean, 
/**
 * Warnings encountered during the cycle (e.g. fitness objective fallback).
 */
warnings: Array<string>, 
/**
 * Raw fitness objective JSON from the policy, preserved for forensic debugging.
 */
rawFitnessObjective: string | null, 
/**
 * Aggregate cost-budget state for this cycle's many CLI spawns (P2). `None`
 * on cycles that ran before budget tracking. Surfaced in the cycle UI.
 */
budget: RunBudgetState | null, };
