// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionListItem = { id: string, persona_id: string, use_case_id: string | null, status: string, input_tokens: number, output_tokens: number, cost_usd: number | null, error_message: string | null, duration_ms: number | null, retry_of_execution_id: string | null, retry_count: number, started_at: string | null, completed_at: string | null, created_at: string, is_simulation: boolean, business_outcome: string, 
/**
 * Run origin, derived in the list SQL (see `LIST_ITEM_COLUMNS` in the
 * executions repo): 'attention' | 'channel' | 'scheduled' | 'simulation'
 * | 'manual'. Precedence in that order; 'manual' is the fallback.
 */
origin: string, 
/**
 * The attention lane (`$._attention.lane` in input_data) when the run was
 * dispatched by the attention loop; `None` otherwise.
 */
origin_lane: string | null, };
