// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a pre-flight execution preview.
 */
export type ExecutionPreview = { 
/**
 * Assembled prompt text (for inspection).
 */
prompt_preview: string, 
/**
 * Approximate input token count.
 */
estimated_input_tokens: bigint, 
/**
 * Projected output tokens (based on typical response ratio).
 */
estimated_output_tokens: bigint, 
/**
 * Estimated input cost (USD).
 */
estimated_input_cost: number, 
/**
 * Estimated output cost (USD).
 */
estimated_output_cost: number, 
/**
 * Estimated total cost (USD).
 */
estimated_total_cost: number, 
/**
 * Model that would be used.
 */
model: string, 
/**
 * Number of memories that would be injected.
 */
memory_count: number, 
/**
 * Number of tools available.
 */
tool_count: number, 
/**
 * Current monthly spend for this persona (USD).
 */
monthly_spend: number, 
/**
 * Monthly budget limit (USD, 0 = unlimited).
 */
budget_limit: number, };
