// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The counters above the board. Every one is `i32`: these reach a TS `number`,
 * and a `bigint` field would break every arithmetic use of it (census
 * `bigint-binding-field`).
 */
export type FeatureBoardTotals = { contexts: number, groups: number, features: number, majors: number, core: number, platform: number, tests: number, unclaimed: number, 
/**
 * Features whose council state is `ready` AND tier `major` - the ones
 * sitting at a human gate right now.
 */
waitingOnYou: number, 
/**
 * Council state in fail / stalled / rejected / approved_drifted.
 */
inTrouble: number, };
