// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileIdeaInput = { project_id: string, title: string, description: string | null, reasoning: string | null, category: string | null, effort: number | null, impact: number | null, risk: number | null, context_id: string | null, 
/**
 * The goal this item serves: a goal id, an id prefix of 8+ characters,
 * or the goal's exact title. Resolved against the project; a reference
 * that names no single goal files the item unbound and says so in
 * `goal_note` rather than refusing the filing.
 */
goal: string | null, };
