// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FleetRunSession } from "./FleetRunSession";
import type { FleetRunTotals } from "./FleetRunTotals";

/**
 * A whole run, ready to render or export.
 */
export type FleetRunReport = { runId: string, runLabel: string | null, 
/**
 * Earliest spawn in the run.
 */
startedAtMs: bigint, sessions: Array<FleetRunSession>, totals: FleetRunTotals, };
