// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One paired device as surfaced to the settings UI (no fingerprint).
 */
export type FleetCompanionDevice = { id: string, name: string, createdAtMs: bigint, lastSeenMs: bigint, revoked: boolean, };
