// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FleetSessionState } from "./FleetSessionState";

/**
 * A tracked Claude Code session.
 *
 * One per spawned PTY child. The `claude_session_id` is `None` until the
 * first `SessionStart` hook fires; we reconcile by `cwd` until then.
 */
export type FleetSession = { 
/**
 * Stable internal id minted at spawn time (UUID v4 as string).
 */
id: string, 
/**
 * Claude Code's own session id (from SessionStart hook). `None` while
 * the session is `Spawning`.
 */
claudeSessionId: string | null, 
/**
 * Working directory the `claude` child was spawned in. Doubles as
 * the project key (we group sessions by `project_label` derived from
 * this path).
 */
cwd: string, 
/**
 * Human-readable project label — last path segment of `cwd` by default,
 * overrideable in settings.
 */
projectLabel: string, 
/**
 * User-supplied per-session name. `None` by default; the UI shows it
 * next to `project_label` when set so users can disambiguate
 * multiple parallel sessions on the same project (e.g. "refactor",
 * "tests", "smoke run"). Settable via `fleet_rename_session`.
 */
name: string | null, 
/**
 * Live terminal title emitted by Claude Code via OSC (a summary of the
 * current task), captured from the PTY stream. `None` until Claude sets one.
 * The UI prefers this over `name` / `project_label` to label a tile, so each
 * session reads distinctly instead of all showing the same project name.
 */
title: string | null, 
/**
 * Extra CLI arguments passed to `claude` at spawn time. Empty by default.
 */
args: Array<string>, 
/**
 * Current lifecycle state. See [`FleetSessionState`].
 */
state: FleetSessionState, 
/**
 * Wall-clock ms since UNIX epoch of the most recent activity signal
 * (hook fired, PTY bytes, JSONL append). Frontend uses this for the
 * "Xs ago" label and Stale detection cutoff.
 */
lastActivityMs: bigint, 
/**
 * When the PTY last produced ANY bytes — including idle status redraws
 * (0 = never). Provenance signal for the state tooltip; total silence
 * is what the frozen-process stall check keys on.
 */
lastPtyOutputMs: bigint, 
/**
 * When the transcript (JSONL) last actually grew, per the staleness
 * ticker's size polling (0 = not yet observed). Provenance signal.
 */
lastGrewMs: bigint, 
/**
 * Wall-clock ms since UNIX epoch when the PTY was spawned.
 */
createdAtMs: bigint, 
/**
 * PID of the `claude` child. `None` after exit.
 */
childPid: number | null, 
/**
 * Exit code if `state == Exited`. `None` for unclean exits (crash / signal).
 */
exitCode: number | null, 
/**
 * Free-form last-state-change reason — surfaced as a tooltip on the
 * status badge. e.g. "Notification: permission requested", "Stop hook".
 */
stateReason: string | null, };
