// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FleetTokenTotals } from "./FleetTokenTotals";
import type { FleetToolCount } from "./FleetToolCount";

/**
 * Structured rollup of a single Claude Code session transcript.
 */
export type FleetTranscriptSummary = { 
/**
 * Claude session id (the JSONL filename stem).
 */
claudeSessionId: string, 
/**
 * Absolute path to the parsed JSONL file.
 */
path: string, 
/**
 * `cwd` recorded in the transcript (the project the session ran in).
 */
cwd: string | null, 
/**
 * Genuine user prompts submitted (tool-result echoes are excluded).
 */
userMessages: number, 
/**
 * Assistant turns.
 */
assistantMessages: number, 
/**
 * Token totals across all assistant turns.
 */
tokens: FleetTokenTotals, 
/**
 * Distinct models seen, in first-seen order.
 */
models: Array<string>, 
/**
 * Per-tool invocation counts, sorted by count desc then name.
 */
tools: Array<FleetToolCount>, 
/**
 * Distinct files modified (Edit/Write/MultiEdit/NotebookEdit), sorted.
 */
filesTouched: Array<string>, 
/**
 * Earliest / latest entry timestamp (ISO-8601, sorts chronologically).
 */
firstTimestamp: string | null, lastTimestamp: string | null, 
/**
 * JSONL lines that failed to parse (format-drift diagnostic).
 */
parseErrors: number, 
/**
 * Non-empty lines read.
 */
totalLines: number, };
