// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state of a tracked Claude Code session.
 *
 * Driven by a union of three signals (in order of authority):
 * 1. Process exit (`Exited`) — PTY child reaper.
 * 2. Hook callbacks — `Notification` → `AwaitingInput`, `Stop` → `Idle`,
 *    `PreToolUse` / `UserPromptSubmit` → `Running`.
 * 3. JSONL transcript mtime — fallback for `Stale` detection.
 *
 * The variants are intentionally string-tagged so the frontend can render
 * them without an integer enum mapping. Keep names stable; they ship in
 * `FLEET_SESSION_STATE` event payloads and persisted decision logs.
 */
export type FleetSessionState = "spawning" | "running" | "awaiting_input" | "idle" | "stale" | "exited";
