// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One session's live monitor stats. Fields the session has no source for
 * (never bound a `claudeSessionId`, no process) read as 0 / `null` — the
 * frontend decides what to show instead.
 */
export type FleetMonitorStats = { 
/**
 * Internal Fleet session id — the join key with `FleetSession`.
 */
sessionId: string, 
/**
 * Bound Claude session id, or `None` when no hook has bound one yet
 * (in which case every transcript-derived field below is 0).
 */
claudeSessionId: string | null, 
/**
 * Output tokens across the whole session — the "effort spent" proxy.
 */
outputTokens: bigint, 
/**
 * Approximate current context-window size (last turn's input + cache read).
 */
contextTokens: bigint, 
/**
 * Subagents launched over the session's lifetime (`Task` tool uses).
 */
subagentsTotal: number, 
/**
 * Subagents open RIGHT NOW — PreToolUse/PostToolUse pairs on `Task`.
 * Never negative; 0 for a session with no live process.
 */
subagentsActive: number, 
/**
 * Background shells launched over the session's lifetime (`Bash` with
 * `run_in_background: true`).
 */
bgProcsLaunched: number, 
/**
 * Resident memory of the session's process in MB, or `None` when the
 * session has no live process (dozing / hibernated / exited).
 */
memMb: bigint | null, };
