// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FleetSessionMode } from "./FleetSessionMode";
import type { FleetSessionState } from "./FleetSessionState";

/**
 * A tracked Claude Code session.
 *
 * One per spawned PTY child. The `claude_session_id` is `None` until the
 * first `SessionStart` hook fires; we reconcile by `cwd` until then.
 */
export type FleetSession = { 
/**
 * Stable internal id minted at spawn time (UUID v4 as string).
 */
id: string, 
/**
 * Claude Code's own session id (from SessionStart hook). `None` while
 * the session is `Spawning`.
 */
claudeSessionId: string | null, 
/**
 * Working directory the `claude` child was spawned in. Doubles as
 * the project key (we group sessions by `project_label` derived from
 * this path).
 */
cwd: string, 
/**
 * Human-readable project label — last path segment of `cwd` by default,
 * overrideable in settings.
 */
projectLabel: string, 
/**
 * User-supplied per-session name. `None` by default; the UI shows it
 * next to `project_label` when set so users can disambiguate
 * multiple parallel sessions on the same project (e.g. "refactor",
 * "tests", "smoke run"). Settable via `fleet_rename_session`.
 */
name: string | null, 
/**
 * Live terminal title emitted by Claude Code via OSC (a summary of the
 * current task), captured from the PTY stream. `None` until Claude sets one.
 * The UI prefers this over `name` / `project_label` to label a tile, so each
 * session reads distinctly instead of all showing the same project name.
 */
title: string | null, 
/**
 * Extra CLI arguments passed to `claude` at spawn time. Empty by default.
 */
args: Array<string>, 
/**
 * How the process is driven — interactive PTY or headless stream-json.
 * The UI never mounts an xterm for a headless session (there is no TTY);
 * it renders the status block / insights and replies via `write_input`,
 * which wraps text into a stream-json user message on this lane.
 */
mode: FleetSessionMode, 
/**
 * Current lifecycle state. See [`FleetSessionState`].
 */
state: FleetSessionState, 
/**
 * Wall-clock ms since UNIX epoch of the most recent activity signal
 * (hook fired, PTY bytes, JSONL append). Frontend uses this for the
 * "Xs ago" label and Stale detection cutoff.
 */
lastActivityMs: bigint, 
/**
 * When the PTY last produced ANY bytes — including idle status redraws
 * (0 = never). Provenance signal for the state tooltip; total silence
 * is what the frozen-process stall check keys on.
 */
lastPtyOutputMs: bigint, 
/**
 * When the transcript (JSONL) last actually grew, per the staleness
 * ticker's size polling (0 = not yet observed). Provenance signal.
 */
lastGrewMs: bigint, 
/**
 * Wall-clock ms since UNIX epoch when the PTY was spawned.
 */
createdAtMs: bigint, 
/**
 * PID of the `claude` child. `None` after exit.
 */
childPid: number | null, 
/**
 * Exit code if `state == Exited`. `None` for unclean exits (crash / signal).
 */
exitCode: number | null, 
/**
 * Free-form last-state-change reason — surfaced as a tooltip on the
 * status badge. e.g. "Notification: permission requested", "Stop hook".
 */
stateReason: string | null, 
/**
 * True while Athena has actively taken this session's `AwaitingInput`
 * ticket and is reasoning about it (a short self-expiring window set by
 * `orchestrate_on_awaiting`). Drives the light-blue "Athena's on it" tile
 * affordance so her work is visible. Only meaningful while `AwaitingInput`;
 * once she acts (→ `Running`) or the window lapses, it's `false`.
 */
athenaActive: boolean, 
/**
 * Light sleep: the process was freed while the session sat parked in
 * `Stale`/`AwaitingInput`, but `state` deliberately still shows what it
 * was doing. The UI renders a small sleep indicator and wakes the session
 * (`claude --resume`, same-slot) when the operator selects it.
 */
dozing: boolean, 
/**
 * Wall-clock ms (UNIX epoch) when Claude's stated usage/session limit
 * resets, parsed from the limit banner (`resets 7:50pm`). `None` when the
 * session is not limit-parked or the banner did not state a parseable
 * time — in which case the mechanical retry keeps its blind cadence. The
 * UI renders it as a countdown chip ("resumes ~19:50") so the operator can
 * see when the fleet comes back instead of watching retries burn cycles.
 * Always in the future; a lapsed stamp is not surfaced.
 */
limitResetAtMs: bigint | null, 
/**
 * TYPED read of why a parked session is parked, from the transcript
 * classifier (`fleet::classify`): `done` | `blocked_question` |
 * `blocked_permission` | `hung_mid_tool`, or `None` when the classifier
 * abstained. `state` alone conflated a finished run, a run waiting on a
 * question, and a genuinely wedged run into one amber bucket, and the
 * distinction lived only inside free-text `state_reason` prose the UI
 * then string-matched. Advisory: it never overrides `state`, it explains
 * it.
 */
staleKind: string | null, 
/**
 * Dispatch-queue position, 1-based and dense, while `state == Queued`.
 * `None` once the session has been promoted (or was never queued).
 */
queueRank: number | null, 
/**
 * When the dispatch was admitted to the queue (ms since epoch). Kept
 * after promotion so the wait can be measured; `None` for a dispatch
 * that started immediately.
 */
queuedAtMs: number | null, 
/**
 * Earliest moment the queue may promote this row (ms since epoch). A
 * row whose gate is still in the future is skipped, not blocked on.
 */
notBeforeMs: number | null, 
/**
 * Who asked for this session — a `DispatchOrigin` token (`manual`,
 * `dev_runner`, `autopilot`, …). `None` for rows written before the
 * queue existed.
 */
origin: string | null, 
/**
 * The persona this dispatch works for, when a persona dispatched it.
 */
personaId: string | null, 
/**
 * The goal the dispatch advances, when one was named.
 */
goalId: string | null, 
/**
 * Which autopilot / night-shift cycle produced this dispatch.
 */
cycleIndex: number | null, 
/**
 * Set only on the RUNNING device for a session a paired device dispatched
 * here (`origin == "remote"`): the `remote_jobs` id that spawned it.
 * `None` for every locally started session.
 */
remoteJobId: string | null, 
/**
 * Set only on the RUNNING device: the peer_id of the device that asked.
 * The tile's "from <device>" chip reads it. `None` for local sessions.
 */
originPeerId: string | null, };
