// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of the fleet hook installation in `~/.claude/settings.json`.
 *
 * Returned by `fleet_check_hooks`. `missing_events` lists the Claude
 * Code hook types we need but didn't find tagged with `_fleet: true` —
 * drives the "Re-install" CTA when the user manually edited the file.
 */
export type FleetHookStatus = { installed: boolean, 
/**
 * Hook event names present and tagged (`Stop`, `Notification`, etc.).
 */
presentEvents: Array<string>, 
/**
 * Hook event names we need but couldn't find.
 */
missingEvents: Array<string>, 
/**
 * Resolved port the installed entries point at. Compared against
 * the currently-bound port to detect stale installs after a restart.
 */
installedPort: number | null, 
/**
 * Whether the installed port matches the currently-bound port.
 */
portMatches: boolean, };
