// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GalaxySubject } from "./GalaxySubject";

export type GalaxyCategory = { id: string, title: string, subjects: Array<GalaxySubject>, };
