// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One technique as the galaxy draws it: a satellite of its subject.
 */
export type GalaxyTechnique = { slug: string, laws: Array<string>, 
/**
 * Up to two trigger phrases, for search and the tooltip.
 */
useWhen: Array<string>, };
