// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single offspring result from a breeding run.
 */
export type GenomeBreedingResult = { id: string, runId: string, 
/**
 * JSON-serialized PersonaGenome.
 */
genomeJson: string, 
/**
 * JSON array of parent IDs for this specific offspring.
 */
parentIds: string, 
/**
 * Which generation this offspring belongs to.
 */
generation: number, 
/**
 * JSON-serialized FitnessScore (null until evaluated).
 */
fitnessJson: string | null, 
/**
 * Overall fitness score (for sorting/ranking).
 */
fitnessOverall: number | null, 
/**
 * Whether user adopted this offspring as a new persona.
 */
adopted: boolean, 
/**
 * The persona ID if this offspring was adopted.
 */
adoptedPersonaId: string | null, createdAt: string, };
