// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single offspring result from a breeding run.
 */
export type GenomeBreedingResult = { id: string, runId: string, 
/**
 * JSON-serialized PersonaGenome.
 */
genomeJson: string, 
/**
 * JSON array of parent IDs for this specific offspring.
 */
parentIds: string, 
/**
 * Which generation this offspring belongs to.
 */
generation: number, 
/**
 * JSON-serialized fitness. When `fitness_source` is `"inherited"` this is
 * the mid-parent *prediction*; when `"measured"` it is a
 * `MeasuredFitness` produced by replaying the fixture set through this
 * offspring (Darwin Mode). Null only if neither could be computed.
 */
fitnessJson: string | null, 
/**
 * Overall fitness for sorting/ranking. Predicted or measured per
 * `fitness_source`.
 */
fitnessOverall: number | null, 
/**
 * Provenance of the fitness fields: `"inherited"` (mid-parent prediction)
 * or `"measured"` (fixture-replay evaluation). `None` on legacy rows,
 * which are all inherited.
 */
fitnessSource: string | null, 
/**
 * Whether user adopted this offspring as a new persona.
 */
adopted: boolean, 
/**
 * The persona ID if this offspring was adopted.
 */
adoptedPersonaId: string | null, createdAt: string, };
