// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitHubRepo = { id: bigint, name: string, fullName: string, private: boolean, defaultBranch: string, };
