// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitLabProject = { id: bigint, name: string, pathWithNamespace: string, webUrl: string, defaultBranch: string | null, };
