// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Honest, probe-derived lifecycle status for a single GitLab deployment.
 *
 * Unlike the raw agent list (which returns rows only for live Duo agents and
 * carries no lifecycle field), this reconciles the LIVE `list_duo_agents`
 * registry against `deployment_history` so the dashboard can show a truthful
 * state per deployment instead of a green `active` by construction:
 *
 * - `active`     — a live Duo Agent definition is currently registered in
 *                  GitLab (confirmed present via the API on this probe).
 * - `file-based` — deployed via the AGENTS.md fallback, i.e. no live Duo
 *                  agent exists. A distinct honest state, previously invisible.
 * - `failed`     — a deploy recorded an `agent_id` (was a live Duo agent) but
 *                  that agent is no longer in the live registry (removed/gone).
 * - `unknown`    — the GitLab API probe could not confirm live state
 *                  (unreachable / errored / Duo API unavailable). Never a
 *                  false green.
 */
export type GitLabDeploymentStatus = { 
/**
 * Live Duo Agent id when this deployment is a live agent; `None` for
 * file-based deploys or when the live agent is gone.
 */
agentId: string | null, 
/**
 * Owning persona id, resolved from history when available.
 */
personaId: string | null, 
/**
 * Persona / agent display name.
 */
personaName: string, 
/**
 * Deploy method: `"api"` (live Duo agent) or `"agents_md"` (file fallback).
 */
method: string, 
/**
 * Deep link to the agent or AGENTS.md file.
 */
webUrl: string | null, 
/**
 * Honest lifecycle token: `active` | `file-based` | `failed` | `unknown`.
 */
status: string, 
/**
 * ISO8601 timestamp of the deploy (from history) or agent creation.
 */
createdAt: string | null, };
