// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitLabPipeline = { id: number, status: string, ref: string, webUrl: string, createdAt: string, updatedAt: string, duration: number | null, };
