// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitLabDeployResult } from "./GitLabDeployResult";

/**
 * Result from a rollback operation.
 */
export type GitLabRollbackResult = { 
/**
 * The tag that was rolled back to
 */
rolledBackTo: string, 
/**
 * New tag created for the rollback
 */
newTag: string | null, 
/**
 * Deploy result from redeploying the old version
 */
deployResult: GitLabDeployResult, };
