// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitLabDeployResult = { agentId: string | null, webUrl: string | null, method: string, credentialsProvisioned: number, };
