// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Working-tree snapshot for one managed project, as the Dev Tools project
 * card renders it.
 *
 * snake_case (no `rename_all`) — the call site in `api/devTools` already
 * declared this exact shape inline, down to `changed_files_count`.
 */
export type GitStatusSummary = { project_id: string, project_name: string, 
/**
 * Empty string on a detached HEAD (`git branch --show-current` prints
 * nothing), which the card renders as "no branch".
 */
branch: string, is_clean: boolean, changed_files_count: number, 
/**
 * Raw `git status --porcelain` lines, status prefix included.
 */
changed_files: Array<string>, 
/**
 * Up to five `git log --oneline` lines.
 */
recent_commits: Array<string>, };
