// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The LEAN row behind the global (all-persona) execution list — Activity, the
 * LLM-calls table, Mission Control's success ring and the Home runs sample.
 *
 * `GlobalExecutionRow` above flattens the whole `PersonaExecution`, blobs and
 * all. Measured (`lean_global_list_payload_is_an_order_of_magnitude_smaller`,
 * blob sizes taken from the 2026-06-02 snapshot): 500 rows serialize to
 * **9.26 MB** as the fat row and **180 KB** as this one — 53x — and the IPC
 * transport `structuredClone`s every hand-out. None of `input_data`,
 * `output_data`, `execution_flows`, `tool_steps`, `execution_config`,
 * `director_review_md` or the log paths is rendered by any of those four
 * surfaces; the detail modal hydrates the fat record through `get_execution`
 * when a row is opened, and the management HTTP API still serves the whole
 * record from `get_all_global`.
 *
 * This is deliberately NOT a flatten of `ExecutionListItem`: that struct is
 * snake_case on the wire (legacy, baselined in the camelCase ratchet), and
 * flattening it under a camelCase container would ship one object with two
 * casings. It carries exactly the fields these surfaces draw — add one here
 * when a surface starts drawing it, not before.
 */
export type GlobalExecutionListItem = { id: string, personaId: string, status: string, 
/**
 * The model the run actually used; `None` when it was never recorded, in
 * which case the UI falls back to the persona's configured model.
 */
modelUsed: string | null, 
/**
 * Thinking budget token, drawn as a chip beside the model.
 */
thinkingLevel: string | null, inputTokens: number, outputTokens: number, costUsd: number, durationMs: number | null, startedAt: string | null, createdAt: string, personaName: string | null, personaIcon: string | null, personaColor: string | null, };
