// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `resolve_goal_progress` — the goal's stored progress alongside a
 * progress value DERIVED from its composed checklist (ad-hoc items + sub-goals
 * + linked team-assignment steps). The UI surfaces `suggested != current` as an
 * accept/edit nudge; a manual override always wins (we never silently write).
 */
export type GoalProgressSuggestion = { goal_id: string, current: number, suggested: number, done_count: number, total_count: number, reason: string, };
