// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a run needs the GPU. `Exclusive` takes the fleet's single GPU
 * token; `Shared` is informational only.
 */
export type GpuClass = "none" | "shared" | "exclusive";
