// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Return of `prepare` — the snapshot path + repo root so the frontend can
 * point the Fleet session's cwd and reference the grounding file.
 */
export type HarvestPrepared = { snapshot_path: string, root_path: string, };
