// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The request body of `POST /dev-tools/app-master/{project_id}/heartbeat`.
 */
export type HeadlessHeartbeatInput = { 
/**
 * `running` (a builder is in flight), `idle` (between wakes) or `ended`
 * (the Director stopped; releases the in-app tick at once).
 */
state: string, 
/**
 * The latest wake note. Trimmed; cut to [`NOTE_MAX_CHARS`].
 */
note?: string, 
/**
 * When the headless master next wakes, RFC 3339.
 */
nextWakeAt?: string, 
/**
 * The active run's short id, when one is in flight.
 */
runId?: string, };
