// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the app's read surfaces carry about a project's headless chair.
 */
export type HeadlessState = { 
/**
 * `running` | `idle` | `ended`.
 */
state: string, note: string, nextWakeAt: string | null, beatAt: string, 
/**
 * True while the beat suppresses the in-app tick (see [`is_fresh`]).
 */
fresh: boolean, };
