// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealingStrategyStat } from "./HealingStrategyStat";

/**
 * Windowed self-healing effectiveness ledger: how often auto-fixes actually
 * held vs. reverted, overall and per strategy.
 *
 * Derived entirely from the `healing_audit_log` terminal-outcome rows written
 * when a healing retry confirms or reverts a pending fix — so revert rates
 * (previously unknowable, since a reverted issue drops back to `open` and
 * loses its `auto_fixed` flag) become first-class.
 */
export type HealingEffectivenessReport = { 
/**
 * Trailing window in days the aggregate covers.
 */
window_days: number, attempted: number, confirmed: number, reverted: number, 
/**
 * Overall `confirmed / attempted`, in `0.0..=1.0`.
 */
success_rate: number, 
/**
 * Per-category breakdown, busiest first.
 */
by_category: Array<HealingStrategyStat>, };
