// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StageStatus } from "./StageStatus";

/**
 * One pipeline stage's verdict.
 */
export type HealthStage = { 
/**
 * Stable machine name. Never localised, never renamed — callers key on it.
 */
name: string, status: StageStatus, 
/**
 * One line of English, for the operator and for Athena's own prompt.
 */
detail: string, };
