// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tolerated defect. The read continued; this is what it skipped.
 */
export type HierarchyWarning = { 
/**
 * Repo-relative path of the offending file or folder.
 */
path: string, message: string, };
