// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HierarchyTechnique = { slug: string, subject: string, title: string, summary: string, 
/**
 * Repo-relative path, suitable for `dev_tools_hierarchy_doc`.
 */
file: string, status: string | null, 
/**
 * Anchor ids into `_laws.md`.
 */
laws: Array<string>, 
/**
 * Other subjects that reference this technique.
 */
sharedWith: Array<string>, };
