// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the graph came from, and — when it is empty — why.
 *
 * An empty graph with no explanation is indistinguishable from a broken
 * reader, so this struct is populated on every path including success.
 */
export type HierarchySource = { 
/**
 * Canonical repo root the reader used, when one could be resolved.
 */
root: string | null, 
/**
 * True when `docs/concepts/paths/` was found and read.
 */
present: boolean, 
/**
 * Human-readable reason the graph is empty. `None` when `present`.
 */
reason: string | null, };
