// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HierarchyCategory = { id: string, title: string, 
/**
 * Compass sequence. Unique across categories (checker-enforced).
 */
order: number, };
