// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recent persona-icon-generation spend, surfaced at the generate affordance so
 * the metered image-API cost isn't invisible.
 */
export type IconGenSpendSummary = { 
/**
 * Estimated USD spent generating persona icons in the window.
 */
totalCostUsd: number, 
/**
 * Number of generations recorded in the window.
 */
generationCount: number, 
/**
 * Window length in days (echoed for the UI copy).
 */
windowDays: number, };
