// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacklogSource } from "./BacklogSource";
import type { IdeaPlan } from "./IdeaPlan";

/**
 * The ONE input every producer builds to file a backlog item.
 *
 * Replaces three positional signatures. Absent-value convention, stated once
 * and applying to every field: a producer OMITS what it has no value for and
 * the door writes SQL NULL. Never `0`, never `""` — the three scales run 1-5,
 * so a `0` is a validation error and not a missing value.
 */
export type IdeaDraft = { projectId: string, 
/**
 * The producer. Written to `dev_ideas.origin`.
 */
source: BacklogSource, 
/**
 * The producer's own sub-key (an Idea-Scanner lens, a static tool name).
 * Written to `dev_ideas.scan_type`; defaults to `source.as_str()`.
 */
scanType: string | null, contextId: string | null, category: string | null, title: string, description: string | null, reasoning: string | null, evidence: string | null, effort: number | null, impact: number | null, risk: number | null, goalId: string | null, useCaseId: string | null, plan: IdeaPlan | null, 
/**
 * Attribution. The door STAMPS these from the caller's dispatch context
 * rather than trusting a producer's claim about itself; a producer that
 * genuinely knows (the Idea Scanner spawns its own CLI) may pass them.
 */
provider: string | null, model: string | null, dedupKey: string | null, 
/**
 * Only a producer with a standing auto-accept arrangement passes this.
 * Omitted means `pending`.
 */
status: string | null, };
