// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The states a backlog item may hold.
 *
 * Closed as of this contract. The column carries no CHECK constraint and
 * `decide_idea_cas` took a bare `&str`, so the vocabulary was open in the
 * database, in Rust and in TypeScript simultaneously — and the two states
 * this enum adds are the ones whose absence let 518 completed items sit in
 * `Accepted` forever.
 */
export type IdeaStatus = "pending" | "accepted" | "rejected" | "archived" | "delivered" | "expired";
