// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlayEnter } from "./OverlayEnter";

export type ImageOverlayStage = { id: string, outputStart: number, outputEnd: number, fadeIn: number, fadeOut: number, positionX: number, positionY: number, 
/**
 * Optional positional entrance — the overlay eases into `position_*` from
 * an offset. This is the "spring up, staggered" motion an explainer video
 * is built from. None = the overlay is static at `position_*`.
 */
enter: OverlayEnter | null, 
/**
 * Must reference a 'file' or 'proxy' source.
 */
sourceId: number, 
/**
 * 1.0 = source's natural size within the frame.
 */
scale: number, };
