// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportedMcpServer = { name: string, label: string, command: string, args: string[], env: Record<string, string>, source: string, };
