// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KbChunk = { id: string, kbId: string, documentId: string, chunkIndex: number, content: string, tokenCount: number, metadataJson: string | null, 
/**
 * 1-based page this chunk was read from; `None` for flat text.
 */
sourcePage: number | null, 
/**
 * 0.0..=1.0 — how faithfully this text represents its source page.
 */
extractionConfidence: number, };
