// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KbDocument = { id: string, kbId: string, sourceType: string, sourcePath: string | null, title: string, contentHash: string, byteSize: number, chunkCount: number, metadataJson: string | null, 
/**
 * Pages in the source (PDF); `None` for flat text.
 */
pageCount: number | null, 
/**
 * Pages with no readable text layer (scanned images). > 0 means part of
 * this document is invisible to search.
 */
emptyPages: number, status: string, errorMessage: string | null, indexedAt: string | null, createdAt: string, };
