// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One typed object extracted from a document.
 */
export type KbEntity = { id: string, runId: string, kbId: string, documentId: string | null, 
/**
 * Source document title, hydrated on read for display. Not a stored column.
 */
documentTitle: string | null, 
/**
 * 1-based page the object was found on; `None` for flat-text sources.
 */
sourcePage: number | null, entityType: string, 
/**
 * The model's short label for this instance, e.g. "F10 footing".
 */
entityKey: string, 
/**
 * Field -> value object matching the run's schema.
 */
attributes: JsonValue | null, extractionConfidence: number, createdAt: string, };
