// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress event for a running extraction pass.
 */
export type KbExtractionProgress = { runId: string, kbId: string, status: string, documentsTotal: number, documentsDone: number, entitiesFound: number, currentDocument: string | null, error: string | null, };
