// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KbSchemaField } from "./KbSchemaField";

/**
 * One entity type the schema will extract (e.g. "footing", "line_item").
 */
export type KbSchemaEntity = { entityType: string, description: string, fields: Array<KbSchemaField>, };
