// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KpiSimIngestSummary = { run_dir: string, measurements_recorded: number, proposals_created: number, findings_created: number,
/**
 * Per-row reasons for anything the validator refused — surfaced in the
 * UI so a lossy ingest is never silent.
 */
skipped: Array<string>, };
