// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed link back to the external KP hiring app job this persona was hired
 * for (agent-candidate bridge). Written once by the `kp_hire_request`
 * approval executor; read by the outbound KP reporter. Typed (not a loose
 * JSON key) because `DesignContextData` has no serde catch-all — unknown
 * keys are DROPPED on round-trip, exactly the bug class a typed field
 * prevents. A stale link (KP app gone, token rotated) never breaks
 * anything: consumers treat push failures as best-effort.
 */
export type KpLink = { 
/**
 * KP job id the hire request originated from.
 */
jobId: string, 
/**
 * Human-readable job title (display only).
 */
jobTitle: string, 
/**
 * Base URL of the KP app instance (e.g. `http://localhost:3001`).
 */
baseUrl: string, 
/**
 * Bearer-ish token for `POST {base_url}/api/agents/report/{token}`.
 */
reportToken: string, 
/**
 * `spec.connectors` from the hire request, verbatim — the tool surface kp
 * actually asked for (typically `["github"]` for an App master).
 *
 * Carried here rather than re-read from the approval payload because the
 * payload is consumed at approval time and the constraint is needed much
 * later, at build verification and at promote. It is the *request*, not a
 * derived allow-list: `personas_engine::kp_tool_surface` turns it into the
 * set of tools a kp hire's build may attach, and drops the rest before the
 * verification gate can count an invented tool as unverified.
 *
 * `#[serde(default)]` — rows written before 2026-08-24 deserialize to an
 * empty list, which constrains a kp hire to the baseline + transport
 * tools only. That is the honest reading: a link that never recorded a
 * request cannot vouch for a connector.
 */
requestedConnectors: Array<string>, 
/**
 * The hire's `appMaster.mandate.approvalGates` named commands (e.g.
 * `npm run test:unit`), so a command runner is part of the mandated
 * surface. False for every hire whose mandate names no gates — and for
 * every ordinary (non-App-master) kp hire.
 */
runsCommands: boolean, };
