// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LabArenaResult = { id: string, runId: string, 
/**
 * Version attribution for the consolidated ratings rollup. `None` on legacy
 * arena rows that measured the persona's current prompt without a version link.
 */
versionId: string | null, versionNumber: number | null, scenarioName: string, modelId: string, provider: string, status: string, outputPreview: string | null, toolAccuracyScore: number | null, outputQualityScore: number | null, protocolCompliance: number | null, inputTokens: number, outputTokens: number, costUsd: number, durationMs: number, rationale: string | null, suggestions: string | null, errorMessage: string | null, evalMethod: string | null, createdAt: string, };
