// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LabResultEvent {
  id: string;
  resultId: string;
  resultKind: string;
  eventIndex: number;
  /**
   * One of: "assistant_text" | "tool_use" | "tool_result" | "system_init" | "result"
   */
  eventType: string;
  toolName: string | null;
  toolArgsPreview: string | null;
  toolResultPreview: string | null;
  textPreview: string | null;
  tsMsRelative: number;
  createdAt: string;
}
