// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single recent export failure for the health-bar drill-down. Trimmed
 * to a 200-char message at record time so the IPC payload stays small.
 */
export type LangfuseExportFailure = { 
/**
 * Unix seconds.
 */
at: bigint, message: string, };
