// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact view of a single trace returned by `GET /api/public/traces`.
 * Keep this narrow: the trace-list panel only needs enough to render a row
 * and build a deep-link. Anything richer belongs in the Langfuse UI itself.
 */
export type LangfuseTraceSummary = { id: string, name: string | null, 
/**
 * ISO-8601 timestamp string as returned by Langfuse.
 */
timestamp: string | null, sessionId: string | null, userId: string | null, projectId: string | null, latencySeconds: number | null, totalCost: number | null, };
