// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a review resolution taught the fleet (Phase 2 — visible learning). The
 * chokepoint already writes a learned/decision/constraint memory; this is the
 * surfaced reference so the resolving UI can show "Learned: …" and link to it.
 */
export type LearnedMemoryRef = { id: string, 
/**
 * `"team"` (shared `team_memories`) or `"persona"` (per-persona memory).
 */
scope: string, 
/**
 * `"decision"` | `"constraint"` | `"learned"`.
 */
category: string, title: string, 
/**
 * The team this memory belongs to (when `scope == "team"`), for deep-link.
 */
teamId: string | null, personaId: string, };
