// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleDocRow } from "./LifecycleDocRow";
import type { LifecycleRelatedItem } from "./LifecycleRelatedItem";
import type { LifecycleRun } from "./LifecycleRun";

/**
 * Layer-2 data for one step: its run history (newest first, at most 30) and,
 * for `docs`, the per-doc rot rows.
 */
export type LifecycleStepDetail = { stepId: string, runs: Array<LifecycleRun>, docs: Array<LifecycleDocRow>, 
/**
 * Backlog items about this step: slow-gate items for its commands, the
 * Overseer's items for the step, doc-rot items (docs step). Newest first,
 * open before closed, at most 20.
 */
related: Array<LifecycleRelatedItem>, };
