// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleSourceKind } from "./LifecycleSourceKind";
import type { LifecycleStepOutcome } from "./LifecycleStepOutcome";

/**
 * A finished task, a base-branch commit or a PR merge, with per-step outcomes.
 */
export type LifecycleEvidenceItem = { sourceKind: LifecycleSourceKind, 
/**
 * Task id, commit sha or PR number.
 */
sourceRef: string, title: string, occurredAt: string, outcomes: Array<LifecycleStepOutcome>, };
