// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How finished work reaches the base branch.
 */
export type LifecycleLandMode = "local_merge" | "pull_request";
