// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleChangeKind } from "./LifecycleChangeKind";
import type { LifecycleStep } from "./LifecycleStep";

/**
 * One toggleable row of the proposal card.
 */
export type LifecycleChange = { kind: LifecycleChangeKind, 
/**
 * The step id, or `"preset"` for a preset change. This is the id the
 * confirm command's `acceptedStepIds` names.
 */
stepId: string, 
/**
 * The step as it is now (`null` for `added` and `preset`).
 */
before: LifecycleStep | null, 
/**
 * The step as proposed (`null` for `removed` and `preset`).
 */
after: LifecycleStep | null, };
