// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleGoalItem } from "./LifecycleGoalItem";

export type LifecycleGoalView = { goalId: string, measurableTotal: number, measurableGreen: number, instructed: number, openItems: number, 
/**
 * The Overseer's items under this goal, one per step it was ever filed
 * for: open (`pending`, `accepted`) first, then newest filed first.
 */
items: Array<LifecycleGoalItem>, };
