// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleDocRow } from "./LifecycleDocRow";
import type { LifecycleEvidenceItem } from "./LifecycleEvidenceItem";
import type { LifecycleRelatedItem } from "./LifecycleRelatedItem";
import type { LifecycleRun } from "./LifecycleRun";

/**
 * Layer-2 data for one step: its run history, for `docs` the per-doc rot
 * rows, the backlog items about it and its evidence history.
 */
export type LifecycleStepDetail = { stepId: string, 
/**
 * `gate` / `tests`: the newest 30 runs PER COMMAND of the step's kinds
 * (so a command run every Measure cannot crowd out one run rarely),
 * all commands merged newest first. Empty for every other step. A run's
 * output is not here: fetch it with `dev_tools_lifecycle_run_output`.
 */
runs: Array<LifecycleRun>, docs: Array<LifecycleDocRow>, 
/**
 * Backlog items about this step: slow-gate items for its commands, the
 * Overseer's items for the step, doc-rot items (docs step). Newest first,
 * open before closed, at most 20.
 */
related: Array<LifecycleRelatedItem>, 
/**
 * This step's evidence: the newest 200 changes (tasks, base-branch
 * commits, PR merges) that carry an outcome for the step, newest first.
 * Each item keeps every step's outcome, so a change can say what it did
 * on the other steps. (The snapshot keeps its own 20.)
 */
evidence: Array<LifecycleEvidenceItem>, };
