// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleGateKind } from "./LifecycleGateKind";

/**
 * A command Measure runs. `id` is a stable slug (dedup keys and history key on it).
 */
export type LifecycleGateCommand = { id: string, command: string, kind: LifecycleGateKind, 
/**
 * Overrides the kind's default budget.
 */
budgetMs: number | null, };
