// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleRelatedSource } from "./LifecycleRelatedSource";

/**
 * One backlog item about a step, as the step screen lists it.
 */
export type LifecycleRelatedItem = { 
/**
 * The `dev_ideas` id.
 */
id: string, title: string, 
/**
 * The idea status token (`pending`, `accepted`, `rejected`, `archived`,
 * `delivered`, `expired`).
 */
status: string, 
/**
 * The finding verification state, when the item carries one.
 */
verifyState: string | null, source: LifecycleRelatedSource, 
/**
 * The command a slow-gate item is about; null for other sources.
 */
commandId: string | null, createdAt: string, };
