// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a step runs before the task's work or after it.
 */
export type LifecyclePhase = "before" | "after";
