// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecyclePreset } from "./LifecyclePreset";
import type { LifecycleStep } from "./LifecycleStep";

/**
 * The lifecycle document stored per version (`dev_lifecycle_versions.doc_json`).
 */
export type LifecycleDoc = { preset: LifecyclePreset, steps: Array<LifecycleStep>, };
