// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleGateKind } from "./LifecycleGateKind";
import type { LifecycleRunOutcome } from "./LifecycleRunOutcome";

/**
 * One command a past Measure ran, in the order it was planned.
 */
export type LifecycleHistoryRun = { commandId: string, kind: LifecycleGateKind, outcome: LifecycleRunOutcome, durationMs: number, valuePct: number | null, };
