// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What git showed for one step of one task or commit.
 */
export type LifecycleOutcome = "done" | "skipped" | "unknown" | "failed";
