// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a step is enforced.
 */
export type LifecycleBindingKind = "app" | "claude_md" | "hook" | "ci" | "advisory";
