// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleHealth } from "./LifecycleHealth";
import type { LifecycleMetric } from "./LifecycleMetric";

/**
 * One command step as judged at one past Measure.
 */
export type LifecycleHistoryCell = { stepId: string, health: LifecycleHealth, reason: string | null, metrics: Array<LifecycleMetric>, };
