// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Evidence tally for one step over the snapshot's evidence window.
 */
export type LifecycleStepTally = { done: number, skipped: number, unknown: number, failed: number, };
