// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleGateCommand } from "./LifecycleGateCommand";
import type { LifecycleLandMode } from "./LifecycleLandMode";

/**
 * Per-step knobs. Every field is optional; a step reads only its own.
 * `prBase` / `automergeTarget` are branch selectors (`main` | `test`), the same
 * vocabulary as `standards_config.branching`.
 */
export type LifecycleStepParams = { lint: boolean | null, codeQuality: boolean | null, docsRequired: boolean | null, landMode: LifecycleLandMode | null, prBase: string | null, automergeEnabled: boolean | null, automergeTarget: string | null, 
/**
 * `gate` / `tests`: the commands Measure runs. `null` = auto-detect from
 * the repo's manifests (package.json scripts, Cargo.toml).
 */
commands: Array<LifecycleGateCommand> | null, 
/**
 * `tests`: coverage at or above this is green (default 70; amber down to 50).
 */
coverageGreenPct: number | null, 
/**
 * `docs`: share of verifiable docs that must be clean (default 90).
 */
docsCleanPct: number | null, 
/**
 * Evidence steps: done-rate at or above this is green (default 80).
 */
doneRatePct: number | null, };
