// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleBindingKind } from "./LifecycleBindingKind";
import type { LifecyclePhase } from "./LifecyclePhase";
import type { LifecycleStepParams } from "./LifecycleStepParams";

/**
 * One step of the practice. Built-in ids: `frame, recall, isolate, link, sync,
 * gate, tests, docs, commit, land, record` (label `null`, the UI labels them
 * from i18n by id). A custom step's id is `x-<slug>` and it must carry `label`.
 */
export type LifecycleStep = { id: string, phase: LifecyclePhase, label: string | null, 
/**
 * Agent-facing rule text, imperative English.
 */
rule: string, bindings: Array<LifecycleBindingKind>, params: LifecycleStepParams, };
