// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleOutcome } from "./LifecycleOutcome";

/**
 * One step's outcome for one evidence item.
 */
export type LifecycleStepOutcome = { stepId: string, outcome: LifecycleOutcome, detail: string | null, };
