// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where one planned command of a running Measure stands.
 */
export type LifecycleCommandState = "pending" | "running" | "done";
