// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveRoadmapLocaleItem } from "./LiveRoadmapLocaleItem";

export type LiveRoadmapLocale = { label: string | null, summary: string | null, items: { [key in string]?: LiveRoadmapLocaleItem }, };
