// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LlmPlanStep } from "./LlmPlanStep";

/**
 * Wire-format result for `plan_goal_llm`.
 */
export type LlmPlanResult = { steps: Array<LlmPlanStep>, };
