// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LlmSpendGroup = { key: string, calls: number, cost_usd: number, input_tokens: number, output_tokens: number, };
