// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of THIS MACHINE a run occupies. Charged against the fleet's
 * machine budget in units (see [`MachineLoad::units`]).
 */
export type MachineLoad = "light" | "moderate" | "heavy" | "exclusive";
