// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManifestSyncMetrics = { syncRounds: number, syncSuccesses: number, syncFailures: number, avgSyncDurationMs: number | null, totalEntriesReceived: number, };
