// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live liveness of the local management HTTP server (the "MCP server" the
 * Settings panel points MCP clients at). `live` reflects an actual `/health`
 * probe of the listener, NOT an optimistic intent flag — an explicit down
 * state when the socket isn't answering.
 */
export type McpServerLiveness = { 
/**
 * True iff `GET http://127.0.0.1:<port>/health` returned 2xx within the
 * probe timeout.
 */
live: boolean, 
/**
 * The port the management server binds (honors the PERSONAS_WEBHOOK_PORT
 * override, so the panel shows the real port).
 */
port: number, };
