// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryStrategyConfig } from "./MemoryStrategyConfig";

/**
 * One selectable memory strategy.
 */
export type MemoryStrategy = { id: string, name: string, tagline: string, icon: string, whatItRemembers: string, bestFor: string, config: MemoryStrategyConfig, 
/**
 * Entities the strategy needs before it's fully live
 * (`home_team` | `knowledge_base` | `obsidian_vault`) — rendered as
 * setup chips in the Foundry review step.
 */
requires: Array<string>, };
