// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Config intent for a memory strategy — which memory subsystems the
 * strategy stands for. v1 is guidance-only.
 */
export type MemoryStrategyConfig = { 
/**
 * `"on"` | `"off"` — per-capability memory generation default.
 */
memories: string, teamPool: boolean, knowledgeBase: boolean, obsidian: boolean, };
