// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaMessage } from "./PersonaMessage";

export type MessageThreadSummary = { threadId: string, parent: PersonaMessage, replyCount: number, latestReplyAt: string | null, };
