// This file was generated by [ts-rs]. Do not edit this file manually.

export interface MetricAnomaly {
  date: string;
  metric: string;
  value: number;
  baseline: number;
  deviation_pct: number;
  execution_id: string | null;
}
