// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A mock tool response within a scenario.
 */
export type MockToolResponse = { toolName: string, description: string | null, mockResponse: JsonValue, };
