// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoutingMatch } from "./RoutingMatch";
import type { RuleProvenance } from "./RuleProvenance";

/**
 * One routing rule: a selector + the model/effort it resolves to.
 */
export type ModelRoutingRule = { match: RoutingMatch, model: string, effort?: string, 
/**
 * Present iff this rule was written by an applied Self-Tuning proposal.
 */
provenance?: RuleProvenance, };
