// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaMonthlySpend } from "./PersonaMonthlySpend";

/**
 * Wrapper returned by get_all_monthly_spend so the frontend knows exactly
 * which period the spend figures cover.
 */
export type MonthlySpendResult = { 
/**
 * ISO-8601 UTC timestamp of the period start used in the query.
 */
periodStartUtc: string, items: Array<PersonaMonthlySpend>, };
