// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-format struct mirroring the n8n payload-size limits, exported to
 * TypeScript via ts-rs. The numeric values themselves are emitted to
 * `src/lib/n8nLimits.generated.ts` by `scripts/generate-n8n-limits.mjs`.
 */
export type N8nPayloadLimits = { maxWorkflowJsonBytes: bigint, maxTransformPayloadBytes: bigint, };
