// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionStatus } from "./SessionStatus";

export type N8nSessionSummary = { id: string, workflow_name: string, status: SessionStatus, step: string, error: string | null, created_at: string, updated_at: string, };
