// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Network access scope level for an imported bundle.
 * - `"none"` – no detected network access (green)
 * - `"restricted"` – known domains / endpoints only (amber)
 * - `"unrestricted"` – broad or unscoped network access (red)
 */
export type NetworkAccessScope = { level: string, domains: Array<string>, tool_integrations: Array<string>, api_endpoints: Array<string>, };
