// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkConfig = { port: number, auto_connect: boolean, max_peers: number, health_check_interval_secs: number, manifest_sync_interval_secs: number, stale_peer_timeout_secs: number, };
