// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkStatusInfo = { is_running: boolean, listening_port: number | null, discovered_peer_count: number, connected_peer_count: number, local_peer_id: string, };
