// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevMilestone } from "./DevMilestone";
import type { DevNote } from "./DevNote";

/**
 * What `notepad_promote_note` hands back: the note (now linked) and the
 * milestone it is the brief of; `created` says whether the milestone was
 * minted from the note or was the project's already-open one.
 */
export type NotePromotion = { note: DevNote, milestone: DevMilestone, created: boolean, };
