// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of a notepad note. Server-validated transitions live in
 * `notepad_set_status`; body/project edits are legal only while `draft`.
 */
export type NoteStatus = "draft" | "published" | "in_progress" | "completed" | "archived";
