// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The five states a note can be in.
 *
 * This is a **lifecycle**, not a label set: the pad, the dispatcher and the
 * `/note-task` run's `result.json` all key off it, and the legal moves between
 * states are the contract that keeps those three honest. The transition table
 * lives in [`NoteStatus::can_transition_to`] and is enforced server-side by
 * `notepad_set_status` — never in the UI, which is free to grey out a button
 * but is never the thing that makes an illegal move impossible.
 */
export type NoteStatus = "draft" | "published" | "in_progress" | "completed" | "archived";
