// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The unread state of one note's thread — only notes with at least one
 * unread entry are returned by `notepad_unread_counts`.
 */
export type NoteUnread = { noteId: string, unread: number, 
/**
 * The newest unread entry's id (the bubble candidate).
 */
latestId: string | null, };
