// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The eight states a note can be in.
 *
 * This is a **lifecycle**, not a label set: the pad, the dispatcher and the
 * `/note-task` run's `result.json` all key off it, and the legal moves between
 * states are the contract that keeps those three honest. The transition table
 * lives in [`NoteStatus::can_transition_to`] and is enforced server-side by
 * `notepad_set_status` — never in the UI, which is free to grey out a button
 * but is never the thing that makes an illegal move impossible.
 *
 * The first five are the PAD's lane (a scratch requirement handed to a run and
 * reported back on). The last three are the SHIP lane: once a note is the
 * living brief of a milestone it tracks the milestone's own life, and the two
 * lanes meet at `scoped` — the state a note enters the moment it acquires a
 * `milestone_id`.
 */
export type NoteStatus = "draft" | "published" | "in_progress" | "completed" | "archived" | "scoped" | "cut" | "shipped";
