// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ObsidianMirrorConfig = { 
/**
 * Athena may consult the vault as an on-demand tool (read) + selective writes.
 */
athena: boolean, 
/**
 * Mirror the execution-knowledge graph into the vault.
 */
executionKnowledge: boolean, 
/**
 * Route Research Lab experiment notes through the Brain vault.
 */
researchLab: boolean, 
/**
 * User dismissed the one-time "we noticed Obsidian" offer.
 */
offerDismissed: boolean, };
