// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * An authentication scheme extracted from the spec.
 */
export type OpenApiAuthScheme = { name: string, schemeType: string, location: string | null, paramName: string | null, scheme: string | null, description: string | null, flows: JsonValue | null, };
