// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenApiModelProperty } from "./OpenApiModelProperty";

/**
 * A data model (schema) extracted from the spec.
 */
export type OpenApiModel = { name: string, modelType: string, description: string | null, properties: Array<OpenApiModelProperty>, };
