// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Easing } from "./Easing";

/**
 * A positional entrance animation. The overlay starts at
 * `position + (offset_x, offset_y)` and eases to `position` over `duration`
 * seconds from the stage's `output_start`.
 *
 * Deliberately position + opacity only, NOT scale. ffmpeg's `overlay` filter
 * takes time-varying `x`/`y` expressions, so position animates cleanly in a
 * single filtergraph pass with no per-frame rasterizer. Scale is not
 * time-varying in the `scale` filter, so a scale-spring would need a second
 * render path — deferred. Opacity uses the existing fade envelope.
 */
export type OverlayEnter = { 
/**
 * Seconds from `output_start` over which the entrance plays. Clamped to
 * the stage duration by the compiler.
 */
duration: number, 
/**
 * Starting offset in frame-relative units (fraction of width / height),
 * added to `position_*` at t=output_start and eased to 0 by
 * output_start + duration. Positive `offset_y` = rises up into place.
 */
offsetX: number, offsetY: number, easing: Easing, };
