// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A peer registered as one of the user's own devices, grouped under a shared
 * `device_group_id`. This is the device-ownership primitive from ADR
 * 2026-05-24-cross-device-persona-continuity: the workspace-sync loop exchanges
 * snapshots only with peers in this registry, and a pairing flow (these
 * commands, or the fleet `/friend` QR-pairing UI) is its writer.
 */
export type OwnedDevice = { 
/**
 * The peer's stable identity (base58 peer_id), matching `discovered_peers`.
 */
peerId: string, 
/**
 * Shared anchor marking this peer as belonging to the same user as us.
 */
deviceGroupId: string, displayName: string, addedAt: string, lastSyncedAt: string | null, };
