// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionStatus } from "./ConditionStatus";

export interface PartialMatchResult {
  triggerId: string;
  triggerName: string;
  personaId: string;
  operator: string;
  windowSeconds: number;
  fired: boolean;
  conditionsTotal: number;
  conditionsMet: number;
  conditionDetails: Array<ConditionStatus>;
  evaluatedAt: string;
  suppressed: boolean;
}
