// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every "a human must decide this" queue's pending count, in one round-trip.
 *
 * The title-bar badge used to be `pending reviews + build questions` while the
 * deck it opens deals SEVEN kinds, so a reviewer with 26 pending ideas and
 * nothing else saw `0`. A number that is confidently wrong is worse than an
 * absent one, and six per-source round-trips on a poll is not a trade a badge
 * should make — hence one connection, six counts.
 *
 * Build questions are deliberately absent: they live in the frontend's
 * `buildSessions` state (a halted CLI awaiting input), not in a table, so the
 * caller adds them. There is nothing here to query for them.
 *
 * `u32`, not `i64`, and that is load-bearing: ts-rs maps `i64` to TypeScript
 * `bigint`, which the badge cannot add to the frontend-derived question count
 * without a conversion nothing else in the tray does. `TriageCounts` above made
 * the same choice for the same reason. A count is non-negative and will not
 * reach four billion.
 */
export type PendingCounts = { goalAcceptance: number, manualReviews: number, ideas: number, practices: number, policyProposals: number, promotionProposals: number, 
/**
 * The six above. The caller adds build questions on top.
 */
total: number, };
