// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One enriched row for the Goal Acceptance view — a goal in
 * `awaiting_acceptance` joined to its project, the project's owning team, and
 * (if linked) the KPI it serves. Flat so the frontend can group it by project
 * → KPI without N round-trips; `current/target/baseline/direction` let the UI
 * render the KPI gauge + a simple "met vs not" tint.
 */
export type PendingAcceptanceGoal = { goal_id: string, title: string, 
/**
 * First paragraph of the goal description (provenance footer stripped).
 */
summary: string | null, project_id: string, project_name: string, team_id: string | null, team_name: string | null, kpi_id: string | null, kpi_name: string | null, kpi_unit: string | null, kpi_current: number | null, kpi_target: number | null, kpi_baseline: number | null, 
/**
 * 'up' | 'down' — which way is better.
 */
kpi_direction: string | null, completed_at: string | null, };
