// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildPhase } from "./BuildPhase";
import type { JsonValue } from "./serde_json/JsonValue";

export type PersistedBuildSession = { id: string, personaId: string, phase: BuildPhase, resolvedCells: JsonValue, pendingQuestion: JsonValue | null, agentIr: JsonValue | null, adoptionAnswers: JsonValue | null, intent: string, errorMessage: string | null, 
/**
 * Build mode — `"interactive"` or `"one_shot"`. NULL legacy rows are
 * surfaced as `Some("interactive")` so the frontend can switch on a
 * string without dealing with three-state logic.
 */
mode: string | null, 
/**
 * Companion chat session that originated this build, when applicable.
 */
companionSessionId: string | null, 
/**
 * Parsed JSON of build_sessions.disabled_dims_json — front-end
 * reads this on hydration to restore the SigilEditModal toggles
 * the user set in a prior visit to this session.
 */
disabledDims: JsonValue | null, createdAt: string, updatedAt: string, };
