// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaMonthlySpend = { id: string, spend: number, max_budget_usd: number | null, name: string, };
