// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All valid statuses for a `PersonaEvent`.
 *
 * Lifecycle: Pending → Processing → Delivered/Completed/Skipped/Failed
 *            Failed → DeadLetter (after max retries) or back to Pending (retry)
 *            DeadLetter → Pending (manual retry) or Discarded (manual discard)
 */
export type PersonaEventStatus = "pending" | "processing" | "delivered" | "completed" | "skipped" | "failed" | "dead_letter" | "discarded";
