// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaTestRun = { id: string, persona_id: string, status: string, models_tested: string, scenarios_count: number, summary: string | null, error: string | null, created_at: string, completed_at: string | null, };
