// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-kind row counts for a persona's channel (the facet rail). Each count
 * uses the SAME predicate as the lens it describes — the rail's invariant is
 * that a facet's count equals what selecting it returns.
 */
export type PersonaChannelKindCounts = { chat: number, report: number, review: number, event: number, memory: number, };
