// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `get_persona_manifest` payload: the on-disk manifest verbatim plus the
 * section map the editor needs to know which headings are law (operator)
 * and which are self-model (agent, diff-gated).
 */
export type PersonaManifestView = { content: string, 
/**
 * `# ` headings only the operator may write (`update_persona_manifest_law`).
 */
lawSections: Array<string>, 
/**
 * `# ` headings only anchored `self_model_diff` proposals may change.
 */
selfSections: Array<string>, 
/**
 * The frontmatter `updated:` stamp, when the file carries one.
 */
updatedAt?: string, 
/**
 * `self_model_diff` proposals still `pending_review` for this persona.
 */
pendingProposals: number, };
