// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaTeam = { id: string, project_id: string | null, parent_team_id: string | null, name: string, description: string | null, canvas_data: string | null, team_config: string | null, icon: string | null, color: string, enabled: boolean, 
/**
 * Workspace facet (Groups→Teams consolidation). Shared instructions
 * appended to every member persona's prompt; defaults applied to new
 * personas. Ported from PersonaGroup.
 */
shared_instructions: string | null, default_model_profile: string | null, default_max_budget_usd: number | null, default_max_turns: number | null, created_at: string, updated_at: string, };
