// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-persona judge dimensions (`scorecard.judge.personas[].dims`).
 */
export type PersonaDims = { correctness: number | null, actionability: number | null, specificity: number | null, roleFidelity: number | null, };
