// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runs per hour for one persona over a trailing window (the Monitor Board's
 * 24h sparkline). `buckets` is oldest first, one entry per UTC hour, ending
 * with the current hour; its length equals the requested window. A persona
 * with no runs in the window is omitted from the result, and consumers read a
 * missing persona as all-zero buckets.
 */
export type PersonaHourlyRuns = { personaId: string, buckets: Array<number>, };
