// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaMemory = { id: string, persona_id: string, title: string, content: string, category: string, source_execution_id: string | null, 
/**
 * Importance score on a 1–5 scale:
 * - 1: Low — minor or ephemeral detail
 * - 2: Below average — limited ongoing relevance
 * - 3: Normal (default) — standard operational knowledge
 * - 4: High — frequently useful context
 * - 5: Critical — essential knowledge for agent operation
 *
 * See MEMORY CONTRACT (4): bounds enforced at the DB layer via trigger.
 */
importance: number, tags: Array<string> | null, 
/**
 * Memory tier: "core" (always injected), "active" (selected by scoring),
 * "archive" (never injected, searchable only). See MEMORY CONTRACT (1)
 * for promotion authority — `core` is user-initiated only.
 */
tier: string, 
/**
 * How many times this memory has been injected into a prompt.
 * MEMORY CONTRACT (3): only `increment_access_batch` writes this column.
 */
access_count: number, 
/**
 * Last time this memory was injected into a prompt (ISO 8601).
 * MEMORY CONTRACT (3): paired with `access_count` and only written by
 * `increment_access_batch`.
 */
last_accessed_at: string | null, created_at: string, updated_at: string, 
/**
 * Capability (use case) attribution. Memories with `use_case_id = Some(_)`
 * are scoped to that capability for injection (active/working tier).
 * `None` means persona-wide; injected for any execution. Core-tier memories
 * are always persona-wide regardless of this column. Phase C5.
 *
 * MEMORY CONTRACT (2): no FK constraint by design. A use_case deletion
 * leaves orphan attributions in place; the row is functionally archived
 * for injection until re-attributed.
 */
use_case_id: string | null, 
/**
 * Workspace-scoped injection anchor. Memories with `home_team_id =
 * Some(T)` are shared with every persona whose `home_team_id = T` — when
 * such a persona runs, the injection path fetches its own memories AND
 * every memory attributed to T, regardless of author. `None` means
 * persona-private (the default). This replaced the retired `group_id`
 * scope in the Groups→Teams consolidation (Phase 5).
 *
 * MEMORY CONTRACT (5): no FK by design — mirrors (2) for use_case_id.
 * Populated by the groups_to_teams data migration; no runtime writer.
 */
home_team_id: string | null, };
