// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaTeamConnection = { id: string, team_id: string, source_member_id: string, target_member_id: string, connection_type: string, condition: string | null, label: string | null, created_at: string, };
