// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaVersion = {
  id: string;
  personaId: string;
  versionNumber: number;
  name: string;
  description: string | null;
  systemPrompt: string;
  structuredPrompt: string | null;
  modelProfile: string | null;
  maxBudgetUsd: number | null;
  maxTurns: number | null;
  timeoutMs: number;
  designContext: string | null;
  changeSummary: string | null;
  tag: string;
  parentVersionId: string | null;
  createdAt: string;
};
