// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single field-level entry in a persona's change history.
 *
 * One row is written per changed field per `update_persona` call. The editor
 * Settings tab surfaces these newest-first so a user can answer "who changed
 * my agent's model / budget / prompt, and when".
 *
 * Secret-bearing fields (`model_profile`, `notification_channels`) never store
 * their real values — `before_value` / `after_value` are redacted to
 * `"(changed)"`. All other values are truncated to a sane display length.
 */
export type PersonaChangeEntry = { id: string, personaId: string, 
/**
 * Persisted column name that changed, e.g. `"name"`, `"system_prompt"`,
 * `"max_budget_usd"`, `"model_profile"`. Rendered as a friendly label in
 * the UI via the i18n `status_tokens`/local map.
 */
field: string, 
/**
 * Prior value (truncated / redacted). `None` when the field had no value.
 */
beforeValue: string | null, 
/**
 * New value (truncated / redacted). `None` when the field was cleared.
 */
afterValue: string | null, 
/**
 * Origin of the edit: `"editor" | "header" | "fanout" | "other"`.
 */
source: string | null, createdAt: string, };
