// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaExecution = { id: string, persona_id: string, trigger_id: string | null, use_case_id: string | null, status: string, input_data: string | null, output_data: string | null, claude_session_id: string | null, log_file_path: string | null, execution_flows: string | null, model_used: string | null, input_tokens: number, output_tokens: number, cost_usd: number, error_message: string | null, duration_ms: number | null, tool_steps: string | null,
/**
 * If this execution is a healing retry, links to the original execution.
 */
retry_of_execution_id: string | null, 
/**
 * Number of retries attempted (0 = original execution).
 */
retry_count: number, started_at: string | null, completed_at: string | null, created_at: string, };
