// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user credential. Field-level rows in `credential_fields` are the
 * authoritative source of truth for secrets — `encrypted_data` and `iv`
 * on this row are LEGACY-ONLY blobs left over from before the per-field
 * migration.
 *
 * **Invariant (post-migration):** for every credential that has at least
 * one `credential_fields` row, `encrypted_data == ''` AND `iv == ''`.
 * Readers must NOT consult `encrypted_data` when field rows exist; doing
 * so reintroduces the dual-source-of-truth bug the migration was meant
 * to eliminate. The invariant is enforced two ways:
 *
 *  1. The `clear_legacy_credential_blobs` migration step empties the
 *     blob columns on every row that has been split into fields.
 *  2. `assert_credential_blob_invariant` runs at startup and emits a
 *     `tracing::error!` for any row that violates the rule, so a future
 *     regression that re-populates `encrypted_data` is loud.
 *
 * New rows written by `create_credential` always set both blob columns
 * to the empty string. The fields-table is the only place secrets live.
 */
export type PersonaCredential = { id: string, name: string, serviceType: string, metadata: string | null, lastUsedAt: string | null, 
/**
 * JSON object of user-picked sub-resources (repos, projects, folders, …).
 * Shape: `{ "<resource_id>": [{ "id", "label", "meta"? }, ...] }`.
 * NULL = broad scope; empty object = picker was opened and skipped.
 * Identifiers are not secrets — stored plaintext. Auth fields that grant
 * access to these resources live in credential_fields (encrypted).
 */
scopedResources: string | null, createdAt: string, updatedAt: string, };
