// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaGroup = { id: string, name: string, color: string, sortOrder: number, collapsed: boolean, description: string | null, defaultModelProfile: string | null, defaultMaxBudgetUsd: number | null, defaultMaxTurns: number | null, sharedInstructions: string | null, createdAt: string, updatedAt: string, };
