// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabRunStatus } from "./LabRunStatus";

export type PersonaTestRun = { id: string, persona_id: string, status: LabRunStatus, models_tested: Array<string>, scenarios_count: number, summary: string | null, error: string | null, created_at: string, completed_at: string | null, };
