// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaGatewayExposure } from "./PersonaGatewayExposure";
import type { PersonaTrustLevel } from "./PersonaTrustLevel";
import type { PersonaTrustOrigin } from "./PersonaTrustOrigin";

export type Persona = { id: string, project_id: string, name: string, description: string | null, system_prompt: string, structured_prompt: string | null, icon: string | null, color: string | null, enabled: boolean, sensitive: boolean, headless: boolean, max_concurrent: number, timeout_ms: number, notification_channels: string | null, last_design_result: string | null, model_profile: string | null, max_budget_usd: number | null, max_turns: number | null, design_context: string | null, group_id: string | null, source_review_id: string | null, trust_level: PersonaTrustLevel, trust_origin: PersonaTrustOrigin, trust_verified_at: string | null, trust_score: number, parameters: string | null, gateway_exposure: PersonaGatewayExposure, created_at: string, updated_at: string, };

export type PersonaParameter = {
  key: string;
  label: string;
  type: ParamType;
  default_value: unknown;
  value: unknown;
  description?: string;
  options?: string[];
  min?: number;
  max?: number;
  unit?: string;
};

export type ParamType = "number" | "string" | "boolean" | "select";
