// This file was generated by [ts-rs]. Do not edit this file manually.

export interface PersonaTestSuite {
  id: string;
  personaId: string;
  name: string;
  description: string | null;
  scenarios: string;
  scenarioCount: number;
  sourceRunId: string | null;
  createdAt: string;
  updatedAt: string;
}
