// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaToolDefinition = { id: string, name: string, category: string, description: string, script_path: string, input_schema: string | null, output_schema: string | null, requires_credential_type: string | null, is_builtin: boolean, created_at: string, updated_at: string, };
