// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeAnalytics } from "./NodeAnalytics";
import type { TopologySuggestion } from "./TopologySuggestion";

export interface PipelineAnalytics {
  team_id: string;
  total_runs: number;
  completed_runs: number;
  failed_runs: number;
  success_rate: number;
  avg_duration_secs: number;
  node_analytics: Array<NodeAnalytics>;
  suggestions: Array<TopologySuggestion>;
}
