// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse playback state. The hidden player window emits these via `radio:state`
 * events so the footer can render the right control affordances.
 */
export type PlayStatus = "stopped" | "playing" | "paused" | "buffering";
