// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyWarningSeverity } from "./PolicyWarningSeverity";

/**
 * A structured policy validation warning with severity.
 */
export type PolicyWarning = { 
/**
 * Severity of this warning.
 */
severity: PolicyWarningSeverity, 
/**
 * Human-readable message describing the issue.
 */
message: string, };
