// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyWarningSeverity } from "./PolicyWarningSeverity";

export type PolicyWarning = { severity: PolicyWarningSeverity, message: string };
