// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `scorecard.judge.portfolio_balance` — work-type diversity assessment.
 */
export type PortfolioBalance = { labelsHistogram: { [key in string]?: number }, score: number | null, note: string | null, };
