// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportConflict } from "./ImportConflict";

export type PortabilityImportResult = { personasCreated: number, teamsCreated: number, toolsCreated: number, credentialsCreated: number, teamMemoriesCreated: number, kpisCreated: number, projectsImported: number, projectsSkipped: number, knowledgeImported: number, knowledgeSkippedDuplicates: number, skillsWritten: number, skillsDeferred: number, twinsImported: number, twinsSkipped: number, twinKbChunksImported: number, 
/**
 * Memories that landed: `companion_node` rows plus design decisions.
 * Items that matched something already in the brain are NOT counted —
 * they were skipped, not merged.
 */
athenaMemoryImported: number, 
/**
 * True when an `identity.md` already existed and was replaced (a
 * timestamped backup was written next to it first). False when the bundle
 * carried no identity, or when there was nothing to replace.
 */
athenaIdentityReplaced: boolean, 
/**
 * How many imported nodes were handed to the background re-embed. A bundle
 * carries text and never vectors, so these have no semantic index until
 * `companion_reembed_missing` runs.
 */
reembedQueued: number, 
/**
 * Non-empty when conflicts were detected on pass 1 — the frontend shows a
 * resolution UI and re-invokes with `resolutions_json`, whose keys
 * are `"<kind>:<bundle_id>"` (see [`ImportConflict`]).
 */
importConflicts: Array<ImportConflict>, 
/**
 * Path of the selected bundle file — returned alongside conflicts so the
 * frontend can pass it back for the resolution pass (mirrors
 * `CredentialImportResult::file_path`).
 */
bundleFilePath: string | null, warnings: Array<string>, idMapping: { [key in string]?: string }, };
