// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortfolioProjectSummary } from "./PortfolioProjectSummary";

export type PortfolioSummary = { projects: Array<PortfolioProjectSummary>, totalGoals: number, totalOpen: number, totalInProgress: number, totalBlocked: number, totalDone: number, totalAtRisk: number, avgProgress: number, };
