// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-project health rollup for the Portfolio surface. Counts use the canonical
 * goal-status buckets (see `normalize_goal_status`); `at_risk` = ongoing goals
 * that are overdue or stalled. Computed in one pass over all goals — no N+1.
 */
export type PortfolioProjectSummary = { projectId: string, projectName: string, teamId: string | null, total: number, open: number, inProgress: number, blocked: number, done: number, 
/**
 * Ongoing (not done) goals that are overdue or stalled.
 */
atRisk: number, 
/**
 * Ongoing goals whose target_date is in the past.
 */
overdue: number, 
/**
 * Mean progress (0-100) across the project's goals (0 when none).
 */
avgProgress: number, };
