// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresetMemberAdoptionSchema } from "./PresetMemberAdoptionSchema";

/**
 * Top-level response of `get_preset_adoption_schema`. The per-preset
 * metadata is duplicated here so the UI can render the questionnaire
 * modal title + the "X of Y members have configurable inputs" summary
 * without a separate `get_team_preset` round-trip.
 */
export type PresetAdoptionSchema = { preset_id: string, 
/**
 * Translated preset name (or canonical English).
 */
preset_name: string, 
/**
 * `members.length` total; `members.iter().filter(non-empty
 * questions).count()` configurable.
 */
member_count: number, configurable_member_count: number, 
/**
 * Sum of `questions.len()` across all members.
 */
total_question_count: number, members: Array<PresetMemberAdoptionSchema>, };
