// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One day of the project pulse, trimmed to what the frontend brief compiler
 * needs. Read-only projection of `engine_project_pulse` (user db).
 */
export type ProjectPulseSnapshot = { day: string, narrativeMd: string, tensions: Array<string>, directions: Array<string>, };
