// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-project outcome of a projection run.
 */
export type ProjectionResult = { project_id: string, project_name: string, 
/**
 * Practices written into this repo's memory file.
 */
practices: number, 
/**
 * True when CLAUDE.md gained the import line on this run (first time).
 */
linked: boolean, 
/**
 * Populated when this project was skipped; the rest still projected.
 */
skipped: string | null, };
