// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The skeleton to write beside the README and `.gitignore`.
 */
export type ProjectTemplate = "empty" | "rust-service" | "node-service" | "python-service";
