// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-project outcome of a projection run.
 */
export type ProjectionResult = { project_id: string, project_name: string, 
/**
 * Practices written into this repo's bundle.
 */
practices: number, 
/**
 * Active playbooks projected as briefs.
 */
playbooks: number, 
/**
 * True when CLAUDE.md gained (or migrated) the import line on this run.
 */
linked: boolean, 
/**
 * Populated when this project was skipped; the rest still projected.
 */
skipped: string | null, };
