// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Get aggregate provider usage stats.
 */
export type ProviderUsageStats = { engine_kind: string, execution_count: bigint, total_cost_usd: number, avg_duration_ms: number, failover_count: bigint, };
