// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderAuditEntry = { id: string, execution_id: string, persona_id: string, persona_name: string, engine_kind: string, model_used: string | null, was_failover: boolean, routing_rule_name: string | null, compliance_rule_name: string | null, cost_usd: number | null, duration_ms: number | null, status: string, created_at: string, };
