// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QualityGateRule } from "./QualityGateRule";

/**
 * Top-level quality-gate configuration for both memory and review filters.
 */
export type QualityGateConfig = { 
/**
 * Rules applied to AgentMemory submissions.
 */
memoryRules: Array<QualityGateRule>, 
/**
 * Category values that cause AgentMemory rejection (lowercase match).
 */
memoryRejectCategories: Array<string>, 
/**
 * Rules applied to ManualReview submissions.
 */
reviewRules: Array<QualityGateRule>, };
