// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayStatus } from "./PlayStatus";
import type { StationCursor } from "./StationCursor";

export type RadioState = { currentStationId: string | null, status: PlayStatus, 
/**
 * Linear volume in [0.0, 1.0]. The IFrame Player API uses 0–100; the
 * hidden window converts at the boundary.
 */
volume: number, 
/**
 * Per-station cursors. Keyed by station id.
 */
stationCursors: { [key in string]?: StationCursor }, };
