// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The pointer a minted charter keeps back to the recipe it came from, so a
 * lesson learned in the field can be proposed back into the registry artifact.
 */
export type RecipeRef = { slug: string, version: string, };
