// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One step of the COARSE shape of the work — for a reader and a diagram, not
 * for a machine. Deliberately NOT the `use_case_flow` graph this replaced:
 * linear, branch-free, no edges, no conditions. If it needs a branch it is a
 * runbook and it does not belong on a recipe.
 */
export type RecipeActivity = { id: string, 
/**
 * A phrase, not an instruction.
 */
label: string, 
/**
 * `observe` | `decide` | `act` | `deliver`.
 */
kind: string, };
