// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One named ROLE a connector plays in the work.
 *
 * A flat type list cannot say "two connectors of this type, in different
 * roles": a code-review recipe needs a local checkout AND a hosted review
 * surface, both `source_control`. Roles say it. When a recipe declares none,
 * every declared type is one role whose name IS the type — which is why the
 * existing `credential_bindings` seam (keyed by type) keeps working unchanged
 * in the common case.
 */
export type RecipeConnectorRole = { 
/**
 * Unique within the recipe; the key adoption binds against.
 */
role: string, 
/**
 * A connector catalog category, same vocabulary as `connector_types`.
 */
type: string, 
/**
 * What this connector is FOR, in one phrase.
 */
note: string, };
