// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discrete user actions on the suggestion chip. Strings on the wire so the
 * table check-constraint can lock the value space without a separate enum
 * table — see the `recipe_suggestion_events.event_type` CHECK in
 * `db::migrations::incremental`.
 */
export type RecipeSuggestionEventType = "impression" | "accept" | "dismiss";
