// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkippedParameterField } from "./SkippedParameterField";

/**
 * How completely a recipe's declared settings survive adoption.
 *
 * `declared == derived` means every promised knob exists. Any `skipped` entry
 * is a setting the recipe advertises that the persona will not expose.
 */
export type RecipeParameterCoverage = { recipeId: string, 
/**
 * Total named `input_schema` fields, deduped by key.
 */
declared: number, 
/**
 * How many of those become editable persona parameters.
 */
derived: number, 
/**
 * The dropped ones, in declaration order.
 */
skipped: Array<SkippedParameterField>, };
