// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecipeExecutionResult = { recipe_id: string, recipe_name: string, rendered_prompt: string, llm_output: string | null, input_data: Record<string, unknown>, executed_at: string, };
