// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated stats over the most recent `sample_size` events. `accept_rate`
 * is computed across decisive events only (accepts + dismisses); silent
 * impressions are excluded from the denominator because most users don't
 * explicitly act on a chip they ignore.
 *
 * `mode_2_eligible` is the gate Phase 5 reads to decide whether the
 * "skip build" shortcut is available. The thresholds (minimum sample,
 * minimum accept rate) live in `commands::recipes::recipe_suggestion_log`
 * so they can be tuned without touching this binding.
 */
export type RecipeSuggestionStats = { impressions: bigint, accepts: bigint, dismisses: bigint, 
/**
 * `accepts / (accepts + dismisses)` over the windowed sample. NaN-free:
 * returns 0.0 when there are no decisive events.
 */
accept_rate: number, 
/**
 * Total decisive events (accepts + dismisses) in the windowed sample.
 * Acts as the n in any "is the rate stable yet" judgement.
 */
decisive_count: bigint, sample_size: bigint, mode_2_eligible: boolean, };
