// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one reconcile pass did. Every number is reported, including zeros --
 * "it ran and found nothing" and "it never ran" are different facts.
 */
export type ReconcileReport = { 
/**
 * Episode markdown files visited.
 */
scanned: number, 
/**
 * Files that had no `companion_node` row and now have one.
 */
indexed: number, 
/**
 * Of [`Self::indexed`], how many were machine correlator records.
 */
indexedMachine: number, 
/**
 * Files skipped because their frontmatter could not be read (no `id`, no
 * `created`, or no frontmatter block at all). Counted, never swallowed.
 */
malformed: number, 
/**
 * True when [`RECONCILE_MAX_PER_RUN`] stopped the pass with work left.
 */
truncated: boolean, };
