// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A registry project slug no managed project matched (plan D3: rendered, not
 * guessed away).
 */
export type RegistryOnlyProject = { slug: string, domains: Array<string>, };
