// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoverageSource } from "./CoverageSource";
import type { CoverageTile } from "./CoverageTile";
import type { LaneDate } from "./LaneDate";
import type { RegistryOnlyProject } from "./RegistryOnlyProject";

export type RegistryCoverage = { 
/**
 * `name:` from `registry.yaml`.
 */
registryName: string | null, headSha: string | null, dirty: boolean, 
/**
 * `generatedAt` from `catalog.json`.
 */
generatedAt: string | null, laneDates: Array<LaneDate>, tiles: Array<CoverageTile>, registryOnly: Array<RegistryOnlyProject>, warnings: Array<string>, source: CoverageSource, };
