// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Remediation = "healthy" | "backoff_retry" | "preemptive_rotation" | "rotate_then_alert" | "disable";
