// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One chunk of a remote session's terminal output, as the
 * `network:remote-session-output` event carries it. A lossy tail: `seq` counts
 * chunks per job so the viewer can tell it skipped some, and nothing replays a
 * dropped chunk.
 */
export type RemoteSessionOutputChunk = { jobId: string, seq: number, chunkB64: string, };
