// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A steering verb the originator may send for a running remote session. A
 * closed grammar: anything else is unrepresentable on the wire.
 */
export type RemoteSessionCommand = "send_input" | "kill" | "wake";
