// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The originator's view of a remote session's lifecycle: every
 * `FleetSessionState` token plus `unknown`.
 *
 * `Unknown` is what the originator shows when it cannot see the session: the
 * link is down, or no mirror or health frame arrived for 45 s (three 15 s
 * health ticks). A quiet remote session is never shown as running.
 */
export type RemoteSessionState = "queued" | "spawning" | "running" | "awaiting_input" | "idle" | "stale" | "finished" | "hibernated" | "exited" | "unknown";
