// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts for UI feedback after a rename. Every field is the number of rows
 * whose stored event_type value was actually changed from `old` to `new`.
 */
export type RenameEventTypeResult = { eventsUpdated: number, subscriptionsUpdated: number, triggerPublishersUpdated: number, triggerListenersUpdated: number, handlerKeysUpdated: number, personaHandlersUpdated: number, };
