// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaReport } from "./PersonaReport";

/**
 * Summary of a message thread: the parent message plus reply count and latest reply timestamp.
 */
export type ReportThreadSummary = { threadId: string, parent: PersonaReport, replyCount: bigint, latestReplyAt: string | null, };
