// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Requirement =
  | { kind: "credential"; serviceType: string; neededBy: string }
  | { kind: "connector"; connectorName: string; neededBy: string }
  | { kind: "persona"; personaId: string; neededBy: string }
  | { kind: "automation"; automationId: string; neededBy: string };
