// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResearchProject = { id: string, name: string, description: string | null, domain: string | null, status: string, thesis: string | null, scopeConstraints: string | null, teamId: string | null, obsidianVaultPath: string | null, createdAt: string, updatedAt: string, };
