// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResearchReportSection = { id: string, reportId: string, sectionKey: string, title: string | null, content: string | null, sortOrder: number, generatedBy: string | null, citationIds: string | null, status: string, createdAt: string, updatedAt: string, };
