// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Difficulty } from "./Difficulty";
import type { EffortBand } from "./EffortBand";
import type { GpuClass } from "./GpuClass";
import type { MachineLoad } from "./MachineLoad";
import type { ProfileSource } from "./ProfileSource";

/**
 * What a run of a charter costs - declared by the persona, pinnable by the
 * operator. Lives at `spec.resourceProfile`; an absent profile reads as
 * [`ResourceProfile::default`] (light / none / standard / m).
 *
 * `pinned` is the operator's lock: a persona never overwrites a pinned
 * profile (enforced at the responsibility write door, not here).
 */
export type ResourceProfile = { machine: MachineLoad, gpu: GpuClass, difficulty: Difficulty, effort: EffortBand, source: ProfileSource, pinned: boolean, 
/**
 * Why the declarer chose these tags - one line, shown in the editor.
 */
rationale: string | null, 
/**
 * RFC 3339 instant of the last self-declaration or operator edit.
 */
declaredAt: string | null, };
