// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { ResponsibilityErrorPolicy } from "./ResponsibilityErrorPolicy";

/**
 * The runtime envelope a charter carries beyond its governance fields — the
 * half of a legacy design-context use case that was never about *what the
 * persona holds* but about *how a run of it is shaped* (input schema, engine
 * mode, notification routing, fixtures, recipe provenance). Stored as the
 * `persona_responsibilities.spec` JSON column (migration
 * `e19_agent_manifest`); every field is optional so a charter authored by
 * hand carries `{}` and a migrated one carries only what its use case had.
 */
export type ResponsibilitySpec = { inputSchema?: JsonValue, sampleInput?: JsonValue, modelOverride?: string, 
/**
 * The legacy use case's `execution_mode`.
 */
engineMode?: string, notificationChannels?: Array<string>, eventSubscriptions?: JsonValue, errorPolicy?: ResponsibilityErrorPolicy, timeFilter?: JsonValue, testFixtures?: JsonValue, sourceRecipeId?: string, sourceRecipeVersion?: string, 
/**
 * The design-context use case this charter was minted from by the
 * one-way migration — the migration's idempotency key, and the pointer
 * the trigger remap (`persona_triggers.responsibility_id`) followed.
 */
migratedFromUseCaseId?: string, memoryPolicy?: JsonValue, suggestedTrigger?: JsonValue, };
