// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coverage memory the App Master decision lane writes back on every wake —
 * how a persona remembers, between wakes, which of its charters it has
 * already looked at and what it decided to leave for next time.
 *
 * Lives on the charter's `spec` (a JSON column) rather than in a new table
 * or the attention ledger on purpose: the ledger records *dispatches*, and a
 * charter the decision deliberately DEFERRED writes no ledger row at all, so
 * the ledger cannot answer "when did I last consider this?". These three
 * stamps can, and they travel with the charter through export/import like the
 * rest of the spec.
 *
 * All three are RFC-3339 strings / free prose written by the loop, never by
 * the operator — treat them as the loop's own bookkeeping, not as authored
 * configuration.
 */
export type ResponsibilityPacing = { 
/**
 * When the decision lane last CONSIDERED this charter (dispatched or
 * deferred). Distinct from `last_dispatched_at`: a charter deferred four
 * wakes running was considered four times and dispatched zero.
 */
lastDecidedAt?: string, 
/**
 * When the decision lane last DISPATCHED work for this charter.
 */
lastDispatchedAt?: string, 
/**
 * The plan's note to its own next wake (≤ 300 chars, bounded at the
 * parse). Rendered back into the next decision prompt so coverage is a
 * memory rather than a fresh guess each tick.
 */
coverageNote?: string, };
