// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoutingClaim } from "./RoutingClaim";

/**
 * A candidate `ModelRoutingRule` diff with its quantified claim.
 */
export type RoutingRuleChange = { 
/**
 * Category the rule targets (`None` would be a universal rule — the v1
 * generator always proposes per-category, so this is always `Some`).
 */
category?: string, 
/**
 * Model the category currently resolves to (rule or observed dominant).
 */
fromModel?: string, toModel: string, claim: RoutingClaim, };
