// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a rule matches against. An all-`None` match is the universal default.
 */
export type RoutingMatch = { personaId?: string, category?: string, };
