// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanAgentMeta = { key: string, label: string, emoji: string, abbreviation: string, color: string, category_group: string, description: string, examples: string };
