// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-trigger record of scheduled slots that were DISCARDED while the app was
 * offline. The startup overdue sweep fires ONE catch-up per trigger and drops
 * the rest under the default backfill cap of 1; this row is the durable
 * "missed N while offline" signal surfaced in the schedule UI. Cleared after
 * the user backfills or dismisses.
 */
export type ScheduleMissedRuns = { triggerId: string, missedCount: number, firstMissedAt: string | null, lastMissedAt: string | null, 
/**
 * Direction 3: machine-readable reason the schedule is Paused/Unscheduled
 * (e.g. `invalid_timezone`). `None` when the schedule is healthy. Surfaced
 * in the schedule row next to the Paused/Unscheduled state.
 */
statusReason: string | null, 
/**
 * Human-facing detail for `status_reason` (e.g. the offending timezone +
 * parser error). Not translated — a diagnostic string.
 */
statusReasonDetail: string | null, };
