// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SchedulerStats = { running: boolean, events_processed: number, events_delivered: number, events_failed: number, triggers_fired: number, };
