// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of a session's screen moved between the last two renders it
 * happened to get — the "is it stuck?" signal.
 *
 * Read-only by construction: it reports whatever the last render already
 * measured and NEVER schedules one, so a session nobody has rendered simply
 * has no verdict (`null` on the wire) rather than costing work to produce one.
 */
export type ScreenHealth = "working" | "cosmetic" | "silent";
