// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An AES-256-GCM-sealed snapshot, base64-encoded for transport/storage. This is
 * the shape the Stage 3b protocol message carries between devices.
 */
export type SealedPayload = { ciphertextB64: string, nonceB64: string, };
