// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One execution referenced by a self-veto.
 */
export type SelfVetoExec = { id: string | null, personaId: string | null, };
