// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-source capture-gate state, surfaced to the UI via Tauri commands.
 * The toggles render against the *_enabled fields; the *_signals_in_window
 * counts populate the "What did Athena see?" view's source headers.
 */
export type SensorySourceState = { 
/**
 * Master kill switch (rarely toggled; defaults true).
 */
globalEnabled: boolean, 
/**
 * Per-source capture gate for clipboard signals (default false).
 */
clipboardEnabled: boolean, 
/**
 * Per-source capture gate for file-watcher signals (default false).
 */
fileChangesEnabled: boolean, 
/**
 * Per-source capture gate for app-focus signals (default false).
 */
appFocusEnabled: boolean, 
/**
 * Number of clipboard signals currently in the rolling window.
 */
clipboardSignalsInWindow: number, 
/**
 * Number of file-watcher signals currently in the rolling window.
 */
fileChangesSignalsInWindow: number, 
/**
 * Number of app-focus signals currently in the rolling window.
 */
appFocusSignalsInWindow: number, 
/**
 * Lifetime total of signals captured since process start (across all sources).
 */
totalSignalsCaptured: bigint, };
