// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed value the guide proposes for a real field. Nothing here is written
 * until the user accepts it, and an accepted value stays editable.
 */
export type SetupProposal = { 
/**
 * Stable per-turn id, assigned by the backend when the turn is parsed —
 * never by the model. Two tone proposals for the same channel are two
 * different offers, so the channel cannot serve as the key.
 */
id: string, kind: "bio" | "role" | "tone", 
/**
 * Which column of the tone row a `kind == "tone"` proposal fills:
 * `"voice"` (the voice directives, and the reading when absent) or
 * `"constraints"` (one Always/Never rule appended to the list). The model
 * is never allowed `"examples"`: a sample message has to be the person's
 * own words, so the client offers those itself from what they typed.
 */
part: "voice" | "constraints" | null, 
/**
 * Tone channel id for `kind == "tone"`; `None` otherwise.
 */
channel: string | null, value: string, 
/**
 * Reply-length guidance, only meaningful for a tone proposal.
 */
lengthHint: string | null, reason: string, };
