// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupKind } from "./SetupKind";

/**
 * One concrete thing standing between a persona and a working run — a
 * connector that is not ready, plus where the user fixes it. Serialized
 * into `personas.setup_detail`.
 */
export type SetupBlocker = { 
/**
 * The connector name as the persona declares it.
 */
connector: string, 
/**
 * What kind of setup it needs — drives UI routing.
 */
kind: SetupKind, 
/**
 * Human-readable one-liner: the connector + its remediation hint.
 */
detail: string, };
