// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One transcript line handed back to the generator so the next question
 * continues a conversation rather than restarting one.
 */
export type SetupTurnMessage = { 
/**
 * `"guide"` (the question) or `"user"` (the answer).
 */
role: "guide" | "user", text: string, };
