// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SharedEventCatalogEntry = { id: string, slug: string, name: string, description: string | null, category: string, publisher: string | null, icon: string | null, color: string | null, samplePayload: string | null, eventSchema: string | null, subscriberCount: number, isFeatured: boolean, status: string, cloudUpdatedAt: string | null, cachedAt: string, };
