// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SharedEventSubscription = { id: string, catalogEntryId: string, slug: string, enabled: boolean, lastCursor: string | null, eventsRelayed: number, lastEventAt: string | null, error: string | null, createdAt: string, updatedAt: string, };
