// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SketchGoal } from "./SketchGoal";
import type { SketchPage } from "./SketchPage";
import type { SketchQuestion } from "./SketchQuestion";

export type SiteSketch = { 
/**
 * One or two sentences: what she understood the site to be.
 */
summary: string, pages: Array<SketchPage>, goals: Array<SketchGoal>, questions: Array<SketchQuestion>, };
