// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SketchQuestion = { question: string, options: Array<string>, 
/**
 * One line: why only the user can answer it.
 */
why: string, };
