// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Skill {
  id: string;
  name: string;
  version: string;
  description: string | null;
  category: string | null;
  isBuiltin: boolean;
  createdAt: string;
  updatedAt: string;
}
