// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillFileDelta } from "./SkillFileDelta";

/**
 * Diff summary returned by [`skill_files_install_preview`] so the UI can show
 * what a re-install would overwrite BEFORE it commits the copy.
 */
export type SkillInstallPreview = { skillName: string, 
/**
 * Absolute path the skill would be installed to.
 */
targetPath: string, 
/**
 * Whether a skill already exists at the target (a re-install / overwrite).
 */
targetExists: boolean, changedCount: number, addedCount: number, removedCount: number, 
/**
 * Per-file deltas (capped for display).
 */
deltas: Array<SkillFileDelta>, };
