// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillEntry = { 
/**
 * Skill directory name (e.g. "research", "add-template")
 */
name: string, 
/**
 * Full path to the skill directory
 */
path: string, 
/**
 * Content of SKILL.md (the main skill definition)
 */
description: string | null, 
/**
 * Number of reference files in the skill directory (excluding SKILL.md)
 */
referenceFileCount: number, 
/**
 * Names of reference files
 */
referenceFiles: Array<string>, };
