// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SlaDailyPoint = { date: string, total: number, successful: number, failed: number, cancelled: number, success_rate: number, };
