// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalSlaStats } from "./GlobalSlaStats";
import type { HealingSummary } from "./HealingSummary";
import type { PersonaSlaStats } from "./PersonaSlaStats";
import type { SlaDailyPoint } from "./SlaDailyPoint";

export type SlaDashboardData = { 
/**
 * Per-persona reliability stats, sorted by total executions descending.
 */
persona_stats: Array<PersonaSlaStats>, 
/**
 * Global aggregate across all personas.
 */
global: GlobalSlaStats, 
/**
 * Fleet-wide healing summary.
 */
healing_summary: HealingSummary, 
/**
 * Daily success-rate trend for the requested period.
 */
daily_trend: Array<SlaDailyPoint>, };
