// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single phase measurement.
 */
export type StartupPhase = { 
/**
 * Human-readable name (e.g. "database_init").
 */
name: string, 
/**
 * Milliseconds elapsed since process start when this phase completed.
 */
elapsedMs: bigint, 
/**
 * Duration of this phase in milliseconds.
 */
durationMs: bigint, };
