// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StationSource } from "./StationSource";

export type Station = { id: string, slug: string, name: string, description: string, accentColor: string, 
/**
 * Optional homepage / attribution link for the provider.
 */
sourceUrl: string | null, 
/**
 * Optional human-readable provider label (e.g. "SomaFM" or
 * "Lofi Girl"). Shown in the picker + settings card.
 */
sourceLabel: string | null, source: StationSource, };
