// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StaticScanResult = { scan_id: string, project_id: string, tool: string, ideas_created: number, stderr: string | null, raw_output_excerpt: string | null };
