// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TwinStyleDims } from "./TwinStyleDims";

/**
 * A materialized tone for one channel, previewed before apply.
 */
export type StyleToneDraft = { channel: string, voiceDirectives: string, examples: Array<string>, constraints: Array<string>, lengthHint: string, dims: TwinStyleDims, };
