// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextScore } from "./ContextScore";

/**
 * Per-subject adherence. The ratio is `clean_contexts / applicable_contexts`
 * and BOTH numbers come from the artifact — `contexts` lists only dirty ones,
 * so the denominator can never be derived from the array.
 *
 * A subject ABSENT from `subjects` has no census rules yet; absence is NOT
 * cleanliness (census coverage ≠ adherence coverage).
 */
export type SubjectScore = { slug: string, 
/**
 * Census rules assigned to this subject.
 */
rules: number, 
/**
 * Surviving census match sites across the repo.
 */
sites: number, 
/**
 * Distinct files with ≥1 site.
 */
matchedFiles: number, 
/**
 * Contexts containing ≥1 file SCANNED by any of the subject's rules.
 */
applicableContexts: number, 
/**
 * Applicable AND zero sites.
 */
cleanContexts: number, contexts: Array<ContextScore>, 
/**
 * Sites in files that belong to NO context.
 */
uncontextedSites: number, };
