// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-subscription health snapshot including tick latency, counts, and error tracking.
 */
export type SubscriptionHealth = { name: string, 
/**
 * Whether the subscription loop is currently running.
 */
alive: boolean, 
/**
 * ISO 8601 timestamp when the subscription loop started.
 */
startedAt: string | null, intervalMs: bigint, lastTickDurationMs: bigint, maxTickDurationMs: bigint, 
/**
 * True when the last tick took longer than the subscription's configured interval.
 */
overrun: boolean, 
/**
 * Total number of successful ticks since startup.
 */
tickCount: bigint, 
/**
 * Total number of tick errors (panics caught by the panic boundary).
 */
errorCount: bigint, 
/**
 * Consecutive panics without a successful tick in between.
 * Resets to 0 after a successful tick.
 */
consecutivePanics: number, 
/**
 * ISO 8601 timestamp of the last completed tick (success or panic).
 */
lastTickAt: string | null, 
/**
 * Rolling average tick duration in milliseconds.
 */
avgTickDurationMs: bigint, 
/**
 * Total number of ticks that exceeded their configured interval.
 */
overrunCount: bigint, 
/**
 * Total number of ticks that exceeded 80% of the configured interval
 * but did not fully overrun.
 */
slowTickCount: bigint, };
