// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Subscription = { projectId: string, projectPath: string, watchGit: boolean, watchActiveRuns: boolean, watchObsidian: boolean, obsidianVaultPath: string | null, enabled: boolean, lastPulseAt: string | null, createdAt: string, updatedAt: string, };
