// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The per-class opt-ins of PHASE2-SPEC 5 (owner decision M19).
 */
export type SyncDataClass = "notes" | "chats";
