// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncState = { id: string, entityType: string, entityId: string, vaultFilePath: string, contentHash: string, syncDirection: string, syncedAt: string, };
