// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A persisted trigger → system-operation automation.
 */
export type SystemOpAutomation = { id: string, 
/**
 * Registered operation key (e.g. `"context_scan"`).
 */
opKind: string, 
/**
 * JSON-encoded op params (e.g. `{"projectId":"…","deltaMode":true}`).
 */
paramsJson: string, 
/**
 * `"schedule"` (cron) | `"event"` (event-bus listener).
 */
triggerKind: string, 
/**
 * Cron expression — set when `trigger_kind == "schedule"`.
 */
cron: string | null, 
/**
 * Optional IANA timezone for the cron.
 */
timezone: string | null, 
/**
 * Event type to listen for — set when `trigger_kind == "event"`.
 */
listenEventType: string | null, 
/**
 * Optional wildcard filter on the event `source_id`.
 */
sourceFilter: string | null, enabled: boolean, 
/**
 * Next computed fire time (schedule kind only).
 */
nextRunAt: string | null, lastRunAt: string | null, 
/**
 * `"ok"` | `"failed"` | `"requested"` (delegated op emitted, frontend not
 * yet reported back) | `"partial"` | `"held"` (approval mode).
 */
lastStatus: string | null,
/**
 * Short human detail of the last run (e.g. a scan id or error).
 */
lastDetail: string | null, 
/**
 * Optional user-facing label.
 */
label: string | null,
/**
 * `"auto"` | `"approval"` — the safety gate for ops that act on production
 * signal (the signal-dispatch ops). `approval` holds the run instead of
 * dispatching (`last_status = "held"`); the human acts from Triage.
 * Manual `run_now` bypasses the gate — running by hand IS the approval.
 */
unattendedMode: string, createdAt: string, updatedAt: string, };
