// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Catalog entry describing one available system operation. Drives the Chain
 * Studio "System events" rail (the right-hand targets).
 */
export type SystemOpKindMeta = { 
/**
 * Stable key matching `SystemOpAutomation.op_kind`.
 */
kind: string, label: string, description: string, 
/**
 * True when the op is scoped to a single dev-tools project (needs a
 * `projectId` param). The Studio prompts for the project on commit.
 */
requiresProject: boolean, };
