// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TablePerfStats = { table: string, totalQueries: bigint, slowQueries: bigint, avgMs: number, p95Ms: number, maxMs: number, lastSlowOperation: string | null, };
