// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TablePerfStats {
  table: string;
  totalQueries: number;
  slowQueries: number;
  avgMs: number;
  p95Ms: number;
  maxMs: number;
  lastSlowOperation: string | null;
}
