// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One table's share of a prune's blast radius.
 */
export type TableImpact = { 
/**
 * Table name (a code identifier, shown verbatim).
 */
table: string, 
/**
 * Rows this table lost when the delete executed. Bounded far under 2^53
 * (a single prune's casualties), so the wire carries a JS number.
 */
rows: number, };
