// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevTask } from "./DevTask";

/**
 * One keyset page of tasks plus per-status counts. Same cursor scheme as
 * `triage_ideas` (`"{created_at}|{id}"`, `created_at DESC, id DESC`).
 * `list_tasks` stays untouched for the existing unpaginated callers.
 */
export type TasksPage = { tasks: Array<DevTask>, cursor: string | null, has_more: boolean, 
/**
 * Per-status totals scoped to the project (NOT to the status filter), so
 * status chips stay truthful beyond the loaded page.
 */
counts: { [key in string]?: number }, };
