// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One message in a team's channel from any author kind.
 */
export type TeamChannelMessage = { id: string, teamId: string, 
/**
 * 'user' | 'athena' | 'director' | 'persona'
 */
authorKind: string, 
/**
 * Persona id when author_kind is 'persona' or 'director'; NULL for user/athena.
 */
authorId: string | null, body: string, 
/**
 * JSON array of persona ids the message is addressed to; NULL = whole team.
 */
addressedTo: string | null, 
/**
 * Threading: the message id this replies to.
 */
replyTo: string | null, 
/**
 * Optional anchor to a specific assignment/mission.
 */
assignmentId: string | null, 
/**
 * 'inject' (reaches step input/prompt) | 'mention' (routes to an actor) |
 * 'display' (human-only). The defined-consumer governance rule.
 */
consumer: string, 
/**
 * JSON `[{step_id, persona_id, at}]` delivery receipts.
 */
deliveries: string | null, createdAt: string, };
