// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TeamAssignment = { id: string, teamId: string, title: string, goal: string, status: string, matchStrategy: string, maxParallelSteps: number, source: string, companionOpId: string | null, createdAt: string, startedAt: string | null, completedAt: string | null, errorMessage: string | null, };
