// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed shape of the `persona_teams.north_star` JSON column — the shared
 * motivation every member imprints ("be #1 in category"). Authored at the
 * team-preset level (D5). Each member shares the `aim` but reaches it via its
 * own `PersonaCore.north_star_commitment` (distinct routes).
 */
export type TeamNorthStar = { 
/**
 * e.g. "Become the #1 <category> product".
 */
aim: string, 
/**
 * The category the team competes in.
 */
category: string, 
/**
 * What winning looks like (≤5 signals).
 */
successSignals: Array<string>, };
