// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle states for a `TeamAssignment`. Terminal: `done`, `failed`, `aborted`.
 * `awaiting_review` is a soft pause — the orchestrator stops the tick loop
 * only for THIS assignment; other assignments on the same team continue.
 */
export type TeamAssignmentStatus = "queued" | "running" | "awaiting_review" | "done" | "failed" | "aborted";
