// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TeamPresetConnection = { 
/**
 * Role label of the source member.
 */
from: string, 
/**
 * Role label of the target member.
 */
to: string, 
/**
 * Connection-type vocabulary; passed unmodified to
 * `create_team_connection`. Common values: `"data"`, `"feedback"`.
 */
connection_type: string, label: string | null, };
