// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TeamAssignmentStep = { id: string, assignmentId: string, stepOrder: number, title: string, description: string | null, status: string, assignedPersonaId: string | null, assignedUseCaseId: string | null, matchConfidence: number | null, matchRationale: string | null, executionId: string | null, 
/**
 * JSON array of step ids — `depends_on` for DAG-style ordering.
 * Empty array (or null) = no prerequisites, eligible from the start.
 */
dependsOn: string | null, outputSummary: string | null, retryCount: number, errorMessage: string | null, startedAt: string | null, completedAt: string | null, };
