// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TeamAssignmentEvent = { id: string, assignmentId: string, stepId: string | null, kind: string, payload: string | null, createdAt: string, };
