// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TeamPresetMember = { 
/**
 * Matches an existing template's `id` (from
 * `scripts/templates/<category>/*.json`). Validated by the adopter,
 * not the loader.
 */
template_id: string, 
/**
 * Logical label used by `TeamPresetConnection.from` / `.to`. Unique
 * within a preset (the loader enforces this).
 */
role: string, 
/**
 * Canvas x/y coordinates passed straight through to `add_team_member`.
 */
x: number, y: number, };
