// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Certification status per team — the gate the dashboard headlines.
 */
export type TeamCertStatus = { teamId: string, 
/**
 * Display label (falls back to `team_id` when no label is present).
 */
team: string, 
/**
 * Trailing consecutive PRODUCTION verdicts over held-out runs, capped at 3.
 */
streak: number, 
/**
 * `streak >= 3`.
 */
certified: boolean, heldOutRuns: number, latestVerdict: string | null, latestRunId: string | null, 
/**
 * Verdict distribution over the team's held-out runs.
 */
verdictCounts: { [key in string]?: number }, };
