// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One deliberation: a bounded conversation with a topic and a live agenda.
 * Length is bounded by **progress** — the agenda backbone plus
 * `consecutive_stall_rounds` — NOT by a turn count (see the plan §6). Cost and
 * idle deadlines are the hard floors.
 */
export type TeamDeliberation = { id: string, teamId: string, 
/**
 * The question the team is deliberating.
 */
topic: string, 
/**
 * Optional prose: what a good outcome looks like.
 */
goal: string | null, 
/**
 * 'open' | 'converging' | 'resolved' | 'escalated' | 'paused' | 'aborted'
 */
status: string, 
/**
 * Moderator rounds so far (escalation cadence).
 */
round: number, 
/**
 * Consecutive non-productive rounds — the circularity bound that replaces
 * the turn budget. Reset to 0 on a `progressed` round.
 */
consecutiveStallRounds: number, 
/**
 * Hard cost floor (USD): pause + escalate when `cost_spent_usd` exceeds it.
 */
costBudgetUsd: number | null, 
/**
 * Rolled-up CLI spend for this deliberation (USD).
 */
costSpentUsd: number, 
/**
 * Hard wall-clock floor: auto-pause if no progress / no user activity by then.
 */
idleDeadline: string | null, 
/**
 * JSON `{kind:'proposal'|'assignment'|'none', ...}` once resolved.
 */
resolution: string | null, 
/**
 * Set when a proposal feeds the DAG.
 */
spawnedAssignmentId: string | null, 
/**
 * 'user' | 'athena' — who opened it.
 */
createdBy: string, createdAt: string, updatedAt: string, };
