// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateBucketUsage } from "./RateBucketUsage";
import type { TierConfig } from "./TierConfig";

/**
 * Full tier usage snapshot returned to the frontend.
 */
export type TierUsageSnapshot = { 
/**
 * Current tier config.
 */
tier: TierConfig, 
/**
 * Per-bucket rate limiter usage.
 */
rateBuckets: Array<RateBucketUsage>, 
/**
 * Total running executions across all personas.
 */
totalRunning: number, 
/**
 * Total queued executions across all personas.
 */
totalQueued: number, 
/**
 * Configured max queue depth per persona.
 */
maxQueueDepth: number, 
/**
 * Whether any bucket is at or above 80% of its limit.
 */
approachingLimit: boolean, };
