// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateBucketUsage } from "./RateBucketUsage";
import type { TierConfig } from "./TierConfig";

export type TierUsageSnapshot = { tier: TierConfig, rate_buckets: RateBucketUsage[], total_running: number, total_queued: number, max_queue_depth: number, approaching_limit: boolean, };
