// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-tier rate and queue limits.
 */
export type TierConfig = { 
/**
 * Display name: "free", "pro", "enterprise"
 */
tierName: string, 
/**
 * Max events per source per minute.
 */
eventSourceMax: number, 
/**
 * Max webhook calls per trigger per minute.
 */
webhookTriggerMax: number, 
/**
 * Max queue depth per persona.
 */
maxQueueDepth: number, };
