// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolErrorKind } from "./ToolErrorKind";

/**
 * Result of a direct (no-LLM) tool invocation.
 *
 * This is the direct-path half of the shared tool-result contract (see
 * `engine::tool_outcome`). Success and failure both populate the typed
 * contract fields — `error_kind` / `http_status` / `retryable` on failure, and
 * `output` is always capped at `DIRECT_TOOL_OUTPUT_CAP_BYTES` with
 * `output_truncated` surfacing any truncation (never silent).
 */
export type ToolInvocationResult = { success: boolean, output: string,
/**
 * True when `output` was capped at the output byte limit.
 */
output_truncated: boolean, error: string | null,
/**
 * Typed failure category (`None` on success).
 */
error_kind: ToolErrorKind | null,
/**
 * HTTP status when the failure came from an HTTP/API call (`None` otherwise).
 */
http_status: number | null,
/**
 * Whether retrying the call could plausibly succeed (timeouts, transport,
 * 5xx, rate-limit). `false` on success and on terminal failures.
 */
retryable: boolean, duration_ms: bigint, tool_name: string,
/**
 * "script" | "api" | "automation"
 */
tool_type: string, };
