// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolErrorKind = "auth" | "timeout" | "http" | "transport" | "tool_error" | "rate_limited" | "misconfigured" | "unknown";
