// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Track = { videoId: string, title: string, artist: string, 
/**
 * Optional — `null` in the seed JSON; the IFrame Player reports the real
 * duration at runtime, but we don't currently round-trip it back into
 * state because tracks are queued by id, not by metadata.
 */
durationSec: number | null, };
