// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sync-safe projection of a `persona_triggers` row. Excludes device-local runtime
 * fields (`last_triggered_at`, `next_trigger_at`) — only the definition syncs.
 */
export type TriggerSnapshot = { id: string, personaId: string, triggerType: string, 
/**
 * JSON-encoded trigger config (cron/timezone, webhook, chain conditions, …).
 */
config: string | null, enabled: boolean, 
/**
 * RFC3339 last-modified; the LWW key, excluded from `content_hash`.
 */
updatedAt: string, };
