// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrustLevel } from "./TrustLevel";

export type TrustedPeer = { peer_id: string, public_key_b64: string, display_name: string, trust_level: TrustLevel, added_at: string, last_seen: string | null, notes: string | null, };
