// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TwinTone = { id: string, twin_id: string, 
/**
 * Channel this tone applies to. Well-known values: "generic", "discord",
 * "slack", "email", "sms", "voice". The "generic" tone is the fallback.
 */
channel: string, 
/**
 * Free-text system-prompt fragment describing how the twin speaks on this
 * channel. Injected as-is into the persona's prompt when a twin tool is
 * called.
 */
voice_directives: string, 
/**
 * JSON array of example messages demonstrating the twin's voice on this
 * channel (few-shot references).
 */
examples_json: string | null, 
/**
 * JSON array of do/don't constraints (e.g. ["No emoji", "No corporate speak"]).
 */
constraints_json: string | null, 
/**
 * Guidance on reply length: "1-3 sentences", "short paragraph", etc.
 */
length_hint: string | null, 
/**
 * JSON-encoded [`TwinStyle`] that produced this row (preset or rolled),
 * carrying THIS channel's resolved dimensions. `None` for hand-written
 * tones. Hand edits after an apply keep it: the upsert never touches it.
 */
style_json: string | null, updated_at: string, };
