// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One partition as seen by `twin_card_inspect`.
 */
export type TwinCardPartitionInfo = { 
/**
 * `voice` | `knowledge` | `training` | `evidence`.
 */
name: string, sealed: boolean, 
/**
 * The partition's SHA-256 matched; `null` when sealed and no passphrase
 * was given (the hash covers the plaintext, so it cannot be checked yet).
 */
hashOk: boolean | null, };
