// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapshot of an on-disk twin wiki. `exists: false` means no compile has
 * run yet (or the dir was deleted out from under us). The frontend uses
 * `last_compiled_at` to render the freshness pill in TwinSelector.
 */
export type TwinWikiStatus = { exists: boolean, fileCount: number, 
/**
 * ISO-8601 UTC timestamp of the newest .md file's mtime; `None` when
 * the directory is empty or absent.
 */
lastCompiledAt: string | null, 
/**
 * Resolved on-disk path. Always populated even when `exists` is false
 * — that's where a subsequent compile would write to.
 */
dirPath: string, };
