// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an import created.
 */
export type TwinCardImportResult = { 
/**
 * The new (or replaced) twin; `""` when the conflict choice was `skip`.
 */
twinId: string, 
/**
 * The partitions applied.
 */
imported: Array<string>, warnings: Array<string>, };
