// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TwinStudioItem } from "./TwinStudioItem";

/**
 * Snapshot of a Studio batch job (status + accumulated items), returned by
 * `twin_studio_get_batch` so the frontend can hydrate even if it missed
 * in-flight events (e.g. it was on a different route while the job ran).
 */
export type TwinStudioBatch = { batchId: string, status: string, phase: string, completed: number, total: number, items: Array<TwinStudioItem>, error: string | null, };
