// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TwinCardPartitionInfo } from "./TwinCardPartitionInfo";

/**
 * A card read without importing it.
 */
export type TwinCardInspection = { 
/**
 * The file's `spec_version` as written (`""` when absent).
 */
specVersion: string, 
/**
 * This app can read that version (major 1). Distinct from `valid`: an
 * unsupported card is not an invalid one.
 */
supported: boolean, 
/**
 * The card validated against the vendored schema.
 */
valid: boolean, name: string | null, partitions: Array<TwinCardPartitionInfo>, 
/**
 * `valid` | `invalid` | `unsigned`.
 */
signature: string, warnings: Array<string>, };
