// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TwinPendingMemory = { id: string, twin_id: string, channel: string | null, content: string, title: string | null, importance: number, status: string, reviewer_notes: string | null, created_at: string, reviewed_at: string | null };
