// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to put in an exported card, and where. The passphrase that seals the
 * personal partitions is NOT a field here: it travels as its own command
 * parameter so no serializable struct ever holds it (census
 * `secret-as-bare-string-field`).
 */
export type TwinCardExportOptions = { 
/**
 * Any of `voice` | `knowledge` | `training` | `evidence`. `voice` is
 * always written (identity rides with it) even when absent here.
 */
partitions: Array<string>, 
/**
 * `twin-card` | `ccv3` (Character Card V3, the full card preserved under
 * `data.extensions["twin-card"]`).
 */
format: string, 
/**
 * Absolute destination path chosen in the save dialog.
 */
path: string, };
