// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TwinCardPartitionInfo } from "./TwinCardPartitionInfo";

export type TwinCardInspection = { specVersion: string, supported: boolean, valid: boolean, name: string | null, partitions: Array<TwinCardPartitionInfo>, signature: string, warnings: Array<string>, };
