// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload of `twin-sample-updated` (`event_name::TWIN_SAMPLE_UPDATED`): a
 * sample's analysis changed state. Carries no sample text.
 */
export type TwinSampleUpdatedEvent = { twinId: string, sampleId: string, 
/**
 * The sample's new `status` (see [`TwinSample::status`]).
 */
status: string, 
/**
 * Open proposals this sample produced (0 until `ready`).
 */
proposals: number, };
