// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an export wrote.
 */
export type TwinCardExportResult = { path: string, 
/**
 * The partitions written, in file order.
 */
partitions: Array<string>, 
/**
 * The subset of `partitions` that was sealed.
 */
sealed: Array<string>, 
/**
 * An Ed25519 signature was written (false when no device identity key
 * was available - readers then report `unsigned`).
 */
signed: boolean, warnings: Array<string>, };
