// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a `twin_compile_wiki` invocation. Tells the caller how many
 * files landed and where, so the frontend can show "12 files · ~/twin-wikis/foo/"
 * without a follow-up status query.
 */
export type TwinWikiCompileResult = { fileCount: number, dirPath: string, 
/**
 * ISO-8601 UTC timestamp.
 */
compiledAt: string, };
