// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One captured writing sample and the state of its analysis.
 */
export type TwinSample = { id: string, twinId: string, text: string, 
/**
 * The tone channel the analysis assigned (`email`, `slack`, ...); `null`
 * until the analysis has run.
 */
channel: string | null, 
/**
 * `selection` | `clipboard` | `forge`.
 */
sourceKind: string, 
/**
 * The page host the sample came from, when it came from a page.
 */
sourceHost: string | null, 
/**
 * `analyzing` | `ready` | `failed` | `refused`.
 */
status: string, 
/**
 * Why it failed, or why it was refused (e.g. it matches a draft the twin
 * itself placed, or it is not the user's own writing).
 */
error: string | null, createdAt: string, analyzedAt: string | null, };
