// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One parked row from an undo pass.
 */
export type UndoConflict = { journalId: number, table: string, rowPk: string | null, reason: string, };
