// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One consult that found no active playbook — a gap in the library, verbatim.
 */
export type UnmatchedIntent = { intent: string, createdAt: string, };
