// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrustLevel } from "./TrustLevel";

export type UpdateTrustedPeerInput = { display_name?: string | null, trust_level?: TrustLevel | null, notes?: string | null, };
