// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCredentialInput = { name: string | null, serviceType: string | null, encryptedData: string | null, 
/**
 * Derived from encryption -- never set by callers.
 * skip_deserializing ensures this is always None from IPC input;
 * the command layer sets it from the encryption result.
 */
iv: string | null, metadata: string | null | null, sessionEncryptedData: string | null, 
/**
 * One-time reference to a completed in-memory OAuth session — see
 * `CreateCredentialInput::oauth_session_ref`. Tokens are merged into the
 * updated field map server-side.
 */
oauthSessionRef?: string, };
