// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateSkillInput {
  name: string | null;
  version: string | null;
  description: string | null;
  category: string | null;
}
