// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create-or-update body for `browser_sites_upsert`.
 *
 * `None` means "leave what the row has" on an update and "take the default"
 * on a create — the same three-state shape `NotePatch` needed, minus the
 * double-option, because no field here is nullable-and-settable except
 * `credential_id`, which has its own command (`bind_credential`).
 */
export type UpsertBrowserSiteInput = { origin: string, label: string | null, enabled: boolean | null, budget: number | null, 
/**
 * Who is adding it. Defaults to `operator` when absent.
 */
created_by: string | null, };
