// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a caller may set on a scenario. `id` absent means create.
 */
export type UpsertScenarioInput = { 
/**
 * `None` creates; `Some` updates that row and refuses if it is gone.
 */
id: string | null, useCaseId: string, 
/**
 * Derived from `title` when absent or blank.
 */
slug: string | null, title: string, axes: { [key in string]?: string }, scope: string, 
/**
 * Stored as given. `None` on `must_hold` means the default floor applies.
 */
floor: number | null, };
