// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one relink pass did. Counts rather than a bare bool, because
 * "nothing needed relinking" and "nothing could be relinked" are opposite
 * answers and a bool spells them the same.
 */
export type UseCaseRelinkSummary = { projectId: string, scanId: string, 
/**
 * Use cases the model was given.
 */
considered: number, 
/**
 * Use cases whose slice was rewritten.
 */
relinked: number, 
/**
 * Slugs the model answered for that this project does not have.
 */
unknownSlugs: Array<string>, 
/**
 * Context names the model answered with that the map does not have.
 */
unknownContexts: Array<string>, 
/**
 * Use cases kept but left UNLINKED because fewer than two contexts
 * resolved: a use case is a slice THROUGH contexts, and one context is a
 * module. Counted rather than rejected - the row stays, the link does not.
 */
underSpanned: Array<string>, };
