// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * At-rest encryption posture of the credential vault.
 *
 * Field names are deliberately snake_case (no `rename_all`) because the
 * frontend has read `status.key_source` / `status.credential_audit_write_failures`
 * since before this payload was typed.
 */
export type VaultStatus = { 
/**
 * Where the master key came from — `"keychain"` when the OS keyring holds
 * it, a fallback label otherwise. The trust badge branches on this.
 */
keySource: string, total: number, encrypted: number, plaintext: number, legacyIpcDecryptCalls: number, credentialAuditWriteFailures: number, };
