// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlapNext } from "./OverlapNext";

export type VideoStage = { 
/**
 * Stable across recompiles of the same Composition.
 */
id: string, 
/**
 * Index into RenderPlan.sources. Source kind must be 'file' or 'proxy'
 * (not 'color' — color fills are implicit gaps, not stages).
 */
sourceId: number, 
/**
 * Absolute start/end on the output timeline, seconds. outputEnd > outputStart.
 */
outputStart: number, outputEnd: number, 
/**
 * Source-time region consumed. sourceEnd > sourceIn.
 */
sourceIn: number, sourceEnd: number, 
/**
 * Playback rate applied to the source.
 */
speed: number, 
/**
 * Effective fades in seconds. For fade-folded transitions these already
 * include the neighbor clip's transitionDuration contribution — renderers
 * do NOT fold, they just apply what's here.
 */
fadeIn: number, fadeOut: number, 
/**
 * Present when this stage temporally overlaps the next video stage.
 * Only emitted when the compiler ran with transitionMode === 'overlap'.
 */
overlapNext: OverlapNext | null, 
/**
 * Mute audio embedded in this clip's source. When true, no contribution
 * to the 'embedded' audio track.
 */
stripEmbeddedAudio: boolean, };
