// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One phase of a project's build plan (Spine → Dynamic Tail; see the web-build
 * doctrine). `status` is `"done" | "active" | "pending"` (kept as a string so a
 * hallucinated value degrades gracefully rather than failing the whole parse).
 */
export type WebBuildPhase = { id: string, title: string, status: string, note: string | null, };
