// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-project adoption state of an adopted practice — the scaling surface:
 * a project newly assigned to the workspace inherits every applicable
 * adopted practice as a `proposed` row (to-adopt queue).
 */
export type WorkspacePracticeAdoption = { practice_id: string, project_id: string, 
/**
 * 'na' | 'proposed' | 'to_process' | 'dispatched' | 'adopted' | 'diverged'
 * (DB CHECK). `to_process` is the execution queue seeded when an
 * ACTIONABLE practice (pitfall/pattern) is adopted.
 */
state: string, 
/**
 * Dedup key of the adopt Fleet dispatch (`workspace:<practice>:<slug>`).
 */
fleet_key: string | null, note: string | null, last_verified_at: string | null, updated_at: string, };
