// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-scope harvest coverage for one member repo — the answer to "how much of
 * this codebase has the library actually read?".
 *
 * Without this row a harvest run cannot tell where it has already been, so
 * every run re-reads the cheapest territory (root configs), finds it already
 * proposed via the dedup list, and returns less than the run before it. The
 * coverage table is what makes successive runs ADVANCE instead of decay, and
 * what lets the UI report an unread surface instead of implying completeness.
 */
export type WorkspaceHarvestCoverage = { project_id: string, 
/**
 * Stable scope slug (`group:execution-orchestration`, `repo-global`, …).
 */
scope_id: string, scope_label: string, 
/**
 * 'group' | 'directory' | 'global'.
 */
kind: string, 
/**
 * Files in the territory — the denominator behind a coverage claim.
 */
file_count: bigint, 
/**
 * NULL means never harvested. That is the point of the row existing.
 */
last_harvested_at: string | null, last_run_dir: string | null, 
/**
 * Items the most recent run produced for this scope.
 */
items_found: bigint, run_count: bigint, 
/**
 * How much of the territory the last run actually READ, self-reported by
 * the harvest session. "Visited" and "covered" are different claims and
 * the ledger must not conflate them: a scope read at 11% is a scope that
 * still owes a pass, even though `last_harvested_at` is set.
 */
files_read: bigint | null, files_total: bigint | null, estimated_pct: bigint | null, 
/**
 * JSON array of paths the last run named as unread. Fed back into the
 * next dispatch for this scope, which is what turns a re-run into a
 * genuine second pass instead of a re-read of the same ground.
 */
unread_pockets: string | null, coverage_note: string | null, updated_at: string, };
