/**
 * Client-side report generator for lab test results.
 *
 * Produces self-contained HTML reports (all styles inlined) or clipboard-
 * friendly markdown from existing result data. No backend changes required.
 */
import { compositeScore } from '@/lib/eval/evalFramework';
import { aggregateArenaResults, aggregateAbResults, aggregateMatrixResults } from './labAggregation';
import { buildEvalGridData } from './evalAggregation';
import type { LabArenaResult } from '@/lib/bindings/LabArenaResult';
import type { LabAbResult } from '@/lib/bindings/LabAbResult';
import type { LabMatrixResult } from '@/lib/bindings/LabMatrixResult';
import type { LabEvalResult } from '@/lib/bindings/LabEvalResult';
import type { LabArenaRun } from '@/lib/bindings/LabArenaRun';
import type { LabAbRun } from '@/lib/bindings/LabAbRun';
import type { LabMatrixRun } from '@/lib/bindings/LabMatrixRun';
import type { LabEvalRun } from '@/lib/bindings/LabEvalRun';

// ── Shared helpers ────────────────────────────────────────────────

function scoreLabel(score: number): string {
  if (score >= 80) return 'Excellent';
  if (score >= 60) return 'Good';
  if (score >= 40) return 'Fair';
  if (score >= 20) return 'Weak';
  return 'Poor';
}

function scoreHexColor(score: number): string {
  if (score >= 80) return '#10b981';
  if (score >= 60) return '#3b82f6';
  if (score >= 40) return '#f59e0b';
  return '#ef4444';
}

function fmtCost(usd: number): string {
  return `$${usd.toFixed(4)}`;
}

function fmtDuration(ms: number): string {
  return ms >= 1000 ? `${(ms / 1000).toFixed(1)}s` : `${ms}ms`;
}

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleString();
}

function escHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// ── Shared HTML template ──────────────────────────────────────────

function wrapHtml(title: string, body: string, meta: { date: string; mode: string; persona: string }): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escHtml(title)}</title>
<style>
  :root { --bg: #0f1117; --card: #161822; --border: #262a3a; --text: #e5e7eb; --muted: #9ca3af; --accent: #60a5fa; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; padding: 2rem; max-width: 960px; margin: 0 auto; }
  h1 { font-size: 1.5rem; font-weight: 700; margin-bottom: 0.25rem; }
  h2 { font-size: 1.15rem; font-weight: 600; margin: 1.5rem 0 0.75rem; border-bottom: 1px solid var(--border); padding-bottom: 0.4rem; }
  h3 { font-size: 0.95rem; font-weight: 600; margin: 1rem 0 0.5rem; }
  .meta { color: var(--muted); font-size: 0.82rem; margin-bottom: 1.5rem; }
  .meta span { margin-right: 1.5rem; }
  .card { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; margin-bottom: 0.75rem; }
  .grid { display: grid; gap: 0.75rem; }
  .grid-2 { grid-template-columns: repeat(2, 1fr); }
  .grid-3 { grid-template-columns: repeat(3, 1fr); }
  table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
  th, td { padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid var(--border); }
  th { font-weight: 600; color: var(--muted); font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.04em; }
  .score { font-weight: 700; font-size: 1.3rem; }
  .metric-row { display: flex; justify-content: space-between; font-size: 0.85rem; margin: 0.25rem 0; }
  .metric-label { color: var(--muted); }
  .bar-bg { height: 6px; background: rgba(255,255,255,0.06); border-radius: 3px; margin-top: 2px; }
  .bar-fill { height: 6px; border-radius: 3px; transition: width 0.3s; }
  .badge { display: inline-block; font-size: 0.72rem; font-weight: 600; padding: 0.15rem 0.5rem; border-radius: 4px; }
  .winner { background: rgba(16,185,129,0.15); color: #10b981; }
  .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.75rem; text-align: center; }
  @media (max-width: 640px) { .grid-2, .grid-3 { grid-template-columns: 1fr; } body { padding: 1rem; } }
</style>
</head>
<body>
<h1>${escHtml(title)}</h1>
<div class="meta">
  <span>${escHtml(meta.persona)}</span>
  <span>${escHtml(meta.mode)} Test</span>
  <span>${escHtml(meta.date)}</span>
</div>
${body}
<div class="footer">Generated by Personas &mdash; ${escHtml(meta.date)}</div>
</body>
</html>`;
}

function metricBar(label: string, value: number): string {
  return `<div class="metric-row"><span class="metric-label">${escHtml(label)}</span><span style="color:${scoreHexColor(value)};font-weight:600">${value}/100</span></div>
<div class="bar-bg"><div class="bar-fill" style="width:${Math.max(value, 2)}%;background:${scoreHexColor(value)}"></div></div>`;
}

// ── Arena report ──────────────────────────────────────────────────

function arenaHtml(run: LabArenaRun, results: LabArenaResult[], personaName: string): string {
  const { aggregates, bestModelId, scenarios } = aggregateArenaResults(results);
  const gridCls = aggregates.length <= 2 ? 'grid-2' : 'grid-3';

  let body = '<h2>Model Performance</h2>';
  body += `<div class="grid ${gridCls}">`;
  for (const agg of aggregates) {
    const isBest = agg.modelId === bestModelId;
    body += `<div class="card">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:0.5rem">
        <strong>${escHtml(agg.modelId)}</strong>
        ${isBest ? '<span class="badge winner">Best</span>' : ''}
      </div>
      <div class="score" style="color:${scoreHexColor(agg.compositeScore)}">${agg.compositeScore}<span style="font-size:0.7rem;font-weight:400;color:var(--muted)">/100 ${scoreLabel(agg.compositeScore)}</span></div>
      ${metricBar('Tool Accuracy', agg.avgToolAccuracy)}
      ${metricBar('Output Quality', agg.avgOutputQuality)}
      ${metricBar('Protocol Compliance', agg.avgProtocolCompliance)}
      <div class="metric-row" style="margin-top:0.5rem"><span class="metric-label">Cost</span><span>${fmtCost(agg.totalCost)}</span></div>
      <div class="metric-row"><span class="metric-label">Avg Duration</span><span>${fmtDuration(agg.avgDuration)}</span></div>
    </div>`;
  }
  body += '</div>';

  body += scenarioTable(scenarios, aggregates.map((a) => a.modelId), results, 'modelId');

  return wrapHtml(`Arena Report — ${personaName}`, body, {
    date: fmtDate(run.createdAt),
    mode: 'Arena',
    persona: personaName,
  });
}

// ── A/B report ────────────────────────────────────────────────────

function abHtml(run: LabAbRun, results: LabAbResult[], personaName: string): string {
  const { versionAggs, scenarios, winnerId } = aggregateAbResults(results);

  let body = '<h2>Version Comparison</h2>';
  body += '<div class="grid grid-2">';
  for (const agg of versionAggs) {
    const isWinner = agg.versionId === winnerId;
    body += `<div class="card">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:0.5rem">
        <strong>Version ${agg.versionNumber}</strong>
        ${isWinner ? '<span class="badge winner">Winner</span>' : ''}
      </div>
      <div class="score" style="color:${scoreHexColor(agg.compositeScore)}">${agg.compositeScore}<span style="font-size:0.7rem;font-weight:400;color:var(--muted)">/100 ${scoreLabel(agg.compositeScore)}</span></div>
      ${metricBar('Tool Accuracy', agg.avgToolAccuracy)}
      ${metricBar('Output Quality', agg.avgOutputQuality)}
      ${metricBar('Protocol Compliance', agg.avgProtocolCompliance)}
      <div class="metric-row" style="margin-top:0.5rem"><span class="metric-label">Cost</span><span>${fmtCost(agg.totalCost)}</span></div>
      <div class="metric-row"><span class="metric-label">Avg Duration</span><span>${fmtDuration(agg.avgDuration)}</span></div>
    </div>`;
  }
  body += '</div>';

  body += abScenarioTable(scenarios, versionAggs, results);

  return wrapHtml(`A/B Report — ${personaName}`, body, {
    date: fmtDate(run.createdAt),
    mode: 'A/B',
    persona: personaName,
  });
}

// ── Eval report ───────────────────────────────────────────────────

function evalHtml(run: LabEvalRun, results: LabEvalResult[], personaName: string): string {
  const { versionAggs, winnerId } = buildEvalGridData(results);
  const gridCls = versionAggs.length <= 2 ? 'grid-2' : 'grid-3';

  let body = '<h2>Version Evaluation</h2>';
  body += `<div class="grid ${gridCls}">`;
  for (const agg of versionAggs) {
    const isWinner = agg.versionId === winnerId;
    body += `<div class="card">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:0.5rem">
        <strong>Version ${agg.versionNumber}</strong>
        ${isWinner ? '<span class="badge winner">Best</span>' : ''}
      </div>
      <div class="score" style="color:${scoreHexColor(agg.compositeScore)}">${agg.compositeScore}<span style="font-size:0.7rem;font-weight:400;color:var(--muted)">/100 ${scoreLabel(agg.compositeScore)}</span></div>
      ${metricBar('Tool Accuracy', agg.avgToolAccuracy)}
      ${metricBar('Output Quality', agg.avgOutputQuality)}
      ${metricBar('Protocol Compliance', agg.avgProtocolCompliance)}
      <div class="metric-row" style="margin-top:0.5rem"><span class="metric-label">Cost</span><span>${fmtCost(agg.totalCost)}</span></div>
      <div class="metric-row"><span class="metric-label">Avg Duration</span><span>${fmtDuration(agg.avgDuration)}</span></div>
    </div>`;
  }
  body += '</div>';

  body += evalScenarioTable(results, versionAggs);

  return wrapHtml(`Eval Report — ${personaName}`, body, {
    date: fmtDate(run.createdAt),
    mode: 'Evaluation',
    persona: personaName,
  });
}

// ── Matrix report ─────────────────────────────────────────────────

function matrixHtml(run: LabMatrixRun, results: LabMatrixResult[], personaName: string): string {
  const { variantAggs, scenarios } = aggregateMatrixResults(results);

  let body = '';
  if (run.draftChangeSummary) {
    body += `<h2>Requested Change</h2><div class="card"><p>${escHtml(run.draftChangeSummary)}</p></div>`;
  }

  body += '<h2>Current vs Draft</h2>';
  body += '<div class="grid grid-2">';
  for (const agg of variantAggs) {
    body += `<div class="card">
      <div style="margin-bottom:0.5rem"><strong>${agg.variant === 'current' ? 'Current' : 'Draft'}</strong></div>
      <div class="score" style="color:${scoreHexColor(agg.compositeScore)}">${agg.compositeScore}<span style="font-size:0.7rem;font-weight:400;color:var(--muted)">/100 ${scoreLabel(agg.compositeScore)}</span></div>
      ${metricBar('Tool Accuracy', agg.avgToolAccuracy)}
      ${metricBar('Output Quality', agg.avgOutputQuality)}
      ${metricBar('Protocol Compliance', agg.avgProtocolCompliance)}
      <div class="metric-row" style="margin-top:0.5rem"><span class="metric-label">Cost</span><span>${fmtCost(agg.totalCost)}</span></div>
      <div class="metric-row"><span class="metric-label">Avg Duration</span><span>${fmtDuration(agg.avgDuration)}</span></div>
    </div>`;
  }
  body += '</div>';

  body += matrixScenarioTable(scenarios, variantAggs, results);

  return wrapHtml(`Matrix Report — ${personaName}`, body, {
    date: fmtDate(run.createdAt),
    mode: 'Matrix',
    persona: personaName,
  });
}

// ── Scenario tables ───────────────────────────────────────────────

function scenarioTable(
  scenarios: string[],
  columnKeys: string[],
  results: LabArenaResult[],
  keyField: 'modelId',
): string {
  const matrix: Record<string, Record<string, LabArenaResult>> = {};
  for (const r of results) {
    if (!matrix[r.scenarioName]) matrix[r.scenarioName] = {};
    matrix[r.scenarioName]![r[keyField]] = r;
  }

  let html = '<h2>Scenario Breakdown</h2><table><thead><tr><th>Scenario</th>';
  for (const col of columnKeys) html += `<th>${escHtml(col)}</th>`;
  html += '</tr></thead><tbody>';

  for (const sc of scenarios) {
    html += `<tr><td>${escHtml(sc)}</td>`;
    for (const col of columnKeys) {
      const r = matrix[sc]?.[col];
      if (r) {
        const comp = compositeScore(r.toolAccuracyScore ?? 0, r.outputQualityScore ?? 0, r.protocolCompliance ?? 0);
        html += `<td style="color:${scoreHexColor(comp)};font-weight:600">${comp}</td>`;
      } else {
        html += '<td style="color:var(--muted)">--</td>';
      }
    }
    html += '</tr>';
  }
  html += '</tbody></table>';
  return html;
}

function abScenarioTable(
  scenarios: string[],
  versionAggs: Array<{ versionId: string; versionNumber: number }>,
  results: LabAbResult[],
): string {
  const matrix: Record<string, Record<string, LabAbResult[]>> = {};
  for (const r of results) {
    if (!matrix[r.scenarioName]) matrix[r.scenarioName] = {};
    if (!matrix[r.scenarioName]![r.versionId]) matrix[r.scenarioName]![r.versionId] = [];
    matrix[r.scenarioName]![r.versionId]!.push(r);
  }

  let html = '<h2>Scenario Breakdown</h2><table><thead><tr><th>Scenario</th>';
  for (const v of versionAggs) html += `<th>v${v.versionNumber}</th>`;
  html += '</tr></thead><tbody>';

  for (const sc of scenarios) {
    html += `<tr><td>${escHtml(sc)}</td>`;
    for (const v of versionAggs) {
      const arr = matrix[sc]?.[v.versionId];
      if (arr && arr.length > 0) {
        const avgComp = Math.round(arr.reduce((sum, r) => sum + compositeScore(r.toolAccuracyScore ?? 0, r.outputQualityScore ?? 0, r.protocolCompliance ?? 0), 0) / arr.length);
        html += `<td style="color:${scoreHexColor(avgComp)};font-weight:600">${avgComp}</td>`;
      } else {
        html += '<td style="color:var(--muted)">--</td>';
      }
    }
    html += '</tr>';
  }
  html += '</tbody></table>';
  return html;
}

function evalScenarioTable(
  results: LabEvalResult[],
  versionAggs: Array<{ versionId: string; versionNumber: number }>,
): string {
  const scenarioSet = new Set<string>();
  const matrix: Record<string, Record<string, LabEvalResult[]>> = {};
  for (const r of results) {
    scenarioSet.add(r.scenarioName);
    if (!matrix[r.scenarioName]) matrix[r.scenarioName] = {};
    if (!matrix[r.scenarioName]![r.versionId]) matrix[r.scenarioName]![r.versionId] = [];
    matrix[r.scenarioName]![r.versionId]!.push(r);
  }

  let html = '<h2>Scenario Breakdown</h2><table><thead><tr><th>Scenario</th>';
  for (const v of versionAggs) html += `<th>v${v.versionNumber}</th>`;
  html += '</tr></thead><tbody>';

  for (const sc of scenarioSet) {
    html += `<tr><td>${escHtml(sc)}</td>`;
    for (const v of versionAggs) {
      const arr = matrix[sc]?.[v.versionId];
      if (arr && arr.length > 0) {
        const avgComp = Math.round(arr.reduce((sum, r) => sum + compositeScore(r.toolAccuracyScore ?? 0, r.outputQualityScore ?? 0, r.protocolCompliance ?? 0), 0) / arr.length);
        html += `<td style="color:${scoreHexColor(avgComp)};font-weight:600">${avgComp}</td>`;
      } else {
        html += '<td style="color:var(--muted)">--</td>';
      }
    }
    html += '</tr>';
  }
  html += '</tbody></table>';
  return html;
}

function matrixScenarioTable(
  scenarios: string[],
  variantAggs: Array<{ variant: string }>,
  results: LabMatrixResult[],
): string {
  const matrix: Record<string, Record<string, LabMatrixResult[]>> = {};
  for (const r of results) {
    if (!matrix[r.scenarioName]) matrix[r.scenarioName] = {};
    if (!matrix[r.scenarioName]![r.variant]) matrix[r.scenarioName]![r.variant] = [];
    matrix[r.scenarioName]![r.variant]!.push(r);
  }

  let html = '<h2>Scenario Breakdown</h2><table><thead><tr><th>Scenario</th>';
  for (const v of variantAggs) html += `<th>${v.variant === 'current' ? 'Current' : 'Draft'}</th>`;
  html += '</tr></thead><tbody>';

  for (const sc of scenarios) {
    html += `<tr><td>${escHtml(sc)}</td>`;
    for (const v of variantAggs) {
      const arr = matrix[sc]?.[v.variant];
      if (arr && arr.length > 0) {
        const avgComp = Math.round(arr.reduce((sum, r) => sum + compositeScore(r.toolAccuracyScore ?? 0, r.outputQualityScore ?? 0, r.protocolCompliance ?? 0), 0) / arr.length);
        html += `<td style="color:${scoreHexColor(avgComp)};font-weight:600">${avgComp}</td>`;
      } else {
        html += '<td style="color:var(--muted)">--</td>';
      }
    }
    html += '</tr>';
  }
  html += '</tbody></table>';
  return html;
}

// ── Markdown generation ───────────────────────────────────────────

interface AggRow {
  label: string;
  compositeScore: number;
  avgToolAccuracy: number;
  avgOutputQuality: number;
  avgProtocolCompliance: number;
  totalCost: number;
  avgDuration: number;
}

function markdownSummary(title: string, rows: AggRow[], scenarios: string[]): string {
  let md = `# ${title}\n\n`;
  md += `| | Composite | Tool Acc. | Output Q. | Protocol | Cost | Avg Duration |\n`;
  md += `|---|:---:|:---:|:---:|:---:|---:|---:|\n`;
  for (const r of rows) {
    md += `| **${r.label}** | ${r.compositeScore} | ${r.avgToolAccuracy} | ${r.avgOutputQuality} | ${r.avgProtocolCompliance} | ${fmtCost(r.totalCost)} | ${fmtDuration(r.avgDuration)} |\n`;
  }
  md += `\n**Scenarios tested:** ${scenarios.length}\n`;
  return md;
}

// ── Public API ────────────────────────────────────────────────────

export type LabRunAny = LabArenaRun | LabAbRun | LabMatrixRun | LabEvalRun;
export type LabResultAny = LabArenaResult | LabAbResult | LabMatrixResult | LabEvalResult;
export type ReportMode = 'arena' | 'ab' | 'eval' | 'matrix';

export function generateHtmlReport(
  mode: ReportMode,
  run: LabRunAny,
  results: LabResultAny[],
  personaName: string,
): string {
  switch (mode) {
    case 'arena':
      return arenaHtml(run as LabArenaRun, results as LabArenaResult[], personaName);
    case 'ab':
      return abHtml(run as LabAbRun, results as LabAbResult[], personaName);
    case 'eval':
      return evalHtml(run as LabEvalRun, results as LabEvalResult[], personaName);
    case 'matrix':
      return matrixHtml(run as LabMatrixRun, results as LabMatrixResult[], personaName);
  }
}

export function generateMarkdownReport(
  mode: ReportMode,
  run: LabRunAny,
  results: LabResultAny[],
  personaName: string,
): string {
  switch (mode) {
    case 'arena': {
      const { aggregates, scenarios } = aggregateArenaResults(results as LabArenaResult[]);
      return markdownSummary(`Arena Report — ${personaName}`, aggregates.map((a) => ({ label: a.modelId, ...a })), scenarios);
    }
    case 'ab': {
      const { versionAggs, scenarios } = aggregateAbResults(results as LabAbResult[]);
      return markdownSummary(`A/B Report — ${personaName}`, versionAggs.map((a) => ({ label: `v${a.versionNumber}`, ...a })), scenarios);
    }
    case 'eval': {
      const { versionAggs } = buildEvalGridData(results as LabEvalResult[]);
      const scenarios = new Set((results as LabEvalResult[]).map((r) => r.scenarioName));
      return markdownSummary(`Eval Report — ${personaName}`, versionAggs.map((a) => ({ label: `v${a.versionNumber}`, ...a })), [...scenarios]);
    }
    case 'matrix': {
      const { variantAggs, scenarios } = aggregateMatrixResults(results as LabMatrixResult[]);
      const title = `Matrix Report — ${personaName}`;
      let md = markdownSummary(title, variantAggs.map((a) => ({ label: a.variant === 'current' ? 'Current' : 'Draft', ...a })), scenarios);
      if ((run as LabMatrixRun).draftChangeSummary) {
        md += `\n**Requested change:** ${(run as LabMatrixRun).draftChangeSummary}\n`;
      }
      return md;
    }
  }
}

export function downloadHtmlReport(html: string, filename: string): void {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
