/** Every literal prototype string for the "Sheet · Wild" layout, gathered so the
 *  consolidation pass can lift them into i18n in one move. No em dashes. */
export const COPY = {
  stock: "PSN 400 · DARKROOM",
  acts: {
    compose: "Brief",
    exposure: "Exposure",
    questions: "Questions",
    wiring: "Wiring",
    draft: "Draft",
    screening: "Screening",
    verdict: "Verdict",
    premiere: "Premiere",
    fogged: "Fogged",
  },
  compose: {
    eyebrow: "Scene 1 · The brief",
    hero: "What should this agent do?",
    placeholder: "Describe the job in plain words. Who it serves, what it watches, what it hands back.",
    launch: "Roll camera",
    context: "Reference notes",
    contextSet: "Notes attached",
    hint: "Enter rolls the camera · Shift+Enter for a new line · Alt+1-8 opens a frame",
  },
  wait: {
    eyebrow: "Scene 2 · Exposure",
    wiringEyebrow: "Scene 4 · Wiring",
    title: "The first exposure is one long take",
    wiringTitle: "Developing your answers into the draft",
    honest: "Nothing comes back until the model finishes its first pass. That usually takes 50 s to 2 min 35 s; the clock below is the real one.",
    over: "Past the usual window. Still running; the clock keeps counting.",
    slateAgent: "Agent",
    slateScene: "Scene",
    slateTake: "Take",
    slateTime: "Running",
    untitled: "Untitled agent",
    background: "You can leave this screen; the build keeps running.",
    lastLine: "Last from the model",
  },
  questions: {
    eyebrow: "Scene 3 · Questions",
    title: "The model needs you on a few frames",
    resume: "Step back in",
    of: (i: number, n: number) => `Question ${i} of ${n}`,
    free: "Or answer in your own words",
    send: "Send",
    keys: "Number keys pick an option · Enter sends · Esc steps back",
    sent: "Sent. Waiting for the next frame.",
  },
  draft: {
    eyebrow: "Scene 5 · Draft",
    namePh: "Name your agent",
    screen: "Screen it",
    refine: "Refine",
    complete: (n: number) => `${n}% developed`,
    prints: "Capabilities on this reel",
    openPrints: "Inspect the prints",
  },
  screening: {
    eyebrow: "Scene 6 · Screening",
    title: "Running the test reel",
    waiting: "Waiting for the first line from the test run",
  },
  verdict: {
    eyebrow: "Scene 6 · Verdict",
    passed: "PASSED",
    failed: "NOT PASSED",
    passedLine: "Every test on the reel came back clean.",
    failedLine: "The test reel came back with problems. Nothing has been promoted.",
    promote: "Promote",
    promoting: "Promoting",
    report: "Full report",
    simulate: "Simulate",
    reject: "Reject draft",
    anyway: "Promote with failing tests…",
    armTitle: "Ship a persona that did not pass?",
    armBody: "It will go live with the failures above. You can still fix it later, but runs may break until you do.",
    armKeep: "Keep it in the lab",
    armGo: "Promote anyway",
  },
  premiere: {
    marquee: "NOW SHOWING",
    starring: "Starring",
    open: "Open agent",
    ready: "Your agent is ready",
    fallbackTag: "A new persona, developed and tested.",
  },
  fogged: {
    eyebrow: "Build stopped",
    title: "The film was fogged",
    body: "The build did not finish. The error below is what came back.",
    retry: "Refine and retry",
    noRetry: "Start a new build from the agents list to try again.",
  },
  frame: {
    blank: "Unexposed",
    latent: "Developing",
    pending: "Needs you",
    unused: "Not used",
    fogged: "Fogged",
    you: "Set by you",
    ai: "Set by the model",
    capabilities: (n: number) => (n === 1 ? "1 capability" : `${n} capabilities`),
    manual: "Runs when you ask",
  },
  loupe: {
    back: "Back to the sheet",
    esc: "Esc",
    notSetYet: "Not set yet. The model decides this unless you do.",
    decidedInBuild: "The model decides this during the build. Open it again once the frame develops.",
    taskNote: "The brief in the centre frame is the task. Write it there; the model splits it into capabilities.",
    choose: "Choose",
    change: "Change",
    on: "On",
    off: "Off",
    perCapability: "By capability",
    nothingHere: "No capability uses this dimension.",
    notesTitle: "Reference notes",
    notesBody: "Paste anything the model should read before it designs: links, examples, rules, the voice you want.",
    notesPh: "Reference material for the build…",
    refineTitle: "Refine the draft",
    printsTitle: "The prints",
    printsBody: "Every capability on the reel. Remove or split any before you promote.",
  },
  rail: {
    idle: "Ready to roll",
    rec: "● Rec",
    hold: "■ Hold",
    window: "usual first take",
    you: "your time",
    model: "model time",
  },
} as const;
