import type { StateCreator } from "zustand";
import type { AgentStore } from "../../storeTypes";
import { reportError } from "../../storeTypes";
import { testDesignFeasibility } from "@/api/templates/design";
import { parseJsonOrDefault } from "@/lib/utils/parseJson";
import {
  computeHealthScore,
  makeIssueId,
  parseFeasibilityToHealthResult,
} from "@/features/agents/health/useHealthCheck";
import type { PersonaHealthCheck, AgentHealthDigest } from "@/features/agents/health/types";
import type { Persona } from "@/lib/bindings/Persona";
import type { DesignContextData } from "@/lib/types/frontendTypes";
import { silentCatch } from "@/lib/silentCatch";

// -- Staleness threshold ----------------------------------------------

/** Data older than 15 minutes is considered stale */
export const DIGEST_STALENESS_MS = 15 * 60 * 1000;

/** Check whether a ISO timestamp is older than the staleness threshold */
export function isTimestampStale(iso: string | null, thresholdMs = DIGEST_STALENESS_MS): boolean {
  if (!iso) return true;
  return Date.now() - new Date(iso).getTime() > thresholdMs;
}

// -- Slice interface --------------------------------------------------

export interface HealthCheckSlice {
  // State
  healthDigest: AgentHealthDigest | null;
  healthDigestRunning: boolean;
  lastDigestAt: string | null;

  // Actions
  runFullHealthDigest: () => Promise<AgentHealthDigest | null>;
  clearHealthDigest: () => void;
}

// -- Helpers ----------------------------------------------------------

/**
 * Per-persona digest check. Calls the shared
 * {@link parseFeasibilityToHealthResult} parser with `withProposals: false`
 * because the digest UI surfaces aggregate counts only — proposals are
 * generated by the per-persona hook on demand.
 *
 * Issue IDs come from the deterministic {@link makeIssueId} hash so
 * `markIssueResolved` from the per-persona panel matches identity even when
 * the same issue was first observed via the digest path. (Pre-W2.6 the slice
 * minted `digest_${Date.now()}_${seq++}` IDs that drifted between paths.)
 */
async function checkSinglePersona(persona: Persona): Promise<PersonaHealthCheck> {
  const ctx = persona.design_context
    ? parseJsonOrDefault<DesignContextData | null>(persona.design_context, null)
    : null;

  const designContext: DesignContextData = ctx ?? { summary: persona.description || persona.name };

  try {
    const raw = await testDesignFeasibility(JSON.stringify(designContext));

    // Digest path: skip proposal generation. Shared parser handles
    // shape-guarding the issue list (richer-than-string entries don't
    // become "[object Object]") and assigns deterministic IDs.
    const result = parseFeasibilityToHealthResult(raw, persona, [], { withProposals: false });

    return {
      personaId: persona.id,
      personaName: persona.name,
      personaIcon: persona.icon,
      personaColor: persona.color,
      result,
      checkedAt: new Date().toISOString(),
    };
  } catch (err) {
    // Per the policy doc in `useHealthCheck.ts`: an empty `catch {}` is never
    // acceptable here. A failed sub-check must not silently make the persona
    // vanish from the digest — the user would see "all healthy" while broken
    // agents are simply absent. Route the error through silentCatch for a
    // Sentry breadcrumb and return a partial-status check with an info-issue
    // explaining the gap, so the persona still appears in the digest with a
    // visible "score is incomplete" signal.
    silentCatch(`healthCheckSlice:checkSinglePersona[${persona.id}]`)(err);
    const errMsg = err instanceof Error ? err.message : String(err);
    const fallbackText = `Health sub-check did not run: ${errMsg}`;
    return {
      personaId: persona.id,
      personaName: persona.name,
      personaIcon: persona.icon,
      personaColor: persona.color,
      result: {
        status: 'partial',
        capabilities: [],
        issues: [
          {
            id: makeIssueId(persona.id, 'info', fallbackText),
            severity: 'info',
            description: fallbackText,
            proposal: null,
            resolved: false,
          },
        ],
      },
      checkedAt: new Date().toISOString(),
    };
  }
}

function aggregateDigest(checks: PersonaHealthCheck[]): AgentHealthDigest {
  let totalErrors = 0;
  let totalWarnings = 0;
  let totalInfos = 0;

  for (const check of checks) {
    for (const issue of check.result.issues) {
      if (issue.severity === 'error') totalErrors++;
      else if (issue.severity === 'warning') totalWarnings++;
      else totalInfos++;
    }
  }

  // Compute aggregate score from all issues across all personas
  const allIssues = checks.flatMap((c) => c.result.issues);
  const totalScore = computeHealthScore(allIssues);

  return {
    generatedAt: new Date().toISOString(),
    personas: checks,
    totalScore,
    totalIssues: totalErrors + totalWarnings + totalInfos,
    errorCount: totalErrors,
    warningCount: totalWarnings,
    infoCount: totalInfos,
  };
}

// -- Slice creator ----------------------------------------------------

export const createHealthCheckSlice: StateCreator<AgentStore, [], [], HealthCheckSlice> = (set, get) => ({
  healthDigest: null,
  healthDigestRunning: false,
  lastDigestAt: null,

  runFullHealthDigest: async () => {
    const { personas } = get();
    if (personas.length === 0) return null;

    set({ healthDigestRunning: true });

    try {
      // Run health checks on all personas in parallel (max 5 concurrent)
      const checks: PersonaHealthCheck[] = [];
      const batchSize = 5;

      for (let i = 0; i < personas.length; i += batchSize) {
        const batch = personas.slice(i, i + batchSize);
        const results = await Promise.allSettled(batch.map(checkSinglePersona));
        for (const r of results) {
          if (r.status === 'fulfilled' && r.value) {
            checks.push(r.value);
          }
        }
      }

      const digest = aggregateDigest(checks);
      set({ healthDigest: digest, healthDigestRunning: false, lastDigestAt: digest.generatedAt });
      return digest;
    } catch (err) {
      reportError(err, "Failed to run health digest", set, { stateUpdates: { healthDigestRunning: false } });
      return null;
    }
  },

  clearHealthDigest: () => set({ healthDigest: null }),
});
