import type {
  ResearchProject, ResearchSource, ResearchHypothesis,
  ResearchExperiment, ResearchFinding, ResearchReport,
} from '@/api/researchLab/researchLab';

export interface CompileArgs {
  report: ResearchReport;
  project: ResearchProject;
  sources: ResearchSource[];
  hypotheses: ResearchHypothesis[];
  experiments: ResearchExperiment[];
  findings: ResearchFinding[];
}

/** Entry point — routes to the right template based on reportType. */
export function compileReport(args: CompileArgs): string {
  switch (args.report.reportType) {
    case 'literature_review': return compileLiteratureReview(args);
    case 'experiment_report': return compileExperimentReport(args);
    case 'full_paper': return compileFullPaper(args);
    case 'executive_summary': return compileExecutiveSummary(args);
    default: return compileDefault(args);
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function citationKey(s: ResearchSource): string {
  const firstAuthor = (s.authors ?? 'Anon').split(/[,&]/)[0]?.trim().split(/\s+/).pop() ?? 'Anon';
  return `${firstAuthor}${s.year ?? ''}`;
}

function renderSourceList(sources: ResearchSource[]): string {
  if (sources.length === 0) return '_No sources linked._\n';
  const byYear = new Map<string, ResearchSource[]>();
  sources.forEach((s) => {
    const year = s.year?.toString() ?? 'Undated';
    const list = byYear.get(year) ?? [];
    list.push(s);
    byYear.set(year, list);
  });
  const years = [...byYear.keys()].sort((a, b) => (a < b ? 1 : -1));
  return years.map((year) => {
    const list = byYear.get(year)!;
    const entries = list.map((s) => {
      const authors = s.authors ? `${s.authors}` : 'Anon.';
      const link = s.url ? ` — [${s.sourceType}](${s.url})` : '';
      const doi = s.doi ? ` · doi:${s.doi}` : '';
      return `- **${s.title}**  \n  ${authors} (${year})${link}${doi}`;
    }).join('\n');
    return `### ${year}\n\n${entries}\n`;
  }).join('\n');
}

function renderHypothesesList(hypotheses: ResearchHypothesis[]): string {
  if (hypotheses.length === 0) return '_No hypotheses yet._\n';
  return hypotheses.map((h, i) => {
    const conf = Math.round(h.confidence * 100);
    const rationale = h.rationale ? `\n  > ${h.rationale.replace(/\n/g, '\n  > ')}` : '';
    return `${i + 1}. **${h.statement}** _(confidence ${conf}%)_${rationale}`;
  }).join('\n');
}

function renderExperimentsList(experiments: ResearchExperiment[], hypotheses: ResearchHypothesis[]): string {
  if (experiments.length === 0) return '_No experiments yet._\n';
  const hMap = Object.fromEntries(hypotheses.map((h) => [h.id, h]));
  return experiments.map((e) => {
    const linked = e.hypothesisId ? hMap[e.hypothesisId] : null;
    const parts: string[] = [`#### ${e.name}`];
    parts.push(`_Status: ${e.status}_`);
    if (linked) parts.push(`**Tests:** ${linked.statement}`);
    if (e.methodology) parts.push(`**Methodology:**\n\n${e.methodology}`);
    if (e.successCriteria) parts.push(`**Success criteria:**\n\n${e.successCriteria}`);
    return parts.join('\n\n');
  }).join('\n\n---\n\n');
}

function renderFindingsList(findings: ResearchFinding[]): string {
  if (findings.length === 0) return '_No findings recorded._\n';
  return findings.map((f) => {
    const parts: string[] = [`### ${f.title}`];
    if (f.category) parts.push(`_${f.category}_`);
    parts.push(`**Confidence:** ${Math.round(f.confidence * 100)}%`);
    if (f.description) parts.push(f.description);
    if (f.generatedBy) parts.push(`\\- _Generated by ${f.generatedBy}_`);
    return parts.join('\n\n');
  }).join('\n\n---\n\n');
}

function header(report: ResearchReport, project: ResearchProject): string {
  const lines = [
    `# ${report.title}`,
    '',
    `_${project.name}${project.domain ? ` · ${project.domain}` : ''}_`,
    '',
    `> Generated ${new Date().toISOString().slice(0, 10)} · format: ${report.format ?? 'markdown'}`,
    '',
  ];
  if (project.thesis) {
    lines.push('## Thesis', '', `> ${project.thesis.replace(/\n/g, '\n> ')}`, '');
  }
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Templates
// ---------------------------------------------------------------------------

function compileLiteratureReview({ report, project, sources }: CompileArgs): string {
  const indexed = sources.filter((s) => s.status === 'indexed');
  const pending = sources.filter((s) => s.status !== 'indexed');
  return [
    header(report, project),
    '## Overview',
    '',
    `This review aggregates ${sources.length} source${sources.length === 1 ? '' : 's'} (${indexed.length} indexed) collected for **${project.name}**.`,
    '',
    '## Indexed Sources',
    '',
    renderSourceList(indexed),
    indexed.length === 0 ? '' : '',
    '## Pending Sources',
    '',
    pending.length === 0 ? '_All sources are indexed._\n' : renderSourceList(pending),
  ].join('\n');
}

function compileExperimentReport({ report, project, experiments, hypotheses, findings }: CompileArgs): string {
  return [
    header(report, project),
    '## Hypotheses under Test',
    '',
    renderHypothesesList(hypotheses),
    '',
    '## Experiments',
    '',
    renderExperimentsList(experiments, hypotheses),
    '',
    '## Findings',
    '',
    renderFindingsList(findings),
  ].join('\n');
}

function compileFullPaper(args: CompileArgs): string {
  const { report, project, sources, hypotheses, experiments, findings } = args;
  const refs = sources
    .slice()
    .sort((a, b) => citationKey(a).localeCompare(citationKey(b)))
    .map((s) => `- [${citationKey(s)}] **${s.title}** — ${s.authors ?? 'Anon.'} (${s.year ?? 'n.d.'}).${s.url ? ` <${s.url}>` : ''}${s.doi ? ` doi:${s.doi}` : ''}`)
    .join('\n');

  return [
    header(report, project),
    '## 1. Introduction',
    '',
    project.description ?? '_No description set for this project._',
    '',
    `This paper investigates the following question: ${project.thesis ?? '_thesis not specified_'}.`,
    '',
    '## 2. Related Work',
    '',
    renderSourceList(sources),
    '',
    '## 3. Methodology',
    '',
    renderHypothesesList(hypotheses),
    '',
    renderExperimentsList(experiments, hypotheses),
    '',
    '## 4. Results',
    '',
    renderFindingsList(findings),
    '',
    '## 5. Discussion',
    '',
    '_To be authored._',
    '',
    '## References',
    '',
    refs.length > 0 ? refs : '_No references._',
  ].join('\n');
}

function compileExecutiveSummary(args: CompileArgs): string {
  const { report, project, sources, hypotheses, experiments, findings } = args;
  const topFindings = [...findings].sort((a, b) => b.confidence - a.confidence).slice(0, 5);
  return [
    header(report, project),
    '## Snapshot',
    '',
    `| Metric | Value |`,
    `|---|---|`,
    `| Sources | ${sources.length} (${sources.filter(s => s.status === 'indexed').length} indexed) |`,
    `| Hypotheses | ${hypotheses.length} |`,
    `| Experiments | ${experiments.length} |`,
    `| Findings | ${findings.length} |`,
    '',
    '## Top Findings',
    '',
    topFindings.length > 0
      ? topFindings.map((f, i) => `${i + 1}. **${f.title}** — ${Math.round(f.confidence * 100)}% confidence${f.category ? ` _(${f.category})_` : ''}`).join('\n')
      : '_No findings recorded._',
    '',
    '## Open Questions',
    '',
    hypotheses.length > 0
      ? hypotheses.slice(0, 5).map((h) => `- ${h.statement}`).join('\n')
      : '_No hypotheses recorded._',
  ].join('\n');
}

function compileDefault(args: CompileArgs): string {
  return compileFullPaper(args);
}
