/**
 * FleetOptimizationCard
 *
 * Displays the single highest-priority optimization recommendation
 * generated by the fleet optimizer. Shown on DashboardHome between
 * Memory Actions and the main content grid.
 */

import { useMemo, useState } from 'react';
import {
  Sparkles,
  TrendingDown,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Zap,
  DollarSign,
  Search,
} from 'lucide-react';
import { useOverviewStore } from "@/stores/overviewStore";
import {
  generateFleetRecommendation,
  type FleetRecommendation,
  type RecommendationType,
} from '@/lib/fleet/fleetOptimizer';

// -- Icon/style mapping ----------------------------------------------

const TYPE_CONFIG: Record<RecommendationType, {
  icon: typeof Sparkles;
  accent: string;
  bg: string;
  border: string;
  badge: string;
}> = {
  downgrade_model: {
    icon: TrendingDown,
    accent: 'text-cyan-400',
    bg: 'bg-cyan-500/8',
    border: 'border-cyan-500/15',
    badge: 'bg-cyan-500/10 text-cyan-300 border-cyan-500/20',
  },
  reduce_retries: {
    icon: Zap,
    accent: 'text-amber-400',
    bg: 'bg-amber-500/8',
    border: 'border-amber-500/15',
    badge: 'bg-amber-500/10 text-amber-300 border-amber-500/20',
  },
  investigate_failures: {
    icon: Search,
    accent: 'text-rose-400',
    bg: 'bg-rose-500/8',
    border: 'border-rose-500/15',
    badge: 'bg-rose-500/10 text-rose-300 border-rose-500/20',
  },
  consolidate_personas: {
    icon: Sparkles,
    accent: 'text-violet-400',
    bg: 'bg-violet-500/8',
    border: 'border-violet-500/15',
    badge: 'bg-violet-500/10 text-violet-300 border-violet-500/20',
  },
  cost_anomaly: {
    icon: DollarSign,
    accent: 'text-red-400',
    bg: 'bg-red-500/8',
    border: 'border-red-500/15',
    badge: 'bg-red-500/10 text-red-300 border-red-500/20',
  },
  healthy_fleet: {
    icon: CheckCircle2,
    accent: 'text-emerald-400',
    bg: 'bg-emerald-500/8',
    border: 'border-emerald-500/15',
    badge: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20',
  },
};

const SEVERITY_LABEL: Record<string, string> = {
  critical: 'Urgent',
  warning: 'Suggested',
  info: 'Insight',
};

// -- Component -------------------------------------------------------

function RecommendationContent({ rec }: { rec: FleetRecommendation }) {
  const [expanded, setExpanded] = useState(false);
  const config = TYPE_CONFIG[rec.type];
  const Icon = config.icon;

  return (
    <div
      className={`animate-fade-slide-in rounded-xl border ${config.border} ${config.bg} overflow-hidden`}
    >
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-white/[0.02] transition-colors"
      >
        <div className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 ${config.badge} border`}>
          <Icon className="w-4 h-4" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <span className="typo-heading text-foreground/90">
              {rec.title}
            </span>
            <span className={`text-[10px] font-bold uppercase tracking-widest px-1.5 py-0.5 rounded-md ${config.badge} border`}>
              {SEVERITY_LABEL[rec.severity] ?? rec.severity}
            </span>
          </div>
          <p className="typo-body text-muted-foreground/80 mt-0.5 truncate">
            {rec.description}
          </p>
        </div>
        <div className="flex-shrink-0 text-muted-foreground/50">
          {expanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
        </div>
      </button>

      {expanded && (
          <div
            className="animate-fade-slide-in overflow-hidden"
          >
            <div className="px-4 pb-3 pt-1 border-t border-primary/5 space-y-2.5">
              {/* Impact */}
              <div className="flex items-start gap-2">
                <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground/60 mt-0.5 w-16 flex-shrink-0">
                  Impact
                </span>
                <span className="typo-body text-foreground/80">{rec.impact}</span>
              </div>

              {/* Action */}
              <div className="flex items-start gap-2">
                <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground/60 mt-0.5 w-16 flex-shrink-0">
                  Action
                </span>
                <span className="typo-body text-foreground/80">{rec.suggestedAction}</span>
              </div>

              {/* Affected agents */}
              {rec.personaNames.length > 0 && (
                <div className="flex items-start gap-2">
                  <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground/60 mt-0.5 w-16 flex-shrink-0">
                    Agent
                  </span>
                  <span className="typo-body text-foreground/80">
                    {rec.personaNames.join(', ')}
                  </span>
                </div>
              )}
            </div>
          </div>
        )}
    </div>
  );
}

export default function FleetOptimizationCard() {
  const executionDashboard = useOverviewStore((s) => s.executionDashboard);
  const healingIssues = useOverviewStore((s) => s.healingIssues);

  const recommendation = useMemo(
    () => generateFleetRecommendation(executionDashboard, healingIssues),
    [executionDashboard, healingIssues],
  );

  // Don't render anything if there's no recommendation or not enough data
  if (!recommendation) return null;

  // Don't show the "healthy fleet" card if there are very few executions
  if (recommendation.type === 'healthy_fleet' && (executionDashboard?.total_executions ?? 0) < 10) {
    return null;
  }

  return (
    <div className="space-y-1.5">
      <h3 className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground/60 px-1 flex items-center gap-1.5">
        <Sparkles className="w-3 h-3" />
        Fleet Optimization
      </h3>
      <RecommendationContent rec={recommendation} />
    </div>
  );
}
