#!/usr/bin/env node
/**
 * SVG → animatable data module for motionize. Parses a traced SVG's <path>s and
 * emits a TS array of `{ d, fill, delay }` the component maps over — so a
 * many-path trace becomes an orchestrated, per-element reveal without
 * hand-classifying paths.
 *
 * Handles the trace gotchas automatically:
 *  - drops the full-canvas background path,
 *  - recolors interior near-white "negative space" paths to `var(--background)`
 *    (so links/holes read as thin lines, not solid),
 *  - assigns each path a `delay` (0..1) from its distance to the canvas centre —
 *    the reveal radiates center-out (hub → links → figures → outer accents).
 *
 * Usage:
 *   node emit-glyph.mjs --input traced.svg --output data.ts --name NETWORK_GLYPH [--order radial|angular]
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, resolve } from "path";

function parseArgs(argv) {
  const a = {};
  for (let i = 2; i < argv.length; i++) {
    if (argv[i].startsWith("--")) { const k = argv[i].slice(2), n = argv[i + 1]; if (n && !n.startsWith("--")) { a[k] = n; i++; } else a[k] = true; }
  }
  return a;
}
const nearWhite = (hex) => {
  const m = /^#([0-9a-f]{6})$/i.exec(hex); if (!m) return false;
  const n = parseInt(m[1], 16), r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
  return r >= 240 && g >= 240 && b >= 240;
};
// rough bbox from all numbers in a path (exact enough to spot the full-canvas rect)
function roughBox(d) {
  const nums = (d.match(/-?\d*\.?\d+/g) || []).map(Number);
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  for (let i = 0; i + 1 < nums.length; i += 2) {
    minX = Math.min(minX, nums[i]); maxX = Math.max(maxX, nums[i]);
    minY = Math.min(minY, nums[i + 1]); maxY = Math.max(maxY, nums[i + 1]);
  }
  return { minX, maxX, minY, maxY };
}
// accurate-ish anchor: the first absolute M coordinate (element position)
function anchor(d) {
  const m = /M\s*(-?\d*\.?\d+)[ ,]+(-?\d*\.?\d+)/.exec(d);
  return m ? { x: +m[1], y: +m[2] } : { x: 512, y: 512 };
}

function main() {
  const args = parseArgs(process.argv);
  if (!args.input || !args.output || !args.name) { console.error("Usage: --input svg --output data.ts --name NAME"); process.exit(1); }
  const svg = readFileSync(args.input, "utf8");
  const vb = /viewBox="([^"]+)"/.exec(svg);
  const wh = /width="(\d+)"\s+height="(\d+)"/.exec(svg);
  const [W, H] = vb ? vb[1].split(/\s+/).slice(2).map(Number) : wh ? [+wh[1], +wh[2]] : [1024, 1024];
  const cx = W / 2, cy = H / 2, maxR = Math.hypot(cx, cy);

  const paths = [...svg.matchAll(/<path\s+fill="(#[0-9A-Fa-f]+)"\s+d="([^"]+)"\s*\/>/g)].map((m) => ({ fill: m[1], d: m[2] }));

  // Paint order (z-order) is PRESERVED — VTracer stacks fills over outlines, so
  // reordering hides colored fills behind navy. `delay` drives timing only.
  const canvasArea = W * H;
  const out = [];
  for (const p of paths) {
    const box = roughBox(p.d);
    const coversCanvas = box.minX <= 2 && box.minY <= 2 && box.maxX >= W - 2 && box.maxY >= H - 2;
    if (nearWhite(p.fill) && coversCanvas) continue; // drop full-canvas bg
    // Only LARGE near-white regions are background negative-space → recolor to the
    // surface. Small near-white paths are FOREGROUND details (sparks, highlights)
    // — keep them light.
    const areaFrac = ((box.maxX - box.minX) * (box.maxY - box.minY)) / canvasArea;
    const fill = nearWhite(p.fill) && areaFrac > 0.1 ? "var(--background)" : p.fill;
    const a = anchor(p.d);
    const dist = Math.hypot(a.x - cx, a.y - cy) / maxR; // 0 (center) .. 1 (corner)
    const ang = (Math.atan2(a.y - cy, a.x - cx) + Math.PI) / (2 * Math.PI); // 0..1 clockwise
    out.push({ d: p.d, fill, delay: Number((args.order === "angular" ? ang : dist).toFixed(3)) });
  }

  const body = `// AUTO-GENERATED by .claude/skills/motionize/tools/emit-glyph.mjs — do not edit by hand.
// Regenerate: node .claude/skills/motionize/tools/emit-glyph.mjs --input <svg> --output <this> --name ${args.name}
export const ${args.name}_VIEWBOX = "0 0 ${W} ${H}";
export const ${args.name}: { d: string; fill: string; delay: number }[] = ${JSON.stringify(out, null, 0)};
`;
  const abs = resolve(args.output);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, body);
  console.log(JSON.stringify({ success: true, output: abs, elements: out.length, dropped: paths.length - out.length }, null, 2));
}
main();
