#!/usr/bin/env node
/**
 * Batch tracer for an ICON SET → one keyed TS map. Traces every `<key>-flat.png`
 * (or `<key>.png`) in a directory and emits
 *   export const <NAME>: Record<string, { viewBox: string; data: {d,fill,delay}[] }>
 * so a component can look a glyph up by key (e.g. archetype id) and render it with
 * MotionizedGlyph. Same trace + emit-glyph gotcha handling as trace.mjs.
 *
 * Usage:
 *   node trace-set.mjs --input-dir out/archetypes --output src/.../archetypeGlyphData.ts \
 *     --name ARCHETYPE_GLYPHS [--color-precision 4] [--filter-speckle 6] [--white-keep 0.1] [--order radial]
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "fs";
import { dirname, resolve, join, basename } from "path";
import { vectorize, ColorMode, Hierarchical, PathSimplifyMode } from "@neplex/vectorizer";
import { optimize } from "svgo";
import { svgToGlyphData } from "./emit-glyph.mjs";

function parseArgs(argv) {
  const a = {};
  for (let i = 2; i < argv.length; i++) {
    if (argv[i].startsWith("--")) { const k = argv[i].slice(2), n = argv[i + 1]; if (n && !n.startsWith("--")) { a[k] = n; i++; } else a[k] = true; }
  }
  return a;
}
const MODE = { spline: PathSimplifyMode.Spline, polygon: PathSimplifyMode.Polygon, pixel: PathSimplifyMode.None };

async function traceOne(buf, args) {
  const config = {
    colorMode: ColorMode.Color,
    colorPrecision: Number(args["color-precision"] ?? 4),
    filterSpeckle: Number(args["filter-speckle"] ?? 6),
    spliceThreshold: 45,
    cornerThreshold: 60,
    hierarchical: Hierarchical.Stacked,
    mode: MODE[args.mode || "spline"] ?? PathSimplifyMode.Spline,
    layerDifference: 5,
    lengthThreshold: Number(args["length-threshold"] ?? 6),
    maxIterations: 10,
    pathPrecision: 5,
  };
  let svg = await vectorize(buf, config);
  svg = optimize(svg, { multipass: true, plugins: [{ name: "preset-default", params: { overrides: { removeViewBox: false } } }] }).data;
  return svg;
}

async function main() {
  const args = parseArgs(process.argv);
  if (!args["input-dir"] || !args.output || !args.name) { console.error("Usage: --input-dir <dir> --output data.ts --name NAME"); process.exit(1); }
  const dir = resolve(args["input-dir"]);
  const files = readdirSync(dir).filter((f) => /\.(png|jpg|jpeg|webp)$/i.test(f)).sort();

  const entries = [];
  for (const f of files) {
    const key = basename(f).replace(/\.(png|jpg|jpeg|webp)$/i, "").replace(/-flat$/, "");
    const svg = await traceOne(readFileSync(join(dir, f)), args);
    // Reuse the same core → { viewBox, data }; strip the module wrapper, keep the array.
    const { ts, elements } = svgToGlyphData(svg, { name: "_TMP", order: args.order, whiteKeep: args["white-keep"] ? Number(args["white-keep"]) : undefined });
    const viewBox = /_TMP_VIEWBOX = "([^"]+)"/.exec(ts)[1];
    const data = /_TMP: [^=]+= (\[.*\]);/s.exec(ts)[1];
    entries.push({ key, viewBox, data, elements });
    process.stderr.write(`  ${key}: ${elements} paths\n`);
  }

  const body = `// AUTO-GENERATED by .claude/skills/motionize/tools/trace-set.mjs — do not edit by hand.
export const ${args.name}: Record<string, { viewBox: string; data: { d: string; fill: string; delay: number }[] }> = {
${entries.map((e) => `  ${JSON.stringify(e.key)}: { viewBox: ${JSON.stringify(e.viewBox)}, data: ${e.data} },`).join("\n")}
};
`;
  const abs = resolve(args.output);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, body);
  console.log(JSON.stringify({ success: true, output: abs, glyphs: entries.length, keys: entries.map((e) => e.key) }, null, 2));
}
main().catch((e) => { console.error(JSON.stringify({ error: String(e?.message || e) }, null, 2)); process.exit(1); });
