//! IPC handler shard 4 — see `super` (`ipc_shards/mod.rs`) for why the list is split
//! and how to add a command.

use super::Shard;
#[allow(unused_imports)] // not every shard names every root module
use crate::{cloud, commands, notifications, test_automation};

pub(super) fn shard(
) -> Shard<impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static> {
    personas_macros::ipc_shard!(tauri::generate_handler![
        // Drive -- managed local filesystem plugin
        commands::drive::drive_get_root,
        commands::drive::drive_storage_info,
        commands::drive::drive_list,
        commands::drive::drive_list_tree,
        commands::drive::drive_search,
        commands::drive::drive_recent,
        commands::drive::drive_stat,
        commands::drive::drive_read,
        commands::drive::drive_read_text,
        commands::drive::drive_write,
        commands::drive::drive_write_text,
        commands::drive::drive_mkdir,
        commands::drive::drive_delete,
        commands::drive::drive_rename,
        commands::drive::drive_move,
        commands::drive::drive_copy,
        commands::drive::drive_open_in_os,
        commands::drive::drive_reveal_in_os,
        // Drive (Finder variant) -- thumbnails, tag index, transfers
        commands::drive::thumbs::drive_thumbnail,
        commands::drive::meta::drive_meta_get,
        commands::drive::meta::drive_tags_set,
        commands::drive::meta::drive_tag_upsert,
        commands::drive::meta::drive_tag_delete,
        commands::drive::meta::drive_tagged,
        commands::drive::transfer::drive_duplicate,
        commands::drive::transfer::drive_import_paths,
        commands::drive::transfer::drive_export_to,
        commands::drive::transfer::drive_abs_paths,
        // Live Roadmap -- runtime-fetched roadmap content
        commands::live_roadmap::fetch_roadmap,
        // Eval / Certification -- read-only viewer over docs/test/runs bundles (dev-only UI)
        commands::eval_runs::list_eval_runs,
        commands::eval_runs::get_cert_status,
        commands::eval_runs::get_eval_run,
        // Obsidian Brain -- Second Brain Sync
        commands::obsidian_brain::obsidian_brain_detect_vaults,
        commands::obsidian_brain::obsidian_brain_test_connection,
        commands::obsidian_brain::obsidian_brain_save_config,
        commands::obsidian_brain::obsidian_brain_get_config,
        commands::obsidian_brain::obsidian_brain_list_saved_vaults,
        commands::obsidian_brain::obsidian_brain_set_saved_vaults,
        commands::obsidian_brain::obsidian_mirror_get_config,
        commands::obsidian_brain::obsidian_mirror_set_config,
        commands::obsidian_brain::obsidian_available,
        commands::obsidian_brain::obsidian_mirror_backfill_execution_knowledge,
        commands::obsidian_brain::obsidian_brain_push_sync,
        commands::obsidian_brain::obsidian_brain_get_sync_log,
        commands::obsidian_brain::obsidian_brain_pull_sync,
        commands::obsidian_brain::obsidian_brain_resolve_conflict,
        commands::obsidian_brain::obsidian_brain_list_vault_files,
        commands::obsidian_brain::obsidian_brain_read_vault_note,
        commands::obsidian_brain::obsidian_brain_push_goals,
        commands::obsidian_brain::obsidian_brain_lint_vault,
        commands::obsidian_brain::obsidian_drive_status,
        commands::obsidian_brain::obsidian_drive_push_sync,
        commands::obsidian_brain::obsidian_drive_pull_sync,
        // Obsidian Brain — Revitalize (background vault memory optimization)
        commands::obsidian_brain::revitalize::obsidian_revitalize_start,
        commands::obsidian_brain::revitalize::obsidian_revitalize_snapshot,
        commands::obsidian_brain::revitalize::obsidian_revitalize_active,
        commands::obsidian_brain::revitalize::obsidian_revitalize_cancel,
        commands::obsidian_brain::revitalize::obsidian_revitalize_history,
        // Obsidian Brain — Graph (Obsidian Memory connector)
        commands::obsidian_brain::graph::obsidian_graph_search,
        commands::obsidian_brain::graph::obsidian_graph_outgoing_links,
        commands::obsidian_brain::graph::obsidian_graph_backlinks,
        commands::obsidian_brain::graph::obsidian_graph_list_orphans,
        commands::obsidian_brain::graph::obsidian_graph_list_mocs,
        commands::obsidian_brain::graph::obsidian_graph_stats,
        commands::obsidian_brain::graph::obsidian_graph_append_daily_note,
        commands::obsidian_brain::graph::obsidian_graph_write_meeting_note,
        commands::obsidian_brain::graph::obsidian_graph_start_watcher,
        commands::obsidian_brain::graph::obsidian_graph_stop_watcher,
        // Companion (Athena)
        commands::companion::companion_init,
        commands::companion::companion_reingest_doctrine,
        commands::companion::tours::companion_compose_tour,
        commands::companion::tours::companion_list_composed_tours,
        commands::companion::chat::companion_send_message,
        commands::companion::chat::companion_list_recent_messages,
        commands::companion::chat::companion_reset_conversation,
        commands::companion::conversation::companion_list_conversations,
        commands::companion::conversation::companion_create_conversation,
        commands::companion::conversation::companion_rename_conversation,
        commands::companion::conversation::companion_archive_conversation,
        commands::companion::conversation::companion_mark_conversation_read,
        commands::companion::chat::companion_interrupt_turn,
        commands::companion::engine::companion_get_engine_settings,
        commands::companion::engine::companion_set_engine_settings,
        commands::companion::engine::companion_probe_engines,
        commands::companion::chat::companion_cancel_autonomy,
        commands::companion::chat::companion_set_autonomous_mode,
        commands::companion::chat::companion_set_dev_mode,
        commands::companion::chat::companion_dev_op_ledger,
        commands::companion::dev_review::companion_dev_op_self_review,
        commands::companion::chat::companion_dev_op_set_verdict,
        commands::companion::chat::companion_set_fleet_boldness,
        commands::companion::chat::companion_get_fleet_boldness,
        commands::companion::chat::companion_wake_stats,
        commands::companion::canvas_control::companion_canvas_control_result,
        commands::companion::fleet_bridge::companion_record_fleet_event,
        commands::companion::fleet_bridge::companion_get_operative_memory_digest,
        commands::companion::mcp_bridge::companion_mcp_resolve_request,
        commands::companion::mcp_bridge::companion_mcp_pending_snapshot,
        #[cfg(feature = "test-automation")]
        commands::companion::mcp_bridge::companion_test_fleet_dispatch,
        #[cfg(feature = "test-automation")]
        commands::companion::approvals::companion_list_pending_approvals,
        commands::companion::backlog_triage::dev_tools_athena_triage_batch,
        commands::companion::backlog_triage::dev_tools_apply_triage_verdicts,
        commands::companion::approvals::companion_approve_action,
        commands::companion::approvals::companion_reject_action,
        commands::companion::approvals::companion_analyze_fleet,
        commands::companion::approvals::companion_dispatch_fleet_plan,
        commands::companion::approvals::companion_create_ship_milestone,
        commands::companion::approvals::companion_create_ship_goals,
        commands::companion::approvals::companion_daily_brief,
        commands::companion::browser_test::browser_bridge_status,
        commands::companion::browser_test::browser_bridge_regenerate_token,
        commands::companion::browser_test::companion_file_browser_defects,
        commands::companion::brain::companion_list_brain_items,
        commands::companion::brain::companion_count_brain_items,
        commands::companion::brain::companion_get_brain_item,
        commands::companion::brain::companion_delete_brain_item,
        commands::companion::brain::companion_reconcile_episodes,
        commands::companion::brain::companion_save_identity,
        commands::companion::brain::companion_correct_identity_claim,
        commands::companion::brain::companion_reembed_missing,
        commands::companion::brain::companion_brain_health,
        commands::companion::feedback::companion_beta_flags,
        commands::companion::feedback::companion_record_ux_signal,
        #[cfg(debug_assertions)]
        commands::companion::debug_export::companion_export_conversation_log,
        commands::companion::daily_goals::companion_daily_goals_state,
        commands::companion::daily_goals::companion_daily_goals_create,
        commands::companion::daily_goals::companion_daily_goals_update,
        commands::companion::daily_goals::companion_daily_goals_toggle,
        commands::companion::daily_goals::companion_daily_goals_discard,
        commands::companion::chat::companion_list_messages_before,
        commands::companion::chat_cards::companion_list_chat_cards,
        commands::companion::chat_cards::companion_resolve_chat_card,
        commands::companion::sidecars::companion_save_turn_sidecar,
        commands::companion::sidecars::companion_get_turn_sidecars,
        commands::companion::voice::companion_tts,
        commands::companion::voice::companion_tts_list_kokoro_voices,
        commands::companion::voice::companion_tts_kokoro_status,
        commands::companion::voice::companion_tts_kokoro_download,
        commands::companion::voice::companion_tts_pocket_status,
        commands::companion::voice::companion_tts_list_pocket_voices,
        commands::companion::voice::companion_tts_pocket_download,
        commands::companion::voice::companion_tts_pocket_import_voice,
        commands::companion::voice::companion_tts_pocket_delete_voice,
        commands::companion::stt::companion_stt_transcribe,
        commands::companion::stt::companion_stt_list_models,
        commands::companion::stt::companion_stt_download_model,
        commands::companion::stt::companion_stt_delete_model,
        commands::companion::stt::companion_stt_engine_status,
        #[cfg(feature = "desktop")]
        commands::companion::voice_hotkey::companion_set_voice_hotkey,
        commands::companion::stt::companion_stt_install_engine,
        commands::companion::consolidate::companion_run_consolidation,
        commands::companion::consolidate::companion_list_consolidation_runs,
        commands::companion::consolidate::companion_list_cycle_reports,
        commands::companion::consolidate::companion_run_sleep_cycle,
        commands::companion::consolidate::companion_get_sleep_pressure,
        commands::companion::consolidate::companion_get_consolidation_items,
        commands::companion::consolidate::companion_apply_consolidation_item,
        commands::companion::consolidate::companion_reject_consolidation_item,
        commands::companion::consolidate::companion_decay_unused_facts,
        commands::companion::consolidate::companion_run_reflection,
        commands::companion::consolidate::companion_list_reflections,
        commands::companion::consolidate::companion_get_reflection,
        commands::companion::consolidate::companion_get_dashboard,
        commands::companion::consolidate::companion_get_cockpit,
        commands::companion::briefing::companion_compose_briefing,
        commands::companion::briefing::companion_record_briefing_action,
        commands::companion::consolidate::companion_pin_widget_to_cockpit,
        commands::companion::consolidate::companion_unpin_widget_from_cockpit,
        commands::companion::observability::companion_get_usage_dashboard,
        commands::companion::observability::companion_get_health,
        commands::companion::observability::companion_get_adaptations,
        commands::companion::observability::companion_prompt_block_stats,
        commands::companion::observability::companion_get_prompt_churn,
        commands::companion::observability::companion_get_spend_rollup,
        commands::companion::proactive::companion_evaluate_proactive_now,
        commands::companion::proactive::companion_list_proactive_messages,
        commands::companion::proactive::companion_engage_proactive,
        commands::companion::proactive::companion_dismiss_proactive,
        #[cfg(feature = "desktop")]
        commands::companion::sensory::companion_get_sensory_state,
        #[cfg(feature = "desktop")]
        commands::companion::sensory::companion_set_sensory_source_enabled,
        #[cfg(feature = "desktop")]
        commands::companion::sensory::companion_purge_sensory_source,
        #[cfg(feature = "desktop")]
        commands::companion::sensory::companion_list_sensory_signals,
        #[cfg(feature = "desktop")]
        commands::companion::sensory::companion_delete_sensory_signal,
        #[cfg(feature = "desktop")]
        commands::companion::sensory::companion_list_cli_session_reads,
        commands::companion::connectors::companion_list_active_connectors,
        commands::companion::connectors::companion_set_active_connectors,
        commands::companion::connectors::companion_set_connector_enabled,
        commands::companion::connectors::companion_remove_connector,
        commands::companion::plugins::companion_list_plugin_toggles,
        commands::companion::plugins::companion_set_plugin_enabled,
        commands::companion::jobs::companion_list_projects,
        commands::companion::jobs::companion_register_project,
        commands::companion::project_tracking::project_tracking_list_subscriptions,
        commands::companion::project_tracking::project_tracking_set_subscription,
        commands::companion::project_tracking::project_tracking_set_master_enabled,
        commands::companion::project_tracking::project_tracking_is_master_enabled,
        commands::companion::project_tracking::project_tracking_run_now,
        commands::companion::project_tracking::project_tracking_get_obsidian_vault,
        commands::companion::jobs::companion_list_jobs,
        commands::companion::jobs::companion_get_job,
        commands::companion::jobs::companion_enqueue_job,
        commands::companion::templates::companion_match_templates,
        commands::companion::decisions::companion_list_design_decisions,
    ])
}
