//! IPC handler shard 1 — see `super` (`ipc_shards/mod.rs`) for why the list is split
//! and how to add a command.

use super::Shard;
#[allow(unused_imports)] // not every shard names every root module
use crate::{cloud, commands, notifications, test_automation};

pub(super) fn shard(
) -> Shard<impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static> {
    personas_macros::ipc_shard!(tauri::generate_handler![
        // Companions -- the CATEGORY: who exists, who may be switched on, who is
        // on. Each companion's own surface keeps its own module; `companion_*`
        // is the shared runtime, `athena_*` is what only she has.
        commands::companions::companions_status,
        commands::companions::companions_set_enabled,
        commands::companions::athena_mark_onboarded,
        // Execution -- Genome Breeding
        commands::execution::genome::genome_extract,
        commands::execution::genome::genome_fitness,
        commands::execution::genome::genome_start_breeding,
        commands::execution::genome::genome_list_breeding_runs,
        commands::execution::genome::genome_get_breeding_results,
        commands::execution::genome::genome_delete_breeding_run,
        commands::execution::genome::genome_adopt_offspring,
        // Execution -- Evolution (auto-evolving personas)
        commands::execution::evolution::evolution_get_policy,
        commands::execution::evolution::evolution_upsert_policy,
        commands::execution::evolution::evolution_toggle,
        commands::execution::evolution::evolution_delete_policy,
        commands::execution::evolution::evolution_list_cycles,
        commands::execution::evolution::evolution_trigger_cycle,
        commands::execution::evolution::evolution_check_eligibility,
        commands::execution::evolution::evolution_list_promotion_proposals,
        commands::execution::evolution::evolution_resolve_promotion_proposal,
        commands::execution::evolution::get_run_budget_state,
        commands::execution::evolution::probe_cli_capabilities,
        // Execution -- Healing
        commands::execution::healing::list_healing_issues,
        commands::execution::healing::get_healing_issue,
        commands::execution::healing::update_healing_status,
        commands::execution::healing::run_healing_analysis,
        commands::execution::healing::get_retry_chain,
        commands::execution::healing::get_healing_timeline,
        commands::execution::healing::list_healing_audit_log,
        commands::execution::healing::get_healing_effectiveness,
        // Execution -- Knowledge Graph
        commands::execution::knowledge::list_execution_knowledge,
        commands::execution::knowledge::get_knowledge_injection,
        commands::execution::knowledge::get_knowledge_summary,
        commands::execution::knowledge::list_scoped_knowledge,
        commands::execution::knowledge::upsert_knowledge_annotation,
        commands::execution::knowledge::verify_knowledge_annotation,
        commands::execution::knowledge::dismiss_knowledge_annotation,
        commands::execution::knowledge::get_shared_knowledge_injection,
        // Design -- Analysis
        commands::design::analysis::start_design_analysis,
        commands::design::analysis::refine_design,
        commands::design::analysis::test_design_feasibility,
        commands::design::analysis::cancel_design_analysis,
        commands::design::analysis::compile_from_intent,
        commands::design::analysis::preview_prompt,
        // Design -- Build Sessions
        commands::design::build_sessions::start_build_session,
        commands::design::build_sessions::start_build_session_headless,
        commands::design::build_sessions::answer_build_question,
        commands::design::build_sessions::cancel_build_session,
        commands::design::build_sessions::get_active_build_session,
        commands::design::build_sessions::get_latest_build_session,
        commands::design::build_sessions::list_build_sessions,
        commands::design::build_sessions::get_build_status,
        commands::design::build_sessions::test_build_draft,
        commands::design::build_sessions::promote_build_draft,
        commands::design::archetypes::list_archetypes,
        commands::design::build_sessions::create_adoption_session,
        commands::design::build_sessions::save_adoption_answers,
        commands::design::build_sessions::update_build_session_disabled_dims,
        commands::design::build_simulate::simulate_build_draft,
        commands::design::build_simulate::get_simulation_artefacts,
        #[cfg(feature = "test-automation")]
        commands::testing::synthesize_review::synthesize_manual_review,
        // Design -- Conversations
        commands::design::conversations::list_design_conversations,
        commands::design::conversations::get_design_conversation,
        commands::design::conversations::get_active_design_conversation,
        commands::design::conversations::create_design_conversation,
        commands::design::conversations::append_design_conversation_message,
        commands::design::conversations::append_single_design_message,
        commands::design::conversations::update_design_conversation_status,
        commands::design::conversations::delete_design_conversation,
        // Design -- N8n Transform
        commands::design::n8n_transform::cli_runner::start_n8n_transform_background,
        commands::design::n8n_transform::job_state::get_n8n_transform_snapshot,
        commands::design::n8n_transform::job_state::clear_n8n_transform_snapshot,
        commands::design::n8n_transform::job_state::cancel_n8n_transform,
        commands::design::n8n_transform::confirmation::confirm_n8n_persona_draft,
        commands::design::n8n_transform::cli_runner::continue_n8n_transform,
        // Design -- N8n Limits (canonical payload caps)
        // Design -- N8n Sessions
        commands::design::n8n_sessions::create_n8n_session,
        commands::design::n8n_sessions::get_n8n_session,
        commands::design::n8n_sessions::list_n8n_session_summaries,
        commands::design::n8n_sessions::update_n8n_session,
        commands::design::n8n_sessions::delete_n8n_session,
        // Design -- Template Adopt (legacy adoption-jobs subsystem retired
        // 2026-05-09; only snapshot poll + instant adopt remain wired)
        commands::design::template_adopt::get_template_adopt_snapshot,
        commands::design::template_adopt::instant_adopt_template,
        // Approach 1 -- always-on adjustment of the pre-built base IR
        commands::design::template_adopt::adjust_adoption_draft,
        // Design -- Team Presets (filesystem-shipped multi-template bundles)
        commands::design::team_presets::list_team_presets,
        commands::design::team_presets::get_team_preset,
        commands::design::team_presets::get_preset_adoption_schema,
        commands::design::team_presets::adopt_team_preset,
        commands::design::team_presets::retry_team_preset_members,
        commands::design::template_adopt::generate_template_background,
        commands::design::template_adopt::get_template_generate_snapshot,
        commands::design::template_adopt::clear_template_generate_snapshot,
        commands::design::template_adopt::cancel_template_generate,
        commands::design::template_adopt::save_custom_template,
        // Design -- Template Integrity (backend verification)
        commands::design::template_adopt::verify_template_integrity_batch,
        // Design -- Template Feedback
        commands::design::template_feedback::create_template_feedback,
        commands::design::template_feedback::list_template_feedback,
        commands::design::template_feedback::get_template_performance,
        // Design -- Team Synthesis
        commands::design::team_synthesis::synthesize_team_from_templates,
        commands::design::team_synthesis::synthesize_project_crew,
        commands::design::team_synthesis::get_project_pulse_snapshots,
        commands::design::team_synthesis::get_crew_fitness,
        // Design -- Platform Definitions
        commands::design::platform_definitions::list_platform_definitions,
        commands::design::platform_definitions::get_platform_definition,
        // Design -- Reviews
        commands::design::reviews::list_design_reviews,
        commands::design::reviews::count_design_reviews,
        commands::design::reviews::list_design_reviews_paginated,
        commands::design::reviews::list_review_connectors,
        commands::design::reviews::list_review_categories,
        commands::design::reviews::cleanup_duplicate_reviews,
        commands::design::reviews::backfill_review_categories,
        commands::design::reviews::backfill_service_flow,
        commands::design::reviews::backfill_related_tools,
        commands::design::reviews::get_trending_templates,
        commands::design::reviews::get_design_review,
        commands::design::reviews::delete_design_review,
        commands::design::reviews::delete_stale_seed_templates,
        commands::design::reviews::start_design_review_run,
        commands::design::reviews::import_design_review,
        commands::design::reviews::batch_import_design_reviews,
        commands::design::reviews::cancel_design_review_run,
        commands::design::reviews::rebuild_design_review,
        commands::design::reviews::get_rebuild_snapshot,
        commands::design::reviews::cancel_rebuild,
        commands::design::reviews::list_manual_reviews,
        commands::design::reviews::list_manual_reviews_page,
        commands::design::reviews::list_manual_reviews_by_execution,
        commands::design::reviews::get_manual_review_counts,
        commands::design::reviews::get_pending_review_counts_by_persona,
        commands::design::reviews::update_manual_review_status,
        commands::design::reviews::dispatch_review_action,
        commands::design::reviews::gc_stale_manual_reviews,
        commands::design::reviews::delete_all_manual_reviews,
        commands::design::reviews::get_pending_review_count,
        commands::design::reviews::list_review_messages,
        commands::design::reviews::add_review_message,
        commands::design::reviews::seed_mock_manual_review,
        commands::execution::knowledge::seed_mock_knowledge,
        commands::tools::triggers::seed_mock_cron_agent,
        commands::communication::reports::seed_mock_message,
        commands::communication::events::seed_mock_event,
        // Design -- Smart Search
        commands::design::smart_search::smart_search_templates,
        // Credentials -- CRUD
        commands::credentials::crud::list_credentials,
        commands::credentials::crud::get_session_public_key,
        commands::credentials::crud::create_credential,
        commands::credentials::crud::update_credential,
        commands::credentials::crud::patch_credential_metadata,
        commands::credentials::crud::credential_blast_radius,
        commands::credentials::crud::delete_credential,
        commands::credentials::crud::list_credential_events,
        commands::credentials::crud::list_all_credential_events,
        commands::credentials::crud::create_credential_event,
        commands::credentials::crud::update_credential_event,
        commands::credentials::crud::delete_credential_event,
        commands::credentials::crud::healthcheck_credential,
        commands::credentials::crud::healthcheck_credential_preview,
        commands::credentials::crud::healthcheck_all_credentials,
        commands::credentials::crud::vault_status,
        commands::credentials::crud::migrate_plaintext_credentials,
        commands::credentials::crud::list_credential_fields,
        commands::credentials::crud::update_credential_field,
        commands::credentials::resources::get_scoped_resources,
        commands::credentials::resources::save_scoped_resources,
        commands::credentials::resources::list_connector_resources,
        commands::credentials::resources::set_credential_scope_enforcement,
        // Credentials -- External API Keys (A2A Gateway management API auth)
        commands::credentials::broker::mint_credential_handle,
        commands::credentials::broker::list_broker_consumers,
        commands::credentials::broker::list_broker_consumer_activity,
        commands::credentials::broker::revoke_broker_consumer,
        commands::credentials::external_api_keys::create_external_api_key,
        commands::credentials::external_api_keys::list_external_api_keys,
        commands::credentials::external_api_keys::revoke_external_api_key,
        commands::credentials::external_api_keys::delete_external_api_key,
        commands::credentials::external_api_keys::get_system_api_key,
        commands::credentials::external_api_keys::list_api_key_audit,
        commands::credentials::external_api_keys::list_pending_pairings,
        commands::credentials::external_api_keys::approve_pairing,
        commands::credentials::external_api_keys::reject_pairing,
        commands::credentials::external_api_keys::revoke_pairing,
        // Credentials -- Audit Log (registered via intelligence module)
        // Credentials -- Connectors
        commands::credentials::connectors::list_connectors,
        commands::credentials::connectors::get_connector,
        commands::credentials::connectors::create_connector,
        commands::credentials::connectors::update_connector,
        commands::credentials::connectors::delete_connector,
        // OpenAPI Autopilot
        commands::credentials::openapi_autopilot::openapi_playground_test,
        // Credentials -- Credential Design
        commands::credentials::credential_design::start_credential_design,
        commands::credentials::credential_design::cancel_credential_design,
        commands::credentials::credential_design::test_credential_design_healthcheck,
        // Credentials -- Negotiator
        commands::credentials::negotiator::start_credential_negotiation,
        commands::credentials::negotiator::cancel_credential_negotiation,
        commands::credentials::negotiator::get_negotiation_step_help,
        // Credentials -- Intelligence
        commands::credentials::intelligence::credential_audit_log,
        commands::credentials::intelligence::credential_audit_log_global,
        commands::credentials::intelligence::credential_usage_stats,
        commands::credentials::intelligence::credential_dependents,
        commands::credentials::intelligence::credential_dependents_all,
    ])
}
