//! IPC handler shard 5 — see `super` (`ipc_shards/mod.rs`) for why the list is split
//! and how to add a command.

use super::Shard;
#[allow(unused_imports)] // not every shard names every root module
use crate::{cloud, commands, notifications, test_automation};

pub(super) fn shard(
) -> Shard<impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static> {
    personas_macros::ipc_shard!(tauri::generate_handler![
        // Infrastructure -- Auth
        commands::infrastructure::auth::login_with_google,
        commands::infrastructure::auth::get_auth_state,
        commands::infrastructure::auth::logout,
        commands::infrastructure::auth::refresh_session,
        commands::infrastructure::auth::clear_pending_oauth,
        commands::infrastructure::auth::login_with_google_drive,
        commands::infrastructure::auth::get_google_drive_status,
        // Infrastructure -- System
        commands::infrastructure::system::system_health_check,
        commands::infrastructure::system::health_check_local,
        commands::infrastructure::system::health_check_agents,
        commands::infrastructure::system::health_check_cloud,
        commands::infrastructure::system::health_check_account,
        commands::infrastructure::system::health_check_circuit_breaker,
        commands::infrastructure::system::health_check_subscriptions,
        commands::infrastructure::system::health_check_environment,
        commands::infrastructure::system::cdc_dropped_count,
        commands::infrastructure::system::storage_usage,
        commands::infrastructure::system::prune_storage,
        commands::infrastructure::system::reclaim_storage,
        commands::infrastructure::system::open_external_url,
        commands::infrastructure::system::open_local_path,
        commands::infrastructure::system::register_claude_desktop_mcp,
        commands::infrastructure::system::unregister_claude_desktop_mcp,
        commands::infrastructure::system::check_claude_desktop_mcp,
        commands::infrastructure::system::get_crash_logs,
        commands::infrastructure::system::clear_crash_logs,
        commands::infrastructure::system::get_log_directory_stats,
        commands::infrastructure::system::report_frontend_crash,
        commands::infrastructure::system::get_frontend_crashes,
        commands::infrastructure::system::clear_frontend_crashes,
        commands::infrastructure::system::get_frontend_crash_count,
        commands::infrastructure::system::get_db_performance,
        // Infrastructure -- Setup / Auto-install
        commands::infrastructure::setup::start_setup_install,
        commands::infrastructure::setup::cancel_setup_install,
        // Infrastructure -- Local scraper (Pumper, Phase 1b)
        commands::infrastructure::scraper::scraper_list_configs,
        commands::infrastructure::scraper::scraper_save_config,
        commands::infrastructure::scraper::scraper_run_config,
        commands::infrastructure::scraper::scraper_delete_config,
        commands::infrastructure::scraper::scraper_run_extract,
        commands::infrastructure::scraper::scraper_preview_extract,
        commands::infrastructure::scraper::scraper_generate_rules,
        commands::infrastructure::scraper::scraper_list_datasets,
        commands::infrastructure::scraper::scraper_query_dataset,
        // Infrastructure -- Settings
        commands::infrastructure::settings::get_app_setting,
        commands::infrastructure::settings::get_app_settings_bulk,
        commands::infrastructure::settings::set_app_setting,
        commands::infrastructure::settings::get_model_routing_rules,
        commands::infrastructure::settings::set_model_routing_rules,
        commands::infrastructure::settings::delete_app_setting,
        commands::infrastructure::settings::get_quality_gate_config,
        commands::infrastructure::settings::set_quality_gate_config,
        commands::infrastructure::settings::reset_quality_gate_config,
        commands::infrastructure::settings::list_settings_audit_entries,
        // Infrastructure -- Qwen remote engine (Phase 1 split engine)
        commands::infrastructure::qwen_engine::set_qwen_credentials,
        commands::infrastructure::qwen_engine::get_qwen_status,
        commands::infrastructure::qwen_engine::clear_qwen_credentials,
        // Infrastructure -- BYOM (Bring Your Own Model)
        commands::infrastructure::byom::get_byom_policy,
        commands::infrastructure::byom::set_byom_policy,
        commands::infrastructure::byom::validate_byom_policy,
        commands::infrastructure::byom::delete_byom_policy,
        commands::infrastructure::byom::list_provider_audit_log,
        commands::infrastructure::byom::list_provider_audit_by_persona,
        commands::infrastructure::byom::get_provider_usage_stats,
        commands::infrastructure::byom::get_provider_usage_timeseries,
        commands::infrastructure::byom::test_provider_connection,
        // Infrastructure -- Cloud
        commands::infrastructure::cloud::cloud_connect,
        commands::infrastructure::cloud::cloud_diagnose,
        commands::infrastructure::cloud::cloud_reconnect_from_keyring,
        commands::infrastructure::cloud::cloud_disconnect,
        commands::infrastructure::cloud::cloud_get_config,
        commands::infrastructure::cloud::cloud_status,
        commands::infrastructure::cloud::cloud_execute_persona,
        commands::infrastructure::cloud::cloud_cancel_execution,
        commands::infrastructure::cloud::cloud_oauth_authorize,
        commands::infrastructure::cloud::cloud_oauth_callback,
        commands::infrastructure::cloud::cloud_oauth_status,
        commands::infrastructure::cloud::cloud_oauth_refresh,
        commands::infrastructure::cloud::cloud_oauth_disconnect,
        commands::infrastructure::cloud::cloud_deploy_persona,
        commands::infrastructure::cloud::cloud_sync_persona,
        commands::infrastructure::cloud::cloud_list_deployments,
        commands::infrastructure::cloud::cloud_pause_deployment,
        commands::infrastructure::cloud::cloud_resume_deployment,
        commands::infrastructure::cloud::cloud_undeploy,
        commands::infrastructure::cloud::cloud_adopt_deployment,
        commands::infrastructure::cloud::cloud_get_base_url,
        commands::infrastructure::cloud::cloud_list_pending_reviews,
        commands::infrastructure::cloud::cloud_respond_to_review,
        commands::infrastructure::cloud::cloud_list_executions,
        commands::infrastructure::cloud::cloud_execution_stats,
        commands::infrastructure::cloud::cloud_get_execution_output,
        commands::infrastructure::cloud::cloud_list_triggers,
        commands::infrastructure::cloud::cloud_create_trigger,
        commands::infrastructure::cloud::cloud_update_trigger,
        commands::infrastructure::cloud::cloud_delete_trigger,
        commands::infrastructure::cloud::cloud_list_trigger_firings,
        commands::infrastructure::cloud::cloud_webhook_relay_status,
        commands::infrastructure::cloud::smee_relay_list,
        commands::infrastructure::cloud::smee_relay_create,
        commands::infrastructure::cloud::smee_relay_update,
        commands::infrastructure::cloud::smee_relay_set_status,
        commands::infrastructure::cloud::smee_relay_delete,
        commands::infrastructure::cloud_sync::cloud_sync_set_enabled,
        commands::infrastructure::cloud_sync::cloud_sync_status,
        commands::infrastructure::cloud_sync::cloud_sync_now,
        cloud::remote_commands::remote_command_list_pending,
        cloud::remote_commands::remote_command_approve,
        cloud::remote_commands::remote_command_reject,
        // Infrastructure -- GitLab
        commands::infrastructure::gitlab::gitlab_connect,
        commands::infrastructure::gitlab::gitlab_connect_from_vault,
        commands::infrastructure::gitlab::gitlab_disconnect,
        commands::infrastructure::gitlab::gitlab_get_config,
        commands::infrastructure::gitlab::gitlab_list_projects,
        commands::infrastructure::gitlab::gitlab_deploy_persona,
        commands::infrastructure::gitlab::gitlab_list_agents,
        commands::infrastructure::gitlab::gitlab_deployment_status,
        commands::infrastructure::gitlab::gitlab_undeploy_agent,
        commands::infrastructure::gitlab::gitlab_revoke_credentials,
        commands::infrastructure::gitlab::gitlab_list_persona_versions,
        commands::infrastructure::gitlab::gitlab_deploy_persona_versioned,
        commands::infrastructure::gitlab::gitlab_rollback_persona,
        commands::infrastructure::gitlab::gitlab_list_persona_branches,
        commands::infrastructure::gitlab::gitlab_setup_persona_branches,
        commands::infrastructure::gitlab::gitlab_list_deployment_history,
        commands::infrastructure::gitlab::list_deployment_history_all,
        commands::infrastructure::gitlab::gitlab_rollback_from_history,
        commands::infrastructure::gitlab::gitlab_get_job_log,
        // Workflows
        commands::infrastructure::workflows::get_workflows_overview,
        commands::infrastructure::workflows::get_workflow_job_output,
        commands::infrastructure::workflows::cancel_workflow_job,
        // Tier usage
        commands::infrastructure::tier_usage::get_tier_usage,
        commands::infrastructure::system_metrics::get_system_metrics,
        // Director -- meta-persona that coaches every other persona
        commands::infrastructure::director::get_director_persona_id,
        commands::infrastructure::director::run_director_on_persona,
        commands::infrastructure::director::run_director_memory_cleanup,
        commands::infrastructure::director::run_director_batch,
        commands::infrastructure::director::list_director_verdicts,
        commands::infrastructure::director::list_director_score_trends,
        commands::infrastructure::director::get_director_portfolio,
        commands::infrastructure::director::get_director_brain_enabled,
        commands::infrastructure::director::set_director_brain_enabled,
        commands::infrastructure::director::get_director_brain_history,
        commands::infrastructure::director::commission_director_experiment,
        commands::infrastructure::director::list_director_experiments,
        commands::infrastructure::director::get_director_campaign_report,
        // Dev Tools -- Projects
        commands::infrastructure::dev_tools::dev_tools_list_projects,
        commands::infrastructure::dev_tools::dev_tools_get_project,
        commands::infrastructure::dev_tools::dev_tools_create_project,
        commands::infrastructure::dev_tools::dev_tools_update_project,
        commands::infrastructure::dev_tools::dev_tools_set_project_enabled,
        commands::infrastructure::dev_tools::dev_tools_set_standards_config,
        commands::infrastructure::dev_tools::dev_tools_backfill_qa_pr_review,
        commands::infrastructure::dev_tools::dev_tools_delete_project,
        commands::infrastructure::dev_tools::dev_tools_get_active_project,
        commands::infrastructure::dev_tools::dev_tools_set_active_project,
        // Dev Tools -- Workspaces (a named grouping of dev projects)
        commands::infrastructure::dev_workspaces::dev_tools_workspace_list,
        commands::infrastructure::dev_workspaces::dev_tools_workspace_create,
        commands::infrastructure::dev_workspaces::dev_tools_workspace_update,
        commands::infrastructure::dev_workspaces::dev_tools_workspace_delete,
        commands::infrastructure::dev_workspaces::dev_tools_workspace_assign_project,
        commands::infrastructure::dev_workspaces::dev_tools_workspace_import_local,
        // Dev Tools -- Goals
        commands::infrastructure::dev_tools::dev_tools_list_goals,
        commands::infrastructure::dev_tools::dev_tools_create_goal,
        commands::infrastructure::dev_tools::dev_tools_update_goal,
        commands::infrastructure::dev_tools::dev_tools_delete_goal,
        commands::infrastructure::dev_tools::dev_tools_reorder_goals,
        // Dev Tools -- Notepad (scratch requirements -> /note-task dispatch)
        commands::infrastructure::dev_tools::notepad_list_notes,
        commands::infrastructure::dev_tools::notepad_create_note,
        commands::infrastructure::dev_tools::notepad_update_note,
        commands::infrastructure::dev_tools::notepad_set_status,
        commands::infrastructure::dev_tools::notepad_delete_note,
        commands::infrastructure::dev_tools::notepad_fork_note,
        commands::infrastructure::dev_tools::notepad_ingest_runs,
        commands::infrastructure::dev_tools::notepad_resolve_suggestion,
        // Browser -- the Whitelist gate (spark browser-control WP1)
        commands::browser::sites::browser_sites_list,
        commands::browser::sites::browser_sites_upsert,
        commands::browser::sites::browser_sites_delete,
        commands::browser::sites::browser_sites_set_enabled,
        commands::browser::sites::browser_sites_set_override,
        commands::browser::sites::browser_sites_bind_credential,
        commands::browser::sites::browser_lease_revoke,
        // Browser -- the controllability scan (WP3)
        commands::browser::sites::browser_scan_site,
        commands::browser::sites::browser_scan_status,
        commands::browser::sites::browser_scan_confirm,
        // Browser -- the embedded webview host (WP2). Page webviews reach
        // the shell over the bridge's WebSocket relay, never over IPC, so
        // there is deliberately no page-facing command here.
        commands::browser::webview::browser_webview_open,
        commands::browser::webview::browser_webview_close,
        commands::browser::webview::browser_webview_focus,
        commands::browser::webview::browser_webview_navigate,
        commands::browser::webview::browser_webview_back,
        commands::browser::webview::browser_webview_forward,
        commands::browser::webview::browser_webview_list,
        commands::browser::webview::browser_webview_set_viewport,
        commands::browser::webview::browser_webview_set_visible,
        commands::browser::webview::browser_webview_pick_target,
        commands::browser::webview::browser_webview_pick_cancel,
        commands::browser::webview::browser_webview_fill,
        commands::browser::webview::browser_webview_submit,
        commands::infrastructure::dev_tools::notepad_link_milestone,
        commands::infrastructure::dev_tools::notepad_promote_note,
        commands::infrastructure::dev_tools::notepad_list_plan_summaries,
        commands::infrastructure::dev_tools::notepad_list_runs,
        commands::infrastructure::dev_tools::notepad_record_run_start,
    ])
}
