//! IPC handler shard 0 — see `super` (`ipc_shards/mod.rs`) for why the list is split
//! and how to add a command.

use super::Shard;
#[allow(unused_imports)] // not every shard names every root module
use crate::{cloud, commands, notifications, test_automation};

pub(super) fn shard(
) -> Shard<impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static> {
    personas_macros::ipc_shard!(tauri::generate_handler![
        // Phase 1
        commands::core::frontend_bridge::greet,
        commands::core::frontend_bridge::log_frontend_error,
        commands::core::frontend_bridge::report_frontend_ready,
        // Test automation (always registered; server only starts when enabled)
        test_automation::__test_respond,
        // Core -- Validation
        // Core -- Personas
        commands::core::personas::list_personas,
        commands::core::personas::get_persona,
        commands::core::personas::set_persona_starred,
        commands::core::personas::set_persona_enabled,
        commands::core::personas::create_persona,
        commands::core::personas::update_persona,
        commands::core::personas::update_persona_parameters,
        commands::core::personas::list_persona_change_log,
        commands::core::personas::sync_capability_parameters,
        commands::core::personas::duplicate_persona,
        commands::core::personas::persona_blast_radius,
        commands::core::personas::delete_persona,
        commands::core::personas::archive_persona,
        commands::core::personas::restore_persona,
        commands::core::personas::bulk_delete_personas,
        commands::core::personas::get_persona_summaries,
        commands::core::personas::get_persona_detail,
        commands::core::personas::list_personas_using_connector,
        commands::core::personas::resolve_effective_config,
        commands::core::personas::resolve_effective_config_bulk,
        // Core -- Use Cases (Phase C3: capability toggle + simulate;
        // Phase C5b: per-capability generation policy + event rename)
        commands::core::use_cases::get_use_case_cascade,
        commands::core::use_cases::set_use_case_enabled,
        commands::core::use_cases::simulate_use_case,
        commands::core::use_cases::set_use_case_generation_settings,
        commands::core::use_cases::count_event_listeners,
        commands::core::use_cases::rename_event_listeners,
        // Core -- Memories
        commands::core::memories::list_memory_categories,
        commands::core::memories::list_memories,
        commands::core::memories::file_memory_claim,
        commands::core::memories::resolve_memory_claims,
        commands::core::memories::list_memory_claims,
        commands::core::memories::memory_disputed_overview,
        commands::core::memories::list_memories_with_stats,
        commands::core::memories::get_memory_count,
        commands::core::memories::get_memory_stats,
        commands::core::memories::list_memories_by_execution,
        commands::core::memories::create_memory,
        commands::core::memories::delete_memory,
        commands::core::memories::delete_all_memories,
        commands::core::memories::merge_memories,
        commands::core::memories::update_memory_importance,
        commands::core::memories::update_memory_content,
        commands::core::memories::batch_delete_memories,
        commands::core::memories::review_memories_with_cli,
        commands::core::memories::reflect_memories_with_cli,
        commands::core::memories::reflect_team_memories_with_cli,
        commands::core::memories::apply_persona_memory_review_proposal,
        commands::core::memories::discard_persona_memory_review_proposal,
        commands::core::memories::list_persona_memory_review_proposals,
        commands::core::memories::get_persona_memory_review_proposal,
        commands::core::memories::update_memory_tier,
        // Core -- Responsibilities (living-agent charters, WP3)
        commands::core::responsibilities::list_persona_responsibilities,
        commands::core::responsibilities::create_persona_responsibility,
        commands::core::responsibilities::update_persona_responsibility,
        commands::core::responsibilities::retire_persona_responsibility,
        commands::core::responsibilities::set_persona_responsibility_status,
        commands::core::responsibilities::list_attention_ledger,
        commands::core::memory_compile::compile_persona_memories,
        // Core -- Memory curation runs (persona_background_job framework)
        commands::core::persona_jobs::enqueue_persona_memory_reflection,
        commands::core::persona_jobs::enqueue_team_memory_reflection,
        commands::core::persona_jobs::set_persona_curation_schedule,
        commands::core::persona_jobs::get_persona_curation_schedule,
        // Core -- Living-agent persona brain (WP4)
        commands::core::persona_brain::run_persona_consolidation_now,
        commands::core::persona_brain::list_persona_episodes,
        commands::core::persona_brain::get_persona_identity,
        commands::core::persona_brain::get_attention_loop_status,
        commands::core::persona_brain::propose_persona_manifest_diffs,
        // Core -- Agent manifest + Brain dashboard (agent-manifest-rebase WP1)
        commands::core::persona_brain::get_persona_manifest,
        commands::core::persona_brain::update_persona_manifest_law,
        commands::core::persona_brain::get_persona_brain_dashboard,
        // Core -- Custom persona icons (desktop only — image decode pipeline)
        #[cfg(feature = "desktop")]
        commands::core::persona_icons::import_persona_icon,
        #[cfg(feature = "desktop")]
        commands::core::persona_icons::list_persona_icons,
        #[cfg(feature = "desktop")]
        commands::core::persona_icons::delete_persona_icon,
        #[cfg(feature = "desktop")]
        commands::core::persona_icon_gen::list_image_gen_credentials,
        #[cfg(feature = "desktop")]
        commands::core::persona_icon_gen::generate_persona_icon,
        #[cfg(feature = "desktop")]
        commands::core::persona_icon_gen::get_persona_icon_gen_spend,
        // Core -- Import/Export
        commands::core::import_export::export_persona,
        commands::core::import_export::import_persona,
        // Core -- Gallery (public share loop)
        commands::core::gallery::gallery_publish_persona,
        commands::core::gallery::gallery_import_persona,
        commands::core::gallery::gallery_publish_preset,
        commands::core::gallery::record_referral,
        commands::core::gallery::get_referral_count,
        // Core -- Data Portability
        commands::core::data_portability::get_export_stats,
        commands::core::data_portability::export_full,
        commands::core::data_portability::export_selective,
        commands::core::data_portability::import_portability_bundle,
        commands::core::data_portability::preview_competitive_import,
        commands::core::data_portability::export_credentials,
        commands::core::data_portability::import_credentials,
        #[cfg(debug_assertions)]
        commands::core::data_portability::export_selective_to_path,
        #[cfg(debug_assertions)]
        commands::core::data_portability::import_portability_bundle_from_path,
        // Core -- Saved Views
        commands::core::saved_views::create_saved_view,
        commands::core::saved_views::list_saved_views,
        commands::core::saved_views::list_saved_views_by_type,
        commands::core::saved_views::delete_saved_view,
        // Core -- Chat
        commands::core::chat::list_chat_sessions,
        commands::core::chat::get_chat_messages,
        commands::core::chat::create_chat_message,
        commands::core::chat::delete_chat_session,
        commands::core::chat::save_chat_session_context,
        commands::core::chat::get_chat_session_context,
        commands::core::chat::get_latest_chat_session,
        // Execution -- Executions
        commands::execution::executions::list_executions,
        commands::execution::executions::list_executions_summary,
        commands::execution::executions::list_all_executions,
        commands::execution::executions::count_executions,
        commands::execution::executions::search_executions,
        commands::execution::executions::get_execution,
        commands::execution::executions::execute_persona,
        commands::execution::executions::prepare_persona_execution,
        commands::execution::executions::cancel_execution,
        commands::execution::executions::list_executions_by_trigger,
        commands::execution::executions::list_executions_for_use_case,
        commands::execution::executions::get_execution_log,
        commands::execution::executions::get_execution_log_lines,
        commands::execution::executions::get_execution_trace,
        commands::execution::executions::get_chain_trace,
        commands::execution::executions::get_chain_stop_reasons,
        commands::execution::journal::get_execution_data_diff,
        commands::execution::journal::undo_execution,
        commands::execution::executions::list_active_chains,
        commands::execution::executions::get_circuit_breaker_status,
        commands::execution::executions::preview_execution,
        commands::execution::executions::dry_run_persona,
        // Execution -- Annotations (tags / note / star)
        commands::execution::annotations::add_annotation,
        commands::execution::annotations::list_execution_annotations,
        commands::execution::annotations::list_persona_annotations,
        commands::execution::annotations::delete_annotation,
        // Execution -- Scheduler
        commands::execution::scheduler::get_scheduler_status,
        commands::execution::scheduler::start_scheduler,
        commands::execution::scheduler::stop_scheduler,
        commands::execution::scheduler::get_subscription_health,
        commands::execution::scheduler::backfill_schedule,
        commands::execution::scheduler::list_schedule_missed_runs,
        commands::execution::scheduler::clear_schedule_missed_runs,
        // Execution -- Tests
        commands::execution::tests::start_test_run,
        commands::execution::tests::list_test_runs,
        commands::execution::tests::get_test_results,
        commands::execution::tests::delete_test_run,
        commands::execution::tests::cancel_test_run,
        commands::execution::tests::validate_n8n_draft,
        commands::execution::tests::test_n8n_draft,
        // Execution -- Test Suites
        commands::execution::test_suites::list_test_suites,
        commands::execution::test_suites::get_test_suite,
        commands::execution::test_suites::create_test_suite,
        commands::execution::test_suites::update_test_suite,
        commands::execution::test_suites::delete_test_suite,
        // Execution -- Output Assertions
        commands::execution::assertions::list_output_assertions,
        commands::execution::assertions::get_output_assertion,
        commands::execution::assertions::create_output_assertion,
        commands::execution::assertions::update_output_assertion,
        commands::execution::assertions::delete_output_assertion,
        commands::execution::assertions::get_assertion_results_for_execution,
        commands::execution::assertions::get_assertion_result_history,
        commands::execution::policy_events::get_policy_events_for_execution,
        // Execution -- Self-Tuning Fabric (policy proposals, review-each)
        commands::execution::policy_tuning::policy_tuning_generate,
        commands::execution::policy_tuning::policy_tuning_list,
        commands::execution::policy_tuning::policy_tuning_apply,
        commands::execution::policy_tuning::policy_tuning_decline,
        // Execution -- Audit Incidents inbox (cross-source triage)
        commands::execution::audit_incidents::list_audit_incidents,
        commands::execution::audit_incidents::get_audit_incidents_summary,
        commands::execution::audit_incidents::get_audit_incident,
        commands::execution::audit_incidents::acknowledge_audit_incident,
        commands::execution::audit_incidents::set_incident_in_progress,
        commands::execution::audit_incidents::resolve_audit_incident,
        commands::execution::audit_incidents::dismiss_audit_incident,
        commands::execution::audit_incidents::reopen_audit_incident,
        commands::execution::audit_incidents::bulk_acknowledge_audit_incidents,
        commands::execution::audit_incidents::bulk_resolve_audit_incidents,
        // Execution -- Autonomous NOC v1 (incident diagnosis + handled lane)
        commands::execution::incident_diagnosis::get_incident_diagnosis,
        commands::execution::incident_diagnosis::diagnose_audit_incident,
        commands::execution::incident_diagnosis::list_autonomously_handled_incidents,
        // Execution -- Lab
        commands::execution::lab::lab_start_arena,
        commands::execution::lab::lab_list_arena_runs,
        commands::execution::lab::lab_get_arena_results,
        commands::execution::lab::lab_delete_arena_run,
        commands::execution::lab::lab_cancel_arena,
        commands::execution::lab::lab_start_ab,
        commands::execution::lab::lab_list_ab_runs,
        commands::execution::lab::lab_get_ab_results,
        commands::execution::lab::lab_delete_ab_run,
        commands::execution::lab::lab_cancel_ab,
        commands::execution::lab::lab_start_matrix,
        commands::execution::lab::lab_list_matrix_runs,
        commands::execution::lab::lab_get_matrix_results,
        commands::execution::lab::lab_delete_matrix_run,
        commands::execution::lab::lab_cancel_matrix,
        commands::execution::lab::lab_accept_matrix_draft,
        commands::execution::lab::lab_start_eval,
        commands::execution::lab::lab_list_eval_runs,
        commands::execution::lab::lab_get_eval_results,
        commands::execution::lab::lab_delete_eval_run,
        commands::execution::lab::lab_cancel_eval,
        commands::execution::lab::lab_get_versions,
        commands::execution::lab::lab_tag_version,
        commands::execution::lab::lab_rollback_version,
        commands::execution::lab::lab_activate_version,
        commands::execution::lab::lab_get_error_rate,
        commands::execution::lab::lab_improve_prompt,
        commands::execution::lab::lab_get_active_progress,
        commands::execution::lab::lab_rate_result,
        commands::execution::lab::lab_get_ratings,
        commands::execution::lab::lab_get_version_ratings,
        commands::execution::lab::lab_get_version_economics,
        commands::execution::lab::lab_get_result_events,
        commands::execution::lab::lab_get_tool_calls,
        commands::execution::lab::lab_get_score_weights,
    ])
}
