//! IPC handler shard 6 — see `super` (`ipc_shards/mod.rs`) for why the list is split
//! and how to add a command.

use super::Shard;
#[allow(unused_imports)] // not every shard names every root module
use crate::{cloud, commands, notifications, test_automation};

pub(super) fn shard(
) -> Shard<impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static> {
    personas_macros::ipc_shard!(tauri::generate_handler![
        // Dev Tools -- milestones (Ship layer: convergence cuts)
        commands::infrastructure::dev_tools::dev_tools_list_milestones,
        commands::infrastructure::dev_tools::dev_tools_create_milestone,
        commands::infrastructure::dev_tools::dev_tools_update_milestone,
        commands::infrastructure::dev_tools::dev_tools_delete_milestone,
        commands::infrastructure::dev_tools::dev_tools_list_milestone_items,
        commands::infrastructure::dev_tools::dev_tools_set_milestone_item,
        commands::infrastructure::dev_tools::dev_tools_remove_milestone_item,
        // The /ship-milestone skill's one gated door back into the app.
        commands::infrastructure::dev_tools::dev_tools_ship_milestone_ingest,
        commands::infrastructure::dev_tools::dev_tools_council_ingest,
        commands::infrastructure::dev_tools::dev_tools_council_list_subjects,
        commands::infrastructure::dev_tools::dev_tools_council_get_run,
        commands::infrastructure::dev_tools::dev_tools_council_decide,
        commands::infrastructure::dev_tools::dev_tools_council_overlay,
        commands::infrastructure::dev_tools::dev_tools_council_read_media,
        commands::infrastructure::dev_tools::dev_tools_triage_verdicts_ingest,
        // Dev Tools -- L1 passport wall (one batched read for N covers)
        commands::infrastructure::dev_tools::dev_tools_project_wall_summary,
        // Dev Tools -- use cases (behavioral slice layer under contexts)
        commands::infrastructure::dev_tools::dev_tools_list_use_cases,
        commands::infrastructure::dev_tools::dev_tools_get_use_case,
        commands::infrastructure::dev_tools::dev_tools_list_use_cases_for_context,
        commands::infrastructure::dev_tools::dev_tools_create_use_case,
        commands::infrastructure::dev_tools::dev_tools_update_use_case,
        commands::infrastructure::dev_tools::dev_tools_delete_use_case,
        commands::infrastructure::dev_tools::dev_tools_set_use_case_tier,
        commands::infrastructure::use_case_scan::dev_tools_scan_use_cases,
        commands::infrastructure::use_case_scan::dev_tools_cancel_use_case_scan,
        commands::infrastructure::use_case_scan::dev_tools_get_use_case_scan_status,
        commands::infrastructure::use_case_scan::dev_tools_relink_use_cases,
        commands::infrastructure::dev_tools_http::dev_tools_bridge_port,
        commands::infrastructure::app_master_adopt::adopt_app_master,
        commands::infrastructure::project_scaffold::create_project_repository,
        commands::infrastructure::architect_adopt::adopt_architect,
        commands::infrastructure::kp_hire::request_hire_from_kp,
        // Dev Tools -- KPIs (outcome layer above goals)
        commands::infrastructure::dev_tools::dev_tools_list_kpis,
        commands::infrastructure::dev_tools::dev_tools_get_kpi,
        commands::infrastructure::dev_tools::dev_tools_create_kpi,
        commands::infrastructure::dev_tools::dev_tools_update_kpi,
        commands::infrastructure::dev_tools::dev_tools_delete_kpi,
        commands::infrastructure::dev_tools::dev_tools_save_kpi_assessment,
        commands::infrastructure::dev_tools::dev_tools_list_kpi_measurements,
        commands::infrastructure::dev_tools::dev_tools_record_kpi_measurement,
        commands::infrastructure::kpi_scan::dev_tools_scan_kpis,
        commands::infrastructure::kpi_sim::dev_tools_kpi_sim_prepare,
        commands::infrastructure::kpi_sim::dev_tools_kpi_sim_ingest,
        commands::infrastructure::feed_impact::dev_tools_feed_impact_ingest,
        commands::infrastructure::memory_ledger::dev_tools_memory_ingest,
        commands::infrastructure::context_map_export::dev_tools_export_backlog_digest,
        commands::infrastructure::memory_ledger::dev_tools_memory_list,
        commands::infrastructure::memory_ledger::dev_tools_memory_coverage,
        commands::infrastructure::memory_ledger::dev_tools_memory_project_vault,
        commands::infrastructure::memory_ledger::dev_tools_memory_import_vault,
        commands::infrastructure::memory_ledger::dev_tools_memory_skill_coverage,
        commands::infrastructure::memory_ledger::dev_tools_memory_skill_contexts,
        commands::infrastructure::memory_ledger::dev_tools_memory_skill_context_pairs,
        commands::infrastructure::kpi_scan::dev_tools_cancel_kpi_scan,
        commands::infrastructure::kpi_scan::dev_tools_get_kpi_scan_status,
        commands::infrastructure::llm_spend::llm_spend_dashboard,
        commands::infrastructure::kpi_compose::dev_tools_compose_kpi_measure,
        commands::infrastructure::kpi_compose::dev_tools_propose_kpi,
        commands::infrastructure::kpi_compose::dev_tools_propose_kpi_auto,
        commands::infrastructure::kpi_compose::dev_tools_get_kpi_compose_status,
        commands::infrastructure::kpi_compose::dev_tools_cancel_kpi_compose,
        commands::infrastructure::dev_tools::dev_tools_evaluate_kpi,
        commands::infrastructure::dev_tools::dev_tools_evaluate_due_kpis,
        // Per-project autopilot (one switch over the KPI→goal→team loop)
        commands::infrastructure::autopilot::dev_tools_get_autopilot_mode,
        commands::infrastructure::autopilot::dev_tools_set_autopilot_mode,
        commands::infrastructure::dev_tools::dev_tools_list_all_kpis,
        commands::infrastructure::dev_tools::dev_tools_list_kpi_measurements_bulk,
        commands::infrastructure::dev_tools::dev_tools_list_kpi_metric_types,
        commands::infrastructure::dev_tools::dev_tools_kpi_matching_credentials,
        commands::infrastructure::dev_tools::dev_tools_kpi_compose_binding,
        commands::infrastructure::dev_tools::dev_tools_kpi_activate_binding,
        commands::infrastructure::dev_tools::dev_tools_kpi_list_bindings,
        // Dev Tools -- Goal Dependencies
        commands::infrastructure::dev_tools::dev_tools_list_goal_dependencies,
        commands::infrastructure::dev_tools::dev_tools_add_goal_dependency,
        commands::infrastructure::dev_tools::dev_tools_remove_goal_dependency,
        // Dev Tools -- Goal Signals
        commands::infrastructure::dev_tools::dev_tools_list_goal_signals,
        // Dev Tools -- Goal Items + progress resolver (goals hub)
        commands::infrastructure::dev_tools::dev_tools_list_goal_items,
        commands::infrastructure::dev_tools::dev_tools_create_goal_item,
        commands::infrastructure::dev_tools::dev_tools_update_goal_item,
        commands::infrastructure::dev_tools::dev_tools_delete_goal_item,
        commands::infrastructure::dev_tools::dev_tools_reorder_goal_items,
        commands::infrastructure::dev_tools::dev_tools_set_goal_verification,
        commands::infrastructure::dev_tools::dev_tools_clear_goal_verification,
        commands::infrastructure::dev_tools::dev_tools_run_goal_uat,
        commands::infrastructure::dev_tools::dev_tools_complete_goal_uat,
        commands::infrastructure::dev_tools::dev_tools_list_child_goals,
        commands::infrastructure::dev_tools::dev_tools_resolve_goal_progress,
        // Dev Tools -- Goals v2 cross-project surfaces (Portfolio / Attention / Timeline / Map)
        commands::infrastructure::dev_tools::dev_tools_list_all_goals,
        // Goal acceptance queue (human-acceptance gate)
        commands::infrastructure::dev_tools::dev_tools_list_pending_acceptance,
        commands::infrastructure::dev_tools::dev_tools_count_pending_acceptance,
        commands::infrastructure::dev_tools::dev_tools_pending_counts,
        commands::infrastructure::dev_tools::dev_tools_resolve_goal_acceptance,
        commands::infrastructure::dev_tools::dev_tools_list_goal_dependencies_for_project,
        commands::infrastructure::dev_tools::dev_tools_list_goal_items_for_project,
        commands::infrastructure::dev_tools::dev_tools_goal_advancing_teams,
        // Staleness engine — goals + ideas + tasks in one ranked queue,
        // plus the accepted-but-never-dispatched list on its own.
        commands::infrastructure::dev_tools::dev_tools_attention_queue,
        commands::infrastructure::dev_tools::dev_tools_undispatched_ideas,
        // Dev Tools -- Context Groups
        commands::infrastructure::dev_tools::dev_tools_list_context_groups,
        commands::infrastructure::dev_tools::dev_tools_list_env_connectors,
        commands::infrastructure::dev_tools::dev_tools_set_env_connector,
        commands::infrastructure::dev_tools::dev_tools_create_context_group,
        commands::infrastructure::dev_tools::dev_tools_update_context_group,
        commands::infrastructure::dev_tools::dev_tools_delete_context_group,
        commands::infrastructure::dev_tools::dev_tools_reorder_context_groups,
        // Dev Tools -- Contexts
        commands::infrastructure::dev_tools::dev_tools_list_contexts,
        commands::infrastructure::dev_tools::dev_tools_create_context,
        commands::infrastructure::dev_tools::dev_tools_update_context,
        commands::infrastructure::dev_tools::dev_tools_delete_context,
        commands::infrastructure::dev_tools::dev_tools_set_context_pinned,
        // Dev Tools -- Context Generation (LLM-powered codebase scan)
        commands::infrastructure::context_generation::dev_tools_scan_codebase,
        commands::infrastructure::context_generation::dev_tools_cancel_scan_codebase,
        commands::infrastructure::context_generation::dev_tools_get_scan_codebase_status,
        commands::infrastructure::context_audit::dev_tools_audit_contexts,
        commands::infrastructure::context_consolidate::dev_tools_repair_cross_refs,
        commands::infrastructure::context_fingerprints::dev_tools_refresh_context_fingerprints,
        // Dev Tools -- Knowledge hierarchy (docs/concepts/paths/, read-only)
        commands::infrastructure::hierarchy_read::dev_tools_hierarchy_graph,
        commands::infrastructure::hierarchy_read::dev_tools_hierarchy_doc,
        commands::infrastructure::hierarchy_read::dev_tools_hierarchy_scorecard,
        // System operations (trigger → built-in op automations; Chain Studio + Context Map)
        commands::infrastructure::system_ops::system_ops_list_kinds,
        commands::infrastructure::system_ops::system_ops_list_automations,
        commands::infrastructure::system_ops::system_ops_create_automation,
        commands::infrastructure::system_ops::system_ops_set_enabled,
        commands::infrastructure::system_ops::system_ops_delete_automation,
        commands::infrastructure::system_ops::system_ops_run_now,
        commands::infrastructure::system_ops::system_ops_report_outcome,
        // Dev Tools -- Context Group Relationships
        commands::infrastructure::dev_tools::dev_tools_list_context_group_relationships,
        commands::infrastructure::dev_tools::dev_tools_create_context_group_relationship,
        commands::infrastructure::dev_tools::dev_tools_delete_context_group_relationship,
        // Dev Tools -- Ideas
        commands::infrastructure::dev_tools::dev_tools_list_ideas,
        commands::infrastructure::dev_tools::dev_tools_get_idea,
        commands::infrastructure::dev_tools::dev_tools_create_idea,
        commands::infrastructure::dev_tools::dev_tools_create_finding,
        commands::infrastructure::dev_tools::dev_tools_list_finding_dedup_keys,
        commands::infrastructure::dev_tools::dev_tools_set_finding_verify_state,
        commands::infrastructure::dev_tools::dev_tools_update_idea,
        commands::infrastructure::dev_tools::dev_tools_accept_idea,
        commands::infrastructure::dev_tools::dev_tools_reject_idea,
        commands::infrastructure::dev_tools::dev_tools_list_pending_ideas,
        commands::infrastructure::dev_tools::dev_tools_triage_ideas,
        commands::infrastructure::dev_tools::dev_tools_delete_idea,
        commands::infrastructure::dev_tools::dev_tools_bulk_delete_ideas,
        // Dev Tools -- Scans
        commands::infrastructure::dev_tools::dev_tools_list_scans,
        commands::infrastructure::dev_tools::dev_tools_get_scan,
        // Dev Tools -- Idea Scanner (LLM-powered)
        commands::infrastructure::idea_scanner::dev_tools_list_scan_agents,
        commands::infrastructure::idea_scanner::dev_tools_run_scan,
        commands::infrastructure::idea_scanner::dev_tools_cancel_scan,
        commands::infrastructure::idea_scanner::dev_tools_get_idea_scan_status,
        // Dev Tools -- Static Scan (deterministic CLI-driven sibling)
        commands::infrastructure::static_scan::dev_tools_set_static_scan_config,
        commands::infrastructure::standards_scan::dev_tools_run_standards_scan,
        commands::infrastructure::standards_scan::dev_tools_list_standards,
        commands::infrastructure::static_scan::dev_tools_run_static_scan,
        // Dev Tools -- Tasks
        commands::infrastructure::dev_tools::dev_tools_list_tasks,
        commands::infrastructure::dev_tools::dev_tools_create_task,
        commands::infrastructure::dev_tools::dev_tools_update_task,
        commands::infrastructure::dev_tools::dev_tools_delete_task,
        commands::infrastructure::dev_tools::dev_tools_tasks_page,
        commands::infrastructure::dev_tools::dev_tools_retry_task,
        commands::infrastructure::dev_tools::dev_tools_dispatch_ideas,
        // Dev Tools -- Task Executor (CLI-powered)
        commands::infrastructure::task_executor::dev_tools_execute_task,
        commands::infrastructure::task_executor::dev_tools_start_batch,
        commands::infrastructure::task_executor::dev_tools_cancel_task_execution,
        commands::infrastructure::task_executor::dev_tools_start_auto_run,
        commands::infrastructure::task_executor::dev_tools_cancel_auto_run,
        commands::infrastructure::task_executor::dev_tools_get_auto_run_status,
        // Dev Tools -- run checkpoints (git rewind for an auto-run)
        commands::infrastructure::run_checkpoints::dev_tools_list_run_checkpoints,
        commands::infrastructure::run_checkpoints::dev_tools_rollback_run_checkpoint,
        // Dev Tools -- Triage Rules
        commands::infrastructure::dev_tools::dev_tools_list_triage_rules,
        commands::infrastructure::dev_tools::dev_tools_create_triage_rule,
        commands::infrastructure::dev_tools::dev_tools_update_triage_rule,
        commands::infrastructure::dev_tools::dev_tools_delete_triage_rule,
        commands::infrastructure::dev_tools::dev_tools_run_triage_rules,
        // Dev Tools -- Overnight Portfolio Engine
        commands::infrastructure::overnight::dev_tools_list_night_runs,
        commands::infrastructure::overnight::dev_tools_run_overnight_now,
        // Dev Tools -- Pipelines (Idea-to-Execution)
        // Dev Tools -- Health Snapshots
        // Dev Tools -- Cross-Project (Codebases connector)
        commands::infrastructure::dev_tools::dev_tools_list_cross_project_relations,
        commands::infrastructure::dev_tools::dev_tools_upsert_cross_project_relation,
        commands::infrastructure::dev_tools::dev_tools_get_cross_project_map,
        commands::infrastructure::dev_tools::dev_tools_generate_cross_project_metadata,
        commands::infrastructure::dev_tools::dev_tools_get_cross_project_metadata,
        commands::infrastructure::dev_tools::dev_tools_probe_repo_evidence,
        commands::infrastructure::dev_tools::dev_tools_create_idea_batch,
        commands::infrastructure::dev_tools::dev_tools_search_across_projects,
        commands::infrastructure::dev_tools::dev_tools_get_project_summary,
        commands::infrastructure::dev_tools::dev_tools_get_dependency_graph,
        // Dev Tools -- Competitions (multi-clone parallel execution)
        commands::infrastructure::dev_tools::dev_tools_start_competition,
        commands::infrastructure::dev_tools::dev_tools_list_competitions,
        commands::infrastructure::dev_tools::dev_tools_get_competition,
        commands::infrastructure::dev_tools::dev_tools_pick_competition_winner,
        commands::infrastructure::dev_tools::dev_tools_cancel_competition,
        commands::infrastructure::dev_tools::dev_tools_refresh_competition_slot,
        commands::infrastructure::dev_tools::dev_tools_get_competition_slot_diff,
        commands::infrastructure::dev_tools::dev_tools_get_strategy_leaderboard,
        commands::infrastructure::dev_tools::dev_tools_switch_to_worktree,
        commands::infrastructure::dev_tools::dev_tools_delete_competition,
        commands::infrastructure::dev_tools::dev_tools_start_slot_server,
        commands::infrastructure::dev_tools::dev_tools_stop_slot_server,
        // Dev Tools -- Implementation Pipeline (Direction 3)
        commands::infrastructure::dev_tools::dev_tools_create_branch,
        commands::infrastructure::dev_tools::dev_tools_apply_diff,
        commands::infrastructure::dev_tools::dev_tools_run_tests,
        commands::infrastructure::dev_tools::dev_tools_get_git_status,
        commands::infrastructure::dev_tools::dev_tools_commit_changes,
        // Dev Tools -- Portfolio Intelligence (Direction 5)
        commands::infrastructure::dev_tools::dev_tools_get_portfolio_health,
        commands::infrastructure::dev_tools::dev_tools_get_tech_radar,
        commands::infrastructure::dev_tools::dev_tools_get_risk_matrix,
        commands::infrastructure::dev_tools::dev_tools_get_project_favicon,
    ])
}
