// Portable passport — render a project's readiness as a self-contained markdown
// report/badge the user can drop into the repo's README or a PR. Makes the
// standard travel WITH the codebase, not just live in the desktop app. (The
// natural next step is a `personas passport verify` CI check that fails a build
// below its golden target — that wants the headless evidence scanner first.)
import { scoreAgainstRubric } from './improve/goldenStandard';
import {
  AUTOMATION_LABEL, PROD_BAND_LABEL, CI_LABEL, TESTS_LABEL, SECURITY_LABEL,
  OBSERVABILITY_LABEL, GRAPH_LABEL, EVALS_LABEL, MIGRATIONS_LABEL, ARCHETYPE_LABEL,
  type AppPassport,
} from './passportModel';

export function passportToMarkdown(p: AppPassport, now: number): string {
  const r = scoreAgainstRubric(p);
  const a = p.automationReadiness;
  const pr = p.productionReadiness;
  const sv = a.selfVerify;
  const selfVerify = [sv.build && 'build', sv.test && 'test', sv.lint && 'lint', sv.typecheck && 'types'].filter(Boolean).join(', ') || 'None';
  const blockers = [...pr.blockers, ...a.blockers];

  const lines: string[] = [
    `# ${p.identity.name} — App Readiness Passport`,
    '',
    `> Generated by Personas · ${new Date(now).toISOString().slice(0, 10)}`,
    '',
    `- **Automation:** ${a.level} · ${a.score}/100 · ${AUTOMATION_LABEL[a.level]}`,
    `- **Production:** ${PROD_BAND_LABEL[pr.band]} · ${pr.score}/100`,
    `- **Golden standard (${ARCHETYPE_LABEL[p.identity.archetype]}):** ${r.goldenPct}%` +
      (r.belowTarget.length ? ` — below target on ${r.belowTarget.map((d) => d.label).join(', ')}` : ' — meets the standard ✓'),
    '',
    '| Dimension | Level |',
    '|---|---|',
    `| Context graph | ${GRAPH_LABEL[a.artifacts.contextGraph]} |`,
    `| Agent instructions | ${a.artifacts.agentInstructions.length ? 'Present' : 'None'} |`,
    `| Self-verify | ${selfVerify} |`,
    `| Evals | ${EVALS_LABEL[a.artifacts.evals]} |`,
    `| CI | ${CI_LABEL[pr.ci.level]} |`,
    `| Tests | ${TESTS_LABEL[pr.tests.level]} |`,
    `| Security | ${SECURITY_LABEL[pr.security.level]} |`,
    `| Observability | ${OBSERVABILITY_LABEL[pr.observability.level]} |`,
    `| Migrations | ${MIGRATIONS_LABEL[pr.delivery.migrations]} |`,
  ];
  if (blockers.length) {
    lines.push('', '## Why it’s not ready');
    for (const b of blockers) lines.push(`- ${b}`);
  }
  lines.push('');
  return lines.join('\n');
}
