import { beforeAll, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen } from "@testing-library/react";

import type { DriveEntry } from "@/api/drive";
import type { DriveApi, FinderViewProps } from "../../types";
import { ListView } from "../ListView";

vi.mock("@/api/drive", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@/api/drive")>();
  return { ...actual, driveThumbnail: vi.fn().mockRejectedValue(new Error("no thumbs")) };
});

// The runtime section strings (`i18n/generated/enSectionStrings.ts`) are
// regenerated by the `i18n-split` codegen, which may lag en.json — feed the
// source catalog straight in so the view is tested against the real copy.
vi.mock("@/i18n/useTranslation", async () => {
  const en = (await import("@/i18n/locales/en.json")).default;
  return {
    useTranslation: () => ({
      t: en,
      language: "en",
      tx: (s: string, vars: Record<string, unknown>) =>
        s.replace(/\{(\w+)\}/g, (_, k: string) => String(vars[k] ?? `{${k}}`)),
    }),
  };
});

function entry(name: string, overrides: Partial<DriveEntry> = {}): DriveEntry {
  return {
    name,
    path: name,
    kind: "file",
    size: 2048,
    modified: "2026-09-17T00:00:00Z",
    mime: "text/plain",
    extension: "txt",
    ...overrides,
  };
}

const ENTRIES: DriveEntry[] = [
  entry("docs", { kind: "folder", mime: null, extension: null }),
  entry("a.txt"),
  entry("b.txt"),
  entry("c.txt"),
  entry("d.txt"),
];

function makeDrive(overrides: Partial<DriveApi> = {}): DriveApi {
  const selection = new Set<string>();
  return {
    currentPath: "",
    entries: ENTRIES,
    visibleEntries: ENTRIES,
    loading: false,
    error: null,
    refresh: vi.fn(),
    selection,
    isSelected: (p: string) => selection.has(p),
    selectOnly: vi.fn(),
    toggleSelect: vi.fn(),
    selectRange: vi.fn(),
    sortKey: "name",
    sortDir: "asc",
    setSort: vi.fn(),
    searchQuery: "",
    recentlyWritten: new Set<string>(),
    recursiveResults: null,
    recursiveLoading: false,
    recursiveQuery: null,
    runRecursiveSearch: vi.fn(),
    clearRecursiveSearch: vi.fn(),
    rememberScroll: vi.fn(),
    recallScroll: vi.fn(() => 0),
    moveManyInto: vi.fn(() => Promise.resolve()),
    navigate: vi.fn(),
    ...overrides,
  } as unknown as DriveApi;
}

function makeProps(drive: DriveApi): FinderViewProps {
  return {
    drive,
    meta: {
      meta: null,
      loading: false,
      tagsFor: () => [],
      setTags: vi.fn(),
      toggleTag: vi.fn(),
      upsertTag: vi.fn(),
      deleteTag: vi.fn(),
      refresh: vi.fn(),
    },
    signedPaths: new Set(),
    onOpen: vi.fn(),
    onContextMenu: vi.fn(),
    onQuickLook: vi.fn(),
    inlineRenamingPath: null,
    onCommitInlineRename: vi.fn(),
    onCancelInlineRename: vi.fn(),
    pendingCreate: null,
    onCommitPendingCreate: vi.fn(),
    onCancelPendingCreate: vi.fn(),
    activeDragCount: null,
    onDragSelectionStart: vi.fn(),
    onDragSelectionEnd: vi.fn(),
    externalDropPath: null,
    onExternalFolderDragOver: vi.fn(),
    onNativeDragOut: vi.fn(),
  };
}

describe("ListView", () => {
  beforeAll(() => {
    // The virtualizer sizes its viewport from the scroll element's rect;
    // jsdom reports 0x0, which would render no rows at all.
    Element.prototype.getBoundingClientRect = () =>
      ({ width: 800, height: 600, top: 0, left: 0, right: 800, bottom: 600, x: 0, y: 0, toJSON: () => ({}) }) as DOMRect;
  });

  it("renders one row per visible entry under the column header", () => {
    render(<ListView {...makeProps(makeDrive())} />);
    expect(screen.getByTestId("finder-list-header")).toBeInTheDocument();
    expect(screen.getAllByTestId("finder-list-row")).toHaveLength(ENTRIES.length);
    expect(screen.getByText("docs")).toBeInTheDocument();
  });

  it("click selects, double-click opens", () => {
    const drive = makeDrive();
    const props = makeProps(drive);
    render(<ListView {...props} />);
    const row = screen.getAllByTestId("finder-list-row")[1] as HTMLElement;
    fireEvent.click(row);
    expect(drive.selectOnly).toHaveBeenCalledWith("a.txt");
    fireEvent.click(row, { ctrlKey: true });
    expect(drive.toggleSelect).toHaveBeenCalledWith("a.txt", true);
    fireEvent.click(row, { shiftKey: true });
    expect(drive.selectRange).toHaveBeenCalledWith("a.txt");
    fireEvent.doubleClick(row);
    expect(props.onOpen).toHaveBeenCalledWith(ENTRIES[1]);
  });

  it("right-click selects an unselected row before opening the menu", () => {
    const drive = makeDrive();
    const props = makeProps(drive);
    render(<ListView {...props} />);
    fireEvent.contextMenu(screen.getAllByTestId("finder-list-row")[2] as HTMLElement, {
      clientX: 10,
      clientY: 20,
    });
    expect(drive.selectOnly).toHaveBeenCalledWith("b.txt");
    expect(props.onContextMenu).toHaveBeenCalledWith(ENTRIES[2], 10, 20);
  });

  it("groups by kind with bucket counts when sorted by kind", () => {
    render(<ListView {...makeProps(makeDrive({ sortKey: "kind" }))} />);
    const headers = screen.getAllByTestId("finder-group-header");
    expect(headers).toHaveLength(2);
    expect(headers[0]).toHaveTextContent("1");
    expect(headers[1]).toHaveTextContent("4");
  });

  it("ghosts a cold folder and shows the search-empty state for a miss", () => {
    const { unmount } = render(
      <ListView {...makeProps(makeDrive({ loading: true, entries: [], visibleEntries: [] }))} />,
    );
    expect(screen.getByTestId("finder-ghost")).toBeInTheDocument();
    unmount();
    render(<ListView {...makeProps(makeDrive({ visibleEntries: [], searchQuery: "zz" }))} />);
    expect(screen.getByTestId("finder-empty-search")).toBeInTheDocument();
  });

  it("puts the phantom create row above the rows", () => {
    const props = makeProps(makeDrive());
    render(<ListView {...{ ...props, pendingCreate: "folder" }} />);
    expect(screen.getByTestId("finder-phantom-row")).toBeInTheDocument();
    expect(screen.getByTestId("finder-inline-name")).toHaveFocus();
  });
});
