// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertMetric } from "./AlertMetric";
import type { AlertOperator } from "./AlertOperator";
import type { AlertSeverity } from "./AlertSeverity";

export type AlertRule = { id: string, name: string, metric: AlertMetric, operator: AlertOperator, threshold: number, severity: AlertSeverity, persona_id: string | null, enabled: boolean, created_at: string, updated_at: string, };
