// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single entry in the snapshot (serialisable version of AmbientSignal).
 */
export type AmbientSignalEntry = { source: string, summary: string, capturedAt: bigint, 
/**
 * Seconds ago relative to snapshot time.
 */
ageSecs: bigint, };
