// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorrelatedEvent } from "./CorrelatedEvent";
import type { RootCauseSuggestion } from "./RootCauseSuggestion";

/**
 * Combined drill-down response for a single anomaly.
 */
export type AnomalyDrilldownData = { anomalyDate: string, anomalyMetric: string, anomalyValue: number, anomalyBaseline: number, anomalyDeviationPct: number, correlatedEvents: Array<CorrelatedEvent>, rootCauseSuggestions: Array<RootCauseSuggestion>, };
