// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a proxied API request.
 */
export type ApiProxyResponse = { status: number, status_text: string, headers: { [key in string]?: string }, body: string, duration_ms: bigint, content_type: string | null, };
