// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical 2D / 3D classification for artist assets.
 *
 * Replaces the prior stringly-typed `"2d"` / `"3d"` tokens. The DB column
 * still stores a string for backwards compatibility (see `ArtistAsset`),
 * but every code path that produces an asset_type now goes through this
 * enum so a typo at the boundary becomes a compile error.
 *
 * Classification CONTRACT (see `commands/artist/mod.rs::scan_dir_recursive`
 * for the implementation):
 *
 *   1. The asset_type is derived ONLY from the immediate child of the
 *      artist root that contains the file ("2d/..." or "3d/...").
 *      Walking arbitrary ancestors looking for a "2d"/"3d" segment was
 *      the prior behavior and produced silent miscategorization (a PNG
 *      under `.../2d/sketches/refs/3d/` was tagged 3D).
 *   2. If the file is not under either bucket directly under the root,
 *      classification falls back to the extension table.
 *   3. If both `2d` and `3d` segments appear in the path between the
 *      file and the root, the tree is ambiguous — `scan_dir_recursive`
 *      logs a warning and skips the file rather than picking one.
 */
export type AssetType = "2d" | "3d";
