// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single promoted incident.
 *
 * `dedup_key = "{source_table}:{source_id}"` is UNIQUE; promoter callers use
 * `INSERT OR IGNORE` so a second promotion of the same source row is a safe
 * no-op (no concurrent-insert coordination needed under SQLite WAL).
 */
export type AuditIncident = { id: string, 
/**
 * Which audit table this incident was promoted from.
 * One of: `fired_alerts`, `tool_execution_audit_log`,
 * `credential_audit_log`, `healing_audit_log`, `provider_audit_log`,
 * `policy_events`, `persona_healing_issues`.
 */
sourceTable: string, 
/**
 * `id` of the row in `source_table`. Lets the UI link back to the
 * source-specific deep-dive view (e.g. HealingIssueModal for
 * `persona_healing_issues` rows).
 */
sourceId: string, 
/**
 * `{source_table}:{source_id}` — UNIQUE, drives idempotent promotion.
 */
dedupKey: string, personaId: string | null, 
/**
 * Denormalized at promotion time so the list query is a single-table
 * scan (no join). Stable name; if a persona is renamed after promotion,
 * the historical incident keeps the old name — acceptable.
 */
personaName: string | null, executionId: string | null, 
/**
 * Normalized severity (see `IncidentSeverity`).
 */
severity: string, 
/**
 * Short machine token describing the incident class
 * (e.g. `tool_error`, `credential_decrypt_failure`, `provider_failover`).
 * Used for icon mapping and i18n lookup; not user-facing prose.
 */
kind: string, 
/**
 * One-line human summary captured at promotion time.
 */
title: string, 
/**
 * Optional longer payload (free text or JSON) for the detail modal.
 */
detail: string | null, 
/**
 * One of `open` / `acknowledged` / `resolved` / `dismissed`. See
 * `IncidentStatus`.
 */
status: string, acknowledgedAt: string | null, 
/**
 * Currently always `"user"` (single-user app). Reserved for future
 * auto-triage attribution.
 */
acknowledgedBy: string | null, resolvedAt: string | null, resolutionNote: string | null, createdAt: string, };
