// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthSubscription } from "./AuthSubscription";
import type { AuthUser } from "./AuthUser";

export type AuthStateResponse = { is_authenticated: boolean, is_offline: boolean, user: AuthUser | null, subscription: AuthSubscription | null, };
