// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutomationRun = { id: string, automationId: string, executionId: string | null, status: string, inputData: string | null, outputData: string | null, platformRunId: string | null, platformLogsUrl: string | null, durationMs: bigint | null, errorMessage: string | null, startedAt: string, completedAt: string | null, };
