// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BudgetAlertRule = { id: string, persona_id: string | null, rule_type: string, threshold_usd: number, enabled: boolean, created_at: string, };
