// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BundleImportOptions = { skip_conflicts: boolean, rename_prefix: string | null, 
/**
 * When set, apply uses the cached preview bytes instead of re-reading the file.
 */
preview_id: string | null, 
/**
 * SHA-256 hash from the preview step. When set, the apply step verifies
 * the bundle bytes match this hash before importing (TOCTOU mitigation).
 */
expected_bundle_hash: string | null, };
