// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Valid roles for chat messages.
 */
export type ChatRole = "user" | "assistant" | "system" | "tool";
