// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CircuitTransitionEvent } from "./CircuitTransitionEvent";
import type { ProviderCircuitState } from "./ProviderCircuitState";

/**
 * Full circuit breaker status snapshot.
 */
export type CircuitBreakerStatus = { providers: Array<ProviderCircuitState>, globalPaused: boolean, globalCooldownRemainingSecs: number, globalFailureCount: number, 
/**
 * Recent state transitions (newest first), capped at 50.
 */
recentTransitions: Array<CircuitTransitionEvent>, };
