// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloudDeployment = { id: string, projectId: string, personaId: string, slug: string, label: string, status: string, webhookEnabled: boolean, webhookSecret: string | null, invocationCount: bigint, lastInvokedAt: string | null, createdAt: string, updatedAt: string, };
