// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloudDailyBreakdown = { date: string, count: bigint, cost: number, successRate: number | null, };
