// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloudWebhookRelayStatus = { connected: boolean, lastPollAt: string | null, activeWebhookTriggers: number, totalRelayed: bigint, error: string | null, };
