// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompileWarning = { "kind": "textFontMissing", overlayId: string, requested: string, fallback: string | null, } | { "kind": "loudnormUnmeasured", audioStageId: string, } | { "kind": "speedClamped", stageId: string, requested: number, applied: number, } | { "kind": "proxyMissing", sourceId: number, originalPath: string, } | { "kind": "audioSourceSilent", sourceId: number, };
