// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Named stages of any compilation pipeline.
 *
 * Every pipeline runs these stages in order.  A stage may short-circuit
 * (e.g. `ResultParsing` can yield a clarification question instead of a result).
 */
export type CompilationStage = "prompt_assembly" | "llm_generation" | "result_parsing" | "validation" | "persist";
