// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate connection health across all peers.
 */
export type ConnectionHealth = { avgLatencyMs: number | null, missedPingCount: number, connectedCount: number, };
