// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextHealthSnapshot = { id: string, project_id: string, group_id: string | null, group_name: string, overall_score: number, security_score: number | null, quality_score: number | null, coverage_score: number | null, debt_score: number | null, issues_found: number, issues_json: string | null, recommendations: string | null, scanned_at: string, };
