// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextAction } from "./ContextAction";
import type { ContextPattern } from "./ContextPattern";

/**
 * A context rule: when a pattern matches, perform an action.
 */
export type ContextRule = { 
/**
 * Unique rule identifier.
 */
id: string, 
/**
 * The persona that owns this rule.
 */
personaId: string, 
/**
 * Human-readable rule name.
 */
name: string, 
/**
 * The pattern to match against context events.
 */
pattern: ContextPattern, 
/**
 * The action to perform when the pattern matches.
 */
action: ContextAction, 
/**
 * Whether this rule is currently active.
 */
enabled: boolean, 
/**
 * Minimum seconds between consecutive matches (prevents spam).
 */
cooldownSecs: number, };
