// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Requirement } from "./Requirement";
import type { UnmetRequirement } from "./UnmetRequirement";

/**
 * The result of resolving all requirements against the current DB state.
 */
export type ContractReport = { 
/**
 * Requirements that are satisfied.
 */
met: Array<Requirement>, 
/**
 * Requirements that are NOT satisfied -- these would cause runtime failure.
 */
unmet: Array<UnmetRequirement>, 
/**
 * True when every requirement is met.
 */
allSatisfied: boolean, };
