// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stats about the context stream (total events broadcast, active subscribers).
 */
export type ContextStreamStats = { 
/**
 * Total events broadcast since engine start.
 */
totalEventsBroadcast: bigint, 
/**
 * Current number of active stream subscribers.
 */
activeSubscribers: number, 
/**
 * Whether the context stream is enabled.
 */
enabled: boolean, };
