// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatePersonaRecipeLinkInput = { persona_id: string, recipe_id: string, sort_order: number | null, config: string | null, };
