// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateReviewMessageInput = { review_id: string, role: string, content: string, metadata: string | null, };
