// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatePersonaGroupInput = { name: string, color: string | null, sortOrder: number | null, description: string | null, };
