// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatePersonaInput = { name: string, system_prompt: string, project_id: string | null, description: string | null, structured_prompt: string | null, icon: string | null, color: string | null, enabled: boolean | null, max_concurrent: number | null, timeout_ms: number | null, model_profile: string | null, max_budget_usd: number | null, max_turns: number | null, design_context: string | null, group_id: string | null, };
