// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateResearchProject = { name: string, description: string | null, domain: string | null, thesis: string | null, scopeConstraints: string | null, teamId: string | null, obsidianVaultPath: string | null, };
