// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateExposedResourceInput = { resource_type: string, resource_id: string, display_name: string, description: string | null, fields_exposed: Array<string>, access_level: string, requires_auth: boolean, tags: Array<string>, expires_at: string | null, };
