// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateRotationPolicyInput = { credential_id: string, rotation_interval_days: number | null, policy_type: string | null, enabled: boolean | null, };
