// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateAutomationInput = { personaId: string, useCaseId: string | null, name: string, description: string | null, platform: string, platformWorkflowId: string | null, platformUrl: string | null, webhookUrl: string | null, webhookMethod: string | null, platformCredentialId: string | null, credentialMapping: string | null, inputSchema: string | null, outputSchema: string | null, timeoutMs: bigint | null, retryCount: number | null, fallbackMode: string | null, };
