// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCredentialInput = { name: string, service_type: string, encrypted_data: string, iv: string, metadata: string | null, session_encrypted_data: string | null, 
/**
 * When true, persist an initial healthcheck_last_success=true on creation
 * (used by catalog flows where the credential was tested before saving).
 */
healthcheck_passed: boolean | null, };
