// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A persona (or team) that depends on a credential.
 */
export type CredentialDependent = { persona_id: string, persona_name: string, 
/**
 * How the dependency was determined: "tool_connector" or "audit_log"
 */
link_type: string, 
/**
 * The connector/service name bridging the dependency.
 */
via_connector: string | null, last_used_at: string | null, };
