// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single entry in the immutable credential audit log.
 */
export type CredentialAuditEntry = { id: string, credentialId: string, credentialName: string, 
/**
 * Operation type: "decrypt", "create", "update", "delete", "healthcheck"
 */
operation: string, personaId: string | null, personaName: string | null, detail: string | null, createdAt: string, };
