// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single entry in the immutable credential audit log.
 */
export type CredentialAuditEntry = { id: string, credential_id: string, credential_name: string, 
/**
 * Operation type: "decrypt", "create", "update", "delete", "healthcheck"
 */
operation: string, persona_id: string | null, persona_name: string | null, detail: string | null, created_at: string, };
