// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a persona deletion, reporting what happened to running executions.
 */
export type DeletePersonaResult = { 
/**
 * True if the persona was successfully deleted from the database.
 */
deleted: boolean, 
/**
 * Number of executions that were cleanly cancelled via the engine.
 */
executionsCancelled: number, 
/**
 * Number of executions that had to be force-marked as cancelled in DB.
 */
executionsForceCancelled: number, 
/**
 * True if the drain timeout was reached before all engine slots cleared.
 */
timeoutReached: boolean, 
/**
 * IDs of executions that could not be cancelled or force-marked.
 */
cancelFailures: Array<string>, };
