// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single message in a design conversation thread.
 */
export type DesignConversationMessage = { 
/**
 * Role of the message author: "user", "assistant", or "system"
 */
role: string, 
/**
 * Message content (instruction, feedback, question, result JSON, etc.)
 */
content: string, 
/**
 * Optional message sub-type for UI rendering hints:
 * "instruction", "feedback", "question", "answer", "result", "error"
 */
messageType: string | null, 
/**
 * ISO 8601 timestamp
 */
timestamp: string, };
