// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file attached during design analysis (API spec, schema, etc.).
 */
export type DesignFile = { name: string, content: string, 
/**
 * File type discriminator: "api-spec", "schema", "mcp-config", "other"
 */
type: string, };
