// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesignFilesSection } from "./DesignFilesSection";
import type { DesignUseCase } from "./DesignUseCase";

/**
 * Structured envelope for the `design_context` JSON column.
 *
 * Three independent sections:
 * - `design_files` — files & references for the AI design prompt
 * - `credential_links` — connector name → credential ID mappings
 * - `use_cases` — structured workflow descriptions from design results
 * - `summary` — optional human-readable summary (legacy compat)
 */
export type DesignContextData = { designFiles: DesignFilesSection | null, credentialLinks: { [key in string]?: string } | null, useCases: Array<DesignUseCase> | null, summary: string | null, };
