// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectorPipelineStep } from "./ConnectorPipelineStep";
import type { DesignFilesSection } from "./DesignFilesSection";
import type { DesignUseCase } from "./DesignUseCase";

/**
 * Structured envelope for the `design_context` JSON column.
 *
 * Independent sections:
 * - `design_files` -- files & references for the AI design prompt
 * - `credential_links` -- connector name -> credential ID mappings
 * - `use_cases` -- structured workflow descriptions from design results
 * - `summary` -- optional human-readable summary (legacy compat)
 * - `connector_pipeline` -- chronological connector interaction sequence
 */
export type DesignContextData = { designFiles: DesignFilesSection | null, credentialLinks: { [key in string]?: string } | null, useCases: Array<DesignUseCase> | null, summary: string | null, connectorPipeline: Array<ConnectorPipelineStep> | null, 
/**
 * Twin profile this persona is pinned to. When `Some`, the
 * `builtin-twin` connector should resolve this id instead of the
 * globally-active twin. Connector resolution wiring is a separate
 * follow-up — for now this is a pure config field round-tripped
 * through the design_context envelope.
 */
twinId: string | null, };
