// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Granular capabilities a desktop connector can request.
 */
export type DesktopCapability = "file_read" | "file_write" | "process_spawn" | "network_local" | "clipboard_read" | "notify" | "env_read" | "system_api";
