// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevProject = { id: string, name: string, root_path: string, description: string | null, status: string, tech_stack: string | null, github_url: string | null, monitoring_credential_id: string | null, monitoring_project_slug: string | null, created_at: string, updated_at: string };
