// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevProject = { id: string, name: string, root_path: string, description: string | null, status: string, tech_stack: string | null, github_url: string | null, monitoring_credential_id: string | null, monitoring_project_slug: string | null, 
/**
 * JSON envelope `{ tool, command }` configuring the static-analysis CLI
 * the `static_scan` runner spawns for this project. None disables the
 * per-project sweep; the runner falls back to package-manager detection.
 */
static_scan_config: string | null, created_at: string, updated_at: string, };
