// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Top failure category with count.
 */
export type DigestFailureCategory = { category: string, count: number, };
