// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DreamFrameEvent } from "./DreamFrameEvent";
import type { JsonValue } from "./serde_json/JsonValue";
import type { SpanType } from "./SpanType";

/**
 * A single reconstructed state frame at a span boundary.
 *
 * Each frame represents the complete execution state at a specific
 * millisecond boundary where a span started or ended.
 */
export type DreamFrame = { 
/**
 * Frame index (0-based, ordered by time).
 */
index: number, 
/**
 * Timestamp in ms from execution start.
 */
timestampMs: number, 
/**
 * What happened at this boundary.
 */
eventType: DreamFrameEvent, 
/**
 * The span that triggered this frame.
 */
triggerSpanId: string, 
/**
 * Human-readable description of what's happening.
 */
description: string, 
/**
 * Span type of the trigger span.
 */
triggerSpanType: SpanType, 
/**
 * All spans currently active (started but not ended) at this timestamp.
 */
activeSpanIds: Array<string>, 
/**
 * All spans completed by this timestamp.
 */
completedSpanIds: Array<string>, 
/**
 * Current tree depth (nesting level of the trigger span).
 */
depth: number, 
/**
 * Cumulative cost up to this frame (USD).
 */
cumulativeCostUsd: number, 
/**
 * Cumulative input tokens up to this frame.
 */
cumulativeInputTokens: number, 
/**
 * Cumulative output tokens up to this frame.
 */
cumulativeOutputTokens: number, 
/**
 * Error at this frame (if the trigger span ended with an error).
 */
error: string | null, 
/**
 * Metadata from the trigger span (tool names, credential names, etc.).
 */
metadata: JsonValue | null, };
