// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContractReport } from "./ContractReport";
import type { DryRunTool } from "./DryRunTool";

/**
 * Result of running the validate-stage checks for a persona without spawning
 * an engine subprocess. All sensitive material (credential values, auth
 * tokens) is intentionally excluded — only the resolved *shape* of the run
 * surfaces here.
 */
export type DryRunReport = { 
/**
 * Synthetic id used for the log file name and trace correlation.
 */
dry_run_id: string, 
/**
 * `true` when every validate check passed and the engine would have
 * proceeded to `SpawnEngine`. Soft warnings do not flip this to `false`.
 */
success: boolean, 
/**
 * Persona that was validated.
 */
persona_id: string, persona_name: string, 
/**
 * Resolved model name (post-cascade). `None` when the persona has no
 * `model_profile.model` configured.
 */
model: string | null, 
/**
 * Provider that would handle the call (e.g. "anthropic", "ollama").
 */
provider: string | null, 
/**
 * Full assembled prompt that would be sent to the engine.
 */
prompt: string, prompt_chars: number, 
/**
 * Tool surface that would have been exposed to the engine.
 */
tools: Array<DryRunTool>, 
/**
 * Names of connectors whose credentials resolved cleanly.
 */
resolved_credentials: Array<string>, 
/**
 * Connector names whose credentials failed to decrypt. Non-empty here
 * flips `success` to false.
 */
credential_failures: Array<string>, 
/**
 * Capability-contract diagnostics (missing connectors / personas /
 * automations).
 */
contract_report: ContractReport | null, 
/**
 * Soft warnings (e.g. unmet contracts, missing credentials) — surfaced
 * to the UI without aborting the dry run.
 */
warnings: Array<string>, 
/**
 * Hard error message if `success == false`.
 */
error: string | null, 
/**
 * Path to the on-disk log file written for this dry run.
 */
log_file_path: string | null, };
