// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type DryRunSimulatedEvent = { event_type: string, source_type: string, source_id: string, target_persona_id: string, target_persona_name: string, payload: JsonValue | null, };
