// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DryRunMatchedSubscription = { subscription_id: string, persona_id: string, persona_name: string, event_type: string, source_filter: string | null, };
