// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigField } from "./ConfigField";

/**
 * The full effective model configuration for a persona, with inheritance metadata.
 */
export type EffectiveModelConfig = {
  personaId: string,
  personaName: string,
  workspaceName: string | null,
  model: ConfigField<string>,
  provider: ConfigField<string>,
  baseUrl: ConfigField<string>,
  authToken: ConfigField<string>,
  maxBudgetUsd: ConfigField<number>,
  maxTurns: ConfigField<number>,
  promptCachePolicy: ConfigField<string>,
};
