// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnclavePolicy } from "./EnclavePolicy";

/**
 * Result of verifying an enclave.
 */
export type EnclaveVerifyResult = { enclaveId: string, signatureValid: boolean, contentIntact: boolean, creatorPeerId: string, creatorDisplayName: string, creatorTrusted: boolean, personaName: string, policy: EnclavePolicy, createdAt: string, enclaveHash: string, };
