// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity level for a classified error.
 */
export type ErrorSeverity = "info" | "low" | "medium" | "high" | "critical";
