// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of an evolution cycle result.
 */
export type EvolutionCycleSummary = { cycleId: string, personaId: string, generation: number, variantsTested: number, winnerFitness: number | null, incumbentFitness: number | null, promoted: boolean, promotedPersonaId: string | null, 
/**
 * Whether all status updates succeeded during the cycle.
 * `false` means the frontend may have shown stale status at some point.
 */
statusReliable: boolean, };
