// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for automatic persona evolution via lab-driven optimization.
 */
export type EvolutionPolicy = { id: string, personaId: string, 
/**
 * Whether auto-evolution is enabled.
 */
enabled: boolean, 
/**
 * JSON-serialized FitnessObjective weights.
 */
fitnessObjective: string, 
/**
 * Mutation rate for variant generation (0.0--1.0).
 */
mutationRate: number, 
/**
 * Number of variants to generate per cycle.
 */
variantsPerCycle: number, 
/**
 * Minimum fitness improvement required to promote a variant (0.0--1.0).
 */
improvementThreshold: number, 
/**
 * Minimum completed executions between evolution cycles.
 */
minExecutionsBetween: number, 
/**
 * Timestamp of last completed evolution cycle.
 */
lastCycleAt: string | null, 
/**
 * Total cycles completed.
 */
totalCycles: number, 
/**
 * Total successful promotions.
 */
totalPromotions: number, createdAt: string, updatedAt: string, };
