// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical execution state machine.
 *
 * Valid transitions:
 *   Queued   -> Running | Failed | Cancelled
 *   Running  -> Completed | Failed | Incomplete | Cancelled
 *
 * This is the single source of truth for execution status. The DB column
 * stores the lowercase string form, the frontend `isExecuting` boolean is
 * derived from `is_active()`, and event payloads carry this enum serialized.
 *
 * The TS binding is exported via ts_rs and consumed by the frontend
 * `executionState.ts` module. **Do not add variants here without updating
 * the `TERMINAL` / `ACTIVE` slices and the compile-time assertion test.**
 */
export type ExecutionState = "queued" | "running" | "completed" | "failed" | "incomplete" | "cancelled";
