// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionSearchResult = { id: string, persona_id: string, persona_name: string | null, persona_icon: string | null, persona_color: string | null, use_case_id: string | null, status: string, excerpt: string, created_at: string, completed_at: string | null, };
