// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-authored annotation on a single persona execution. Free-form tags,
 * a short note, and a star flag — mirrors LangSmith trace annotations.
 * One row per (execution_id, author); re-saving overwrites the prior value.
 */
export type ExecutionAnnotation = { id: string, execution_id: string, persona_id: string, author: string, 
/**
 * Free-form labels (e.g. "regression", "golden-example", "investigate").
 */
tags: Array<string>, note: string | null, starred: boolean, created_at: string, updated_at: string, };
