// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardCostAnomaly } from "./DashboardCostAnomaly";
import type { DashboardDailyPoint } from "./DashboardDailyPoint";
import type { DashboardTopPersona } from "./DashboardTopPersona";

/**
 * Combined response for the execution metrics dashboard.
 */
export type ExecutionDashboardData = { daily_points: Array<DashboardDailyPoint>, top_personas: Array<DashboardTopPersona>, cost_anomalies: Array<DashboardCostAnomaly>, total_executions: number, total_cost: number, overall_success_rate: number, avg_latency_ms: number, };
