// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resource the user has chosen to expose to the P2P network.
 */
export type ExposedResource = { id: string, resource_type: string, resource_id: string, display_name: string, description: string | null, fields_exposed: string, access_level: string, requires_auth: boolean, tags: string, created_at: string, expires_at: string | null, };
