// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Labels that can be applied to template feedback.
 * This is the single source of truth — the TypeScript type is auto-generated via ts-rs.
 */
export type FeedbackLabel = "accurate_prompt" | "good_tool_selection" | "reliable" | "cost_efficient" | "wrong_tools" | "poor_instructions" | "missing_context" | "over_engineered" | "under_specified" | "wrong_triggers" | "credential_issues";
