// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rating sentiment for template feedback.
 * This is the single source of truth — the TypeScript type is auto-generated via ts-rs.
 */
export type FeedbackRating = "positive" | "negative" | "neutral";
