// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitLabDeploymentRecord = {
  id: string;
  personaId: string;
  personaName: string;
  projectId: number;
  /** "api" or "agents_md" */
  method: string;
  credentialsProvisioned: number;
  /** "success" or "failed" */
  deployResult: string;
  agentId: string | null;
  webUrl: string | null;
  /** Snapshot of the system prompt at deploy time */
  snapshotPrompt: string | null;
  /** If this was a rollback, the ID of the deployment it rolled back from */
  rolledBackFrom: string | null;
  createdAt: string;
};
