// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitLabAgentTool = { name: string, description: string, inputSchema: Record<string, unknown> | null, };
