// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitLabAgentTool } from "./GitLabAgentTool";

export type GitLabAgentDefinition = { name: string, description: string, systemPrompt: string, model: string | null, tools: Array<GitLabAgentTool>, metadata: Record<string, unknown> | null, };
