// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitLabDeployResult = { agentId: string | null, webUrl: string | null, 
/**
 * "api" if deployed via Duo Agent API, "agents_md" if via AGENTS.md file
 */
method: string, 
/**
 * Number of credentials provisioned as CI/CD variables (0 if not requested)
 */
credentialsProvisioned: number, };
