// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HealingKnowledge = { id: string, service_type: string, pattern_key: string, description: string, recommended_delay_secs: number | null, occurrence_count: number, last_seen_at: string, created_at: string, };
