// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An entry in the healing audit log that captures events where healing
 * subsystems attempted an action but silently could not complete it.
 */
export type HealingAuditEntry = { id: string, personaId: string | null, executionId: string | null, 
/**
 * "knowledge_parse_error" | "knowledge_persist_error" | "ai_heal_section_missing"
 * | "ai_heal_unknown_target" | "ai_heal_unknown_fix_type" | "dedup_skipped"
 */
eventType: string, 
/**
 * Which subsystem produced this entry (e.g. "knowledge_extraction", "ai_healing", "healing_analysis")
 */
subsystem: string, message: string, detail: string | null, createdAt: string, };
