// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KbDocument = { id: string, kbId: string, sourceType: string, sourcePath: string | null, title: string, contentHash: string, byteSize: number, chunkCount: number, metadataJson: string | null, status: string, errorMessage: string | null, indexedAt: string | null, createdAt: string, };
