// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A knowledge base match result from vector search.
 */
export type KbMatch = { 
/**
 * Name of the knowledge base that contained the match.
 */
kbName: string, 
/**
 * The chunk text that matched.
 */
chunkText: string, 
/**
 * Cosine similarity score (0.0 = no similarity, lower distance = better match).
 */
similarity: number, 
/**
 * Source file path of the matched chunk (if available).
 */
sourceFile: string | null, };
