// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionKnowledge } from "./ExecutionKnowledge";

/**
 * Dashboard summary of the knowledge graph for a persona or globally.
 */
export type KnowledgeGraphSummary = { total_entries: number, tool_sequence_count: number, failure_pattern_count: number, model_performance_count: number, top_patterns: Array<ExecutionKnowledge>, recent_learnings: Array<ExecutionKnowledge>, };
