// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KnowledgeBase = { id: string, credentialId: string, name: string, description: string | null, embeddingModel: string, embeddingDims: number, chunkSize: number, chunkOverlap: number, documentCount: number, chunkCount: number, status: string, createdAt: string, updatedAt: string, };
