// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabRunStatus } from "./LabRunStatus";

export type LabArenaRun = { id: string, personaId: string, status: LabRunStatus, modelsTested: string, scenariosCount: number, useCaseFilter: string | null, summary: string | null, llmSummary: string | null, progressJson: string | null, error: string | null, createdAt: string, completedAt: string | null, };
