// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabRunStatus } from "./LabRunStatus";

export type LabConsensusRun = { id: string, personaId: string, status: LabRunStatus, numSamples: number, modelId: string, scenariosCount: number, useCaseFilter: string | null, agreementRate: number | null, summary: string | null, llmSummary: string | null, progressJson: string | null, error: string | null, createdAt: string, completedAt: string | null, };
