// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabRunStatus } from "./LabRunStatus";

export type LabEvalRun = { id: string, personaId: string, status: LabRunStatus, 
/**
 * Version IDs, e.g. ["uuid1","uuid2","uuid3"]
 */
versionIds: Array<string>, 
/**
 * Version numbers, e.g. [1,3,5]
 */
versionNumbers: Array<number>, modelsTested: Array<string>, scenariosCount: number, useCaseFilter: string | null, testInput: string | null, summary: string | null, llmSummary: string | null, progressJson: string | null, error: string | null, createdAt: string, completedAt: string | null, };
