// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload sent from the frontend when saving a Langfuse connection
 * manually. The managed-stack flow uses `langfuse_stack_start` instead and
 * never goes through this struct.
 */
export type LangfuseSaveRequest = { host: string, publicKey: string, secretKey: string, redactContent: boolean, enabled: boolean, 
/**
 * Optional project id for "Open in Langfuse" deep links. Empty / absent
 * means we don't know — the deep-link button is hidden in that case.
 */
projectId: string | null, };
