// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LangfuseJobKind } from "./LangfuseJobKind";

/**
 * Returned by `langfuse_stack_start` so the frontend has a job id to
 * correlate against progress events. The actual start work runs in a
 * detached tokio task — this command does not block.
 */
export type LangfuseJobHandle = { jobId: string, kind: LangfuseJobKind, };
