// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LangfuseJobKind } from "./LangfuseJobKind";

/**
 * Final event emitted on `langfuse://stack/done` when a background job
 * completes (success or failure). Frontend uses this to clear the
 * in-progress UI state.
 */
export type LangfuseStackDone = { jobId: string, kind: LangfuseJobKind, success: boolean, error: string | null, 
/**
 * For `InstallerDownload`, the absolute path of the saved installer.
 */
installerPath: string | null, };
