// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Computed anomaly scores for a credential, persisted in the ledger.
 */
export type LedgerAnomalyScore = { failure_rate_total: number, failure_rate_5m: number, failure_rate_1h: number, failure_rate_24h: number, permanent_failure_rate_1h: number, transient_failure_rate_1h: number, remediation: string, sample_count: number, data_stale: boolean, };
