// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaManualReview } from "./PersonaManualReview";

/**
 * One keyset-paginated page of manual reviews, newest-first — the L1/L2 layer of the overview layered-fetch contract. `nextCursor` is null once the list is exhausted.
 */
export type ManualReviewPage = { rows: Array<PersonaManualReview>, nextCursor: string | null, hasMore: boolean, };
