// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable snapshot of messaging metrics for the frontend.
 */
export type MessagingMetrics = { messagesSent: bigint, messagesReceived: bigint, messagesDroppedBufferFull: bigint, messagesRateLimited: bigint, bytesSent: bigint, bytesReceived: bigint, };
