// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaMessage } from "./PersonaMessage";

/**
 * Summary of a message thread: the parent message plus reply count and latest reply timestamp.
 */
export type MessageThreadSummary = { threadId: string, parent: PersonaMessage, replyCount: bigint, latestReplyAt: string | null, };
