// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A topic mentioned across several notes that doesn't have its own page yet.
 */
export type MissingPageCandidate = { 
/**
 * The topic / concept that should have a dedicated page.
 */
topic: string, 
/**
 * Vault-relative paths where the topic is mentioned without a wikilink.
 */
mentionedIn: Array<string>, 
/**
 * One-sentence justification for why a dedicated page would help.
 */
rationale: string, };
