// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of activating/deactivating a workflow.
 */
export type N8nActivateResult = { id: string, active: boolean, };
