// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionStatus } from "./SessionStatus";

export type N8nSessionResponse = { id: string, workflow_name: string, status: SessionStatus, raw_workflow_json: string, parser_result: unknown | null, draft_json: unknown | null, user_answers: unknown | null, step: string, error: string | null, persona_id: string | null, transform_id: string | null, questions_json: unknown | null, created_at: string, updated_at: string, };
