// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaEvent } from "./PersonaEvent";

export type PaginatedEvents = { events: Array<PersonaEvent>, has_more: boolean, };
