// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An entry in a peer's synced manifest.
 */
export type PeerManifestEntry = { id: string, peer_id: string, resource_type: string, resource_id: string, display_name: string, access_level: string, tags: Array<string>, synced_at: string, };
