// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in `persona_curation_schedule`. Public type returned to the
 * frontend.
 */
export type PersonaCurationSchedule = { personaId: string, 
/**
 * 5-field cron expression (minutes hours dom month dow). Validated
 * against `engine::cron::parse_cron` at IPC boundary.
 */
cronExpr: string, lastCurationAt?: string, createdAt: string, updatedAt: string, };
