// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaSlaStats = { persona_id: string, persona_name: string, total_executions: bigint, successful: bigint, failed: bigint, cancelled: bigint, 
/**
 * Success rate as 0.0–1.0.
 */
success_rate: number, avg_duration_ms: number, p95_duration_ms: number, total_cost_usd: number, 
/**
 * Mean time between failures in seconds (null if < 2 failures).
 */
mtbf_seconds: number | null, 
/**
 * Count of consecutive recent failures (0 = healthy).
 */
consecutive_failures: bigint, 
/**
 * Number of healing issues auto-fixed for this persona.
 */
auto_healed_count: bigint, };
