// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildPhase } from "./BuildPhase";
import type { JsonValue } from "./serde_json/JsonValue";

export type PersistedBuildSession = { id: string, personaId: string, phase: BuildPhase, resolvedCells: JsonValue, pendingQuestion: JsonValue | null, agentIr: JsonValue | null, intent: string, errorMessage: string | null, createdAt: string, };
