// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaHealth } from "./PersonaHealth";

/**
 * Lightweight summary for sidebar badges: trigger count, last execution time, and health.
 */
export type PersonaSummary = { personaId: string, enabledTriggerCount: bigint, lastRunAt: string | null, health: PersonaHealth, };
