// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight summary for sidebar badges: trigger count and last execution time.
 */
export type PersonaSummary = { persona_id: string, enabled_trigger_count: bigint, last_run_at: string | null, };
