// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaToolUsage = { id: string, execution_id: string, persona_id: string, tool_name: string, invocation_count: number, created_at: string, };
