// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaEventStatus = "pending" | "processing" | "delivered" | "completed" | "skipped" | "failed" | "dead_letter" | "discarded";
