// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaHealingIssue = { id: string, persona_id: string, execution_id: string | null, title: string, description: string, severity: string, category: string, suggested_fix: string | null, auto_fixed: boolean, status: string, created_at: string, resolved_at: string | null, };
