// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaTeam = { id: string, project_id: string | null, name: string, description: string | null, canvas_data: string | null, team_config: string | null, icon: string | null, color: string, enabled: boolean, created_at: string, updated_at: string, };
