// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Origin of a persona's trust classification.
 */
export type PersonaTrustOrigin = "builtin" | "user" | "system";
