// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaTrigger = { id: string, persona_id: string, trigger_type: string, config: string | null, enabled: boolean, 
/**
 * Persisted lifecycle status: "active", "paused", "errored", or "disabled".
 * Added by migration; older rows are backfilled from `enabled`.
 */
status: string, last_triggered_at: string | null, next_trigger_at: string | null, 
/**
 * Monotonic version counter for race-safe CAS in `mark_triggered`.
 */
trigger_version: number, created_at: string, updated_at: string, use_case_id: string | null, };
