// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaSkill = { id: string, personaId: string, skillId: string, enabled: boolean, config: string | null, createdAt: string, };
