// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigGene } from "./ConfigGene";
import type { ModelGene } from "./ModelGene";
import type { PromptSegment } from "./PromptSegment";
import type { ToolGene } from "./ToolGene";

/**
 * The complete decomposed genome of a persona.
 */
export type PersonaGenome = { 
/**
 * Source persona ID this genome was extracted from.
 */
sourcePersonaId: string, 
/**
 * Source persona name (for display).
 */
sourcePersonaName: string, 
/**
 * System prompt decomposed into paragraph-level segments.
 */
promptSegments: Array<PromptSegment>, 
/**
 * Structured prompt JSON (kept as opaque string for crossover).
 */
structuredPrompt: string | null, 
/**
 * Tool selection and ordering.
 */
tools: ToolGene, 
/**
 * Model/provider preferences.
 */
model: ModelGene, 
/**
 * Behavioral configuration.
 */
config: ConfigGene, 
/**
 * Description text.
 */
description: string | null, };
