// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonaMetricsSnapshot = { id: string, persona_id: string, snapshot_date: string, total_executions: number, successful_executions: number, failed_executions: number, total_cost_usd: number, total_input_tokens: number, total_output_tokens: number, avg_duration_ms: number, tools_used: string | null, events_emitted: number, events_consumed: number, messages_sent: number, created_at: string, };
