// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectHealthEntry } from "./ProjectHealthEntry";

/**
 * Summary returned by the portfolio health tool.
 */
export type PortfolioHealthSummary = { total_projects: number, active_projects: number, total_ideas: number, pending_ideas: number, total_tasks: number, running_tasks: number, avg_health_score: number | null, projects: Array<ProjectHealthEntry>, };
