// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Daily-bucketed performance data point for the Prompt Performance Dashboard.
 */
export type PromptPerformancePoint = { date: string, avg_cost_usd: number, avg_duration_ms: number, avg_input_tokens: number, avg_output_tokens: number, total_executions: number, success_count: number, failed_count: number, error_rate: number, 
/**
 * Percentile latencies computed from raw durations
 */
p50_duration_ms: number, p95_duration_ms: number, p99_duration_ms: number, };
