// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PromptAbExecResult = { status: string, duration_ms: number | null, cost_usd: number, input_tokens: number, output_tokens: number, output_preview: string | null, error_message: string | null, };
