// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Two notes that should be cross-linked but aren't.
 */
export type ProposedLink = { 
/**
 * Vault-relative path of the note that should gain the wikilink.
 */
fromPath: string, 
/**
 * Vault-relative path of the target note.
 */
toPath: string, 
/**
 * Why the LLM believes these notes should be linked.
 */
rationale: string, };
