// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of testing a provider connection.
 */
export type ProviderConnectionResult = { provider_id: string, reachable: boolean, latency_ms: bigint | null, version: string | null, error: string | null, };
