// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncConflict } from "./SyncConflict";

export type PullSyncResult = { created: bigint, updated: bigint, conflicts: Array<SyncConflict>,
/**
 * Count of entities where both app and vault sides edited independently
 * but ended up identical (lucky convergence). Distinct from a no-op:
 * surfaces in the UI as a confirmation toast so the user can see the
 * audit trail of avoided conflicts.
 */
converged: bigint, errors: Array<string>, };
