// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type QueryResult = { columns: Array<string>, rows: Array<Array<JsonValue>>, row_count: number, duration_ms: number, truncated: boolean, };
