// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type RecipeExecutionResult = { recipe_id: string, recipe_name: string, rendered_prompt: string, llm_output: string | null, input_data: { [key in string]?: JsonValue }, executed_at: string, };
