// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecipeVersionDraft = { prompt_template: string, input_schema: string | null, sample_inputs: string | null, description: string | null, changes_summary: string | null, };
