// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Remediation action recommended by the anomaly scorer.
 */
export type Remediation = "Healthy" | "BackoffRetry" | "PreemptiveRotation" | "RotateThenAlert" | "Disable";
