// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResearchExperiment = { id: string, projectId: string, hypothesisId: string | null, name: string, methodology: string | null, inputSchema: string | null, successCriteria: string | null, status: string, pipelineId: string | null, createdAt: string, updatedAt: string, };
