// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResearchCitation = { id: string, sourceId: string, citedSourceId: string | null, citedReference: string | null, context: string | null, createdAt: string, };
