// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entry in the risk matrix aggregation.
 */
export type RiskMatrixEntry = { project_id: string, project_name: string, risk_category: string, severity: string, description: string, affected_contexts: Array<string>, };
