// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome status for a credential rotation attempt.
 *
 * This is a terminal status (no further transitions) -- each rotation
 * attempt produces exactly one status when it completes.
 *
 * Stored in `credential_rotation_history.status TEXT`.
 */
export type RotationEntryStatus = "success" | "failed" | "skipped";
