// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * v3.2 — Locked enum for `sample_output.format` (D-01). Unknown values are
 * rejected at deserialize time by serde; the normalizer also warn-and-coerces
 * any unknown JSON string it sees before deserialize (defense-in-depth).
 */
export type SampleOutputFormat = "markdown" | "plain" | "json" | "html";
