// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Valid session statuses for an n8n transform session.
 * Use `as_str()` when writing to the database or setting status fields.
 */
export type SessionStatus = "draft" | "analyzing" | "transforming" | "awaiting_answers" | "editing" | "confirmed" | "failed" | "interrupted";
