// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SharedEventFiring = { id: string, catalogSlug: string, eventType: string, payload: string | null, firedAt: string, };
