// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user's subscription to a shared event feed.
 */
export type SharedEventSubscription = { id: string, catalogEntryId: string, slug: string, enabled: boolean, lastCursor: string | null, eventsRelayed: bigint, lastEventAt: string | null, error: string | null, createdAt: string, updatedAt: string, };
