// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SharedEventRelayStatus = { connected: boolean, lastPollAt: string | null, activeFeeds: number, totalRelayed: bigint, error: string | null, };
