// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentSignature } from "./DocumentSignature";

/**
 * Input for creating a new signature (returned by sign operation).
 */
export type SignDocumentResult = { signature: DocumentSignature, 
/**
 * The detached signature JSON that can be saved alongside the document.
 */
sidecar_json: string, };
