// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmeeRelayStatus = { channelUrl: string | null, connected: boolean, eventsRelayed: bigint, lastEventAt: string | null, error: string | null, };
