// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-channel result returned by `test_channel_delivery`. (DELIV-06, D-07)
 * NOTE: the IPC command itself lives in Plan 02; the type lives here so the
 * binding regen can attach to a single file.
 */
export type TestDeliveryResult = { channelType: string, success: boolean, latencyMs: bigint, error: string | null, rateLimited: boolean | null, };
