// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result from running tests on a project.
 */
export type TestRunResult = { project_id: string, success: boolean, total_tests: number, passed: number, failed: number, skipped: number, duration_ms: bigint, output: string, error: string | null, };
