// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One YouTube track for a `youtubeTracks` station.
 */
export type Track = { videoId: string, title: string, artist: string, 
/**
 * Optional — null in the seed; the IFrame Player reports the real
 * duration at runtime.
 */
durationSec: number | null, };
