// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle states for a persona trigger.
 *
 * Valid transitions:
 *   Active  -> Paused | Errored | Disabled
 *   Paused  -> Active | Disabled
 *   Errored -> Active | Paused | Disabled
 *   Disabled -> Active
 *
 * Persisted in the `status TEXT` column on `persona_triggers`.
 * The legacy `enabled INTEGER` column is kept in sync for backwards
 * compatibility with queries that filter on `enabled = 1`.
 */
export type TriggerStatus = "active" | "paused" | "errored" | "disabled";
