// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle states for a persona trigger.
 *
 * Valid transitions:
 *   Active  -> Paused | Errored | Disabled
 *   Paused  -> Active | Disabled
 *   Errored -> Active | Paused | Disabled
 *   Disabled -> Active
 *
 * The DB stores `enabled INTEGER` (0|1). For backwards compatibility,
 * use [`TriggerStatus::from_enabled`] / [`TriggerStatus::is_enabled`]
 * to bridge the gap until a full migration adds a status column.
 */
export type TriggerStatus = "active" | "paused" | "errored" | "disabled";
