// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerValidationCheck } from "./TriggerValidationCheck";

export type TriggerValidationResult = { valid: boolean, checks: Array<TriggerValidationCheck>, };
