// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary returned to the UI after a docs ingest pass.
 */
export type TwinIngestDocsSummary = { filesIngested: number, chunksAdded: number, filesSkipped: number, };
