// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TwinVoiceProfile = { id: string, twin_id: string, 
/**
 * Voice provider: "elevenlabs" (only option for now).
 */
provider: string, 
/**
 * FK to the credential vault — the ElevenLabs API key credential.
 */
credential_id: string | null, 
/**
 * The provider-specific voice identifier (e.g. ElevenLabs voice ID).
 */
voice_id: string, 
/**
 * ElevenLabs model ID (e.g. "eleven_multilingual_v2").
 */
model_id: string | null, 
/**
 * Stability slider 0.0–1.0 (higher = more consistent, lower = more expressive).
 */
stability: number, 
/**
 * Similarity boost 0.0–1.0 (higher = closer to original voice).
 */
similarity_boost: number, 
/**
 * Style exaggeration 0.0–1.0.
 */
style: number, updated_at: string, };
