// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationDeployStatus } from "./AutomationDeployStatus";
import type { AutomationFallbackMode } from "./AutomationFallbackMode";

export type UpdateAutomationInput = { name: string | null, description: string | null, useCaseId: string | null | null, platformWorkflowId: string | null | null, platformUrl: string | null | null, webhookUrl: string | null | null, webhookMethod: string | null, platformCredentialId: string | null | null, credentialMapping: string | null | null, inputSchema: string | null | null, outputSchema: string | null | null, timeoutMs: bigint | null, retryCount: number | null, fallbackMode: AutomationFallbackMode | null, deploymentStatus: AutomationDeployStatus | null, errorMessage: string | null | null, };
