// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCredentialInput = { name: string | null, service_type: string | null, encrypted_data: string | null, 
/**
 * Derived from encryption — never set by callers.
 * skip_deserializing ensures this is always None from IPC input;
 * the command layer sets it from the encryption result.
 */
iv: string | null, metadata: string | null | null, };
