// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frontend-facing generation policy. Mirrors the TS `UseCaseGenerationSettings`
 * shape. All fields optional so callers can patch one knob without rewriting
 * the whole struct.
 */
export type UseCaseGenerationSettings = { memories: string | null, reviews: string | null, events: string | null, event_aliases: { [key in string]?: string } | null, };
