// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Webhook source attachment payload — captured during the build wizard
 * when the LLM picks `trigger_type: "webhook"` for a capability and asks
 * the user for a smee.io URL via a clarifying_question carrying
 * `accepts_webhook_source: true`. C7 (2026-04-28).
 *
 * The frontend submits this via `answer_build_question`; the answer
 * command appends a fenced summary of the URL to the answer text so the
 * LLM can place it on the trigger config's `smee_channel_url` field.
 * Promote-time then reads the trigger config and auto-creates a
 * `smee_relays` row pointing at this persona.
 */
export type UserWebhookSource = { 
/**
 * `https://smee.io/<channel>` URL the user pasted (or created at
 * smee.io/new and copied back).
 */
channelUrl: string, 
/**
 * Optional comma-separated `event_type` allowlist forwarded to the
 * `smee_relays.event_filter` column. Empty / None means no filter
 * (relay forwards every smee event to the persona).
 */
eventFilter: string | null, };
