// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrokenWikilink } from "./BrokenWikilink";
import type { OrphanNote } from "./OrphanNote";
import type { StaleNote } from "./StaleNote";

export type VaultLintReport = { vaultPath: string, scannedCount: bigint, staleNotes: Array<StaleNote>, brokenWikilinks: Array<BrokenWikilink>, orphans: Array<OrphanNote>, generatedAt: string, };
