// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VaultConnectionResult = { valid: boolean, noteCount: bigint, vaultName: string, error: string | null, };
