import { invokeWithTimeout as invoke } from "@/lib/tauriInvoke";

// Types mirror src-tauri/src/engine/director.rs. Canonical bindings are
// generated by ts-rs on `cargo test` under src/lib/bindings/ — once they
// land we can switch to importing from there.

export type DirectorSeverity = 'info' | 'warning' | 'error';

export type DirectorCategory =
  | 'prompt'
  | 'health'
  | 'triggers'
  | 'credentials'
  | 'memory'
  | 'usefulness';

export interface DirectorReport {
  evaluatedPersonas: number;
  verdictsEmitted: number;
  personasSkippedNoExecutions: number;
  generatedAt: string;
}

export interface DirectorVerdictRow {
  reviewId: string;
  personaId: string;
  severity: string;
  category: string;
  title: string;
  description: string | null;
  rationale: string | null;
  suggestedActions: string[];
  status: string;
  createdAt: string;
  executionId: string;
}

export async function getDirectorPersonaId(): Promise<string> {
  return invoke<string>('get_director_persona_id');
}

// Phase 2 runs the Director persona through the execution runner and polls it
// to completion, so a single evaluation can take minutes (backend ceiling is
// 360s). Use generous timeouts well above the default 90s.
const DIRECTOR_RUN_TIMEOUT_MS = 420_000; // 7 min — one target
const DIRECTOR_BATCH_TIMEOUT_MS = 1_800_000; // 30 min — sequential over many

export async function runDirectorOnPersona(personaId: string): Promise<number> {
  return invoke<number>('run_director_on_persona', { personaId }, { timeoutMs: DIRECTOR_RUN_TIMEOUT_MS });
}

export async function runDirectorBatch(maxPersonas?: number): Promise<DirectorReport> {
  return invoke<DirectorReport>(
    'run_director_batch',
    { maxPersonas: maxPersonas ?? null },
    { timeoutMs: DIRECTOR_BATCH_TIMEOUT_MS },
  );
}

export async function listDirectorVerdicts(personaId?: string): Promise<DirectorVerdictRow[]> {
  return invoke<DirectorVerdictRow[]>('list_director_verdicts', {
    personaId: personaId ?? null,
  });
}
