#!/usr/bin/env node
/**
 * rustTsExports — discovers every `#[derive(TS)] #[ts(export)]` type in a Rust
 * tree, i.e. every type that ts-rs will WRITE a file for under
 * `src/lib/bindings/`.
 *
 * ---------------------------------------------------------------------------
 * WHY THIS EXISTS
 * ---------------------------------------------------------------------------
 * The CI binding-drift job is diff-shaped (`git diff --quiet src/lib/bindings/`),
 * and ts-rs never DELETES: when a Rust type is removed, its generated `.ts` file
 * simply stays on disk forever, producing no diff and no untracked file. A
 * diff-shaped gate cannot see that by construction. Only an inventory of what
 * SHOULD exist can, and that is what this module builds.
 *
 * ---------------------------------------------------------------------------
 * PARSING NOTES — every one of these is a shape that ACTUALLY EXISTS here
 * ---------------------------------------------------------------------------
 *  - The attribute is `#[ts(export)]`, occasionally with arguments
 *    (`#[ts(export, concrete(T = String))]`). Match the `export` TOKEN, not the
 *    whole literal.
 *  - Doc comments, line comments and further attributes sit between the
 *    attribute and the item — the same trap that cost check-command-registration
 *    seven definitions.
 *  - **Attributes span multiple lines.** `src/radio/mod.rs:49` has a four-line
 *    `#[serde( tag = "kind", … )]` between `#[ts(export)]` and its enum. A
 *    line-shaped "is this an attribute?" test sees line 2 (`tag = "kind",`) as
 *    the item and gives up. Bracket depth, not line shape, is what skips an
 *    attribute.
 *  - **Some exported types are generated by a `macro_rules!`.** `#[ts(export)]`
 *    appears once inside `declare_lifecycle!` (core/src/lifecycle.rs:155) and
 *    produces THREE real bindings (ExecutionState, TriggerStatus,
 *    AutomationDeployStatus) whose names exist only at the call sites. This is
 *    the documented reason an earlier count was wrong by 19: "macro-generated
 *    derives have no literal `enum` line". So a `#[ts(export)]` inside a macro
 *    body is resolved by walking that macro's INVOCATIONS instead.
 *  - Types are gated behind cargo features (`ml`, `p2p`, `desktop`). A gated
 *    type still HAS Rust source, so it is not an orphan; gates are ignored.
 *  - `#[ts(rename = …)]` / `#[ts(export_to = …)]` appear ZERO times here
 *    (measured), so the emitted file name IS the Rust item name. If either is
 *    ever introduced, `renamed` reports it rather than silently mapping to the
 *    wrong file — a rename would make a live type look like an orphan.
 */
import { readdirSync, readFileSync, statSync } from "node:fs";
import { resolve, join, dirname, sep } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DEFAULT_RUST_ROOT = resolve(__dirname, "..", "..", "src-tauri");

const SKIP_DIRS = new Set(["target", "node_modules", "gen", ".git"]);

/** Recursively collect *.rs files under `root`, sorted for determinism. */
export function collectRustFiles(root) {
  const out = [];
  const walk = (dir) => {
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      const full = join(dir, e.name);
      if (e.isDirectory()) {
        if (!SKIP_DIRS.has(e.name)) walk(full);
      } else if (e.isFile() && e.name.endsWith(".rs")) {
        out.push(full);
      }
    }
  };
  if (statSync(root, { throwIfNoEntry: false })) walk(root);
  return out.sort();
}

const TS_ATTR_START = /^\s*#\[ts\(/;
const ATTR_START = /^\s*#!?\[/;
const LINE_COMMENT = /^\s*\/\//;
const ITEM = /^\s*(?:pub(?:\s*\([^)]*\))?\s+)?(struct|enum|type)\s+([A-Za-z_][A-Za-z0-9_]*)/;
const MACRO_DEF = /^\s*(?:#\[macro_export\]\s*)?macro_rules!\s+([A-Za-z_][A-Za-z0-9_]*)/;

/** Count `[`/`]` outside of string literals — good enough for attribute text. */
function bracketDelta(line) {
  let d = 0;
  let inStr = false;
  for (let k = 0; k < line.length; k++) {
    const c = line[k];
    if (inStr) {
      if (c === "\\") k++;
      else if (c === '"') inStr = false;
      continue;
    }
    if (c === '"') inStr = true;
    else if (c === "[") d++;
    else if (c === "]") d--;
    else if (c === "/" && line[k + 1] === "/") break; // rest is a comment
  }
  return d;
}

/**
 * Read a complete attribute starting at `i`, returning its text and the index
 * of the first line after it. Handles attributes spanning any number of lines.
 */
function readAttr(lines, i) {
  let depth = 0;
  let text = "";
  let j = i;
  do {
    text += lines[j];
    depth += bracketDelta(lines[j]);
    j++;
  } while (depth > 0 && j < lines.length);
  return { text, next: j };
}

/**
 * From line `i`, skip doc comments / line comments / blank lines / attributes
 * (multi-line included) and return the first line index that is none of those.
 */
function skipToItem(lines, i) {
  let j = i;
  while (j < lines.length) {
    if (lines[j].trim() === "" || LINE_COMMENT.test(lines[j])) {
      j++;
      continue;
    }
    if (ATTR_START.test(lines[j])) {
      j = readAttr(lines, j).next;
      continue;
    }
    return j;
  }
  return j;
}

/** Line ranges of every `macro_rules!` body in a file, by macro name. */
function macroBodies(lines) {
  const bodies = [];
  for (let i = 0; i < lines.length; i++) {
    const m = MACRO_DEF.exec(lines[i]);
    if (!m) continue;
    // Walk brace depth from this line to find the body's end.
    let depth = 0;
    let started = false;
    let j = i;
    for (; j < lines.length; j++) {
      for (const c of lines[j]) {
        if (c === "{") {
          depth++;
          started = true;
        } else if (c === "}") depth--;
      }
      if (started && depth <= 0) break;
    }
    bodies.push({ name: m[1], start: i, end: Math.min(j, lines.length - 1) });
    i = j;
  }
  return bodies;
}

/**
 * @param {string} [rustRoot]
 * @returns {{
 *   exports: {name:string,kind:string,file:string,line:number,viaMacro?:string}[],
 *   unresolved: {file:string,line:number,reason:string}[],
 *   renamed: {file:string,line:number,attr:string}[],
 *   macroTemplates: {macro:string,file:string,line:number}[],
 * }}
 */
export function discoverTsExports(rustRoot) {
  const root = rustRoot ? resolve(rustRoot) : DEFAULT_RUST_ROOT;
  const files = collectRustFiles(root);
  const exports = [];
  const unresolved = [];
  const renamed = [];
  const macroTemplates = [];

  const parsed = files.map((file) => ({
    file,
    rel: file.slice(root.length + 1).split(sep).join("/"),
    lines: readFileSync(file, "utf-8").split(/\r?\n/),
  }));

  for (const { rel, lines } of parsed) {
    const bodies = macroBodies(lines);
    for (let i = 0; i < lines.length; i++) {
      if (!TS_ATTR_START.test(lines[i])) continue;
      const { text, next } = readAttr(lines, i);
      const args = text.replace(/^\s*#\[ts\(/, "").replace(/\)\]\s*$/, "");
      if (!/(^|[\s,])export([\s,)]|$)/.test(args)) continue;
      if (/\b(rename|export_to)\s*=/.test(args)) {
        renamed.push({ file: rel, line: i + 1, attr: text.trim() });
      }

      const inMacro = bodies.find((b) => i >= b.start && i <= b.end);
      if (inMacro) {
        // The item name lives at the call sites, not here.
        macroTemplates.push({ macro: inMacro.name, file: rel, line: i + 1 });
        i = next - 1;
        continue;
      }

      const j = skipToItem(lines, next);
      const found = j < lines.length ? ITEM.exec(lines[j]) : null;
      if (found) {
        exports.push({ name: found[2], kind: found[1], file: rel, line: j + 1 });
      } else {
        unresolved.push({ file: rel, line: i + 1, reason: "no item after #[ts(export)]" });
      }
      i = next - 1;
    }
  }

  // Resolve macro-generated exports by walking every invocation of each macro
  // whose body carries a `#[ts(export)]`.
  const macroNames = [...new Set(macroTemplates.map((t) => t.macro))];
  for (const macro of macroNames) {
    const call = new RegExp(`(?:^|[^A-Za-z0-9_$])(?:(?:\\$crate|crate)::)?${macro}!\\s*[{(\\[]`);
    let hits = 0;
    for (const { rel, lines } of parsed) {
      const bodies = macroBodies(lines);
      for (let i = 0; i < lines.length; i++) {
        if (!call.test(lines[i])) continue;
        // A DOC COMMENT showing the macro's own usage (`/// declare_lifecycle! {`
        // at core/src/lifecycle.rs:60) is a call-shaped line that generates
        // nothing. Left unfiltered it resolved to `type Err = String` 36 lines
        // later and reported a phantom binding named `Err`.
        if (LINE_COMMENT.test(lines[i])) continue;
        // Recursive internal arms sit inside the macro's own body; their
        // `pub enum $Name` carries a `$`, which ITEM cannot match anyway, but
        // skipping them keeps the report honest.
        if (bodies.some((b) => i >= b.start && i <= b.end)) continue;
        // The generated item's name is the first `pub enum|struct` line inside
        // the invocation body — bounded by that body's braces, not by a
        // line-count window that could run past it into unrelated code.
        // A macro may be invoked with any delimiter — `m! {}`, `m!()`, `m![]` —
        // so all three count. Tracking only braces let a `m!(arg);` invocation
        // never "start", which made the scan run to end of file and adopt the
        // next unrelated item as macro-generated.
        let depth = 0;
        let started = false;
        for (let j = i; j < lines.length; j++) {
          for (const c of lines[j]) {
            if (c === "{" || c === "(" || c === "[") {
              depth++;
              started = true;
            } else if (c === "}" || c === ")" || c === "]") depth--;
          }
          if (j > i && !LINE_COMMENT.test(lines[j])) {
            const found = ITEM.exec(lines[j]);
            if (found) {
              exports.push({ name: found[2], kind: found[1], file: rel, line: j + 1, viaMacro: macro });
              hits++;
              break;
            }
          }
          if (started && depth <= 0) break;
        }
      }
    }
    if (hits === 0) {
      for (const t of macroTemplates.filter((t) => t.macro === macro)) {
        unresolved.push({
          file: t.file,
          line: t.line,
          reason: `#[ts(export)] inside macro_rules! ${macro} with zero resolvable invocations`,
        });
      }
    }
  }

  exports.sort((a, b) => a.name.localeCompare(b.name) || a.file.localeCompare(b.file));
  return { exports, unresolved, renamed, macroTemplates };
}
