/**
 * TeamNetworkGlyph — /motionize POC, round 2 (richer + more control).
 *
 * A traced collaborative-network scene (central spark-hub, 5 ring figures, links
 * with midpoint nodes, orbit arcs, accent dots — 44 individually-addressable
 * paths from VTracer). Each path carries a baked `delay` from its distance to the
 * hub, so the reveal RADIATES center-out: hub pops, links extend, figures spring
 * into the ring, accents twinkle last — every element under explicit control.
 *
 * Data (paths + fills + radial delays) is generated by the skill's emit-glyph.mjs
 * (regenerate command in networkGlyphData.ts). Reduced-motion aware; theme-adaptive
 * (interior negative space = var(--background)).
 */
import { motion } from 'framer-motion';
import { useMotion } from '@/hooks/utility/interaction/useMotion';
import { NETWORK_GLYPH, NETWORK_GLYPH_VIEWBOX } from './networkGlyphData';

/** How long the whole center-out reveal takes (delay 0..1 maps into this). */
const SPREAD_S = 0.85;

export function TeamNetworkGlyph({ className = 'w-40 h-40' }: { className?: string }) {
  const { shouldAnimate } = useMotion();

  if (!shouldAnimate) {
    return (
      <svg viewBox={NETWORK_GLYPH_VIEWBOX} className={className} aria-hidden role="img">
        {NETWORK_GLYPH.map((p, i) => <path key={i} d={p.d} fill={p.fill} />)}
      </svg>
    );
  }

  return (
    <svg viewBox={NETWORK_GLYPH_VIEWBOX} className={className} aria-hidden role="img">
      {NETWORK_GLYPH.map((p, i) => (
        <motion.path
          key={i}
          d={p.d}
          fill={p.fill}
          initial={{ opacity: 0, scale: 0.3 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ type: 'spring', stiffness: 300, damping: 18, delay: 0.1 + p.delay * SPREAD_S }}
          style={{ transformOrigin: 'center', transformBox: 'fill-box' }}
        />
      ))}
    </svg>
  );
}
