/**
 * useTriageCopy — the translated strings the triage adapters need.
 *
 * The model layer (`triageTypes` / `triageAdapters`) is deliberately i18n-free:
 * adapters receive already-translated copy so the same `TriageItem` can be
 * rendered by surfaces that resolve strings differently. This hook is the one
 * place that binds that contract to the app's translation tree.
 */
import { useMemo } from 'react';

import { useTranslation } from '@/i18n/useTranslation';

import { DEFAULT_TRIAGE_COPY, type TriageCopy } from './triageAdapters';

export function useTriageCopy(): TriageCopy {
  const { t } = useTranslation();
  const m = t.monitor;

  return useMemo<TriageCopy>(
    () => ({
      ...DEFAULT_TRIAGE_COPY,
      accept: m.triage_accept,
      reject: m.triage_reject,
      skip: m.triage_skip,
      adopt: m.triage_adopt,
      approve: m.triage_approve,
      submit: m.triage_submit,
      defer: m.triage_defer,
      buildNow: m.triage_build_now,
      buildNowHint: m.triage_build_now_hint,
      deprecate: m.triage_deprecate,
      deprecateHint: m.triage_deprecate_hint,
      openBuilder: m.triage_open_builder,
      openBuilderHint: m.triage_open_builder_hint,
      carryOutHint: m.triage_carry_out_hint,
      severity: m.triage_fact_severity,
      reviewType: m.triage_fact_type,
      persona: m.triage_fact_persona,
      raised: m.triage_fact_raised,
      project: m.triage_fact_project,
      category: m.triage_fact_category,
      origin: m.triage_fact_origin,
      scanner: m.triage_origin_scanner,
      effort: m.triage_fact_effort,
      impact: m.triage_fact_impact,
      risk: m.triage_fact_risk,
      value: m.triage_fact_value,
      topic: m.triage_fact_topic,
      practiceKind: m.triage_fact_kind,
      altitude: m.triage_fact_altitude,
      durability: m.triage_fact_durability,
      confidence: m.triage_fact_confidence,
      evidenceSeen: m.triage_fact_evidence_seen,
      workspace: m.triage_fact_workspace,
      answerPlaceholder: m.triage_answer_placeholder,
      noDescription: m.triage_no_description,
      cloud: m.triage_source_cloud,
      local: m.triage_source_local,
      blocking: m.triage_blocking,
      blockingDetail: m.triage_blocking_detail,
      viewRun: m.triage_view_run,
      viewRunHint: m.triage_view_run_hint,
      priority: m.triage_fact_priority,
      priorityRank: m.triage_priority_rank,
      appliesTo: m.triage_fact_applies_to,
      appliesToAny: m.triage_applies_any,
      adoptReach: m.triage_fact_adopt_reach,
      adoptReachValue: m.triage_adopt_reach_value,
      reasonTitle: m.triage_reason_title,
      reasonSkip: m.triage_reason_skip,
      reasonPlaceholder: m.triage_reason_placeholder,
      reasonNotNeeded: m.triage_reason_not_needed,
      reasonWrongApproach: m.triage_reason_wrong_approach,
      reasonAlreadyHandled: m.triage_reason_already_handled,
      reasonNeedsInfo: m.triage_reason_needs_info,
      reasonOutOfScope: m.triage_reason_out_of_scope,
      reasonByDesign: m.triage_reason_by_design,
      reasonNotWorthIt: m.triage_reason_not_worth_it,
      reasonAlreadyDone: m.triage_reason_already_done,
      supersededTitle: m.triage_superseded_title,
      supersededSkip: m.triage_superseded_skip,
      questionsPending: m.triage_questions_pending,
      questionsFact: m.triage_fact_questions,
      policyApply: m.triage_policy_apply,
      policyDecline: m.triage_policy_decline,
      policySource: m.triage_policy_source,
      policyKindRouting: m.triage_policy_kind_routing,
      policyKindBudget: m.triage_policy_kind_budget,
      policyRoutingTitle: m.triage_policy_routing_title,
      policyRoutingBody: m.triage_policy_routing_body,
      policyBudgetIntroduceTitle: m.triage_policy_budget_introduce,
      policyBudgetRaiseTitle: m.triage_policy_budget_raise,
      policyBudgetLowerTitle: m.triage_policy_budget_lower,
      policyBudgetBody: m.triage_policy_budget_body,
      fromModel: m.triage_fact_from_model,
      toModel: m.triage_fact_to_model,
      saving: m.triage_fact_saving,
      savingValue: m.triage_policy_saving_value,
      qualityDelta: m.triage_fact_quality,
      policyQualityDrop: m.triage_policy_quality_drop,
      policyQualityDropDetail: m.triage_policy_quality_drop_detail,
      qualityBasis: m.triage_fact_basis,
      basisLab: m.triage_policy_basis_lab,
      basisSuccess: m.triage_policy_basis_success,
      runs: m.triage_fact_runs,
      runsValue: m.triage_policy_runs_value,
      ceiling: m.triage_fact_ceiling,
      proposedCeiling: m.triage_fact_proposed_ceiling,
      observedSpend: m.triage_fact_spend,
      noCeiling: m.triage_policy_no_ceiling,
      reasonQualityRisk: m.triage_reason_quality_risk,
      reasonSavingTooSmall: m.triage_reason_saving_too_small,
      reasonThinEvidence: m.triage_reason_thin_evidence,
      reasonKeepCurrent: m.triage_reason_keep_current,
      promote: m.triage_promote,
      evolutionSource: m.triage_evolution_source,
      evolutionTitle: m.triage_evolution_title,
      evolutionMeasured: m.triage_evolution_measured,
      incumbentScore: m.triage_fact_incumbent,
      winnerScore: m.triage_fact_challenger,
      gain: m.triage_fact_gain,
      bar: m.triage_fact_bar,
      points: m.triage_evolution_points,
      fitnessSource: m.triage_fact_fitness,
      evolutionLock: m.triage_evolution_lock,
      evolutionLockDetail: m.triage_evolution_lock_detail,
      evolutionLockFact: m.triage_fact_pinned_to,
      reasonGainTooSmall: m.triage_reason_gain_too_small,
      reasonPromptWorse: m.triage_reason_prompt_worse,
      reasonFreshCycle: m.triage_reason_fresh_cycle,
    }),
    [m],
  );
}
