/**
 * Template Origin Verification & Sandbox Mode
 *
 * Provides content-hash based integrity verification for templates,
 * origin tracking, trust level derivation, and sandbox policy enforcement.
 *
 * Built-in templates (shipped with the app) are automatically verified.
 * AI-generated templates get "generated" origin with full trust.
 * Community/imported templates from unknown origins are sandboxed with
 * restricted capabilities until explicitly approved by the user.
 */
import type {
  TemplateOrigin,
  TemplateTrustLevel,
  TemplateVerification,
  SandboxPolicy,
} from '@/lib/types/templateTypes';
import { SANDBOX_POLICY } from '@/lib/types/templateTypes';

// ── Content hashing ──────────────────────────────────────────────────

/**
 * Compute a SHA-256 hex digest of a string using the Web Crypto API.
 * Used to verify template content integrity.
 */
export async function computeContentHash(content: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(content);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Synchronous content hash using a simple deterministic hash.
 * Used when Web Crypto is unavailable or sync computation is needed.
 */
export function computeContentHashSync(content: string): string {
  let h1 = 0xdeadbeef;
  let h2 = 0x41c6ce57;
  for (let i = 0; i < content.length; i++) {
    const ch = content.charCodeAt(i);
    h1 = Math.imul(h1 ^ ch, 2654435761);
    h2 = Math.imul(h2 ^ ch, 1597334677);
  }
  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507);
  h1 ^= Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  h2 = Math.imul(h2 ^ (h2 >>> 16), 2246822507);
  h2 ^= Math.imul(h1 ^ (h1 >>> 13), 3266489909);
  return (4294967296 * (2097151 & h2) + (h1 >>> 0)).toString(16).padStart(16, '0');
}

// ── Known built-in template IDs ──────────────────────────────────────

/** Set of template IDs that ship with the application (populated at build time) */
const builtinTemplateIds = new Set<string>();

/**
 * Register a template ID as a known built-in.
 * Called during catalog initialization.
 */
export function registerBuiltinTemplate(id: string): void {
  builtinTemplateIds.add(id);
}

/**
 * Register all built-in template IDs from the catalog.
 */
export function registerBuiltinTemplates(ids: string[]): void {
  for (const id of ids) {
    builtinTemplateIds.add(id);
  }
}

/** Check if a template ID is a registered built-in */
export function isBuiltinTemplate(id: string): boolean {
  return builtinTemplateIds.has(id);
}

// ── Origin detection ─────────────────────────────────────────────────

/** Well-known seed run IDs that indicate built-in templates */
const BUILTIN_RUN_IDS = new Set(['seed-category-v1']);

/**
 * Determine the origin of a template based on available metadata.
 */
export function detectTemplateOrigin(params: {
  testCaseId?: string;
  testRunId?: string;
  /** Whether the template was generated by the design engine */
  isDesignGenerated?: boolean;
}): TemplateOrigin {
  const { testCaseId, testRunId, isDesignGenerated } = params;

  // Check if it's a registered built-in template
  if (testCaseId && isBuiltinTemplate(testCaseId)) {
    return 'builtin';
  }

  // Check if it was seeded from the built-in catalog
  if (testRunId && BUILTIN_RUN_IDS.has(testRunId)) {
    return 'builtin';
  }

  // Check if it was generated by the design engine
  if (isDesignGenerated) {
    return 'generated';
  }

  return 'unknown';
}

// ── Trust level derivation ───────────────────────────────────────────

/**
 * Derive the trust level from a template's origin and integrity status.
 */
export function deriveTrustLevel(
  origin: TemplateOrigin,
  integrityValid: boolean,
): TemplateTrustLevel {
  switch (origin) {
    case 'builtin':
      // Built-in templates are verified if integrity check passes
      return integrityValid ? 'verified' : 'untrusted';
    case 'generated':
      // User-generated templates within the app are trusted
      return 'verified';
    case 'community':
      // Community templates are sandboxed
      return 'sandboxed';
    case 'unknown':
    default:
      return 'untrusted';
  }
}

/**
 * Get the appropriate sandbox policy for a trust level.
 */
export function getSandboxPolicy(trustLevel: TemplateTrustLevel): SandboxPolicy | null {
  switch (trustLevel) {
    case 'verified':
      return null; // No restrictions
    case 'sandboxed':
      return { ...SANDBOX_POLICY };
    case 'untrusted':
      return {
        ...SANDBOX_POLICY,
        canUsePolling: false,
        requireApproval: true,
      };
  }
}

// ── Full verification ────────────────────────────────────────────────

/**
 * Build a complete TemplateVerification for a template.
 */
export function verifyTemplate(params: {
  testCaseId?: string;
  testRunId?: string;
  isDesignGenerated?: boolean;
  designResultJson?: string | null;
}): TemplateVerification {
  const origin = detectTemplateOrigin(params);

  // Compute content hash if design result is available
  const contentHash = params.designResultJson
    ? computeContentHashSync(params.designResultJson)
    : null;

  // Built-in and generated templates pass integrity by default
  const integrityValid = origin === 'builtin' || origin === 'generated';
  const trustLevel = deriveTrustLevel(origin, integrityValid);
  const sandboxPolicy = getSandboxPolicy(trustLevel);

  return {
    origin,
    trustLevel,
    contentHash,
    integrityValid,
    sandboxPolicy,
  };
}

// ── Sandbox enforcement helpers ──────────────────────────────────────

/**
 * Filter suggested triggers based on sandbox policy restrictions.
 */
export function filterTriggersForSandbox(
  triggerTypes: string[],
  policy: SandboxPolicy | null,
): string[] {
  if (!policy) return triggerTypes;

  return triggerTypes.filter((t) => {
    if (t === 'webhook' && !policy.canUseWebhooks) return false;
    if (t === 'polling' && !policy.canUsePolling) return false;
    return true;
  });
}

/**
 * Apply sandbox policy overrides to adoption preferences.
 * Returns the adjusted values with explanations of what was changed.
 */
export function applySandboxOverrides(
  policy: SandboxPolicy | null,
  preferences: {
    maxConcurrent: number;
    requireApproval: boolean;
    maxBudgetUsd: number | null;
  },
): {
  maxConcurrent: number;
  requireApproval: boolean;
  maxBudgetUsd: number | null;
  overrides: string[];
} {
  if (!policy) {
    return { ...preferences, overrides: [] };
  }

  const overrides: string[] = [];
  let { maxConcurrent, requireApproval, maxBudgetUsd } = preferences;

  if (maxConcurrent > policy.maxConcurrent) {
    maxConcurrent = policy.maxConcurrent;
    overrides.push(`Max concurrent limited to ${policy.maxConcurrent} (sandbox mode)`);
  }

  if (policy.requireApproval && !requireApproval) {
    requireApproval = true;
    overrides.push('Human review required (sandbox mode)');
  }

  if (policy.budgetEnforced && maxBudgetUsd === null) {
    maxBudgetUsd = 5.0;
    overrides.push('Budget cap set to $5.00 (sandbox mode)');
  }

  return { maxConcurrent, requireApproval, maxBudgetUsd, overrides };
}

// ── Display helpers ──────────────────────────────────────────────────

/** Human-readable labels for trust levels */
export const TRUST_LEVEL_LABELS: Record<TemplateTrustLevel, string> = {
  verified: 'Verified',
  sandboxed: 'Sandboxed',
  untrusted: 'Unverified',
};

/** Color classes for trust level badges */
export const TRUST_LEVEL_COLORS: Record<TemplateTrustLevel, { bg: string; text: string; border: string }> = {
  verified: { bg: 'bg-emerald-500/10', text: 'text-emerald-400', border: 'border-emerald-500/20' },
  sandboxed: { bg: 'bg-amber-500/10', text: 'text-amber-400', border: 'border-amber-500/20' },
  untrusted: { bg: 'bg-red-500/10', text: 'text-red-400', border: 'border-red-500/20' },
};

/** Origin display labels */
export const ORIGIN_LABELS: Record<TemplateOrigin, string> = {
  builtin: 'Built-in',
  generated: 'AI Generated',
  community: 'Community',
  unknown: 'Unknown Origin',
};
