// PROTOTYPE ROUND (spark council-readout). Scoreboard's own English words.
// Consolidation moves the winner's into `t.council` with all 14 locales.
export const S = {
  esc: 'Esc',
  band: 'The council, member by member',
  overall: 'Overall',
  bar: 'bar',
  noOverall: 'No overall',
  short: '{gap} short of the bar',
  clears: 'clears by {gap}',
  measured: '{percent} measured',
  advisory: 'Uncalibrated: judged floors are advisory, the overall only orders the queue.',
  trusted: 'Calibrated: floors and the bar bind.',
  fullRound: 'Full council',
  liteRound: 'Lite round',
  roundOf: 'round {round} of {cap}',
  liteNote: 'Lite rounds are read, never decided; a full council has to run first.',
  oldRound: 'Reading round {round}. Only the latest round can be decided.',
  rounds: 'Rounds',
  roundLabel: 'Round {round}',
  weight: '{percent} weight',
  floor: 'floor {floor}',
  floorHit: 'Below its floor',
  confidence: { low: 'Low confidence', med: 'Medium confidence', high: 'High confidence' } as Record<string, string>,
  confidenceShort: { low: 'low', med: 'medium', high: 'high' } as Record<string, string>,
  kind: { mechanical: 'Mechanical', judged: 'Judged', mixed: 'Mixed' } as Record<string, string>,
  severity: { high: 'High', med: 'Medium', low: 'Low' } as Record<string, string>,
  severityCount: { high: '{count} high', med: '{count} medium', low: '{count} low' } as Record<string, string>,
  notMeasured: 'Not measured',
  notRun: 'The round never reached this member.',
  carried: 'carried',
  mustAddress: 'Must address',
  general: 'Council',
  findings: 'Findings',
  findingsCount: '{count} findings',
  noFindings: 'This member recorded no findings.',
  evidence: 'Evidence',
  techniques: 'Registry techniques',
  proof: { execution: 'executed', inspection: 'inspected', claim: 'claimed' } as Record<string, string>,
  seen: 'seen {count} times',
  readMore: 'Read the whole finding',
  readLess: 'Show less',
  moreEvidence: 'Show {count} more',
  lessEvidence: 'Show fewer',
  reading: 'The council’s reading',
  summaryFallback: 'The council left no summary. This is the subject’s own description.',
  hardFailures: 'Hard failures',
  scope: 'Scope',
  paths: '{count} files judged',
  head: 'Head',
  finished: 'Finished',
  ingested: 'Ingested',
  runDir: 'Run folder',
  copy: 'Copy the run folder',
  loading: 'Reading the council',
};

export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => String(vars[k] ?? ''));
}
