/**
 * Generative Tours — frontend ingest/validation for Athena-composed tours.
 *
 * The Rust side (`companion::tours`) already validates a composed spec
 * against the generated anchor manifest before persisting it to
 * `companion_tours`. This module is the defense-in-depth twin: everything
 * that enters the runtime tour registry passes `validateDynamicTour` against
 * the SAME manifest (`tourAnchorManifest.json`, generated by
 * `scripts/docs/gen-tour-anchors.mjs`), so a stale DB row or a tampered
 * payload can never drive the spotlight at an unknown anchor or the router
 * at an unknown section.
 *
 * Invalid pieces degrade honestly, mirroring the shared UX contract:
 *  - unknown highlight anchor → the STEP is rejected (never silently played);
 *  - unknown sidebar section / sub-tab setter → step rejected;
 *  - zero valid steps → the whole tour is rejected and the caller surfaces
 *    the failure state instead of faking a tour.
 */
import { invokeWithTimeout as invoke } from '@/lib/tauriInvoke';
import manifest from '@/features/onboarding/anchors/tourAnchorManifest.json';
import {
  isSafeTourTestId,
  registerDynamicTour,
  isDynamicTourId,
  type DynamicTourId,
  type TourDef,
  type TourStepDef,
  type TourSubStepDef,
} from './tourSlice';

/** Completion event every composed step advances on (acknowledge button). */
export const COMPOSED_STEP_EVENT = 'tour:composed-step-explored' as const;

const MAX_STEPS = 12;
const MAX_SUB_STEPS = 6;
const MAX_TEXT = 600;

const testids = new Set<string>(manifest.testids);
const dynamicPrefixes: string[] = manifest.dynamicPrefixes;
const sidebarSections = new Set<string>(manifest.sidebarSections);
const subTabSetters = new Set<string>(manifest.subTabSetters);

/** An anchor is known when declared verbatim or under a dynamic testid template prefix. */
export function isKnownAnchor(anchor: string): boolean {
  if (!isSafeTourTestId(anchor)) return false;
  if (testids.has(anchor)) return true;
  return dynamicPrefixes.some((p) => anchor.startsWith(p) && anchor.length > p.length);
}

/** Raw record shape returned by `companion_compose_tour` / `companion_list_composed_tours`. */
export interface ComposedTourRecord {
  id: string;
  topic: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  /** Serialized steps array (validated server-side; re-validated here). */
  stepsJson: string;
  /** 'ready' | 'stale' — stale = anchor manifest drifted since composition. */
  status: string;
  createdAt: string;
}

export type DynamicTourValidation =
  | { ok: true; def: TourDef & { id: DynamicTourId } }
  | { ok: false; errors: string[] };

function str(v: unknown, max = MAX_TEXT): string | null {
  if (typeof v !== 'string') return null;
  const t = v.trim();
  if (!t || t.length > max) return null;
  return t;
}

function validateSubStep(raw: unknown, path: string, errors: string[]): TourSubStepDef | null {
  if (typeof raw !== 'object' || raw === null) {
    errors.push(`${path}: not an object`);
    return null;
  }
  const r = raw as Record<string, unknown>;
  const id = str(r.id, 80);
  const label = str(r.label, 160);
  const hint = str(r.hint) ?? '';
  if (!id || !label) {
    errors.push(`${path}: missing id/label`);
    return null;
  }
  const sub: TourSubStepDef = { id, label, hint };
  if (r.highlightTestId !== undefined && r.highlightTestId !== null) {
    const anchor = str(r.highlightTestId, 120);
    if (!anchor || !isKnownAnchor(anchor)) {
      errors.push(`${path}: unknown anchor "${String(r.highlightTestId)}"`);
      return null;
    }
    sub.highlightTestId = anchor;
  }
  return sub;
}

function validateStep(raw: unknown, index: number, errors: string[]): TourStepDef | null {
  const path = `steps[${index}]`;
  if (typeof raw !== 'object' || raw === null) {
    errors.push(`${path}: not an object`);
    return null;
  }
  const r = raw as Record<string, unknown>;
  const id = str(r.id, 80) ?? `composed-step-${index + 1}`;
  const title = str(r.title, 160);
  const description = str(r.description);
  const hint = str(r.hint) ?? '';
  if (!title || !description) {
    errors.push(`${path}: missing title/description`);
    return null;
  }

  const nav = (typeof r.nav === 'object' && r.nav !== null ? r.nav : null) as Record<string, unknown> | null;
  const sidebarSection = nav ? str(nav.sidebarSection, 40) : null;
  if (!sidebarSection || !sidebarSections.has(sidebarSection)) {
    errors.push(`${path}: unknown sidebarSection "${String(nav?.sidebarSection)}"`);
    return null;
  }
  const step: TourStepDef = {
    id,
    title,
    description,
    hint,
    nav: { sidebarSection },
    completeOn: COMPOSED_STEP_EVENT,
    subSteps: [],
  };
  if (nav?.subTabSetter !== undefined && nav.subTabSetter !== null) {
    const setter = str(nav.subTabSetter, 40);
    const subTab = str(nav.subTab, 60);
    if (!setter || !subTabSetters.has(setter) || !subTab) {
      errors.push(`${path}: unknown subTabSetter "${String(nav.subTabSetter)}"`);
      return null;
    }
    step.nav.subTabSetter = setter;
    step.nav.subTab = subTab;
  }
  if (r.highlightTestId !== undefined && r.highlightTestId !== null) {
    const anchor = str(r.highlightTestId, 120);
    if (!anchor || !isKnownAnchor(anchor)) {
      errors.push(`${path}: unknown anchor "${String(r.highlightTestId)}"`);
      return null;
    }
    step.highlightTestId = anchor;
  }
  const narration = r.narration !== undefined ? str(r.narration) : null;
  if (narration) step.narration = narration;

  if (Array.isArray(r.subSteps)) {
    for (const [i, s] of r.subSteps.slice(0, MAX_SUB_STEPS).entries()) {
      const sub = validateSubStep(s, `${path}.subSteps[${i}]`, errors);
      if (!sub) return null; // reject the whole step on any bad sub-step
      step.subSteps.push(sub);
    }
  }
  return step;
}

/**
 * Validate a composed-tour record into a playable `TourDef`. Strict: any
 * step with an unknown anchor or nav target rejects that step's whole tour
 * shape only if NO valid steps survive; a partially-bad tour is rejected
 * outright too (a walkthrough with silently-missing chapters would teach
 * wrong) — every step must validate.
 */
export function validateDynamicTour(record: ComposedTourRecord): DynamicTourValidation {
  const errors: string[] = [];
  if (!isDynamicTourId(record.id)) {
    return { ok: false, errors: [`id "${record.id}" is not a dynamic tour id`] };
  }
  const title = str(record.title, 160);
  if (!title) return { ok: false, errors: ['missing title'] };

  let rawSteps: unknown;
  try {
    rawSteps = JSON.parse(record.stepsJson);
  } catch {
    return { ok: false, errors: ['stepsJson is not valid JSON'] };
  }
  if (!Array.isArray(rawSteps) || rawSteps.length === 0 || rawSteps.length > MAX_STEPS) {
    return { ok: false, errors: [`steps must be 1-${MAX_STEPS} entries`] };
  }
  const steps: TourStepDef[] = [];
  for (const [i, raw] of rawSteps.entries()) {
    const step = validateStep(raw, i, errors);
    if (!step) return { ok: false, errors };
    steps.push(step);
  }
  return {
    ok: true,
    def: {
      id: record.id,
      title,
      description: str(record.description) ?? '',
      icon: 'Sparkles',
      color: 'violet',
      steps,
    },
  };
}

/**
 * Validate + register a composed tour. Returns the playable id, or null when
 * validation failed (callers show the honest failure state; never a broken tour).
 */
export function ingestComposedTour(record: ComposedTourRecord): DynamicTourId | null {
  const result = validateDynamicTour(record);
  if (!result.ok) {
    if (typeof console !== 'undefined') {
      console.warn('[dynamicTours] rejected composed tour', record.id, result.errors);
    }
    return null;
  }
  return registerDynamicTour(result.def);
}

// -- IPC ------------------------------------------------------------------

/** Ask Athena to compose a walkthrough for `topic`. Slow (one-shot LLM call). */
export function composeTour(topic: string, summary?: string): Promise<ComposedTourRecord> {
  return invoke('companion_compose_tour', { topic, summary: summary ?? null }, { timeoutMs: 180_000 });
}

/** All persisted composed tours, newest first (server re-validates → status). */
export function listComposedTours(): Promise<ComposedTourRecord[]> {
  return invoke('companion_list_composed_tours', {});
}
