use serde::{Deserialize, Serialize};
use ts_rs::TS;

use personas_db::models::CreateLabResultEventInput;

// -- Types ------------------------------------------------------

/// Model configuration for a test run, passed from the frontend.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TestModelConfig {
    pub id: String,
    pub provider: String,
    pub model: Option<String>,
    pub base_url: Option<String>,
    pub auth_token: Option<String>,
    /// Effort level: "low" / "medium" / "high".
    /// `None` falls back to `prompt::DEFAULT_EFFORT` ("medium").
    /// The lab uses this to vary effort across test cells alongside model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effort: Option<String>,
}

/// Parse and validate model configs from frontend JSON values.
pub fn parse_model_configs(
    models: Vec<serde_json::Value>,
) -> Result<Vec<TestModelConfig>, personas_core::error::AppError> {
    let mut configs: Vec<TestModelConfig> = Vec::new();
    for v in models {
        match serde_json::from_value(v.clone()) {
            Ok(config) => configs.push(config),
            Err(e) => {
                return Err(personas_core::error::AppError::Validation(format!(
                    "Invalid model config: {e}"
                )))
            }
        }
    }
    if configs.is_empty() {
        return Err(personas_core::error::AppError::Validation(
            "No valid models provided".into(),
        ));
    }
    Ok(configs)
}

/// A test scenario generated by the coordinator LLM.
///
/// Wire format: snake_case (no `rename_all` annotation). Frontend consumers must
/// read `input_data`, `mock_tools`, `expected_behavior`, `expected_tool_sequence`,
/// `expected_protocols` as snake_case. The `mapRunStatusPayload` bridge in
/// `src/hooks/realtime/useRunEventListener.ts` does NOT recursively camelCase
/// nested objects; this type is passed through.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct TestScenario {
    pub name: String,
    pub description: String,
    pub input_data: Option<serde_json::Value>,
    pub mock_tools: Vec<MockToolResponse>,
    pub expected_behavior: String,
    pub expected_tool_sequence: Option<Vec<String>>,
    pub expected_protocols: Option<Vec<String>>,
}

/// A mock tool response within a scenario.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct MockToolResponse {
    pub tool_name: String,
    pub description: Option<String>,
    pub mock_response: serde_json::Value,
}

/// Tauri event payload for test run progress.
///
/// Wire format: snake_case. Subscriber bridge: `mapRunStatusPayload` in
/// `src/hooks/realtime/useRunEventListener.ts` flattens snake_case → camelCase
/// for top-level fields but leaves `scores` and `scenarios` as-is.
#[derive(Debug, Clone, Serialize, Deserialize, TS, Default)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct TestRunStatusEvent {
    pub run_id: String,
    pub phase: String,
    pub scenarios_count: Option<usize>,
    pub current: Option<usize>,
    pub total: Option<usize>,
    pub model_id: Option<String>,
    pub scenario_name: Option<String>,
    pub status: Option<String>,
    pub scores: Option<TestScores>,
    pub summary: Option<serde_json::Value>,
    pub error: Option<String>,
    /// Emitted once during the "generated" phase so the frontend can save scenarios to a suite.
    pub scenarios: Option<Vec<TestScenario>>,
    /// Elapsed wall-clock milliseconds since the run started (for live progress display).
    pub elapsed_ms: Option<u64>,
}

/// Per-scenario scores; serialized snake_case directly into TestRunStatusEvent.scores.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct TestScores {
    pub tool_accuracy: Option<i32>,
    pub output_quality: Option<i32>,
    pub protocol_compliance: Option<i32>,
}

pub struct ScoreResult {
    pub tool_accuracy: Option<i32>,
    pub output_quality: Option<i32>,
    pub protocol_compliance: Option<i32>,
    pub output_preview: Option<String>,
    pub tool_calls_actual: Option<personas_db::models::Json<Vec<String>>>,
    pub input_tokens: i64,
    pub output_tokens: i64,
    pub cost_usd: f64,
    pub duration_ms: i64,
    pub error_message: Option<String>,
    pub rationale: Option<String>,
    pub suggestions: Option<String>,
    pub eval_method: Option<String>,
    /// Captured stream events from the CLI execution. Carried through scoring
    /// so per-mode persist callbacks can write them into `lab_result_events`
    /// keyed by the freshly-created result row's id.
    pub events: Vec<CreateLabResultEventInput>,
}

impl ScoreResult {
    /// Build a placeholder result for a cancelled or errored cell: every
    /// score/telemetry field is empty/zeroed, and `error_message` carries `msg`.
    /// Callers that also want `output_preview` populated (the "error" branch,
    /// as opposed to "cancelled") should set it on the returned value.
    ///
    /// Replaces four verbatim-duplicated 17-field `ScoreResult` literals that
    /// had drifted apart across `run_test` and `run_lab_loop` (refactor audit,
    /// Theme I).
    pub(crate) fn from_error(msg: impl Into<String>) -> ScoreResult {
        let msg = msg.into();
        ScoreResult {
            tool_accuracy: None,
            output_quality: None,
            protocol_compliance: None,
            output_preview: None,
            tool_calls_actual: None,
            input_tokens: 0,
            output_tokens: 0,
            cost_usd: 0.0,
            duration_ms: 0,
            error_message: Some(msg),
            rationale: None,
            suggestions: None,
            eval_method: None,
            events: Vec::new(),
        }
    }
}

// -- CLI helpers ------------------------------------------------

/// Structured output from a CLI execution.
pub struct ExecutionOutput {
    pub(crate) assistant_text: String,
    pub(crate) tool_calls: Vec<String>,
    pub(crate) input_tokens: u64,
    pub(crate) output_tokens: u64,
    pub cost_usd: f64,
    pub(crate) duration_ms: u64,
    pub(crate) error: Option<String>,
    /// Per-event capture of the CLI stream-JSON lines, in order. Used by lab
    /// modes to populate `lab_result_events` so the ScenarioDetailPanel can
    /// render the conversation post-hoc. Empty for paths that don't produce
    /// stream JSON (e.g., native Ollama HTTP).
    pub(crate) events: Vec<CreateLabResultEventInput>,
}

impl ExecutionOutput {
    /// Read access for out-of-crate consumers (e.g. measured-fitness scoring)
    /// without opening the field itself to mutation.
    pub fn assistant_text(&self) -> &str {
        &self.assistant_text
    }
}
