/**
 * Presence island (R5 · A) - prototype copy, English only.
 *
 * TODO(prototype, 2026-10-07): extract to i18n when a winner is picked.
 * Kept out of the locale files on purpose (the module's prototype exemption,
 * see `../../../nextCopy.ts`): a losing variant costs no translation work.
 */

export const ISLAND_COPY = {
  tab: 'R5 · A',
  island: 'Athena',
  // Resting capsule: one label, never a cut sentence.
  needYou: (n: number) => (n === 1 ? '1 needs you' : `${n} need you`),
  workingOn: (n: number) => `Working on ${n}`,
  thinking: 'Thinking',
  reviewing: 'Reviewing',
  using: (tool: string) => `Running ${tool}`,
  quiet: 'All quiet',
  openChat: 'Open the conversation',
  foldChat: 'Fold into the island',
  keyChat: 'Alt C',
  keyThreads: 'Alt T',
  keyWork: 'Alt W',
  keyEsc: 'Esc',
  keyEnter: 'Enter',
  keyRange: '1–9',
  // Thread rail
  rail: 'Run threads',
  openRail: 'Open the thread board',
  foldBoard: 'Fold the board',
  board: 'Threads',
  boardSummary: (lanes: number, live: number) => `${lanes} lanes · ${live} running`,
  athenaLane: 'Athena',
  gate: (n: number) => (n === 1 ? 'Blocked on you' : `${n} blocked on you`),
  gateShort: 'Needs you',
  waitsFor: 'Waits for you',
  nothingRunning: 'Nothing running in this lane',
  otherThreads: 'Other conversations',
  unread: (n: number) => `${n} new`,
  more: (n: number) => `+${n}`,
  state: {
    running: 'running',
    spawning: 'starting',
    awaiting_input: 'waits for you',
    stale: 'stuck',
    queued: 'queued',
    idle: 'idle',
    failed: 'failed',
    waiting: 'blocked',
    blocked: 'blocked',
    scheduled: 'check-in',
  } as Record<string, string>,
  // Decision sheet
  sheet: 'Decision',
  itemOf: (i: number, n: number) => `${i} of ${n}`,
  herPick: 'Her pick',
  askHer: 'Ask Athena',
  composing: 'She is weighing it',
  keyAsk: '0',
  keysChoose: 'choose',
  keysAsk: 'ask her',
  keysWalk: 'walk the queue',
  keysFold: 'fold',
  keysConfirm: 'take her pick',
  details: 'What it will run',
  nothingWaiting: 'Nothing waits on you.',
  nothingWaitingSub: 'When she needs a call, the island lights.',
  aboutThis: (kind: string) => `Re: this ${kind}`,
  noun: {
    session_request: 'session question',
    decision: 'decision',
    approval: 'approval',
    plan: 'plan',
    failure: 'failure',
    warning: 'warning',
    nudge: 'note',
    assignment: 'assignment',
  } as Record<string, string>,
  // Conversation
  stop: 'Stop',
  back: 'Back to the conversation',
} as const;
