pub mod ai_artifact_flow;
pub mod api_proxy;
pub mod auth_detect;
pub mod auto_cred_browser;
pub mod cli_capture;
pub mod connectors;
pub mod credential_design;
pub mod credential_recipes;
pub mod crud;
pub mod db_schema;
#[cfg(feature = "desktop")]
pub mod desktop;
#[cfg(feature = "desktop")]
pub mod desktop_bridges;
pub mod discovery;
pub mod external_api_keys;
pub mod foraging;
pub mod intelligence;
pub mod mcp_gateways;
pub mod mcp_tools;
pub mod negotiator;
pub mod nl_query;
pub mod oauth;
pub mod openapi_autopilot;
pub mod query_debug;
pub mod resources;
pub mod rotation;
pub mod schema_proposal;
pub(crate) mod shared;
#[cfg(feature = "ml")]
pub mod vector_kb;
