/**
 * TypeScript types mirroring the Rust build session models.
 *
 * These will eventually be auto-generated by ts-rs, but are defined manually
 * now so frontend development can proceed in parallel with backend work.
 */

/** Runtime-validated list of build phases — single source of truth for both
 *  the BuildPhase type and the isBuildPhase guard. */
export const BUILD_PHASES = [
  "initializing",
  "analyzing",
  "awaiting_input",
  "resolving",
  "draft_ready",
  "completed",
  "failed",
  "cancelled",
  "testing",
  "test_complete",
  "promoted",
] as const;

/** Build session lifecycle phase, matching the Rust BuildPhase enum. */
export type BuildPhase = typeof BUILD_PHASES[number];

export function isBuildPhase(value: unknown): value is BuildPhase {
  return typeof value === "string" && (BUILD_PHASES as readonly string[]).includes(value);
}

/** Runtime-validated list of cell build statuses. */
export const CELL_BUILD_STATUSES = [
  "hidden",
  "revealed",
  "pending",
  "filling",
  "resolved",
  "highlighted",
  "updated",
  "error",
] as const;

/** Visual status of a single matrix cell during the build flow. */
export type CellBuildStatus = typeof CELL_BUILD_STATUSES[number];

export function isCellBuildStatus(value: unknown): value is CellBuildStatus {
  return typeof value === "string" && (CELL_BUILD_STATUSES as readonly string[]).includes(value);
}

// ---------------------------------------------------------------------------
// v3 capability-framework domain types
// ---------------------------------------------------------------------------

/** Persona behavior core — the shared mission + identity. */
export interface PersonaBehaviorCore {
  mission: string;
  identity: { role: string; description: string };
  voice: { style: string; output_format: string };
  principles: string[];
  constraints: string[];
  decision_principles?: string[];
  verbosity_default?: "terse" | "normal" | "verbose";
}

/** One entry in the Phase-B capability enumeration. */
export interface CapabilityDraft {
  id: string;
  title: string;
  capability_summary: string;
  user_facing_goal?: string;
}

/** A review policy for one capability. */
export interface ReviewPolicy {
  mode: "never" | "on_low_confidence" | "always";
  context: string;
}

/** A memory policy for one capability. */
export interface MemoryPolicy {
  enabled: boolean;
  context: string;
}

/** An event subscription entry. */
export interface EventSubscriptionEntry {
  event_type: string;
  direction: "emit" | "listen" | "subscribe";
  description?: string;
}

/** A notification channel entry. */
export interface NotificationChannelEntry {
  channel: string;
  target: string;
  format?: string;
}

/** A capability with its envelope (fields filled in progressively by Phase C). */
export interface CapabilityState {
  id: string;
  title: string;
  capability_summary: string;
  user_facing_goal?: string;
  enabled_by_default?: boolean;

  suggested_trigger?: {
    trigger_type: "schedule" | "polling" | "webhook" | "manual" | "event";
    config?: Record<string, unknown>;
    description?: string;
  } | null;
  connectors?: string[];
  notification_channels?: NotificationChannelEntry[];
  review_policy?: ReviewPolicy;
  memory_policy?: MemoryPolicy;
  event_subscriptions?: EventSubscriptionEntry[];
  input_schema?: Array<{ name: string; type: string; required: boolean; description?: string }>;
  sample_input?: Record<string, unknown>;
  tool_hints?: string[];
  use_case_flow?: {
    nodes: Array<{ id: string; label: string; kind?: string }>;
    edges: Array<{ from: string; to: string; label?: string }>;
  };
  error_handling?: string;

  /** Which fields have landed so far — used by the UI to show resolution progress. */
  resolvedFields: Record<string, "pending" | "resolved">;
}

/** Persona-wide resolution values. */
export interface PersonaResolution {
  tools?: Array<{ name: string; description?: string; category?: string }>;
  connectors?: Array<{
    name: string;
    service_type: string;
    purpose?: string;
    has_credential?: boolean;
  }>;
  notification_channels_default?: NotificationChannelEntry[];
  operating_instructions?: string;
  tool_guidance?: string;
  error_handling?: string;
  core_memories?: Array<{ title: string; content: string }>;
}

/**
 * Discriminated union matching the Rust BuildEvent enum.
 * The `type` field is the serde tag (tag = "type").
 */
export type BuildEvent =
  | {
      type: "cell_update";
      session_id: string;
      cell_key: string;
      data: unknown;
      status: string;
    }
  | {
      type: "question";
      session_id: string;
      cell_key: string;
      question: string;
      options: string[] | null;
    }
  | {
      type: "progress";
      session_id: string;
      dimension: string | null;
      message: string;
      percent: number | null;
      activity?: string;
    }
  | {
      type: "error";
      session_id: string;
      cell_key: string | null;
      message: string;
      retryable: boolean;
    }
  | {
      type: "session_status";
      session_id: string;
      phase: string;
      resolved_count: number;
      total_count: number;
    }
  // v3 capability-framework events (additive; coexist with legacy events).
  // The CLI emits these directly; the backend parser ALSO mirrors each to a
  // legacy cell_update/question for the old 3×3 matrix UI. See
  // docs/concepts/persona-capabilities/C4-build-from-scratch-v3-handoff.md §3.8.
  | {
      type: "behavior_core_update";
      session_id: string;
      data: unknown;
      status: string;
    }
  | {
      type: "capability_enumeration_update";
      session_id: string;
      data: unknown;
      status: string;
    }
  | {
      type: "capability_resolution_update";
      session_id: string;
      capability_id: string;
      field: string;
      value: unknown;
      status: string;
    }
  | {
      type: "persona_resolution_update";
      session_id: string;
      field: string;
      value: unknown;
      status: string;
    }
  | {
      type: "clarifying_question_v3";
      session_id: string;
      /** "mission" | "capability" | "field" */
      scope: string;
      capability_id: string | null;
      field: string | null;
      question: string;
      options: string[] | null;
    };

/** A pending question the user needs to answer for a specific cell. */
export interface BuildQuestion {
  cellKey: string;
  question: string;
  options: string[] | null;
}

/** Full persisted build session loaded from SQLite. */
export interface PersistedBuildSession {
  id: string;
  personaId: string;
  phase: BuildPhase;
  resolvedCells: Record<string, unknown>;
  pendingQuestion: BuildQuestion | null;
  agentIr: unknown | null;
  intent: string;
  errorMessage: string | null;
  createdAt: string;
}

/** User's answer to a build question. */
export interface UserAnswer {
  cell_key: string;
  answer: string;
}

/** Lightweight session summary for list views. */
export interface BuildSessionSummary {
  id: string;
  personaId: string;
  phase: BuildPhase;
  intent: string;
  createdAt: string;
}

/** Result of testing a single tool against its real API. */
export interface ToolTestResult {
  tool_name: string;
  status: "passed" | "failed" | "skipped" | "credential_missing";
  http_status?: number;
  latency_ms?: number;
  error?: string;
  connector?: string;
  output_preview?: string;
}

/** Aggregate report from testing all tools in a build draft. */
export interface TestReport {
  tools_tested: number;
  tools_passed: number;
  tools_failed: number;
  tools_skipped: number;
  credential_issues: Array<{ connector: string; issue: string }>;
  /** Connector resolution status — which connectors were matched to user credentials */
  connectors_resolved?: Array<{ name: string; has_credential: boolean }>;
  results: ToolTestResult[];
  /** Human-friendly summary generated by LLM */
  summary?: string;
}

/** Result returned by the promote_build_draft Tauri command. */
export interface PromoteBuildResult {
  persona: unknown;
  triggers_created: number;
  tools_created: number;
  connectors_needing_setup: string[];
  entity_errors: Array<{
    entity_type: string;
    entity_name: string;
    error: string;
  }>;
}
