/**
 * TypeScript types mirroring the Rust build session models.
 *
 * These will eventually be auto-generated by ts-rs, but are defined manually
 * now so frontend development can proceed in parallel with backend work.
 */

/** Build session lifecycle phase, matching the Rust BuildPhase enum. */
export type BuildPhase =
  | "initializing"
  | "analyzing"
  | "awaiting_input"
  | "resolving"
  | "draft_ready"
  | "completed"
  | "failed"
  | "cancelled"
  | "testing"
  | "test_complete"
  | "promoted";

/** Visual status of a single matrix cell during the build flow. */
export type CellBuildStatus =
  | "hidden"
  | "revealed"
  | "pending"
  | "filling"
  | "resolved"
  | "highlighted"
  | "updated"
  | "error";

/**
 * Discriminated union matching the Rust BuildEvent enum.
 * The `type` field is the serde tag (tag = "type").
 */
export type BuildEvent =
  | {
      type: "cell_update";
      session_id: string;
      cell_key: string;
      data: unknown;
      status: string;
    }
  | {
      type: "question";
      session_id: string;
      cell_key: string;
      question: string;
      options: string[] | null;
    }
  | {
      type: "progress";
      session_id: string;
      dimension: string | null;
      message: string;
      percent: number | null;
      activity?: string;
    }
  | {
      type: "error";
      session_id: string;
      cell_key: string | null;
      message: string;
      retryable: boolean;
    }
  | {
      type: "session_status";
      session_id: string;
      phase: string;
      resolved_count: number;
      total_count: number;
    };

/** A pending question the user needs to answer for a specific cell. */
export interface BuildQuestion {
  cellKey: string;
  question: string;
  options: string[] | null;
}

/** Full persisted build session loaded from SQLite. */
export interface PersistedBuildSession {
  id: string;
  personaId: string;
  phase: BuildPhase;
  resolvedCells: Record<string, unknown>;
  pendingQuestion: BuildQuestion | null;
  agentIr: unknown | null;
  intent: string;
  errorMessage: string | null;
  createdAt: string;
}

/** User's answer to a build question. */
export interface UserAnswer {
  cell_key: string;
  answer: string;
}

/** Lightweight session summary for list views. */
export interface BuildSessionSummary {
  id: string;
  personaId: string;
  phase: BuildPhase;
  intent: string;
  createdAt: string;
}

/** Result of testing a single tool against its real API. */
export interface ToolTestResult {
  tool_name: string;
  status: "passed" | "failed" | "skipped" | "credential_missing";
  http_status?: number;
  latency_ms?: number;
  error?: string;
  connector?: string;
  output_preview?: string;
}

/** Aggregate report from testing all tools in a build draft. */
export interface TestReport {
  tools_tested: number;
  tools_passed: number;
  tools_failed: number;
  tools_skipped: number;
  credential_issues: Array<{ connector: string; issue: string }>;
  results: ToolTestResult[];
  /** Human-friendly summary generated by LLM */
  summary?: string;
}

/** Result returned by the promote_build_draft Tauri command. */
export interface PromoteBuildResult {
  persona: unknown;
  triggers_created: number;
  tools_created: number;
  connectors_needing_setup: string[];
  entity_errors: Array<{
    entity_type: string;
    entity_name: string;
    error: string;
  }>;
}
