/** Prototype strings for "Sheet · Cinema". Gathered in one place so they can be
 *  extracted into i18n at consolidation. Dimension labels and descriptions are
 *  NOT here: they come from `t.agents.glyph_dim_label` / `glyph_dim_desc`. */
export const COPY = {
  heroAsk: "What should this agent do for you?",
  placeholder: "e.g. Summarize my unread emails each morning",
  launch: "Launch",
  launching: "Launching",
  buildRange: "3 to 6 min",
  context: "Reference context",
  contextAdded: "Context added",
  contextHint: "Docs, examples or constraints the build should read. Optional.",
  contextPlaceholder: "Paste a sample, a style guide, what to never do...",
  done: "Done",
  recipes: {
    orStartFrom: "Or start from",
    buildingOn: "Building on recipe",
    match: (pct: number) => `${pct}% match`,
  },
  buildLog: "Build log",
  buildLogHint: "The build's own output, newest at the bottom.",
  buildLogEmpty: "No output yet.",
  back: "Back to the sheet",

  loupe: {
    esc: "Esc",
    questionOf: (i: number, n: number) => `Question ${i} of ${n}`,
    needsYou: "Needs you",
    empty: "Nothing on this frame yet.",
  },

  scene: {
    compose: "Scene 1 · Describe",
    casting: "Scene 2 · Casting",
    questions: "Scene 3 · Questions",
    review: "Scene 3 · Your answers",
    wiring: "Scene 4 · Wiring",
    draft: "Scene 5 · Draft",
    screening: "Scene 6 · Screening",
    verdict: "Scene 6 · Results",
    premiere: "Premiere",
    stopped: "Build stopped",
  },

  phaseLabel: {
    initializing: "Warming up",
    analyzing: "Reading your brief",
    awaiting_input: "Waiting for you",
    resolving: "Wiring",
    draft_ready: "Draft ready",
    completed: "Complete",
    testing: "Screening",
    test_complete: "Screened",
    promoted: "Promoted",
    failed: "Stopped",
    cancelled: "Cancelled",
  } as Record<string, string>,

  casting: "Casting your persona",
  deliberating: "Weighing the final candidates",
  crowned: "Meet your persona",
  firstPassNote: "The first pass usually lands between 50 s and 2 min 35 s, all at once.",
  take: "Take",
  phase: "Phase",
  time: "Time",
  agent: "Agent",
  yourAgent: "Your agent",
  capabilities: "Capabilities",
  composingCaps: "Composing capabilities",

  questionsFor: (n: number) => `${n} question${n === 1 ? "" : "s"} for you`,
  questionsNote: "Developed frames were decided without asking. Glowing frames need you.",
  continueQuestions: "Continue",
  questionOf: (i: number, n: number) => `${i} / ${n}`,
  next: "Next",
  reviewAnswers: "Review answers",
  prev: "Back",
  ownWords: "Answer in your own words...",
  answersReady: (n: number) => `${n} answer${n === 1 ? "" : "s"} ready`,
  send: "Send answers",
  sending: "Sending",
  sendNote: "Nothing is sent until you press this.",

  wiring: "Connecting apps and triggers",
  wiringNote: "Your answers are in. Usually under a minute.",

  draftReady: "Draft ready",
  runTests: "Run tests",
  refine: "Refine",
  refineHint: "Say what should change. The draft is rebuilt and its tests reset.",
  reviewCaps: "Review capabilities",
  capsHint: "What the draft will do, one capability at a time. Remove one, or split it into a refine.",
  screening: "Screening",
  passed: "PASSED",
  failed: "FAILED",
  testsPassed: "Every screening passed",
  testsFailed: "A screening failed",
  promote: "Promote",
  viewReport: "Test report",
  promoteAnyway: "Promote anyway...",
  promoteAnywayTitle: "Promote with a failing test?",
  promoteAnywayBody: "The agent goes live even though its screening failed. You can refine it afterwards, but it will run as it is now.",
  reject: "Reject",
  rejectTitle: "Reject this draft?",
  rejectBody: "The draft is discarded. Nothing was promoted and nothing will run.",

  nowShowing: "NOW SHOWING",
  starring: "Starring",
  ready: "Your agent is ready",
  openAgent: "Open agent",

  stoppedAt: (t: string) => `Build stopped at ${t}`,
  cancelled: "Build cancelled",
  startOver: "Start over",
  startOverNote: "Your description stays.",

  buildTime: "Build time",
  yourTime: "you",
  frame: {
    needsYou: "Needs you",
    developing: "Developing",
    notSet: "Not set",
    error: "Did not resolve",
    unexposed: "Unexposed",
    byYou: "Set by you",
    byAi: "Decided by the build",
    runsOnAsk: "Runs when you ask",
    on: "On",
    off: "Off",
    choose: "Choose",
    perCapability: "Per capability",
    ownValue: "Own value",
    inherits: "Inherits agent-wide",
    none: "Not used",
    preLaunchNote: "Anything left empty is decided by the build.",
    decidedLater: "Decided during the build.",
    thisAgent: "This agent",
  },
} as const;
