// Declared inputs and outputs for the codegen tasks that may be SKIPPED when nothing they
// read has changed (scripts/run-codegen.mjs).
//
// A task is listed here only if its inputs are cheap to enumerate AND certain - every
// byte the generator reads is named below. A task that is not listed always runs, and
// that is the right default, not a gap to close:
//
//   gp-index        reads `git ls-files` (the whole tree is its input)
//   commands, connectors, shared-events, guidance-anchors, scan-match, bindings-index,
//   catalog, recipe-index, checksums, n8n-limits
//                   each under 350 ms and none on the critical path: the preset runs in
//                   parallel, so its wall time is its SLOWEST task. Measured 2026-09-18:
//                   sprites 3.1 s, gp-index 1.0 s, i18n-split 0.9 s, everything else
//                   95-335 ms. Caching the small ones would add hashing and buy nothing.
//   system-skills   mirrors into a gitignored dir another process may have wiped
//   host-check, cache-budget
//                   they observe the MACHINE, not the tree. Never cacheable, and
//                   run-codegen.mjs refuses to cache them even if someone lists them here.
//
// `inputs` and `outputs` are repo-relative. An entry is a file path, or
// `{ dir, match?, recursive? }` for every file in a directory whose NAME passes `match`.
// Inputs are hashed by content; outputs are fingerprinted by size + mtime, so an output
// that was deleted, regenerated by hand or replaced by a checkout forces a re-run.

export const CODEGEN_IO = {
  // Its outputs (sprite-dark.webp, sprite-light.webp) live in its input directory, so the
  // match mirrors the generator's own filter: <id>-dark|light.webp, never sprite-*.
  sprites: {
    inputs: [
      { dir: 'public/agent_icons', match: /^(?!sprite-).+-(dark|light)\.webp$/ },
      // the encoder's version decides the output bytes
      'node_modules/sharp/package.json',
    ],
    outputs: ['public/agent_icons/sprite-dark.webp', 'public/agent_icons/sprite-light.webp', 'src/lib/icons/agentIconSprite.generated.ts'],
  },
  i18n: {
    inputs: ['src/i18n/locales/en.json'],
    outputs: ['src/i18n/generated/types.ts', 'src/i18n/generated/sectionShapes.ts'],
  },
  'i18n-split': {
    inputs: [{ dir: 'src/i18n/locales', match: /\.json$/ }, 'src/i18n/routeSections.ts'],
    outputs: [{ dir: 'src/i18n/section-locales', recursive: true }, 'src/i18n/generated/enSectionStrings.ts'],
  },
};

/** Tasks that must run every time whatever CODEGEN_IO says. */
export const NEVER_CACHE = new Set(['host-check', 'cache-budget']);
